igniterealtime/Openfire

src/java/org/jivesoftware/openfire/http/HttpSession.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java, src/java/org/jivesoftware/openfire/session/LocalClientSession.java, src/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java, src/java/org/jivesoftware/openfire/session/LocalSession.java
I'm pretty sure that 4158dd77e4776fa263373e7cb83467ebd5cd3e6d is sound. 7bbfb9dbc49600ea8ffd02129909c152a2f73a72 should be too since I doubt that there is a case where Connection in the constructor is null. But since I don't longer have a Openfire instance to test I can't confirm it.
=> OF-855/OF-857 improvements

src/java/org/jivesoftware/openfire/OfflineMessageStrategy.java, src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/nio/ClientConnectionHandler.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java, src/java/org/jivesoftware/openfire/nio/OfflinePacketDeliverer.java
This patch is to prevent a stack overflow in certain exception cases
where a connection has been closed, but its corresponding session is
still present in the routing table. The patch synchronizes the internal
connection close logic before handing the connection back to mina to 
close the IoSession asynchronously.
=> OF-857: Synchronize connection/session cleanup

src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
When a peer server leaves the cluster, drop all routing references
corresponding to that node from the remaining members.
Ensure that all packets are handled by the backup routing mechanism in
the event that an exception occurs during primary packet processing.
=> OF-864: Cleanup routes to defunct cluster nodes

src/java/org/jivesoftware/admin/AuthCheckFilter.java, src/test/java/org/jivesoftware/admin/AuthCheckFilterTest.java
I don't see any reason why the URL need to be chopped at the @ char. 
If so, please let me know.
Additionally it breaks one functionality in the MUC Plugin (to add / remove user role from a channel) 
The MUC Plugin mentioned problem: https://community.igniterealtime.org/thread/53822
=> Removed chopping by @ character in the URL, to get MUC Plugin running

src/java/org/jivesoftware/openfire/SessionManager.java
Fixes an intermittent race condition observed under high load by adding a newly authenticated session into the core routing table before removing it from the list of pre-authenticated sessions.
=> OF-866: Prevent "session not found" errors

.travis.yml
So that travis-CI will error out when a plugin fails to build.  The default
action is to silently ignore and continue building.
=> Add -Dhalt.on.plugin.error=true to travis ant script

build/lib/versions.txt, src/java/org/jivesoftware/openfire/http/HttpBindManager.java
- cleanup lib versions to remove obsolete MINA notes
- use C2S compression policy rather than S2S compression policy for BOSH
connector
=> OF-626: Incorporate review feedback

src/java/org/apache/mina/management/MINAStatCollector.java
Fixes a race condition where (apparently) the removeSession method is invoked before the addSession method has completed.
=> OF-878: NPE in MINAStatCollector

src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/XMPPServer.java
Appearently there can only be one ServerItemsProvider. What happened here is that disco#items requests were now routed to SessionManager, which returned an empty result, which means service discovery fails.
It seems like Openfire can only host items for the whole server, not for single users, so the real fix needs some more investigation.
Original commit: 9c904ce569f1ce4facbab700a7be94318b5e4a3f
=> Revert fix for OF-874 because it introduced a critical regression.

src/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
If a CDATA section ends with the sequence ]]]> (note the preceding square brace) the XMLLightweightParser was not correctly detecting the end of the CDATA section.  This fixes how the XMLLightweightParser handles CDATA sections that end with ]]]>
=> Fix parsing logic of CDATA in  XMLLightweightParser

src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
Prevent recursion when attempting to send an error response packet via S2S to a non-responsive remote domain.
=> OF-888: Fix outgoing S2S packet delivery failure

src/java/org/jivesoftware/openfire/SessionManager.java
This is for OF-454, which got fixed insufficiently in my opinion.
As per my tests, the broadcastPresenceToOtherResources (introduced with 3.9.0) made presences delivered twice to the other resources. I guess because normal presence routing logic already took care about routing to other resources.
However, it still didn't send initial presence to the generating resource (RFC 6121 § 4.4.2.).
I guess this is a critical part and there was some discussion in OF-454, so please review mindfully and merge with care.
I did some tests and it behaves as expected, but I'd like to have some other opinions/tests.
=> Send initial presence to the generating resource.

src/java/org/jivesoftware/openfire/http/HttpBindServlet.java, src/java/org/jivesoftware/openfire/http/HttpConnection.java, src/java/org/jivesoftware/openfire/http/HttpSession.java
Per spec, the ack attribute in the response <body/> allows a BOSH client
to verify that sent stanzas with the corresponding rid(s) have been
successfully received by the server.
This PR is a cherry-pick for commit 70de10f89c38486c9cb37988485fc695e0d0dc5a from PR #209.
=> OF-909: Include ack in BOSH response body element

build/debian/control
When installing openfire 3.10 JRE 7 is required - that's good and I think it was one of my past PRs.
On one of my servers the installation fails because openjre is installed in headless (without X libraries) mode.
This PR adds the headless JRE to the dependencies as well.
```
dpkg: regarding openfire_3.10.0_all.deb containing openfire, pre-dependency problem:
openfire pre-depends on openjdk-7-jre | oracle-java7-jre
openjdk-7-jre is not installed.
oracle-java7-jre is not installed.
```
=> Add openjdk headless dependency to avoid installing X libraries

src/java/org/jivesoftware/openfire/nio/ConnectionHandler.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java
MINA 2.0.8 introduces support for half-duplex close of TCP channels (see DIRMINA-785).
As part of this change, IoHandlers got a new method. The default behavior of the
IoHandlerAdapter closes the MINA session when this handler is triggered. However,
without an Openfire-specific extension (in ConnectionHandler), this fails to close
Openfire-maintained resources. As a result, CPUs could start to spin in NIO code,
resulting in 100% CPU cycles.
To fix this issue, ConnectionHandler now overrides the default functionality and
triggers a normal closure of the session (both in Openfire as well as MINA context).
Additionally, to prevent the CPU spin, MINA sessions need to be closed synchronously
(as opposed to the async closure Openfire had up until now). I cannot quite explain
the need for this …
=> OF-883: Compensate for new half-duplex close of TCP channel in MINA

src/java/org/jivesoftware/openfire/Connection.java, src/java/org/jivesoftware/openfire/net/SocketConnection.java, src/java/org/jivesoftware/openfire/net/VirtualConnection.java, src/java/org/jivesoftware/openfire/nio/ConnectionHandler.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java
By closing a session when the new MINA inputClosed() handler is triggered, we run
the risk of sending data to the peer. As that peer is known to be dead, this is
pointless (and potentially dangerous - deadlocks have been observed that are likely
related to this scenario).
To prevent sending data during session closure, the close() method has been
overloaded with an argument that indicates if the peer is known to be dead. When
set, its implementation will not attempt to send data.
=> OF-883: Prevent sending data to known disconnected peers.

src/plugins/fastpath/src/java/org/jivesoftware/xmpp/workgroup/WorkgroupManager.java
Following suit with Users/Groups, Workgroups should order in alpha, shouldn't they?
=> Order Fastpath Workgroups by Display Name

src/java/org/jivesoftware/openfire/nio/NIOConnection.java
There is a deadlock while reading the state variable if close() is running.
This switches the state to be volatile instead - it's only written to inside
the lengthy close() lock, so this should be reasonable.
=> Do not synchronize on isClosed()

build/build.xml, build/debian/openfire.conffiles, build/installer/openfire.install4j, build/rpm/openfire.spec, src/conf/modules.xml, src/java/org/jivesoftware/openfire/XMPPServer.java
This change moves the list of modules to be loaded from hard coded in XMPPServer to defined in conf/modules.xml.  My motivation is to allow me to replace Openfire behavior defined in modules that can't be overridden or changed in a plugin.
There are two basic elements of the change.  First, the loadModules method has been updated to open the modules.xml file and pass the contents of the file to loadModule.  
The second part of the change is to modify the modules map to use a String as the key.  This allows for the modules to be looked up by the name they implement instead of the class that is actually implementing.
=> Make module loading driven by a file

build/installer/openfire.install4j, build/osx/resources/postupgrade, build/osx/resources/preupgrade, build/rpm/openfire.spec, build/solaris/postinstall, build/solaris/preremove
Currently, if users make changes to the lib/log4j.xml file, these changes are over-written by the installers for subsequent releases.  I have made an attempt to correct this for all platforms but debian.
=> OF-913 Treat lib/log4j.xml as a config file in installers

src/web/component-session-details.jsp, src/web/server-session-details.jsp, src/web/session-details.jsp, src/web/session-row.jspf
Updated JSP pages around sessions to prevent them from blowing up when an UnknownHostException is thrown and show 'Invalid session/connection' instead. The user can then manually remove those sessions.
=> Prevent sessions in admin console from showing UnknownHostException

src/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceManager.java
This patch repairs an incompatibility of the current default PURGE_FOR_SIZE - SQL-query by adding a separated variant for the database-type mySQL.
Previously this incompatibility was provoked by "fixing" the default-query for hsqldb - see OF 789 [https://igniterealtime.org/issues/browse/OF-789] and thread on https://community.igniterealtime.org/message/250575 )
=> Restored and separated Database-Query for MYSQL

src/plugins/ofmeet/src/java/org/jitsi/jicofo/BridgeSelector.java
FIXED:  typo
1. 'for' was 'fro' (Line 126)
=> FIXED:  typo

src/plugins/jmxweb/src/hawtio/app/wiki/exemplar/camel-blueprint.xml, src/plugins/userImportExport/classes/wildfire-user-schema.xsd.xml
There was a typo. The XML Schema instance namespace should be "www.w3c.org", not "www.w3.org".
- src/plugins/userImportExport/classes/wildfire-user-schema.xsd.xml
- src/plugins/jmxweb/src/hawtio/app/wiki/exemplar/camel-blueprint.xml
(from http://www.w3.org/2001/XMLSchema to http://www.w3c.org/2001/XMLSchema)
=> fix XML Schema instance namespace in two XML Schema files.

src/java/org/jivesoftware/openfire/nio/NIOConnection.java
Original issue (OF-857) has been addressed by providing an alternate
packet deliverer (to offline storage). This additional logic was an
ill-advised "belt-and-suspenders" attempt to prevent the recursion which
was occurring before the backup deliverer was implemented.
=> OF-903: Simplify backup packet delivery

src/conf/openfire.xml, src/java/org/jivesoftware/openfire/OfflineMessageStore.java, src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/net/StanzaHandler.java, src/java/org/jivesoftware/openfire/session/LocalClientSession.java, src/java/org/jivesoftware/openfire/session/LocalSession.java, src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
This patch adds a basic, non-resumable, XEP-0198 acking solution. It will
redirect "lost" messages to offline storage, but does not attempt to suspend
the session, so will not allow any resumptions.
=> Initial xep-0198 message ack implementation

src/java/org/jivesoftware/openfire/clearspace/ClearspaceX509TrustManager.java, src/java/org/jivesoftware/openfire/net/ClientTrustManager.java, src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/util/CertificateManager.java, src/java/org/jivesoftware/util/cert/CNCertificateIdentityMapping.java, src/java/org/jivesoftware/util/cert/CertificateIdentityMapping.java, src/java/org/jivesoftware/util/cert/SANCertificateIdentityMapping.java, src/web/security-keystore.jsp
Resubmitting this pull request from a different branch. See [here](https://github.com/igniterealtime/Openfire/pull/225).
"This change allows users to specify classes in the Openfire properties (similar to AuthorizationManager) to map different identity credentials from certificates. This change is useful during client authentication with certificates (mutual authentication) in order to provide different credentials to the AuthorizationMapping (e.g. full subject distinguished name instead of only common name).
This change is taking code out of CertificateManager.java and moving it into CNCertificateIdentityMapping and SANCertificateIdentityMapping which implement a new CertificateIdentityMapping interface. In CertificateManager it fell back to the CN if the SAN did not have any XMPP OIDs …
=> Allow users to specifiy custom classes to map credentials from certificates

src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cluster/HazelcastClusterNodeInfo.java
Using getHostString() to benefit from not attempting a reverse lookup.
Or will cause very big delay if the ip address doese not have configured
host name.
=> HazelcastClusterNodeInfo communication has big delay.

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/ConversationManager.java
1) add new monitoring plugin description
2) fix MySQL Error 1093(can't modify the same table which is used in the SELECT part) in ConversationManager
=> fixed MySQL Error 1093 in monitoring plugin ConversationManager & added description

src/java/org/jivesoftware/openfire/http/HttpSession.java
Append XMPP client namespace to outbound BOSH packets only when needed.
=> OF-938: Use correct namespace for BOSH packets

src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java
Details: https://community.igniterealtime.org/message/252259#252259
----
(Transcription in case the link becomes broken)
Hi! I've been dealing with the same problem as other, with Hazelcast reporting that it failed to execute cluster tasks in the set timeout period. As others, I have also seen that the expected timeout time had indeed not elapsed, and that sometimes the cluster nodes appear as not available from the clustering page in the admin console. Finally, I have also seen messages being lost and synchronization on clients connected to servers sometimes failing, and I am assuming that this last part is just a symptom of the same problem.
A colleague of mine spotted this in the hazelcast plugin source code.
Class: ClusteredCacheFactory
```java
/*01.*/ public Collection<Object> …
```
=> OF-943: Timeout issues on synchronous cluster tasks

src/plugins/hazelcast/changelog.html, src/plugins/hazelcast/plugin.xml
This PR updates the plugin metatdata to prepare a release for the timeout bug fix which was previously committed (via PR#288).
=> OF-943: Fix timeout issues in HZ plugin

build/build.xml
Instead, any Ant version higher than 1.7.1 is now accepted.
=> OF-373: Build should not check for explicit Ant version numbers

src/java/org/jivesoftware/openfire/OfflineMessageStore.java
Detect offline messages that fail to parse; write to error log before
discarding as undeliverable. This will unblock the offline message queue
for future (valid) messages addressed to the affected user.
=> OF-949: Catch parsing errors for offline messages

src/java/org/jivesoftware/database/DbConnectionManager.java
This should fix the problem introduced in #306.
=> [OF-958] Avoiding DB properties when reading DB connection configuration

src/java/org/jivesoftware/openfire/keystore/IdentityStoreConfig.java, src/java/org/jivesoftware/openfire/keystore/TrustStoreConfig.java, src/web/user-roster-add.jsp
For some reason, the default validation fails to iterate over all providers and will fail if the default
provider does not support the algorithm of the chain. To work around this issue, the code now iterates over each provider explicitly, returning success when at least one provider validates the chain successfully.
This replaces an earlier attempt to fix this issue by explicitly naming one (and just one) provider.
=> OF-946: Help Java to find the correct Security Provider

src/java/org/jivesoftware/openfire/SessionPacketRouter.java, src/java/org/jivesoftware/openfire/auth/DefaultAuthProvider.java, src/java/org/jivesoftware/openfire/auth/ScramUtils.java, src/java/org/jivesoftware/openfire/group/GroupJID.java, src/java/org/jivesoftware/openfire/http/HttpBindServlet.java, src/java/org/jivesoftware/openfire/http/HttpSession.java, src/java/org/jivesoftware/openfire/ldap/LdapManager.java, src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java, src/java/org/jivesoftware/openfire/sasl/SaslServerPlainImpl.java, src/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java, src/java/org/jivesoftware/util/AesEncryptor.java, src/java/org/jivesoftware/util/StringUtils.java, src/java/org/jivesoftware/util/cert/SANCertificateIdentityMapping.java, src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/StreamManagementPacketRouter.java, src/test/java/org/jivesoftware/openfire/group/GroupJIDTest.java
- Use String.getBytes(Charset) instead of String.getBytes(String)
- Use new String(byte[], Charset) instead of new String(byte[], String)
-> Get rid of UnsupportedEncodingException.
-> Less try-catch blocks.
=> Make code more readable by using StandardCharsets.UTF_8.

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
Currently, when conversation.maxRetrievable > 0 and startDate > maxRetrievableDate, result is set to null instead of startDate.
=> fix getAuditedStartDate resetting startDate to null

src/java/org/jivesoftware/openfire/container/PluginClassLoader.java, src/java/org/jivesoftware/openfire/container/ResourceEntry.java
Different plug-ins should not be able to obtain other plug-ins through reflection resource.
PluginClassloader for each plug-in classes and resources provides a local isolation mechanism
that will safeguard their load classes and resources, when loading plugin all the resources
and classes only in PluginClassloader , and does not exist in the parent Classloader.
When the plugin needs to load a resource, it will first load plugins own resources in PluginClassloader,
and secondly then required to load in the parent Classloader
=> Add PluginClassLoader plugin loader isolation mechanism

src/java/org/jivesoftware/admin/AuthCheckFilter.java, src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, src/java/org/jivesoftware/util/ConcurrentHashSet.java, src/plugins/fastpath/src/java/org/jivesoftware/xmpp/workgroup/WorkgroupPresence.java, src/plugins/fastpath/src/java/org/jivesoftware/xmpp/workgroup/dispatcher/RoundRobinDispatcher.java, src/plugins/gojara/src/java/org/jivesoftware/openfire/plugin/gojara/messagefilter/MainInterceptor.java
ConcurrentHashSet seems to be a relict from earlier Java times.
Since Java 1.6 the preferred method to create a "ConcurrentHashSet" is to use Collections.newSetFromMap(new ConcurrentHashMap<?, ?>())
I suggest to delete ConcurrentHashSet.java at latest with Openfire 4.
=> Deprecate ConcurrentHashSet in favor of Collections.newSetFromMap().

src/java/org/jivesoftware/admin/LdapGroupTester.java, src/java/org/jivesoftware/admin/LdapUserProfile.java, src/java/org/jivesoftware/admin/LdapUserTester.java, src/java/org/jivesoftware/database/EmbeddedConnectionProvider.java, src/java/org/jivesoftware/openfire/http/ResourceServlet.java, src/java/org/jivesoftware/openfire/starter/ServerStarter.java
Most methods in org.jivesoftware.util.Log are deprecated, stating that org.slf4j.Logger should be used instead.
This PR uses org.slf4j.Logger in Openfire core now.
=> Replace deprecated org.jivesoftware.util.Log with org.slf4j.Logger

src/java/org/jivesoftware/openfire/http/HttpSession.java
This patch fixes a problem introduced by an earlier patch whereby a
change to the Packet namespace inadvertently cascaded to child XML
elements.
=> OF-938: Apply packet namespace via string insert

src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCRoomEntity.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/utils/MUCRoomUtils.java
This patch shows which groups have one of the affiliations
admin|member|owner|outcast.
In case the new query parameter expandGroups is set to true, the group
member's jids are added to the explicit jids.
=> restAPI: make group affiliations per room visible

build/build.xml
Don't know why, but it fixes the issue described here:
https://community.igniterealtime.org/thread/55868
org.apache.jasper.JasperException: XML parsing error on file /WEB-INF/web.xml
=> Clean plugins directory when calling Ant "plugins" target.

src/java/org/jivesoftware/openfire/launcher/Launcher.java
Also note the removal of `frame.setState(Frame.ICONIFIED);`
This is on purpose in order to prevent weird behavior with Mac OS X.
Thx to wroot for reporting.
=> Restore tray icon click functionality after moving to AWT tray.

src/java/org/jivesoftware/openfire/starter/ServerStarter.java
f81c28b replaced org.jivesoftware.util.Log with org.slf4j.Logger.
This commit partially reverts this.
Apparently the build process produces an additional startup.jar, which contains the ServerStarter class. However, it doesn't add slf4j-api.jar to the classpath or manifest.
Because Openfire's classpath, lib folder and build structure is pretty confusing (e.g. slf4j-api.jar gets merged into a new openfire.jar, there's an extra JiveClassLoader, etc...), it's hard to solve this in a reasonable way at the moment.
=> Prevent NoClassDefFoundError during Openfire start.

src/java/org/jivesoftware/util/StringUtils.java, src/test/java/org/jivesoftware/util/StringUtilsTest.java
- The 4 replace methods were nearly identical.
- Deprecate String utility, which has a simple one-liner equivalent in the JDK
- Use DatatypeConverter for byte[] to hex. It's less code and even 2-3 times faster than the previous method.
=> StringUtils: Simplify verbose/duplicate and obsolete code constructs

src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
This is highlighted as "probably a bug" in my IDE.
E.g. `new byte[]{1}.equals(new byte[]{1})` is always false.
But `Arrays.equals(new byte[]{1}, new byte[]{1});` is true.
=> byte[].equals() should probably be Arrays.equals()

src/java/org/jivesoftware/util/Version.java, src/test/java/org/jivesoftware/util/VersionTest.java
- Make it final and immutable.
- Use pattern-based parsing, which allows to also parse the ReleaseStatus and the statusVersion.
- Implement toString() method.
- Implement equals() and hashCode(), which is a strong recommendation when implementing Comparable: From the JavaDoc: "It is strongly recommended that (x.compareTo(y)==0) == (x.equals(y))", which was not the case.
- Allow CharSequence
- Simplify getVersionString() method (less duplicate code).
- Improve compareTo() method by properly comparing more than 2 digits and also comparing ReleaseStatus and statusVersion
=> Various improvements in Version class

src/java/org/jivesoftware/util/cache/CacheFactory.java
When switch to/from clustered deployment, ensure that critical cached
items such as components and remote servers are not inadvertently
dropped from the cache.
=> OF-974: Migrate cache content

src/java/org/jivesoftware/database/SchemaManager.java, src/java/org/jivesoftware/openfire/commands/SessionData.java
Remove "private" default constructor to enable subclasses, mock testing, etc. Separate commits for SchemaManager and SessionData classes in case these need to be cherry-picked later.
=> Support mock testing

src/plugins/clientControl/src/web/WEB-INF/web-custom.xml, src/plugins/fastpath/src/web/WEB-INF/web-custom.xml, src/plugins/gojara/src/web/WEB-INF/web-custom.xml, src/plugins/jmxweb/src/WEB-INF/web.xml, src/plugins/kraken/src/web/WEB-INF/web-custom.xml, src/plugins/monitoring/src/web/WEB-INF/web-custom.xml, src/plugins/mucservice/src/web/WEB-INF/web-custom.xml, src/plugins/ofmeet/src/WEB-INF/web.xml, src/plugins/presence/src/web/WEB-INF/web-custom.xml, src/plugins/restAPI/src/web/WEB-INF/web-custom.xml, src/plugins/userservice/src/web/WEB-INF/web-custom.xml, src/spank/WEB-INF/web.xml, src/web/WEB-INF/web.xml
Old version 2.4 was J2EE 1.4
Also remove <taglib> from web.xml. This was required in JSP 1.2, but is no longer in JSP 2.0 (Servlet API 2.4) and gives warnings since it has been removed from the XSD.
See http://wiki.metawerx.net/wiki/RemovingTaglibFromWeb.xml
=> Update web.xml schema namespaces to version 3.1 (Java EE 7)

src/java/org/jivesoftware/openfire/net/ServerSocketReader.java
This PR removes the thread pool from the ServerSocketReader, causing
stanzas from a particular S2S session to be processed serially on the same
thread used by the ServerSocketReader.
Each ServerSocketReader currently has a thread to itself, so this is unlikely
to have a serious impact on performance, but does have a very positive impact
on correctness.
=> OF-115 Process S2S stanzas from a session serially

src/java/org/jivesoftware/openfire/pep/PEPService.java, src/java/org/jivesoftware/openfire/pubsub/PubSubModule.java
The specification (XEP-0060) recommends generating unique message ids
within a pubsub instance to aid troubleshooting for notification
delivery issues when needed. This replaces a ridiculously long and
inefficient string concatenation with something a bit more tidy and
concise.
=> Simplify and shorten pubsub message id

src/java/org/jivesoftware/openfire/IQRouter.java
Avoids NPE by dropping (and optionally logging) error response stanzas
if the original packet has no sender JID.
=> Fix NPE when handling routing failures

src/java/org/jivesoftware/openfire/Connection.java, src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/http/HttpSession.java, src/java/org/jivesoftware/openfire/http/HttpSessionManager.java, src/java/org/jivesoftware/openfire/net/SocketConnection.java, src/java/org/jivesoftware/openfire/net/SocketReadingMode.java, src/java/org/jivesoftware/openfire/net/StanzaHandler.java, src/java/org/jivesoftware/openfire/net/VirtualConnection.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java, src/java/org/jivesoftware/openfire/session/LocalClientSession.java, src/java/org/jivesoftware/openfire/session/LocalComponentSession.java, src/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java, src/java/org/jivesoftware/openfire/session/LocalServerSession.java, src/java/org/jivesoftware/openfire/session/LocalSession.java, src/java/org/jivesoftware/openfire/session/Session.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteSession.java, src/plugins/websocket/changelog.html, src/plugins/websocket/plugin.xml, src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
I feel the language (the stream's "xml:lang" attribute) should be in the Session interface rather than the Connection (similar as the stream id), because it's unrelated to the session's transport.
The HttpSession already did that.
Otherwise the used language is not easy to retrieve, e.g. when using SessionManager to get the session and OF-208 is hard to solve.
Alternatively we can expose the Connection in the Session interface, but this approach feels wrong to me.
Also use `java.util.Locale` rather than String, because it better reflects what can be in `xml:lang` (it can also have country codes, e.g. "de-CH")
=> Language info should be in the Session, not in the Connection

src/web/WEB-INF/admin.tld
This is related to the JSP upgrade.
Some tags have changed after moving from the DTD to the XSD.
See also https://blogs.oracle.com/jluehe/entry/validate_your_tag_library_descriptor
=> Update admin.tld to use the latest taglib version.

src/java/org/jivesoftware/openfire/roster/Roster.java
Received reports of unexpected roster caching caused by this change (not
verified). Additional investigation is needed to determine whether/how
to fix original issue reported via OF-473.
=> OF-473: Revert original patch

src/test/java/org/jivesoftware/openfire/keystore/CheckChainTrustedTest.java
My guess is that the libraries that are available on Travis (in its ANT_HOME perhaps) do not support the parameterized tests in this class. Lets ignore them for now.
=> Ignore test that makes Travis fail.

src/java/org/jivesoftware/openfire/auth/DefaultAuthProvider.java, src/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java
The salt size was 32, and the database column was a VARCHAR(32).
However, the salt was base64 encoded prior to insertion, and this caused it to
be too large. Therefore this patch reduces the size to 24 bytes, which expands
to 8 units of three bytes encoded as four characters, hence 32 characters total.
=> OF-631 Reduce salt size to fit database

src/java/org/jivesoftware/openfire/net/TLSStreamHandler.java, src/java/org/jivesoftware/openfire/server/ServerDialback.java
These two patches add the missing "to" attribute from the stream open for verify-only connections, and
also negotiate TLS if offered, using the S2S configuration.
Tested by running it up in production on d.c.n
=> OF-984 / OF-985 Dialback fixes for to attribute and TLS

src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
OF-983 appears to be caused by a complex bouncing process run while the
authentication check lock is held. This patch moves the actual bounce to
outside the synchronized block, so the code no longer deadlocks.
Untested, but based on the stack traces in OF-983 reports.
=> OF-983 Do not bounce packets while lock is held

src/java/org/jivesoftware/openfire/PresenceManager.java, src/java/org/jivesoftware/openfire/handler/IQLastActivityHandler.java, src/java/org/jivesoftware/openfire/spi/PresenceManagerImpl.java
If a query has no 'to' attribute it should be treated on behalf of the sender.
It should not be treated as if it were targeted to the server (and return the server uptime).
The former logic also threw an UserNotFoundException, if the user queried itself, because the user was not on his own roster.
I've fixed that in the canProbePresence method.
Fixes issue OF-982
=> Fix XEP-0012 logic.

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCUser.java
XEP-0045 discusses how a request to join a room is the only case where a MUC
element should exist in presence. Therefore, a conformant client will always
send this whenever it believes it is not joined. This can happen in cases of
stanza loss (due to network outage) or remote server crash.
This patch assumes that a client sending a MUC element is trying to join, and
will go through much of the motions of the join, including sending history as
required, existing occupants' presence, and so on. To other existing occupants,
however, it'll look like an ordinary presence update.
=> Assume a client with MUC elements in presence needs to join

src/java/org/jivesoftware/openfire/handler/PresenceSubscribeHandler.java, src/java/org/jivesoftware/openfire/roster/Roster.java
This should fix OF-317.
During testing also discovered an UserNotFoundException thrown by canProbePresence, because it was passed the JID instead of the username.
=> Subscribe with Response Unsubscribed Causes Roster Push to Responding Client

src/java/org/jivesoftware/openfire/muc/HistoryStrategy.java, src/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCUser.java, src/web/muc-room-edit-form.jsp
Ensure that the MUC room subject is set correctly from initial request and upon subsequent reload.
Initial testing looks good, but would welcome additional validation and testing with various XMPP clients if possible.
=> OF-122: Fix inconsistent MUC subject handling

src/test/java/org/jivesoftware/openfire/keystore/KeystoreTestUtils.java
This fix was applied a while back on an earlier incarnation of this test class.
=> Avoid using classes from sealed packages

src/java/org/jivesoftware/openfire/XMPPServer.java
Not sure when this got changed, but the module loader uses the interface class name as a key, not the implementation class name.
=> Fix NPE when accessing AuditManager module

src/web/session-details.jsp
Possibly a copy/paste glitch from an earlier refactoring exercise.
=> Avoid nested EL delimiters

src/java/org/jivesoftware/openfire/user/DefaultUserProvider.java
The reason is, that when calling the createUser() method, the caller thinks user creation succeeded, even if it might not.
This leads to unexpected behavior.
I've experienced that, when trying to create a user with a name of > 100 length:
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'name' at row 1
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4230)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4164)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2838)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1307)
at …
=> DefaultUserProvider: Rethrow exception instead of silently logging it.

src/java/org/jivesoftware/openfire/net/SocketConnection.java, src/java/org/jivesoftware/openfire/net/SocketReadingMode.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
When STARTTLS fails, there are two distinct types of failure. Each type should
be handled in a distinct manner.
Note that this commit applies a fix to the S2S code only. C2S may also need work.
=> OF-973: TLS negotiation failures should come in two flavors.

.travis.yml, build/build.xml, src/test/java/org/jivesoftware/openfire/keystore/CheckChainTrustedTest.java
The Github-based CI server (Travis), tends to run out of resources quickly.
This commit adds a new optional flag that allows the build to skip tests that
are known to be resource intensive.
Example usage: ant -DskipResourceIntensiveTests=true clean test
=> Making Travis happy

src/i18n/openfire_i18n_cs_CZ.properties, src/i18n/openfire_i18n_de.properties, src/i18n/openfire_i18n_en.properties, src/i18n/openfire_i18n_es.properties, src/i18n/openfire_i18n_fr.properties, src/i18n/openfire_i18n_ja_JP.properties, src/i18n/openfire_i18n_nl.properties, src/i18n/openfire_i18n_pl_PL.properties, src/i18n/openfire_i18n_pt_BR.properties, src/i18n/openfire_i18n_pt_PT.properties, src/i18n/openfire_i18n_ru_RU.properties, src/i18n/openfire_i18n_sk.properties, src/i18n/openfire_i18n_zh_CN.properties, src/java/org/jivesoftware/openfire/spi/ConnectionConfiguration.java, src/java/org/jivesoftware/openfire/spi/ConnectionListener.java, src/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java, src/test/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactoryTest.java, src/web/connection-settings-advanced.jsp, src/web/connection-settings-external-components.jsp, src/web/connection-settings-socket-c2s.jsp, src/web/connection-settings-socket-s2s.jsp
This pull request has two major changes:
1. The configuration of protocols and cipher suites now depends on one setting, instead of having both a 'enabled' as well as a 'disabled' list. As a side effect, this improves the default values, which up until this change were either to narrow (nothing) or to wide (every possible option was enabled). Now, the Java-configured default is used when no Openfire-specific setting is available.
2. Most of the TLS settings have been moved to an 'advanced settings' page on the Admin console. There, you can now also configure encryption protocols en cipher suites.
=> OF-1004: Reduce complexity of connection configuration

src/java/org/jivesoftware/util/SimpleSSLSocketFactory.java
A default SSLContext object cannot be re-initialized. This causes LDAPS to fail.
=> OF-1010: Cannot re-init default SSLContext

src/web/connection-settings-advanced.jsp
This commit is a cosmetic change to the admin panel. If the JVM supports
SSLv2Hello, it is no longer presented as an encryption protocol, but rather
as an option.
=> Admin console: SSLv2Hello isn't a protocol, but an option.

src/java/org/jivesoftware/util/CertificateManager.java
This is a tiny usability improvement, Dave and me ran into this when trying to import the LetsEncrypt Intermediate certificate.
=> OF-1011: Trim each line of a PEM representation

src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
If route.really-all-resources enabled it's not requere process message again via priority algorithm.
We already processed in 560 line. 
If we not stop (return) than session.process() call twice (first in line 560 and next in next other)
=> Fix twice sending of messages on route.really-all-resources=true

src/java/org/jivesoftware/openfire/net/SocketReadingMode.java, src/java/org/jivesoftware/openfire/net/StanzaHandler.java, src/java/org/jivesoftware/openfire/session/LocalClientSession.java
toString() was called on the Locale here, resulting e.g. in "de_DE".
Instead it should be "de-DE".
=> xml:lang in stream header should conform to a language tag.

src/java/org/jivesoftware/openfire/muc/MUCEventDelegate.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Extend MUCEventDelegate by sendingInvitationRejection method similarly as sendingInvitation methods for thrid-party developers that impliment MUCEventDelegate for thrid-party MUC providers
=> MUC Invitation rejection delegate call

src/java/org/jivesoftware/openfire/muc/HistoryStrategy.java
Default to lenient policy, allowing override to strict (conforming)
policy. Tested using Pidgin, Psi, and Exodus. Refer to details in
OF-122.
=> OF-122: MUC subject change policy

src/java/org/jivesoftware/openfire/audit/spi/AuditorImpl.java
When a log directory cannot be created, a warning should be logged,
and null pointers should be prevented when the directory is being
referenced.
=> OF-1000 Prevent NPE and improve logging

src/java/org/jivesoftware/openfire/container/PluginServlet.java
For some reason, XPath-based selection of nodes no longer works. Traversing
the Dom4j object resolves that problem.
=> OF-1025: Restore web-custom.xml functionality

src/java/org/jivesoftware/openfire/roster/Roster.java
When a shared group is removed from a roster item, fire an update or
delete event to keep the corresponding Roster cache in sync.
=> OF-1023: Fire contactChanged/Deleted events

src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/WebSocketConnection.java
The old logic produced XML like:
&lt;presence xmlns="jabber:client" from="..." to="...">&lt;show xmlns="">xa&lt;/show>&lt;status xmlns=""/>&lt;/presence>
This is basically the same fix as in 6965c13.
Relates to OF-938.
=> WebSocket plugin: Fix wrong namespace adding to empty elements

src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
The issue is that messages, which get resent from offline storage already have an older timestamp.
There should not be another delayed delivery extension, which "overwrites" the old one.
Messages looked like that:
&lt;message>&lt;body>...&lt;/body>&lt;delay xmlns="urn:xmpp:delay" stamp="2016-01-06T13:48:45.312Z">&lt;/delay>&lt;delay xmlns="urn:xmpp:delay" stamp="2016-01-06T13:49:56.674Z">&lt;/delay>&lt;/message>
Instead the original timestamp should be preserved.
=> Don't add multiple delayed delivery extension to resent messages.

src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
This commit notifies all users that are in a MUC on the local server node of
a shut down of the service. The notification conforms to XEP-0045.
In order to prevent a prolonged shut down, this commit:
- ensures that a shutdown routine is executed just once (instead of for each
type of interface being shut down: module,component and listener)
- the presence stanza that is sent is constructed using in-memory objects
only (no database lookups)
- all notification occurs in a thread pool, which will concurrently process
them, but will terminate forcibly after a certain amount of time.
=> OF-1033: Users should be notified of MUC service shutdown

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Returns the count of nicknames rather than the number of connections
(full JIDs), which will now also match the list of occupants.
=> OF-821: Count occupants by nickname

build/build.xml, documentation/dist/changelog.html, src/java/org/jivesoftware/openfire/XMPPServer.java
This assumes pull requests #486 , #503, #504 are approved and merged first.
=> Denote Openfire 4.0.0 Release

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Two commits that fix issues related to banning users from MUC rooms.
1. Openfire sends presence of "none" instead of "outcast" when a user is banned.
2. A user is not kicked from a non members-only room when they are banned.
Looks like both were introduced in commit 822abb014741b82d9248c3f747bea64779546999
=> Fixes for banning problems in MUC rooms

src/plugins/clientControl/plugin.xml, src/plugins/clustering/plugin.xml, src/plugins/contentFilter/plugin.xml, src/plugins/dbaccess/plugin.xml, src/plugins/emailListener/plugin.xml, src/plugins/fastpath/plugin.xml, src/plugins/gojara/plugin.xml, src/plugins/hazelcast/plugin.xml, src/plugins/jingleNodes/plugin.xml, src/plugins/justmarried/plugin.xml, src/plugins/kraken/plugin.xml, src/plugins/monitoring/plugin.xml, src/plugins/motd/plugin.xml, src/plugins/nodejs/plugin.xml, src/plugins/packetFilter/plugin.xml, src/plugins/presence/plugin.xml, src/plugins/rayo/plugin.xml, src/plugins/registration/plugin.xml, src/plugins/restAPI/plugin.xml, src/plugins/search/plugin.xml, src/plugins/sip/plugin.xml, src/plugins/stunserver/plugin.xml, src/plugins/subscription/plugin.xml, src/plugins/userCreation/plugin.xml, src/plugins/userImportExport/plugin.xml, src/plugins/userservice/plugin.xml, src/plugins/xmldebugger/plugin.xml
Previously, we had a quasi-hack of `3.11.0-alpha` as the min requirement
on these, but this release never happened.  This update moves all these
plugins to 4.0.0, which hopefully provokes less confusion.
=> Update plugin min Openfire version requirement to 4.0.0

src/java/org/jivesoftware/openfire/net/StanzaHandler.java
I did not reproduce the NPE, but having a session already closed when </stream> is received sounds plausible to me. Some kind of race between handling the last data and following socket disconnect perhaps?
=> OF-1042: Don't NPE when a session is already closed when </stream>

src/java/org/jivesoftware/openfire/OfflineMessageStore.java, src/test/java/org/jivesoftware/openfire/OfflineMessageStoreTest.java
The problem was, that the logic stored empty chat messages, which contained a thread and chat state. The loop first checked the namespace of the thread, which was empty and therefore thought it should store it.
=> Should not store chat state messages, which contain a thread element.

src/java/org/jivesoftware/openfire/OfflineMessageStrategy.java
Existing code already tried to prevent message bounces when a stanza was
sent by the server itself. This commit builds on that solution.
Also, debug logging was added for the store-and-* strategies when storage
was no longer possible as a result of quota limitations (we had a hard time
debugging this)
=> OF-1046: Improve offline-storage usage

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java, src/java/org/jivesoftware/openfire/keystore/CertificateStoreManager.java, src/java/org/jivesoftware/openfire/keystore/IdentityStore.java, src/web/security-certificate-store-management.jsp
This pull request adds checks that prevent catastrophic failures when configuration is not as-expected. This allows, for example. the admin console to start up with a non-encrypted port only when TLS configuration is incorrect.
Also: added basic support for editing of certificate store management properties and improved error notification on th admin console.
=> OF-1049: Fixes for certificate management

src/java/org/jivesoftware/openfire/keystore/IdentityStore.java
OF-1049 fix provided by aberenguel in https://github.com/igniterealtime/Openfire/pull/514
This PR contains the SHA-1 to SHA-2 commit from the original PR. As it's a major change, we shouldn't add that in a patch release (4.0.1), but we do want this on master (4.1.0).
=> Improve certificate signatures with SHA-2 functions

src/java/org/jivesoftware/openfire/container/PluginManager.java
The unmodifiable collection in the original code is not immutable: when
the original collection is modified, this is reflected (which can cause
problems in iterators created from the unmodifiable collection). This
commit creates a new collection to prevent this from happening.
=> OF-1051: Prevent ConcurrentModificationException

src/java/org/jivesoftware/util/TaskEngine.java
Do not allow TimerThread to exit when the server becomes heavily loaded,
preferring instead to use the caller's thread to execute a scheduled
task when needed. This may result in a temporary slowdown, but is better
than a hard failure which requires a restart of the server.
=> OF-1063: Prevent TimerThread from exiting

src/java/org/jivesoftware/openfire/http/HttpBindServlet.java
In the current read scheme for Openfire, it is possible that due
to variable width encoding that we sometimes only create a
string with a partial character.
This breaks the message text and causes encoding issues when read.
This change modifies the way the characters are
read to use an bytearrayoutputstream and
only do the string conversion once.
Since we only do the string creation once after the full
buffer is read, we no longer have encoding
issues with broken unicode characters.
=> Fix unicode read on input

src/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java, src/java/org/jivesoftware/openfire/disco/IQDiscoItemsHandler.java
I've removed the "userFeatures", because I think a user cannot have features.
As per XEP-0163:
The server MUST return an identity of "pubsub/pep" on behalf of the account (as well as a list of the namespaces and other features it [the server?)] supports)
Anyway, the old logic only returned one feature (disco#info) for the user,
which was wrong, too (the pubsub features were missing at least)
disco#items addressed to the account (bare jid) or without 'to' attribute are treated the same now, too.
Also partially addresses OF-872.
=> OF-462 PEP should process IQ-gets that have no 'to' attribute.

src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
In #routeToComponent, it is first checked if the component is being hosted in the local JVM. If it was not found, then all nodes in the ComponentsCache are checked to find if the component is hosted by one of those. In this process, the local routing table is again searched for the component, because it may have been added after the previous check. However, after this search, there is no null check done for the searched route. This results in an NPE when the component was not found locally and the #process(packet) method is called on the object. 
This also prevents the code from searching other nodes that may have been in the nodes set. Added a null check to prevent this scenario.
=> NullPointerException in RoutingTableImpl.

src/web/user-summary.jsp
Some user providers might not provide a creation date for each user. There's no reason that the Admin Console should not be able to cope with that.
=> Admin Console: prevent NPE on missing user creation date.

src/java/org/jivesoftware/openfire/user/UserManager.java, src/test/java/org/jivesoftware/openfire/keystore/KeystoreTestUtils.java
When the property provider.user.className is set, a new UserProvider will be initialized.
Openfire should revert back to the default provider when that property is deleted.
=> OF-1094: Allow reset of UserProvider

src/java/org/jivesoftware/openfire/muc/spi/IQMUCRegisterHandler.java
With the current implementation, any user can send the register IQ to register with
a room as a 'member'. This also allows outcasts, that were banned from a room, to be
able to register again as a member, and eventually re-join the room. The solution is
to prevent outcasts from registering with the room.
=> Outcasts should not be allowed to register with room.

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/openfire/sasl/AnonymousSaslServer.java, src/java/org/jivesoftware/openfire/sasl/ExternalClientSaslServer.java, src/java/org/jivesoftware/openfire/sasl/ExternalServerSaslServer.java, src/java/org/jivesoftware/openfire/sasl/Failure.java, src/java/org/jivesoftware/openfire/sasl/JiveSharedSecretSaslServer.java, src/java/org/jivesoftware/openfire/sasl/SaslFailureException.java, src/java/org/jivesoftware/openfire/sasl/SaslServerFactoryImpl.java, src/plugins/fastpath/src/java/org/jivesoftware/xmpp/workgroup/WorkgroupManager.java, src/web/user-summary.jsp
A bit of rework of the SASL implementation. This commit changes the signature of SASLAuthentication,
so that it can be used to register/deregister new SASL mechanisms (represented by the new interface
SaslMechanism). Existing mechanisms have been pulled out of the original, bulky SASLAuthentication
class.
=> OF-1092: Pluggable SASL mechanism

src/java/org/jivesoftware/util/cert/SANCertificateIdentityMapping.java, src/test/java/org/jivesoftware/util/CertificateManagerTest.java
Please refer to OF-1100 for the rationale of this change.
This commit adds a couple of unit tests, of which two tests fail without the changes in this commit.
The way how I construct certificates in the unit tests (notably: the subjectAltName extensions) is copy/pasted from Google results. I'm not sure that this is the correct way of going about. I appreciate feedback on that, as well as generic feedback on the solution itself (although arguably, that should better be added as a comment on OF-1100).
=> OF-1100: Allow for subjectAltNames of type 'DNS'

src/java/org/jivesoftware/openfire/keystore/OpenfireX509TrustManager.java, src/test/java/org/jivesoftware/openfire/keystore/KeystoreTestUtils.java
There's one unit test that occasionally fails. This occurs as a result of an unintended
collision. As part of the test, many certificates are generated and stored in keystores.
The alias used for the entry was based on the hashcode of the public ke of the certificate.
The value range of those hashcodes is fairly small (it has only a couple of digits), which
leads to occasional collisions, causing the test to fail.
This commit replaces the hashcode-based alias with the Base64-encoded public key information.
This ensures that aliases for distinct keys are also distinct, while ensuring that the
aliases for equal keys are equal.
=> Prevent occasional failure of CheckChainTrustedTest

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler.java
IQ result should be the last stanza. This way, clients know that the
last archived message has arrived.
=> OF-1089: Send IQ result only after messages

src/java/org/jivesoftware/openfire/nio/NIOConnection.java
Since the release of Openfire 3.9.3, users have reported problems with
"ghost" sessions left on the server. After reviewing the changes that
went into the 3.9.3 release, it seemed the fix for OF-464 may have had
some side effect causing this.
Since Igniterealtime's Openfire was reproducing OF-829, I did a test
whereby the functional changes of Igniterealtime/Openfire@ad08cae
were reverted.  After 36 hours, there were no ghosts!  Thinking about
this further, I think that only the change made to deliverRawText may
be to blame here.  Typically, this is used as a last gasp attempt
at delivering data to a connection that is closing/about to close.
The hope is that this change does not necessitate reopening OF-464.
=> OF-929 prevent ghosts by removing ioSession check

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/database/monitoring_db2.sql, src/plugins/monitoring/src/database/monitoring_hsqldb.sql, src/plugins/monitoring/src/database/monitoring_mysql.sql, src/plugins/monitoring/src/database/monitoring_oracle.sql, src/plugins/monitoring/src/database/monitoring_postgresql.sql, src/plugins/monitoring/src/database/monitoring_sqlserver.sql, src/plugins/monitoring/src/database/upgrade/4/monitoring_db2.sql, src/plugins/monitoring/src/database/upgrade/4/monitoring_hsqldb.sql, src/plugins/monitoring/src/database/upgrade/4/monitoring_mysql.sql, src/plugins/monitoring/src/database/upgrade/4/monitoring_oracle.sql, src/plugins/monitoring/src/database/upgrade/4/monitoring_postgresql.sql, src/plugins/monitoring/src/database/upgrade/4/monitoring_sqlserver.sql
This is my first commit for this project so i do not know much about the rules when it comes to database changes.
The objective of this pull request is to improve the queries done on a PostgreSQL setup for the message archives.
I have checked that there are several WHERE clauses to the fields fromJID, toJID of the ofMessageArchive table.
The indexes i have added should improve performance on PostgreSQL setup and WILL avoid sequential scan over those fields. Sequential scan are bad when you have lots of messages, rooms and users, which is our company case.
The diff shows changes to the entire file but that is because the file was filled with "^M" chars at the end of every line.
The only changes are: 
CREATE INDEX ofMessageArchive_fromjid_idx ON ofMessageArchive (fromJID);
CREATE INDEX …
=> Adding indexes to PostgreSQL for message search query improvement

src/java/org/jivesoftware/openfire/spi/ConnectionListener.java
Stored preferences of encryption protocols and/or cipher suites might include
non-supported items. To prevent issues, the list of preferences should be checked
against the currently supported items.
=> OF-1118: Don't try to use unsupported encryption settings.

src/plugins/search/src/web/advance-user-search.jsp, src/web/user-properties.jsp
Some user providers might not be able to provide a creation date. There's no reason
that the admin page should fail over that.
Note that this commit completes commit 2746a7f409b075bbeb74fba37bda6765a0fe2b6d,
which had an correct but incomplete fix for the same problem.
=> OF-1093: Allow for empty/unknown user creation dates.

src/java/org/jivesoftware/openfire/muc/MUCRoom.java, src/java/org/jivesoftware/openfire/muc/spi/IQAdminHandler.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, src/web/muc-room-occupants.jsp
Also include the actor in every presence, not just the presence sent to the kicked occupant, so that other occupants know, who kicked whom.
This is achieved by not creating a copy of the presence.
=> Include nickname in actor element when kick a MUC occupant.

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep/AbstractXepSupport.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/Xep0136Support.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/Xep0313Support.java
Description [here](https://community.igniterealtime.org/thread/56546).
The problem was due to a wrong namespace for the IQHandler This does NOT fix the [OF-1078 issue](https://community.igniterealtime.org/external-link.jspa?url=https%3A%2F%2Figniterealtime.org%2Fissues%2Fbrowse%2FOF-1078)
=> Fix non-working XEP-0136 for monitoring plugin

src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteSession.java
The doSynchronousClusterTask method can return a null when the cluster
node info can't be found.  This will cause an NPE in some methods that
try to autobox the null to a primitive.
This change forces some default for those values that return primitive
types.
=> Fixing NPE in RemoteSession

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Removing registration from room calls #addNone, which removes the requester
JID from all affiliation lists. But #applyAffiliationChange sets the affiliation
back to 'member' after it does not find the JID in any affiliation lists. It
should set the affiliation to 'none' before sending the updated presences.
=> Set affiliation to 'none' after removing registration from room.

src/java/org/jivesoftware/openfire/group/AbstractGroupProvider.java
The abstract implementation of GroupProvider should not hide the thrown
clause as defined by the createGroup() signature.
=> OF-1126: Abstract implemenation should not change signature

build/eclipse/classpath
Verified as building and launching successfully under Eclipse Luna.
Note that this still requires the eclipse "launcher" to be tuned to point to correct Openfire home and libdir plus references to resources like the sidebar.
=> Update eclipse project file to reflect changed list of jars. 

build/eclipse/classpath
Add their source directories and libraries where possible. 
Unable to add:
- clustering - seems dependant on coherence library not in repo
- rayo - duplicate classes cause clashes with jingleNodes and nodejs plugins so I've skipped adding it for now
e.g.
org.xmpp.jnodes.RelayChannel - in both jingleNodes and rayo
org.jitsi.util.OSUtils - in both nodejs and rayo
For the duplicate classes - I understand that plugins are isolated class-loader wise - but the clashes means you can't use a single eclipse project with them in. If these classes can't be moved to a common library the traditional approach with eclipse would be to have individual projects per plugin. Perhaps I should take this discussion to your forums - or you've indicated your reluctance to have such things in the repo, so maybe …
=> Eclipse project: Add extra plugins

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRole.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Previous stanza had status code 321 (membership revoked), but still had the owner and role set to the old role:
affiliation="owner" role="moderator"
Now it is the correct role after revoking membership:
affiliation="none" role="none"
(sorry for the presenceUpdated method. I don't know why git thinks there are changes. I tried 3 times without formatting anything there and it's always the same).
=> Include correct affiliation and role after revoking MUC membership.

build/build.xml, build/rpm/openfire.spec
Ant RPM build configuration is modified such that:
- rpmbuild arch of x86_64 is now default.  This will require a
change to the Ignite's Bamboo to specify a 64bit JRE to bundle
- the rpmbuild arch logic is simplified and one can now specify
which arch to build for by setting `-Drpmbuild.arch=<arch>`
- the resulting RPM filenames are changed, such to allow upgrades
between alpha builds, beta/rc builds and GA builds without
having to `rpm --force` these.  See note below on the new
RPM filenames.
- the changelog field in the RPM will contain the hash of the
last commit in the local repository `git rev-parse --short HEAD`
- A new `git.revision` Ant target is introduced so support the
inclusion of this in the build metadata
New RPM filenames:
For General Releases we get x.y.z-1
For Alpha …
=> OF-1111 Rethink RPM build and versioning

src/java/org/jivesoftware/openfire/LocalSessionManager.java, src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/multiplex/ClientSessionConnection.java, src/java/org/jivesoftware/openfire/multiplex/ConnectionMultiplexerManager.java, src/java/org/jivesoftware/openfire/multiplex/MultiplexerPacketHandler.java, src/java/org/jivesoftware/openfire/multiplex/Route.java, src/java/org/jivesoftware/openfire/server/ServerDialback.java, src/java/org/jivesoftware/openfire/session/RemoteSessionLocator.java, src/java/org/jivesoftware/openfire/spi/BasicStreamIDFactory.java, src/plugins/clustering/src/java/com/jivesoftware/openfire/session/DeliverRawTextTask.java, src/plugins/clustering/src/java/com/jivesoftware/openfire/session/IncomingServerSessionTask.java, src/plugins/clustering/src/java/com/jivesoftware/openfire/session/ProcessPacketTask.java, src/plugins/clustering/src/java/com/jivesoftware/openfire/session/RemoteIncomingServerSession.java, src/plugins/clustering/src/java/com/jivesoftware/openfire/session/RemoteSession.java, src/plugins/clustering/src/java/com/jivesoftware/openfire/session/RemoteSessionLocator.java, src/plugins/clustering/src/java/com/jivesoftware/openfire/session/RemoteSessionTask.java, src/plugins/clustering/src/java/com/jivesoftware/util/cache/ClusterListener.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/DeliverRawTextTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/IncomingServerSessionTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/ProcessPacketTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteIncomingServerSession.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteSession.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteSessionLocator.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteSessionTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusterListener.java
To represent a stream ID, Openfire defines the StreamID interface. However,
that interface is hardly used. Instead, simple String representations are used
in most places.
StreamIDs should conform to some specifications (notably: they shouldn't
include XML special characters). An implementation of the StreamID interface
is a good place to enforce specifications like that.
This commit replaces all String-based stream ID representations with an
implemenation of StreamID. For clustering/hazelcast, the serialized string
is still being used to exchange data between nodes (I expect that this allows
older and newer cluster nodes to continue to exchange cache information within
the same cluster).
Also in this commit:
- StreamID implementations check for (and escape) XML special characters.
- …
=> OF-1125: Should use StreamID class instead of String.

src/web/setup/ldap-server.jspf
We had a user run into an issue where the ldap password was longer than
what the input field allowed. Size has been increased to a more liberal
maximum.
=> OF-1129: Increase maxLength of input fields

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler.java
If no 'xmlns' is set for the stanza then as per XML namespacing rules it would
inherit the default namespace, which is wrong (see XEP-0297).
=> OF-1132: Ensure that retreived messages have a namespace.

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
`Sasl.createSaslServer()` explicitly states that the value of `serverName` must be a fully qualified host name.
=> OF-477: SASL requires FQHN (not XMPP domain name)

src/web/plugin-admin.jsp
Working theory is that the encoding of this form prevents the csfr input field to be parsed properly by ParamUtils.
=> OF-777: Workaround for CSFR with file upload.

build/build.xml, build/debian/rules
The ?= was not setting JAVA_HOME, despite it not being set in the shell before starting the ant command. The build was then failing with a "You must specify a valid JAVA_HOME or JAVACMD!"
The := forces it to that path. Which is slightly brittle, but if someone else wants to figure it out they're welcome.
=> Forced set of JAVA_HOME

build/build.xml
* ```override``` defined just once (and set to false)
* a plugin can be skipped by setting a property ```plugin.pluginname.skip```  to true (for example: ```‑Dplugin.broadcast.skip=true```)
* plugins that are built set the property above, to prevent rebuilding during the same Ant invocation (speeds up parent/child plugin builds)
=> OF-1149: Improve build speed

src/java/org/jivesoftware/openfire/pep/PEPService.java, src/java/org/jivesoftware/openfire/pubsub/PubSubModule.java
Both PEP and Pubsub configure leaf nodes to store -1 items by default; however
this value is not corrected by the usual post-configuration checks to 1, and
this in turn means that when gathering the items to return, the single
item is removed.
This PR corrects the issue by setting the maxPublishedItems in the default
configuration to 1 instead in both cases.
=> OF-1141 Fix default configuration of PEP/PubSub

src/java/org/jivesoftware/openfire/auth/AuthProviderMapper.java, src/java/org/jivesoftware/openfire/auth/AuthorizationBasedAuthProviderMapper.java, src/java/org/jivesoftware/openfire/auth/HybridAuthProvider.java, src/java/org/jivesoftware/openfire/auth/MappedAuthProvider.java, src/java/org/jivesoftware/openfire/user/AuthorizationBasedUserProviderMapper.java, src/java/org/jivesoftware/openfire/user/HybridUserProvider.java, src/java/org/jivesoftware/openfire/user/MappedUserProvider.java, src/java/org/jivesoftware/openfire/user/UserMultiProvider.java, src/java/org/jivesoftware/openfire/user/UserProviderMapper.java
This commit introduces a new AuthProvider and UserProvider that, similar to the
HybridAuthProvider and -UserProvider can be configured to use more than one backend
store. Where the Hybrids iterate over all of their providers in an attempt to
fulfill a request, these new 'Mapped' variants will first determine what provider
is to be used for a particular user, and will then operate on only that provider.
This is useful where particular users are required to be restricted to specific
backends.
=> OF-1139: User-to-provider mapping

build/eclipse/classpath
As above extra libs needed to make the eclipse project error free after initial check out.
=> Add newly added jmxweb libs to the eclipse project classpath.

src/database/upgrade/22/openfire_oracle.sql, src/database/upgrade/23/openfire_oracle.sql
alter statements (at least in oracle 11g or earlier) do not allow the
COLUMN keyword after ADD in an ALTER statement
It looks like the update SQL for Oracle was copied from Postgresql? Or maybe it works on Oracle 12c? Anyway this fixes the DDL for Oracle 11g and I assume it would still work on Oracle 12c.
=> OF-1168 fix Oracle DDL to use varchar2 and fix alter statements

src/java/org/jivesoftware/openfire/group/ConcurrentGroupMap.java, src/java/org/jivesoftware/openfire/roster/Roster.java, src/java/org/jivesoftware/util/ConcurrentHashSet.java
The JDK 7 signature of ConcurrentHashMap#keySet() returns a Set, while JDK 8 signature
returns a KeySetView, which is a new class in JDK 8. As a result, using Java 7 to run
an Openfire instance that is compiled with Java 8 (using the -source/-target 1.7
compilation flags) causes a java.lang.NoSuchMethodError.
To work around this problem, this commit applies a workaround as presented by
Martin Buchholz in https://bugs.openjdk.java.net/browse/JDK-8151366
This commit should be reverted after Openfire stops to support Java 7.
=> OF-1116: Apply workaround for Java 7/8 compatibility issue

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/web/import-truststore-certificate.jsp, src/web/security-truststore.jsp
* OF-1173 EXTERNAL was not offered by default.
* OF-777 CSRF protection was broken for truststore management.
* OF-777 Truststore deletion redirected to the wrong success page.
=> OF-1173: X.509/TLS related fixes

src/java/org/jivesoftware/openfire/net/DNSUtil.java
Individual domains can be redirected to a specific handling host by use
of the DNS override property, dnsutil.dnsOverride
This patch allows a wildcard "*" entry to override all domains without
a specific override, for example:
dnsutil.dnsOverride = {*,127.0.0.1:5269}
... redirects all outgoing S2S traffic to port 5269 on localhost.
=> OF-1172 Add support for a wildcard DNS override

documentation/docs/db-integration-guide.html, src/java/org/jivesoftware/openfire/admin/JDBCAdminProvider.java
JDBCAdminProvider can read the list of admin users from a database
This was contributed years ago (before GitHub) at the same time when I added the _useConnectionProvider_ setting to all JDBC*Providers but it was never taken. This is another try. It is the only *Provider class that doesn't has a JDBC based implementation.
=> OF-1199: New JDBC based AdminProvider

src/java/org/jivesoftware/openfire/http/HttpBindManager.java
Documentation: http://download.eclipse.org/jetty/9.3.11.v20160721/apidocs/org/eclipse/jetty/server/handler/ContextHandler.html#setAllowNullPathInfo-boolean-
=> OF-1180: BOSH endpoints redirect all the requests with the trailing slash

build/debian/control
See discussion on PR #624 , it is not clear to me what the equivalent of this is for build-deps, but this will at least help those who installed Oracle JRE and not OpenJDK
=> OF-1177 allow java7-runtime-headless to satisfy .deb requirement

build/rpm/openfire.spec
Adds explicit requirement for jre-headless to be installed for the noarch RPM.
Note: the epoch is set to 1 for this requirement as well, which seems to be the convention based on https://fedorahosted.org/released/javapackages/doc/#_jvm
=> OF-1175 Require jre-headless >= 1:1.7.0 for noarch RPM

src/java/org/jivesoftware/openfire/lockout/LockOutManager.java
The LockOutManager stores a null LockOutFlag (the default) in the cache,
which shouldn't work (and doesn't in a cluster).
=> OF-1156 Do not store null LockOutFlag in Cache

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRole.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
This is related to f2386cc, where affiliation updates were not broadcast correctly to MUC occupants.
The error here is, when an owner/admin assigns the moderator role, the new role is not reflected in the presence broadcast.
So neither the actor, nor all other particpants get notifications about the new moderator.
=> OF-1146 Update presence after setting a MUC role.

src/java/org/jivesoftware/openfire/handler/IQPrivacyHandler.java, src/java/org/jivesoftware/openfire/privacy/PrivacyListManager.java, src/java/org/jivesoftware/openfire/privacy/PrivacyListProvider.java
From [here](https://community.igniterealtime.org/thread/59616)
There are 2 instances of PrivacyListProvider (one in PrivacyListManager and the other in IQPrivacyHandler)
The issue was : both instances have separate privacyListCount variables, which are filled during PrivacyListProvider constructor (== server startup).
Thus, if at server startup the privacyListCount is 0, and one of the instances adds a PrivacyList, the other will never be informed and discard all changes and reads.
Fix : make privacyListCount static.
=> OF-1206: PrivacyLists on first run

src/plugins/hazelcast/changelog.html, src/plugins/hazelcast/classes/hazelcast-cache-config.xml, src/plugins/hazelcast/plugin.xml, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCache.java
This pull request fixes the issues identified in the post at https://community.igniterealtime.org/message/261078 - i.e. a lack of time-to-live-seconds configuration, and an error when setting the MaxLifetime property
=> OF-1210 Correct the cache behaviour for Hazelcast backed caches

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
```
when canSendPrivateMessage is null will throw NullPointException
if use canSendPrivateMessage() method when canSendPrivateMessage
is null will return "anyone"
```
=> OF-1207 Fix join room send private packet issue

src/i18n/openfire_i18n_en.properties, src/web/index.jsp
Introduces i18n string of index.process_owner "OS Process Owner:".
On Windows, I believe the value field will be 'SYSTEM'
=> OF-190 show java process owner on admin console

src/java/org/jivesoftware/openfire/ldap/LdapManager.java, src/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java, src/test/java/org/jivesoftware/util/LDAPTest.java
As mentioned in https://community.igniterealtime.org/message/261521 the use of wildcards in the user search was broken when using LDAP.
=> OF-1226 Enable use of wildcard when searching users in LDAP

src/java/org/jivesoftware/openfire/http/HttpBindServlet.java
We've yet to find the root cause of the state=EOF errors we've been seeing (which may be caused by an issue in our infrastructure or possibly client implementation), but this server-side change stopped file desciptors from being leaked when the error is thrown.
For more details see discussion in https://community.igniterealtime.org/thread/58399
=> OF-1201: Complete context if an exception is thrown when setting read listener

src/java/org/jivesoftware/openfire/OfflineMessageStore.java
This change ensures that messages are received in the order that they were originally sent to the user that was unavailable/offline.
=> OF-1223 sort load of ofOffline by date

src/plugins/monitoring/src/database/monitoring_oracle.sql
since two long columns are not permitted in one table by oracle and the
datatype long is deprecated, the respective columns are changed to clob
=> OF-1212 adjust ddl statements for oracle

src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
Various non-conformances in message routing caused some odd behaviour where
combinations of outgoing PEP events failing to be delivered could cause
errors to be delivered to all available clients.
This fixes message routing for three cases:
- Headline messages sent to the bare JID are now broadcast.
- Headline emssages sent to an offline session are discarded.
- Groupchat messages sent to a bare JID are handed to offline processing,
however these should not occur.
- Errors sent to the bare JID are discarded.
=> OF-1171 Update message routing to RFC 6120

src/java/org/jivesoftware/openfire/forward/Forwarded.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler0.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler1.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/Result.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/Xep0313Support1.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java
This PR adds support for multiple versions of MAM in common deployment, the :0 and :1 versions.
While these two variants use much the same protocol, the message delivery and "fin" markers are
delivered in two different ways, and they therefore operate in a different namespace.
=> OF-1214 Update MAM (XEP-0313) to support :0 and :1 versions

src/java/org/jivesoftware/openfire/auth/AuthorizationManager.java
When a user is created due to successful authentication, now calls the full process of user creation, including firing events for plugins.
=> OF-1235 Fixes user_created event not being fired on user creation due to auth.

src/plugins/fastpath/changelog.html, src/plugins/fastpath/plugin.xml
Refactoring work done in 4.1 release of Openfire lead to an introduction of a requirement on `JiveSharedSecretSaslServer`
=> OF-1232 Bump fastpath minServerVersion to 4.1

src/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
Openfire previously would respond to all incoming domains with the IM domain,
this patch examines and validates the "to" attribute on inbound streams and
responds accordingly.
=> OF-1123 Respond to incoming streams with the right domain

src/java/org/jivesoftware/openfire/auth/AuthFactory.java, src/java/org/jivesoftware/openfire/auth/AuthProvider.java, src/java/org/jivesoftware/openfire/auth/DefaultAuthProvider.java, src/java/org/jivesoftware/openfire/auth/HybridAuthProvider.java, src/java/org/jivesoftware/openfire/auth/JDBCAuthProvider.java, src/java/org/jivesoftware/openfire/auth/MappedAuthProvider.java, src/java/org/jivesoftware/openfire/auth/NativeAuthProvider.java, src/java/org/jivesoftware/openfire/auth/POP3AuthProvider.java, src/java/org/jivesoftware/openfire/crowd/CrowdAuthProvider.java, src/java/org/jivesoftware/openfire/ldap/LdapAuthProvider.java, src/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java
This PR makes the existing SCRAM support use the AuthProvider interface throughout.
It should be noted that there is an internal API which pulls a "UserInfo" structure from the database
in a single call, and the individual API calls simply fetch this and extract the required portion.
It feels as though this UserInfo access ought to be a public API, perhaps?
=> OF-1104 Ensure SCRAM uses AuthProvider API

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
As noted in #642, we never generate "=" from a null successData, and other cases might not be handled correctly on observing the code.
Unlike #642, this maintains (and corrects) the <challenge/> handling code in this area, and combines it to a single sendElement() call used by both.
=> OF-1236 Handle and generate single equals sign in SASL exchanges properly

src/java/org/jivesoftware/openfire/auth/JDBCAuthProvider.java
This allows using nt password hashes in JDBC connections. This is useful if you have users that are imported from or stored with compatibility to active directory in mind. E.g. this is done in the Alfresco database.
=> Add NT hashing for JDBC connections

src/java/org/jivesoftware/admin/PluginFilter.java, src/java/org/jivesoftware/openfire/crowd/CrowdAuthProvider.java, src/java/org/jivesoftware/openfire/muc/MUCRoom.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java, src/java/org/jivesoftware/util/CertificateManager.java, src/java/org/jivesoftware/util/log/util/CommonsLogFactory.java
addresses warnings thrown by `ant javadocs`
=> javadoc fixes and remove legacy SVN RCS tags

src/java/org/jivesoftware/openfire/muc/HistoryRequest.java, src/java/org/jivesoftware/openfire/muc/HistoryStrategy.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
This change means that room subject changes are no longer held within the
history transcript, but instead are always sent in a distinct action afterward.
Although this means that repeated changes will not be replayed in history, this
seems to be normal behaviour on other servers, and simplified the history replay
code considerably.
=> OF-1061 Always send room subject after history

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/XMPPServer.java, src/java/org/jivesoftware/openfire/XMPPServerInfo.java, src/java/org/jivesoftware/openfire/net/MulticastDNSService.java, src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/openfire/spi/XMPPServerInfoImpl.java, src/web/server-props.jsp, src/web/setup/setup-host-settings.jsp
This commit intends to have better default values for two properties of Openfire:
- the XMPP domain name (eg: igniterealtime.org)
- the FQDN of the server (eg: xmpp.igniterealtime.org)
Older code did not always make a clear distinction (ambiguously referring to
'server name'). Having a proper FQDN has become more important, as newer SASL
implementations depend on the client using the same FQDN as what is configured
in the server).
This commit removes support for changing the XMPP domain name at run time (although
you can obviously still change the corresponding property). Instead, the FQDN can
now be changes (although will require a restart).
Additionally, the XMPPServerInfo implementation got a bit of a refactoring: values
that are not expected to be modified (or considered unmodifiable …
=> OF-477: Improve default XMPP domain name and FQDN

src/java/org/jivesoftware/util/CertificateManager.java
Openfire, during setup, generates a certificate, that it cannot parse later.
This commit changes the generation routine, changing the subjectAltName value
from a tagged object to non-tagged string.
=> OF-1245: Prevent error while parsing self-generated certificate

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/net/DNSUtil.java, src/web/dns-check.jsp, src/web/index.jsp, src/web/style/global.css
This commit adds an admin console page that allows an administrator to evaluate
the DNS SRV configuration in context of the XMPP domain name and fully qualified
domain name of the sever that is running Openfire.
=> OF-1244: Admin console DNS SRV evaluation

src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
By adding an additional access check fo the remote domain in the main loop,
we avoid the need to tie up an OutgoignSessionPromise thread during S2S
initiation.
=> OF-1188 Add remote domain access check in main thread

src/java/org/jivesoftware/openfire/net/SocketReader.java, src/java/org/jivesoftware/openfire/net/StanzaHandler.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
In one case, the outgoing stream header includes the wrong domain, which causes an error in SASL EXTERNAL on some servers.
=> OF-1233 More cases

src/plugins/monitoring/src/web/archiving-settings.jsp
Removing the Effect.Fade strips a javascript error from blocking the rebuild; in addition I've added substantial logging around this to ensure nothing else was preventing it.
=> OF-1031 Ensure manual index rebuilds work

src/java/org/jivesoftware/util/cache/Cache.java, src/java/org/jivesoftware/util/cache/DefaultCache.java
This takes the previous (reverted) patch, and adds code to log the issue rather than treating it as a fatal error.
The property allow.cache.null is true by default so that this cannot do any harm (but will log scary messages).
=> OF-1156 Warn (and possibly die) on null storage in DefaultCache

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/filetransfer/proxy/FileTransferProxy.java, src/web/file-transfer-proxy.jsp
The file transfer proxy will listen on, and report, a set of network interfaces. Sometimes, the proxy
is not reachable on these addresses directly (for instance in a network environment where NAT comes
into play).
This commit re-purposes the 'xmpp.proxy.externalip' property. Earlier, this was used to make the proxy
bind to a specific interface. As this is quite similar to the functionality provided by the
'network.interface' property, 'xmpp.proxy.externalip' now controls only what interface is reported. It
no longer affect the interface binding process directly. This functionality has also been added to the
admin console.
=> OF-512: Allow 'reported' streamhost to be modified.

src/java/org/jivesoftware/util/cache/DefaultCache.java
Move the logged exception when `null` keys are allowed for storage to debug level.
=> OF-1252 Move and tweak null store cache message

src/database/openfire_mysql.sql, src/database/upgrade/25/openfire_hsqldb.sql, src/database/upgrade/25/openfire_mysql.sql, src/database/upgrade/25/openfire_oracle.sql, src/database/upgrade/25/openfire_postgresql.sql, src/database/upgrade/25/openfire_sqlserver.sql, src/database/upgrade/25/openfire_sybase.sql
Most database update scripts version 25 identify themselfs incorrectly as 24. This causes the update script to be executed each time that Openfire starts.
=> OF-1254 and OF-1255: Fix various database scripts.

src/web/setup/setup-admin-settings.jsp
Exception handling is used to determine if the default admin console username/password
applies. This exception handling should be more specific than depend on any Exception.
Instead, authentication-related exceptions should be used.
=> OF-1253: Be more specific when detecting default username/password

src/java/org/jivesoftware/openfire/group/GroupManager.java
When evicting cache entries for group members, the members of other
groups that are affected should also be evicted.
=> OF-1263: Improve cache invalidation for group metadata

src/java/org/jivesoftware/openfire/starter/JiveClassLoader.java
We had some patches in a jar in the lib folder and the jar was named something like aaa_patches.jar so that it would override classes in openfire.jar. This worked sometimes but it wasn't consistent across installations despite using the same versions of Java and the same OS. Files.listFiles() doesn't make any promises about the order it will return files in. (This patch sorts the list of jars so that the order is consistent across installations on the same platform (unix or windows, or everywhere if you don't have jars with mixed case filenames).
=> make sure jars in openfire lib are added to the classpath in predictable order

src/java/org/jivesoftware/openfire/http/HttpSession.java, src/java/org/jivesoftware/openfire/sasl/ExternalClientSaslServer.java
This patches the 4.1 branch so that EXTERNAL sasl auth works. Existing code was causing StackOverFlow error. 
It looks like my editor also removed trailing white space and removed unused imports, let me know if that is a problem.
=> OF-1290 fix EXTERNAL auth stackoverflow error - 4.1.x

src/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java
Adding elements and attributes to the new element doesn't work, since reparenting the old elements generates an exception. This exception wasn't logged.
* Exception logged
* id attribute copied, if present.
* Elements copied deeply/properly.
Test stanza:
```
<message xmlns="jabber:client" to="blah@conference.cridland.im" type="groupchat" id="5260">
<body>This is a message with a label.</body>
<custom xmlns='tmp:custom'/>
<custom-attr xmlns='tmp:custom2' attr='value'/>
<custom-child xmlns='tmp:custom3'>
<child>element</child>
</custom-child>
<custom-text xmlns='tmp:custom4'>Text here</custom-text>
</message>
```
=> OF-1271 Copy elements correctly

plugins/jmxweb/pom.xml, xmppserver/pom.xml
This commit introduces some dependencies that were added to Openfire since the original Maven stucture was build in #347. With these, the Maven build should compile again.
=> Another few Maven dependencies.

src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
We have a 2 node Openfire cluster (Openfire 4.1.1) and we create persistent chat rooms using the Rest API plugin (version: 1.2.5). When a chat room is created on node1 using the RestAPI it is propagated to node2 before completely processing it. This is causing a variety of issues. Here is a couple of examples:
1. If modification date is not set on the request we run into a HazelcastSerializationException when serializing the room (as org.jivesoftware.openfire.muc.spi.LocalMUCRoom.writeExternal assumes a non null modified date). 
2. The room is in a locked state when it is serialized and sent to the other node. So after a room is created on node1 if a client tries to join the room on node2 it will get an item-not-found error from Openfire. If node2 is restarted at this point then all is …
=> RestAPI plugin synchronizing invalid room state when creating a room in a clustered Openfire

src/java/org/jivesoftware/openfire/ldap/LdapManager.java
A new property (ldap.encodeMultibyteCharacters) is introduced that controls if multibyte characters in LDAP search queries are escaped.
Escaping of these characters started with the fix for OF-830, which appears to have caused OF-1305. Although I can't say that escaping of characters is wrong (per RFC 4515), it does cause real-world problems.
This fix defaults to not encoding again (reverting back to the behavior pre OF-830, without affecting other changes made in OF-830).
=> OF-1305: Make escaping of multibyte characters in LDAP search optional.

src/web/setup/setup-admin-settings.jsp, src/web/setup/setup-admin-settings_test.jsp
This fixes some encoding issues, preventing LDAP users that have an '@' character in their username from becoming admin.
=> OF-119: LDAP users with '@' sign can be made admin.

plugins/pom.xml
The build plans for the plugins should not inherit from the parent project, as this
ties their existence in with our parent project. Third party developers cannot do
this (without modifying the parent project structure). We should facilitate third
party developers, and use the same tools as we provide them.
This commit removes the parent/child dependencies between the top-level parent POM
and the plugins POM. There still as a parent/child dependency between the plugins
POM and each individual plugin.
Although I'm not sure this change is a complete solution, it is aimed to more closely
represent a development setup in which a third party developer might find itself. To
create a plugin of their own, they can now:
- Use our 'plugins' module directly (define it as a parent)
- Replace our …
=> OF-546: Plugins should not inherit from parent.

plugins/pom.xml, pom.xml, src/java/org/jivesoftware/admin/JSTLFunctions.java, webadmintld/pom.xml, webadmintld/src/assembly/taglib.xml, webadmintld/src/main/resources/META-INF/admin.tld, webadmintld/src/main/resources/META-INF/tags/admin/contentBox.tagx, webadmintld/src/main/resources/META-INF/tags/admin/infoBox.tagx
For plugins to be able to use the tags used in the admin console, the tags should be distributed in a library. By making this library a Maven module, plugins can define the library as a dependency.
Note that the admin.tld file is duplicated, but *slightly* modified in the Maven module: the path of the tags is different (META-INF vs WEB-INF).
=> OF-546: Distribute custom tags in a library.

src/java/org/jivesoftware/openfire/ldap/LdapManager.java
Openfire repeatedly searches for the same UserDN values. This cache should alleviate the backend storage and improve performance.
=> OF-1306: Add a cache for UserDN search results.

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/web/archiving-settings.jsp
The CSRF check was armed by default, which does not make sense when first visiting the page and no actions are requested.  This would result in an error shown that the 'Archive Index rebuild failed".  I also removed an unused css import
=> OF-1334 Don't do CSRF check unless actions are requested

src/java/org/jivesoftware/openfire/user/User.java, src/java/org/jivesoftware/openfire/user/UserManager.java, src/java/org/jivesoftware/openfire/user/property/DefaultUserPropertyProvider.java, src/java/org/jivesoftware/openfire/user/property/HybridUserPropertyProvider.java, src/java/org/jivesoftware/openfire/user/property/JDBCUserPropertyProvider.java, src/java/org/jivesoftware/openfire/user/property/MappedUserPropertyProvider.java, src/java/org/jivesoftware/openfire/user/property/UserPropertyProvider.java, src/java/org/jivesoftware/openfire/user/property/UserPropertyProviderMapper.java, src/plugins/justmarried/changelog.html, src/plugins/justmarried/plugin.xml, src/plugins/justmarried/pom.xml, src/plugins/justmarried/src/java/org/jivesoftware/openfire/plugin/married/JustMarriedPlugin.java, src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/pom.xml, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/JustMarriedController.java
This commit adds a new feature to Openfire, that allows one to store user properties in an external system. This is quite similar to concepts like UserProvider, AuthProvider, GroupProvider, and so on.
The default behavior, moved from the User class to DefaultUserPropertyProvider, continues to use the ofUserProp database table. Provider implementations matching those of other types of providers have been added.
=> OF-1336: Introduce UserPropertyProvider

src/java/org/jivesoftware/openfire/auth/AuthorizationBasedAuthProviderMapper.java, src/java/org/jivesoftware/openfire/user/AuthorizationBasedUserProviderMapper.java
This commit fixes a runtime problem caused by SortedSet usage with providers that are not Comparable. By using a different Set implementation, iteration order is predictable, without there being a need for providers being Comparable.
=> OF-1348: Can't use SortedSet without Comparable items.

.editorconfig
EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.
Note that this file defines very basic settings:
- line ending (unix-style)
- last line ends with a newline
- character set (UTF-8)
- indent uses 4 spaces
=> Adds an EditorConfig file.

src/java/org/jivesoftware/openfire/http/HttpBindManager.java
The static web content handler is allowed to be null (when there's no static content to be served). In such case, the null-handler shouldn't be loaded in Jetty (which will throws nullpointers).
=> OF-1326: Allow for missing static web content.

documentation/docs/index.html, documentation/docs/separating-admin-users-guide.html
Usage of Mapped providers requires a lot of configuration, that should be documented. The documentation provided in this commit describes a common use case, in which admins are to be retrieved from the default providers, while regular users are obtained from an external system.
=> OF-1345 OF-1139: 'Mapped' providers should be documented.

src/i18n/openfire_i18n_en.properties, src/web/setup/setup-profile-settings.jsp
This is a complex problem.  During setup, fetching xmppSettings from the session may fail due to an invalid session state maintained between the client browser and the server.  This is likely caused by a previous HTTPS session to the same server hostname setting a `JSESSIONID` that subsequently can not be overwritten by the current HTTP openfire-setup session.
This introduces i18n string `setup.invalid_session`
=> OF-1331 Warn user during setup when a session failure occurs

src/web/user-properties.jsp
This fixes a NPE that can present itself on the User Properties screen
Steps to reproduce:
- Attempt to view the User Properties for a user that does not exist, e.g. by accessing http://<server>:9090/user-properties.jsp?username=foobar
Expected results
- An indication is presented that the requested user does not exist
Actual results
- A stack trace is presented 
```
Exception:
java.lang.NullPointerException
at org.jivesoftware.openfire.admin.user_002dproperties_jsp._jspService(user_002dproperties_jsp.java:394)
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHan …
```
=> OF-1363: Fix NPE on User Properties screen

src/web/system-cache.jsp
The Admin Console allows caches to be emptied. This should not be allowed for all caches.
Openfire uses caches for two distinct purposes:
- To improve performance, where it's expensive to obtain certain data
- To share information in the cluster
It is possible that information that cannot be re-retrieved is stored in a cache (with the intend to share it in the cluster). Purging such a cache would irrecoverably delete information, almost certainly introducing problems. The internals of the routing table are based on such caches.
Openfire should not allow that caches are purged, when those caches store information that cannot be retrieved again.
=> OF-1365: Don't allow caches that do not expire to be purged.

src/java/org/jivesoftware/openfire/group/ConcurrentGroupMap.java
Fixing NullPointerException caused by having a mix of valid Groups and NULLs inside the result of getGroupsFromKeys. See: https://community.igniterealtime.org/message/265804
=> OF-1366: Fixing NullPointerException caused by NULLs in map

src/i18n/openfire_i18n_en.properties, src/web/login.jsp
Here's the message displayed with the username contains '@'
> Login failed: You provided what appears to be an email address, consider using just the user part (everything before the @). Typical installations use just 'admin' as the username.
=> OF-1368 Display more-useful admin console msg on user@ login failures

src/java/org/jivesoftware/util/cache/Cache.java, src/plugins/hazelcast/plugin.xml, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java
[NB. This is a re-submit of a previous pull request without superfluous commits]
I recently came across an issue whereby if you set a cache size/lifetime using Cache.setMaxCacheSize() / Cache.setMaxLifetime() it has no effect on Hazelcast backed Caches - configuration is taken solely from the hazelcast-cache-config.xml file.
This PR configures the underlying Hazelcast IMap based on the values that were previously set by these methods, defaulting to the values in hazelcast-cache-config.xml if not present. Some discussion on this can be found at https://groups.google.com/forum/#!topic/hazelcast/DYmHGo-sCnI
Note; currently it's not possible to modify these values after an IMap has been created -
the Javadoc for Cache has been updated to reflect this. hazelcast/hazelcast#592 suggests that …
=> Ensure that Hazelcast backed Cache objects have the correct settings

src/java/org/jivesoftware/openfire/session/ConnectionSettings.java, src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
A new properyt, 'xmpp.server.allow-anonymous-outbound-data' controls if client sessions that are anonymous can send data to remote domains. By default, they cannot.
=> OF-1208: Disallow (by default) S2S for anonymous users.

src/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
This PR allows a component to subscribe to XMPP pubsub nodes. Given a component is part of the Openfire deployment, it must already be trusted so there are no security issues.
=> Allow components to subscribe to nodes

src/java/org/jivesoftware/util/cert/SANCertificateIdentityMapping.java
This change allows a sub-class to support additional OID values in the certificate by overriding a single method.
I am extracting the "otherName" from a client cert (smartcard) and the OID is 
[1.3.6.1.4.1.311.20.2.3](http://www.oid-info.com/get/1.3.6.1.4.1.311.20.2.3) which this class doesn't handle. 
With the change in this pull request my subclass is able to extract the string value of otherName with the following code:
```java
protected String parseOtherName(ASN1ObjectIdentifier typeId, ASN1Primitive value) {
String otherName = null;
if (value instanceof ASN1TaggedObject) {
ASN1TaggedObject taggedObject = (ASN1TaggedObject) value;
ASN1Primitive primitive = taggedObject.getObject();
if (primitive instanceof DERUTF8String) {
otherName = ((DERUTF8String)primitive).getString();
} else { …
```
=> Support UPN OID extraction directly in SANCertificateIdentityMapping

src/java/org/jivesoftware/database/SchemaManager.java
PreparedStatements are not useful at this Point, because no parameters are set. They also prevent the creation of trigger in orcale, so use simple statements, see
[docs.oracle.com](http://docs.oracle.com/cd/E11882_01/java.112/e16548/oraint.htm#CHDIIDBE)
=> Using Statement instead of PreparedStatement

src/java/org/jivesoftware/openfire/admin/JDBCAdminProvider.java
The PR allows the JDBCAdminProvider to update the list of admin users, as well as simply retrieve them. 
Existing users will default to the current behaviour; i.e. the provider will be read-only unless the additional properties are set to allow users to be added/removed from the list.
=> Add option to make the JDBCAdminProvider read/write

src/plugins/hazelcast/changelog.html, src/plugins/hazelcast/plugin.xml, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/HazelcastPlugin.java
This PR switches to using a PluginManagerListener to wait for the plugins to load before attempting to start Hazelcast clustering, instead of an arbitrary delay of 5 seconds. 
We came across this when we were getting inconsistent behaviour on plugin startup; plugin A*** was working just fine, plugin W*** would, sometimes, get confused as clustering was started in the middle of it's plugin initialisation. Possibly less of an issue in OF version 4.2 as plugins will be loaded in parallel, but even so ...
I also added a missing changelog entry for version 2.2.2.
=> OF-1376 Use an event rather than an arbitrary delay before starting clustering

src/java/org/jivesoftware/openfire/ldap/LdapManager.java
This PR actually does very little; instead of hardcoding the class name - `"com.sun.jndi.ldap.LdapCtxFactory"` it is determined from the class itself - `LdapCtxFactory.class.getName()`
The only reason for this is to deliberately introduce an explicit warning at compile time, as the compiler now knows we're using an internal API. 
```
[of.javac] Openfire\src\java\org\jivesoftware\openfire\ldap\LdapManager.java:87: warning: LdapCtxFactory is internal proprietary API and may be removed in a future release
[of.javac]     private static final String DEFAULT_LDAP_CONTEXT_FACTORY = LdapCtxFactory.class.getName();
```
This may become more of an issue if/when Openfire moves to Java 9.
=> Determine the class name from the class, rather than hard-coding it

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/pubsub/Node.java, src/resources/jar/admin-sidebar.xml, src/web/pubsub-node-affiliates-delete.jsp, src/web/pubsub-node-affiliates-edit.jsp, src/web/pubsub-node-affiliates.jsp, src/web/pubsub-node-delete.jsp, src/web/pubsub-node-items.jsp, src/web/pubsub-node-subscribers.jsp, src/web/pubsub-node-summary.jsp
* Page for viewing existing affiliates
* Ability to delete affiliates (will remove all subscriptions)
* Ability to edit the affiliation type (subscriptions are updated
as appropriate)
Rebased on top of the PEP stuff so works there as well.
Note: I am not proud of the nested switch statement in pubsub-node-affiliates-edit.jsp, but it is just a reflection of how the current affiliate implementation works and I didn't want to mess with that.
=> OF 35 - Affiliates pages for pub sub admin console.

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/pubsub/Node.java, src/java/org/jivesoftware/openfire/pubsub/PubSubModule.java, src/java/org/jivesoftware/openfire/pubsub/PubSubServiceInfo.java, src/resources/jar/admin-sidebar.xml, src/web/pubsub-form-table.jsp, src/web/pubsub-node-affiliates-edit.jsp, src/web/pubsub-node-edit.jsp, src/web/pubsub-node-summary.jsp, src/web/pubsub-service-summary.jsp
Adding pages to configure the PubSub service and configure leafNodes.
Node configuration is based on existing Configuration forms mechanism, Data form is requested and a UI is generated from the form, the form is tailored slightly and there is some validation (on fields with users and groups). On submission the completed form goes back to the existing Node.configure() method.
Service configuration uses a similar mechanism in order to re-use form generation and processing code.
Note that these pages are (currently) only for PubSub and do not show up when viewing PEP nodes.
Second commit fixes a couple of bugs in previous OF-35 work including OF-1386.
=> OF-35 Node config and Service config pages

src/database/openfire_db2.sql, src/database/openfire_hsqldb.sql, src/database/openfire_mysql.sql, src/database/openfire_oracle.sql, src/database/openfire_postgresql.sql, src/database/openfire_sqlserver.sql, src/database/openfire_sybase.sql, src/database/upgrade/26/openfire_db2.sql, src/database/upgrade/26/openfire_hsqldb.sql, src/database/upgrade/26/openfire_mysql.sql, src/database/upgrade/26/openfire_oracle.sql, src/database/upgrade/26/openfire_postgresql.sql, src/database/upgrade/26/openfire_sqlserver.sql, src/database/upgrade/26/openfire_sybase.sql, src/java/org/jivesoftware/database/SchemaManager.java, src/java/org/jivesoftware/util/JiveGlobals.java, src/java/org/jivesoftware/util/JiveProperties.java, src/java/org/jivesoftware/util/PropertyClusterEventTask.java, src/java/org/jivesoftware/util/XMLProperties.java, src/web/server-properties.jsp
OF-1159 identifies the problem that changes to the file `conf/security.xml` are not reflected across all nodes in the cluster when a property is encrypted. This patch adds a `encrypted` column to the database, and uses that instead of a local file to identify is the property is encrypted.
Note; if a property is already encrypted by the presence of the indicator in `security.xml` then the database column will not be updated until that property is updated/deleted. It is at this time that the encryption indicator in `security.xml` is removed, but that will only happen on nodes that are part of the cluster at the time of the change.
=> Fix OF-1159 - add database column to identify encryption status

src/java/org/jivesoftware/openfire/XMPPServer.java
Note: this doesn't yet support every piece of configuration that the UI does, but does support most of it.
I was unsure exactly where the code should go, maybe a standalone class that the web UI uses too? But this is a start, and works for our purposes currently.
If `<setup>true</setup>` does not exist in openfire.xml (i.e. setup is not complete, and a block does exist called `<autosetup>` with a `<run>true</run>` property inside it, that looks like this:
```xml
<autosetup>
<run>true</run>
<locale>en</locale>
<xmpp>
<domain>localhost</domain>
<fqdn>localhost</fqdn>
</xmpp>
<encryption>
<algorithm>AES</algorithm>
<key>some-key</key>
</encryption>
<database>
<mode>standard</mode>
<defaultProvider>
<driver>org.postgresql.Driver</driver> …
```
=> OF-1412 Add automated setup support on first run

README.md
I replaced the info for the old Community with the info for the new Discourse one and added a link to the Community under Resources.
=> Update README.md for Discourse Info

src/java/org/dom4j/io/XMPPPacketReader.java, src/test/java/dom/io/XMPPPacketReaderTest.java
Openfire prevents the need to re-scope XML (as described in RFC 6120 section 4.8.3) by
pre-emptively remove certain namespaces (such as 'jabber:client' and 'jabber:server').
It should not, however, remove these namespaces everywhere. This commit prevents such
removal in places other than the first and second level elements (typically: stream
and stanza elements).
=> OF-1335: Don't strip namespaces everywhere.

src/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java, src/java/org/jivesoftware/openfire/http/HttpBindManager.java, src/java/org/jivesoftware/openfire/keystore/CertificateStore.java, src/java/org/jivesoftware/openfire/keystore/CertificateStoreConfiguration.java, src/java/org/jivesoftware/openfire/keystore/CertificateStoreManager.java, src/java/org/jivesoftware/openfire/keystore/CertificateStoreWatcher.java, src/java/org/jivesoftware/openfire/keystore/TrustStore.java, src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/openfire/sasl/ExternalClientSaslServer.java, src/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java, src/java/org/jivesoftware/openfire/spi/ConnectionAcceptor.java, src/java/org/jivesoftware/openfire/spi/ConnectionListener.java, src/java/org/jivesoftware/openfire/spi/ConnectionManagerImpl.java, src/java/org/jivesoftware/openfire/spi/LegacyConnectionAcceptor.java, src/java/org/jivesoftware/openfire/spi/MINAConnectionAcceptor.java, src/java/org/jivesoftware/util/CertificateEventListener.java, src/java/org/jivesoftware/util/CertificateManager.java
This commit grew a little larger than anticipated - my apologies for the reviewer. The original intend
for this was to allow changes in the java Keystore to be applied, without requiring a restart of Openfire.
This is what allows outside processes to update the Keystores - think Let's Encrypt - but could also be
useful for other purposes.
In the process of writing this code, I've found that a restart of the Connection Acceptor would still cause
all existing connections to be terminated. This is why a 'reload configuration' method was added.
I've found that the old Certificate Event Listener methods were unuseful. They were pretty detailled, but
all implementations used them in the same way: "reload everything". I've replaced those with one
'something changed' event. Also, the event …
=> OF-1373: Allow certificate changes to be applied without a restart.

src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
We already avoid this for other cases, but the simple case of A->C reusing the session for  B->C was not handled.
=> OF-1309 Do not try to piggyback on SASL authenticated sessions

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
This checks to see if any occupant exists with
the same full jid, and if so treats this as a
clientOnlyJoin (ie, rejoin).
=> OF-1422 Handle rejoins with nick-sharing

src/plugins/justmarried/changelog.html, src/plugins/justmarried/plugin.xml, src/plugins/justmarried/src/java/org/jivesoftware/openfire/plugin/married/JustMarriedPlugin.java
Still works as intended if you are just renaming a user.
Now, if you are using it to copy a user, the new users nickname, on other people rosters, will reflect the new name and not the old users nickname.
=> OF-1134 - Update copied users nickname on other users rosters

src/plugins/hazelcast/changelog.html, src/plugins/hazelcast/plugin.xml, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCache.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java
This PR works around the issue caused by not being able to update IMap settings in Hazelcast 3.5.x. 
I think a proper fix would be to update to Hazelcast 3.9, but that's probably a significant chunk of work and should probably wait until after 4.2.
=> OF-1416: Ensure that hazelcast cache entries expire correctly

src/java/org/jivesoftware/openfire/handler/PresenceSubscribeHandler.java, src/java/org/jivesoftware/openfire/roster/RosterItem.java
For example, PacketInterceptors may need to reuse these functions.
=> Allow code reuse from plugins

src/java/org/jivesoftware/openfire/websocket/OpenfireWebSocketServlet.java
Openfire already uses xmpp.parser.buffer.size as
the maximum stanza size in NIO client sessions.
This change ensures that this is also used when
configuring Websocket sessions.
=> OF-1423 Honour configuration for message size

src/java/org/jivesoftware/openfire/IQRouter.java, src/java/org/jivesoftware/openfire/RoutingTable.java, src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java, src/java/org/jivesoftware/openfire/server/RemoteServerManager.java, src/java/org/jivesoftware/openfire/session/DomainPair.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java, src/java/org/jivesoftware/openfire/session/RemoteSessionLocator.java, src/java/org/jivesoftware/openfire/spi/LocalRoutingTable.java, src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, src/java/org/jivesoftware/util/S2STestService.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/DeliverRawTextTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/OutgoingServerSessionTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/ProcessPacketTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteOutgoingServerSession.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteSessionLocator.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusterListener.java, src/plugins/kraken/plugin.xml, src/plugins/kraken/src/java/net/sf/kraken/TransportInstance.java, src/web/server-session-details.jsp, src/web/server-session-row.jspf, src/web/server-session-summary.jsp
Because we cannot always multiplex outgoing sessions, we may have multiple outgoing routes to the same domain.
This means that when we have a route A->B, and try to send traffic for conference.A->B, the traffic is rejected and the session closed, and we can end up creating a new session which becomes the new route to B, unsuited to traffic from A itself. This has some interesting (read, confusing) side effects, beyond simple loss of communication.
For example, if a user at B has a user at A in their roster, the session B-A is typically open before the user can join a room at conference.B. When joining, the stanzas associated with the join are all sent "at once", and promptly rejected. Other users then see both an unavailable (ie, leaving) presence from the user at B, followed by a …
=> OF-1309 Route based on DomainPairs

src/test/java/org/jivesoftware/util/StringUtilsTest.java
Test was looking trying to assure that after some time a number of seconds will pass, but with time units like "30 seconds". That was causing problems while I was building Openfire in Polish version of OS and units were named in Polish (e.g. second - sekunda). Credit for this to Guus but I was asked to PR this.
=> Fix for time assurance test

src/java/org/jivesoftware/openfire/handler/IQPingHandler.java
OpenFire was throwing a NPE when receiving a Ping request with the type attribute missing.
This PR will just make it return null, and not throw an exception.
=> OF-1431 Add null safety on packet.getType()

src/java/org/jivesoftware/openfire/http/HttpBindManager.java
This prevents errors (caused by the extensionHandlers to still be in 'running' state) when
restarting the HttpBindManager.
=> OF-1436: Handle lifecycle of manually added Jetty Handlers.

src/java/org/jivesoftware/openfire/session/LocalSession.java, src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java, src/web/session-details.jsp, src/web/session-row.jspf
This patch adds a lot of debug logging, plus stops the
console NPE'ing when you try to view a detached session.
It also detaches a session before trying to reattach it, to
avoid it being unrouted when the connection is closed.
=> OF-1437 Try to stop sessions having their routes removed

src/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
There is no point in calling `isRegisteredUser` (and thus making a `disco#info` query) if the sender is a component.
There is a bigger [issue](https://discourse.igniterealtime.org/t/calling-usermanager-isregistereduser-jid-from-i-o-handler-thread/79779) related to calling `isRegisteredUser` from the I/O handler thread. Beside optimization this fix avoids it for the components.
=> OF-1434 Check if sender is a component first in PubSubEngine::createNodeHelper

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
The logic here was wrong, but trying to handle SCRAM when we
could read the password, or there was native support. However,
the existing SCRAM code doesn't perform any fallback - instead
that's left to the AuthProviders themselves to implement.
So the new logic just assumes that an AuthProvider which can
provide that fallback will advertise it. If we later make this
support generic, it can go into the AuthFactory level.
=> OF-1430 SCRAM should just be used when supported

xmppserver/pom.xml
By default, the MINA artifacts pull in 'bundle' instead of 'jar' dependencies. This confuses Intellij,
and likely, other tooling. This commit excludes the 'bundle' dependencies, instead relying on the
fact that all excluded dependency-dependencies are present (as first-level dependencies of the project
itself).
This commit should not introduce any functional changes, but should facilitate developers.
=> OF-546: Exclude MINA bundles

xmppserver/pom.xml
Caused by the groupId changing from dom4j to org.dom4j between the two versions - so the older version needs to be specifically excluded.
=> OF-1442: Exclude the old version of dom4j

build/rpm/openfire.spec
Oracle and IBM JREs appear to provide 'jre' properly, whilst not java-headless
=> OF-1443 have RPM require java, instead of java-headless

src/plugins/gojara/changelog.html, src/plugins/gojara/plugin.xml, src/plugins/gojara/src/database/gojara_db2.sql, src/plugins/gojara/src/database/gojara_hsqldb.sql, src/plugins/gojara/src/database/gojara_mysql.sql, src/plugins/gojara/src/database/gojara_oracle.sql, src/plugins/gojara/src/database/gojara_postgresql.sql, src/plugins/gojara/src/database/gojara_sqlserver.sql, src/plugins/gojara/src/database/gojara_sybase.sql, src/plugins/gojara/src/database/upgrade/1/gojara_db2.sql, src/plugins/gojara/src/database/upgrade/1/gojara_hsqldb.sql, src/plugins/gojara/src/database/upgrade/1/gojara_mysql.sql, src/plugins/gojara/src/database/upgrade/1/gojara_oracle.sql, src/plugins/gojara/src/database/upgrade/1/gojara_postgresql.sql, src/plugins/gojara/src/database/upgrade/1/gojara_sqlserver.sql, src/plugins/gojara/src/database/upgrade/1/gojara_sybase.sql
This table does only exist in upgrade folder, and was did not exist.
It also contain a deprecation fix for SQL-Server 2016+ https://docs.microsoft.com/en-us/sql/database-engine/deprecated-database-engine-features-in-sql-server-2016#features-not-supported-in-a-future-version-of-sql-server
=> gojara Fixed ofGojaraSessions missing after install

src/database/upgrade/25/openfire_db2.sql, src/database/upgrade/25/openfire_hsqldb.sql, src/database/upgrade/25/openfire_mysql.sql, src/database/upgrade/25/openfire_oracle.sql, src/database/upgrade/25/openfire_postgresql.sql, src/database/upgrade/25/openfire_sqlserver.sql, src/database/upgrade/25/openfire_sybase.sql
This is an attempt to workaround an issue introduced whereby the database schema version is incorrect.  More info is here
https://discourse.igniterealtime.org/t/79916
I did not test this with mysql yet, as it has the most complex change to try dropping an index.
=> OF-1254 drop ofMucConvLog_msg_id index prior to creating it

pom.xml, src/plugins/pom.xml, xmppserver/pom.xml
This commit aims to make the Maven structure more compatible with Sonatypes guidelines for artifact distribution, as defined on http://central.sonatype.org/pages/ossrh-guide.html
A new Maven profile 'release' is added, that intends to produce all required artifacts. Usage: `mvn -P release clean verify`
=> OF-1447: Improve Maven structure

src/web/session-row.jspf
It assumes that all sessions are LocalClientSessions. But, in a multi-node hazelcast enabled openfire environment,
there may be remote (not local) sessions as well.  The bug is a cast of sess to LocalClientSession, but that isn't always appropriate. Session Details and Session Summary jspf pages use this jspf file
=> OF-1460, Session Row jspf has a Hazelcast related, type casting bug

src/java/org/jivesoftware/openfire/muc/HistoryStrategy.java
When specifying “Show a Specific Number of Messages” for Group Chat
History Settings, the user get one message to many. For example, if 10
is specified. the user get the last eleven messages in the room.
=> OF-1468 Group Chat History returns one message too many

src/java/org/jivesoftware/openfire/http/HttpBindManager.java
Currently the endpoint is only available via ws://host:port/ws/
It will now also be available via ws://host:port/ws
(note the lack of the trailing slash).
URLs without trailing slash seem to be the standard for BOSH and WebSockets and are also used by XEP-0156.
This commit increases interoperability.
=> WebSocket endpoint should allow null path.

src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusterListener.java
Avoid NPE Exception in ClusterListener, nodeCleanup, when there are no sessions on the node to cleanup
=> OF-1467, Check nodeRoutes.containsKeys(key) to avoid NPE 

src/plugins/callbackOnOffline/changelog.html, src/plugins/callbackOnOffline/plugin.xml, src/plugins/callbackOnOffline/pom.xml, src/plugins/callbackOnOffline/readme.html, src/plugins/callbackOnOffline/src/java/com/fotsum/CallbackOnOffline.java, src/plugins/callbackOnOffline/src/java/com/fotsum/MessageData.java
I've improved a bit CallbackOnOffline plugin. Things that has been changed: 
* Sending POST request instead of GET. I think POST is way more appropriate that GET, as we actually post some data. 
* Sending data in JSON body instead of query params
* Improved logs a bit (logging all properties on start if debug is enabled)
* **Sending body of message** in callback. This is main reason I updated plugin. Body of message is sent inside of JSON. Using property `plugin.callback_on_offline.send_body` it's possible to disable that feature. Enabled by default. 
* Updated readme and changelog 
Example JSON that is send in callback:
```JSON
{
"token":"21uh9d1h91d",
"from":"user@mychatapp.com",
"to":"user123@mychatapp.com",
"body":"Message body, so what user's typed"
}
```
=> Improved CallbackOnOffline plugin

src/web/pubsub-node-affiliates.jsp
When comparing JID to determine the order to show, do not assume full JID's. A affiliation is linked to a bare JID.
=> OF-1477: Sorting order should be based of bare JID

src/plugins/hazelcast/classes/hazelcast-cache-config.xml, src/plugins/hazelcast/classes/hazelcast-local-config.xml.template, src/plugins/hazelcast/readme.html, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/HazelcastPlugin.java
If it doesn't already exist, the Hazelcast plugin will create a file conf/hazelcast-local-config.xml that contains default network settings, etc.
This file is not replaced when the plugin is upgraded, thus preserving local configuration..
=> HZ-8: Preserve Hazelcast network settings between plugin upgrades

src/web/plugin-admin.jsp
I've replaced usage of `PluginDownloadManager.downloadPlugin` (in which we had the argument order backwards) with `PluginDownloadManager.installPlugin` (which is also used when initially installing, rather than updating, a plugin).
Simply fixing the argument order `PluginDownloadManager.downloadPlugin` would have done the trick, but introduced a UI issue. As the callback did not refer to the hashCode of the plugin that was modified, the update-spinner never got cancelled. By switching to `installPlugin`, we get this value immediately.
There are small functional differences between `downloadPlugin` and `installPlugin`, but they don't appear to affect the user experience at all.
=> OF-1464: Fix plugin updates via admin console.

src/java/org/jivesoftware/util/cert/SANCertificateIdentityMapping.java
I'm seeing the following error on startup when using a certificate signed by our internal CA, and I've also reproduced it when using a self-signed certificate with OpenSSL.
```
2018.02.17 22:20:50 WARN  [pool-4-thread-1]: org.jivesoftware.util.cert.SANCertificateIdentityMapping - Unable to parse a byte array (of length 29) as a subjectAltName 'otherName'. It is ignored.
java.lang.ClassCastException: org.bouncycastle.asn1.DERTaggedObject cannot be cast to org.bouncycastle.asn1.ASN1String
at org.jivesoftware.util.cert.SANCertificateIdentityMapping.parseOtherNameXmppAddr(SANCertificateIdentityMapping.java:239)
at org.jivesoftware.util.cert.SANCertificateIdentityMapping.parseOtherName(SANCertificateIdentityMapping.java:168)
at org.jivesoftware.util.cert.SANCertificateIdentityMapping.mapIdentit …
```
=> OF-1283 Handling xmppAddr in SSL cert being a type of ASN1TaggedObject

src/java/org/jivesoftware/util/CertificateManager.java, src/web/security-certificate-details.jsp
When displaying the details of a certificate, the admin console now also shows
its PEM representation. This is convenient for copy/pasting the certificate into
other tools.
=> OF-1493: Admin console: Show PEM representation of certificate.

src/java/org/jivesoftware/openfire/cluster/ClusterManager.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java
... this enables the cache migration to complete before Hazelcast is shutdown
=> HZ-11: Fire the left cluster event before we leave the cluster

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Upon External Serialization, do a null check on modificationDate. It is possible that the modificationDate is null, if the room was just created through REST API and Hazelcast enabled with more than 1 node in the cluster.  That results in an NPE, partial room creation, and failure in communicating the room updated event via hazelcast.
If modification date is null, send the creationDate value instead for the hazelcast room updated event
see https://discourse.igniterealtime.org/t/openfire-hazelcast-clustering-rest-api-room-creation-npe-when-no-modificaitondate-sent/80619/2
=> OF-1474_hazelcast_rest_api_create_room_npe

src/java/org/jivesoftware/openfire/session/LocalSession.java
I've found this after a round of testing by Daniel (of Conversations fame). I'm assuming, but was unable to verify, that this condition is caused by our recent addition of Stream Management - which leaves a session open, outliving its connection, perhaps.
=> OF-1481: Don't attempt to send over a non-existing connection.

src/java/org/jivesoftware/openfire/cluster/ClusterManager.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java, src/web/system-clustering.jsp
This turned out to be because the clustering didn't like being enabled as part of the Jetty thread - so it was necessary to start it in another thread, and wait for it to complete. 
I suggest it's a candidate for 4.2.3 as well as 4.3.0
=> HZ-9: Ensure clustering works properly when enabled through the admin UI

src/java/org/jivesoftware/openfire/net/StanzaHandler.java
This should introduce no functional change, other than properly log the event.
=> OF-1507: Handle S2S stream errors.

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Rest API and Multi-node Hazelcast cluster - Delete Room not propagated to other nodes
With this change, all nodes in the cluster are aware of room deletion.
=> OF-1540 Rest API, delete room should send RoomRemovedEvent to cluster

src/java/org/jivesoftware/admin/AuthCheckFilter.java, src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/auth/AuthFactory.java, src/java/org/jivesoftware/openfire/auth/AuthToken.java, src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/openfire/session/LocalClientSession.java, src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
The 'isAnonymous' method need not do a user lookup to determine if the associated session is using anonymous authentication. This information is available when the token is created. By removing this lookup, load is reduced.
Additionally, the token implementation itself need not contain data that is guaranteed to be identical for each token (the XMPP domain name).
Lastly, the AuthToken javadoc defines that the containing username will be null for anonymous users. This means that there's no need to track that status in an additional field.
This above leads to a simplification of the AuthToken implementation (less complexity is good for maintenance). This PR also removes one instance where the username is set to the resource-part value of an anonymous session. The Javadoc of getUsername() …
=> OF-1545: Authtoken and anonymous authentication

pom.xml, src/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java, src/java/org/jivesoftware/openfire/http/HttpBindManager.java, src/plugins/jmxweb/plugin.xml, src/plugins/jmxweb/pom.xml, src/plugins/jmxweb/src/java/com/ifsoft/jmxweb/plugin/OpenfireLoginService.java, xmppserver/pom.xml
In addition to simply changing the dependent version of Jetty, this PR includes;
1. Removing references to the long deprecated SPDY protocol
2. Use the GzipHandler instead of the deprecated GzipFilter for the BOSH handler
3. Modify the OpenfireLoginService in the JmxWeb plugin to comply with the updated interface for the Jetty LoginService
1) I am confident works
2) I don't have an easy way to test this, unfortunately
3) I don't even know where to begin on this plugin - but compiling is nearly the same as working, right? @deleolajide you may want to check that this still does what you expect.
=> OF-1527: Update to Jetty 9.4.10.v20180503

src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/handler/PresenceUpdateHandler.java, src/java/org/jivesoftware/openfire/roster/Roster.java
I don't think the fix for OF-454 ever completely worked. It is based on a presence broadcast that sends a presence update to all subscribed entities, as well as all resources of the same user that are available.
The problem lies in the fact that the presence update was 'recorded' in the client session only after this broadcast was done. When iterating over all client session to find resources that are available, the session from where the update originated, is still reporting the previous presence state (in case of a new session: unavailable).
To me, re-ordering events seem logical, and desirable for other reasons. It makes sense to first store the presence update in the client session, and only then broadcast the update.
=> OF-1433 / OF-454: Reflect presence updates

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/pom.xml, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler.java
Fix for preventing users to access message history (archive search) of a chatroom when they are no occupant in the chatroom at the moment of search.
The fix results in a Forbidden response being send when the requestor of the archive search is not an occupant in the chatroom.
See [Openfire 4.2.3 monitoring service 1.6.0 does not check user has the right to enter the archive] (https://discourse.igniterealtime.org/t/openfire-4-2-3-monitoring-service-1-6-0-does-not-check-user-has-the-right-to-enter-the-archive/82037)
=> OF-1566: Fix for archive search with password protected chatrooms

src/java/org/jivesoftware/openfire/ldap/LdapManager.java, src/web/security-certificate-details.jsp, starter/pom.xml, webadmintld/pom.xml, xmppserver/pom.xml
This PR contains a couple of smaller changes that allow the code to be compiled with Java 10, while remaining compatible with Java 8.
Note that even with these changes, Openfire still will not run with Java 10. At the very least, a [runtime issue with Apache MINA needs to be resolved](https://issues.apache.org/jira/projects/DIRMINA/issues/DIRMINA-1088). There likely are other problems too.
=> OF-1383: Changes to prepare for Java 9 onwards.

src/plugins/hazelcast/plugin.xml, src/plugins/hazelcast/pom.xml
(overlapping, unrelated commits meant thiis wasn't caught before the merge to master)
=> Make hazelcast a SNAPSHOT version as it depends on a SNAPSHOT Openfire

src/java/org/jivesoftware/openfire/container/PluginManager.java
If a plugin added a listener when the plugins were already loaded, then existing listeners were re-notified as well as the new listener.
This ensures that only the new listener is notified.
=> OF-1582: Ensure that only the newly added listener is fired

src/conf/openfire.xml
I recently noticed that whilst the "enabled if no property is present" is correct set to false, on new installs the property is set to true.
I also removed the requestFrequency (which defaults to 5 anyway).
=> OF-1563 (4.2.x): Ensure that stream management settings are not enabled on a new install

src/conf/openfire.xml
I recently noticed that whilst the "enabled if no property is present" is correct set to false, on new installs the property is set to true.
I also removed the requestFrequency (which defaults to 5 anyway) and the now redundant, commented out SPDY settings.
=> OF-1563: Ensure that stream management settings are not enabled on a new install

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
When a participant joins a MUC that it already is in (eg: a client state sync issue), Openfire should use the presence information from the latest join, not the original one.
=> OF-1581: Use latest presence info when syncing MUC join status

src/database/openfire_db2.sql, src/database/openfire_hsqldb.sql, src/database/openfire_mysql.sql, src/database/openfire_oracle.sql, src/database/openfire_postgresql.sql, src/database/openfire_sqlserver.sql, src/database/openfire_sybase.sql, src/database/upgrade/29/openfire_db2.sql, src/database/upgrade/29/openfire_hsqldb.sql, src/database/upgrade/29/openfire_mysql.sql, src/database/upgrade/29/openfire_oracle.sql, src/database/upgrade/29/openfire_postgresql.sql, src/database/upgrade/29/openfire_sqlserver.sql, src/database/upgrade/29/openfire_sybase.sql, src/java/org/jivesoftware/database/SchemaManager.java, src/java/org/jivesoftware/util/AesEncryptor.java, src/java/org/jivesoftware/util/Blowfish.java, src/java/org/jivesoftware/util/Encryptor.java, src/java/org/jivesoftware/util/JiveProperties.java, src/test/java/org/jivesoftware/util/AesEncryptorTest.java
Note 1; this only applies to the properties in the database. Encrypted properties in the `openfire.xml` all share the same, default IV. But as there are only two, and the only place they are used is in the same folder where we could save the IV (`security.xml`), there's no practical security advantage.
Note 2; If the Blowfish algorithm is used, an random IV is generated and saved, but it's not actually used during the decryption process.
=> OF-1533: Use a random IV for each new encrypted property

src/i18n/openfire_i18n_en.properties, src/web/user-summary.jsp
This reverts (most of) commit e1ee7a3c75b8110f921ae23b038d32cdd086d757.
The changes in the original commit caused all users to be obtained from
the user provider when looking at the user-summary page. For instances
with many users, this requires to much resources and takes to long to
complete.
=> Revert "OF-1542: Apply filtering to the user summary page"

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/Connection.java, src/java/org/jivesoftware/openfire/ConnectionManager.java, src/java/org/jivesoftware/openfire/net/BlockingAcceptingMode.java, src/java/org/jivesoftware/openfire/net/BlockingReadingMode.java, src/java/org/jivesoftware/openfire/net/ClientStanzaHandler.java, src/java/org/jivesoftware/openfire/net/ComponentStanzaHandler.java, src/java/org/jivesoftware/openfire/net/DNSUtil.java, src/java/org/jivesoftware/openfire/net/MultiplexerStanzaHandler.java, src/java/org/jivesoftware/openfire/net/ServerSocketReader.java, src/java/org/jivesoftware/openfire/net/ServerStanzaHandler.java, src/java/org/jivesoftware/openfire/net/SocketAcceptThread.java, src/java/org/jivesoftware/openfire/net/SocketAcceptingMode.java, src/java/org/jivesoftware/openfire/net/SocketConnection.java, src/java/org/jivesoftware/openfire/net/SocketReader.java, src/java/org/jivesoftware/openfire/net/SocketReadingMode.java, src/java/org/jivesoftware/openfire/net/SocketUtil.java, src/java/org/jivesoftware/openfire/net/VirtualConnection.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java, src/java/org/jivesoftware/openfire/server/ServerDialback.java, src/java/org/jivesoftware/openfire/session/ConnectionSettings.java, src/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java, src/java/org/jivesoftware/openfire/spi/ConnectionListener.java, src/java/org/jivesoftware/openfire/spi/ConnectionManagerImpl.java, src/java/org/jivesoftware/openfire/spi/LegacyConnectionAcceptor.java, src/test/java/org/jivesoftware/openfire/net/DNSUtilTest.java, src/web/connection-settings-socket-s2s.jsp, src/web/index.jsp, src/web/server-props.jsp
This adds support for doing 'direct' TLS (as opposed to StartTLS) when performing server-to-server communication (federation).
With this PR, Openfire can establish direct TLS s2s connections, and also can accept such connections.
=> OF-1579: Add support for XEP-0368 "SRV records for XMPP over TLS"

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, src/web/muc-create-permission.jsp
The existing options that allow an administrator to configure who is allowed to create new group chat rooms should get an additional option: allow all locally registered users to create rooms. This could be used to prevent anonymous users, and users from other XMPP domains, from creating rooms.
=>  OF-1553: Allow MUC room creation to be limited to registered local users.

src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
The `<resume/>` element sent by the client during a XEP-0198 session
resumption contains an `h` attribute which is validated to ensure it
has not acknowledged more stanzas than were actually sent.
However, we were validating that against the current session, whose
counters would be disabled, and therefore left at zero. This simply
checks them against the correct session instead - the `otherSession`
which is to be resumed.
=> OF-1590 Validate h against resumed session

src/java/org/jivesoftware/openfire/group/GroupManager.java, src/java/org/jivesoftware/openfire/lockout/LockOutManager.java, src/java/org/jivesoftware/openfire/privacy/PrivacyListManager.java, src/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java, src/java/org/jivesoftware/openfire/roster/RosterManager.java, src/java/org/jivesoftware/openfire/user/UserManager.java, src/java/org/jivesoftware/openfire/vcard/DefaultVCardProvider.java
For now, only applies to usernames.
It fixes some deadlocks between PrivacyListManager and RosterManager.
It is related to the two following issues
https://issues.igniterealtime.org/browse/OF-1337
https://issues.igniterealtime.org/browse/OF-944
=> OF-1337 OF-944: First attempt to standardize the String-intern-as-a-mutex hack.

i18n/src/main/resources/openfire_i18n_en.properties, i18n/src/main/resources/openfire_i18n_nl.properties, src/java/org/jivesoftware/openfire/handler/IQvCardHandler.java
When the VCard provider is read-only, there's no need to log a VCard update attempt
to the 'error' level. This commit reduces the log verbosity, and improves the error
sent back to the client.
=> OF-1592: Be less verbose when VCard updates fail expectedly.

i18n/src/main/resources/openfire_i18n_en.properties, src/java/org/jivesoftware/util/StringUtils.java, src/java/org/jivesoftware/util/cache/DefaultCache.java, src/web/system-cache.jsp
This shows the number of cache culls in the last 3/6/12 hours on the cache summary screen. Note that no cull counts are shown for clustered caches as the culling is done behind the scenes.
=> OF-1479: Show the number of cache culls in the last three hours

src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusterListener.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java
On startup the ClusteredCacheFactory calls the constructor of the ClusterListener, which calls the CacheFactory.isSeniorClusterMember(). This method checks if the clusterListerner object is null. This is always the case because the object is not set at this moment.
This pull request ensures, that that the markedAsSeniorClusterMember will be fired on startup on a single node (or the first) too.
=> Fix marked as senior event is not triggered

src/plugins/jingleNodes/pom.xml, src/plugins/kraken/pom.xml, src/plugins/pom.xml, src/plugins/rayo/pom.xml, src/plugins/sip/pom.xml, src/plugins/userImportExport/plugin.xml, src/web/pubsub-node-summary.jsp, src/web/session-summary.jsp, webadmin/pom.xml
This is a re-work of https://github.com/igniterealtime/Openfire/pull/1080
My poor git skills, coupled with a fairly significant amount of change in master, meant it was easier for me to do this in  a a new branch.
Note; where possible, I'm made sure that plugins depend on the 4.2.0 parent - where they depend on 4.3.0-SNAPSHOT, I've made sure that they also specify a minServerVersion of 4.3.0 as changes in the Jetty compiler mean that a plugin compiled against 4.3.0 will not work with 4.2.x (though a plugin compiled against 4.2.0 will work on 4.3.0 unless there are 4.3.0 specifics in play).
=> OF-1528: Allow Java 8 to be used when compiling JSP pages

src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
When an external component gets disconnected from a remote cluster node, the routing table
should remove the association for that component with that cluster node, instead of the
association for that component with the _local_ cluster node.
=> OF-1617: Correctly remove remote component routes from routing table.

src/java/org/jivesoftware/openfire/SessionManager.java, src/java/org/jivesoftware/openfire/container/PluginCacheRegistry.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, src/java/org/jivesoftware/util/cache/CacheFactory.java, src/java/org/jivesoftware/util/cache/CacheFactoryStrategy.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cluster/NodeRuntimeStats.java, src/web/system-clustering.jsp
This PR adds Java generics to the two `CacheFactory.doSynchronousClusterTask(...)` methods - and also updates the calls to those methods to reflect this change.
Note; I've not raised a JIRA for this as it's really an internal change - but happy to do so if it's thought necessary,
=> Genericize the calling of cluster tasks.

src/java/org/jivesoftware/openfire/http/HttpBindManager.java, src/java/org/jivesoftware/openfire/http/TempFileToucherTask.java
Introduces a task that, periodically, updates the 'last modified' date of all files in the Jetty 'tmp' directories. This prevents operating systems from removing files that it thinks are unused.
=> OF-1534: Jetty temp file toucher

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
Some fixes:
- a key reference was not fixed in the OF-1296 (line 502)
- the commit 15b31b08 removed the key prefix (line 610).
Specially the second one was causing some caching inconsistencies.
=> OF-1296: Fixing wrong keys for groupMetaCache

xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
The orphan component cache entry had a DEFAULT_NODE_ID as node ID
which was added before Hazelcast was initialized with a real node ID.
When the real node ID was ready and it was added to component cache
without removing the old entry.  So the component cache always had two
entries for a component.  When the component was disconnected, the
Component Manager believed that the component existed and prevented the
component to reconnect.
=> Remove an orphan component cache entry before adding a new one.

xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQPrivateHandler.java
Through OF-1515, a PEP/Private XML Storage conversion was added that can be used to manage
bookmarks via both mechanisms.
There's a protoXEP that describes this functionality: https://xmpp.org/extensions/inbox/bookmarks-conversion.html
It defines a namespace to identify this feature, which can be used by clients, to prevent them
from merging data obtained from both mechanisms (Gajim reportedly does this).
This feature is added to Openfire by this commit.
=> OF-1515: Add Bookmarks Conversion feature

xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
The routing table uses a cache that maps a bare JID to all full JIDs for a user.
The collection of full JIDs should not contain duplicates. Before the change for
OF-1589, this collection was defined as a Set, but changed to a List. This commit
changes it back to a Set, guaranteeing uniqueness again.
=> OF-1637: Ensure unique values for full-to-bare JID mapping

xmppserver/src/main/java/org/jivesoftware/openfire/vcard/DefaultVCardProvider.java
Fixed a confusing comment in ```DefaultVCardProvider``` that was probably just copy&pasted from the method above.
=> Fix Copy&Paste comment error

README.md, distribution/pom.xml
Also add appropriate dependencies to the disutribution project to make it
easier/quicker to build and run just the core Openfire server.
=> Update documentation to reflect the use of Maven

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
(The JRE doesn't contain a content type for CSS files, for example)
=> OF-1584 bis: Use the Jetty content type mappings instead of the JRE

build/debian/openfire.init.d
Might be useful.
```
root@app-server[192.168.100.83] ~ # /etc/init.d/openfire status
best java alternative in: /usr/lib/jvm/java-8-openjdk-amd64/jre
openfire is not running
root@app-server[192.168.100.83] ~ # /etc/init.d/openfire start
best java alternative in: /usr/lib/jvm/java-8-openjdk-amd64/jre
Starting openfire: openfire.
root@app-server[192.168.100.83] ~ # /etc/init.d/openfire status
best java alternative in: /usr/lib/jvm/java-8-openjdk-amd64/jre
openfire is running with pid 21048
root@app-server[192.168.100.83] ~ # 
```
=> Added a status function to init.d/openfire

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMetadataHelper.java
The initial bug report was against a long-retired plugin, but that's not to say it couldn't happen elsewhere so this PR protects against exceptions of this sort.
=> OF-1453: Protect against exceptions during plugin initialisation

plugins/restAPI/plugin.xml, plugins/restAPI/pom.xml, plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCInvitationEntity.java, plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java
This endpoint for the restAPI plugin allows to send MUC invitations on behalf of the chatroom.
An optional reason may be provided. It does _not_ change any memberships or room affiliations.
Tested (and works) on Psi+.
=> Add MUC invitation endpoint to restAPI

xmppserver/src/main/java/org/eclipse/jetty/util/WebAppLoaderFix.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
This is caused by a Jetty bug (https://github.com/eclipse/jetty.project/issues/1425) which has a workaround (https://github.com/gaohoward/jetty.project/commit/f5b86c8f13b12aba7120647ee29d82a514146f9b) that the HttpBindManager now takes advantage of.
Note; we may need to revisit this come Java 9.
=> OF-1522: Ensure Jetty contexts are fully cleaned

distribution/src/database/upgrade/27/openfire_db2.sql, distribution/src/database/upgrade/27/openfire_hsqldb.sql, distribution/src/database/upgrade/27/openfire_mysql.sql, distribution/src/database/upgrade/27/openfire_oracle.sql, distribution/src/database/upgrade/27/openfire_postgresql.sql, distribution/src/database/upgrade/27/openfire_sqlserver.sql, distribution/src/database/upgrade/27/openfire_sybase.sql, distribution/src/database/upgrade/28/openfire_db2.sql, distribution/src/database/upgrade/28/openfire_hsqldb.sql, distribution/src/database/upgrade/28/openfire_mysql.sql, distribution/src/database/upgrade/28/openfire_oracle.sql, distribution/src/database/upgrade/28/openfire_postgresql.sql, distribution/src/database/upgrade/28/openfire_sqlserver.sql, distribution/src/database/upgrade/28/openfire_sybase.sql, distribution/src/database/upgrade/29/openfire_db2.sql, distribution/src/database/upgrade/29/openfire_hsqldb.sql, distribution/src/database/upgrade/29/openfire_mysql.sql, distribution/src/database/upgrade/29/openfire_oracle.sql, distribution/src/database/upgrade/29/openfire_postgresql.sql, distribution/src/database/upgrade/29/openfire_sqlserver.sql, distribution/src/database/upgrade/29/openfire_sybase.sql, xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
Before:
version 27 Did the `ofPrivate`->`ofPubSub` migration with `OF1515.java`. This class used `JiveGlobals`, which reads from `ofProperty`.
version 28 Dropped `ofPrivate`
version 29 Added the `iv` column to `ofProperty`
With this PR:
version 27 Adds the `iv` column to `ofProperty`
version 28 Does the `ofPrivate`->`ofPubSub` migration
version 29 Drops `ofPrivate`
Tested with a new install of Openfire 4.2.3 on PostgreSQL, creating some private storage entries, then running Openfire 4.3.0-beta with this PR applied. ofPrivate entries were migrated to ofPubSub - though OF-1390 is still an issue when viewing entries the first time.
=> OF-1648: Add IV column to ofProperty before the ofPrivate migration

plugins/openfire-plugin-assembly-descriptor/src/main/resources/assemblies/openfire-plugin-assembly.xml
Note; this is required for https://github.com/igniterealtime/openfire-xmldebugger-plugin/issues/2 to ensure plugins can have their own log4j2 config. 
In an idea world, we would have a proper plugin repo structure
```
src/main/java
src/main/resources
src/main/webapp
src/test/java
src/test/resources 
```
etc. but that's something to tackle for another day ...
=> Ensure that the resources folder is included in the distribution

xmppserver/pom.xml, xmppserver/src/test/java/org/jivesoftware/Fixtures.java, xmppserver/src/test/java/org/jivesoftware/admin/AuthCheckFilterTest.java, xmppserver/src/test/java/org/jivesoftware/openfire/handler/IQEntityTimeHandlerTest.java, xmppserver/src/test/resources/conf/openfire.xml, xmppserver/src/test/resources/log4j2-test-mvn.xml
1. Introduce a mvn specific log4j2 config file that sends logging output to target/surefire-reports/test.log
2. Replace some System.out.println() statements with genuine assertions
3. Introduce a Fixture that re-configures openfire home to a folder containing a "blank" openfire.xml to prevent JiveGlobals.getProperty() from complaining to stderr in tests.
=> Reduce the amount of noise being sent to stdout/stderr;

.travis.yml, pom.xml
`mvn verify` will now generate javadoc and sources jar files too.
`mvn package` does not - as the generation can be slow which is a PITA during the dev/test cycle.
=> OF-1660: Generate javadoc artifacts as part of the verify phase

distribution/pom.xml
The PR ensures that the search plugin is properly included in the distribution.
~~DO NOT MERGE until there's a repo available containing the search plugin, and that repo is referenced by Openfire. Until then, the build will fail as org.igniterealtime.openfire.plugins:search:1.7.1 will not be found anywhere.~~
=> OF-1650: Add search.jar to the distribution-base

documentation/database.html
Documentation is suggesting to use super old MySQL versions, which are not even working with the currently included connector. So maybe we should suggest using recent and supported versions of MySQL. Also removed chapter about varchar as it is related to even older version of MySQL, probably not relevant for a long time. Updated reference link to the currently used version of connector.
=> OF-1669 don't use exact versions in db guide

xmppserver/src/main/java/org/jivesoftware/util/Version.java, xmppserver/src/test/java/org/jivesoftware/util/VersionTest.java
=> OF-1671: Ensure Openfire can copy with a non-snapshot four digit version (4.3 backport)

src/java/org/jivesoftware/util/Version.java, src/test/java/org/jivesoftware/util/VersionTest.java
=> OF-1671: Ensure Openfire can copy with a non-snapshot four digit version (4.2 backport)

i18n/src/main/resources/openfire_i18n_en.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, xmppserver/src/main/webapp/muc-sysadmins.jsp
When a MUC room is configured to require a password upon entry, a sysadmin should be able
to join the room (without providing the password).
The above will now be the default configuration. It can be configured, through the admin
console, on a per conference service basis (which is the same context in which sysadmins
are defined).
=> OF-1670: Allow MUC sysadmins to join a password protected room

i18n/src/main/resources/openfire_i18n_en.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, xmppserver/src/main/webapp/muc-sysadmins.jsp
When a MUC room is configured to require a password upon entry, a sysadmin should be able
to join the room (without providing the password).
The above will now be the default configuration. It can be configured, through the admin
console, on a per conference service basis (which is the same context in which sysadmins
are defined).
=> OF-1670: Allow MUC sysadmins to join a password protected room (4.3 backport)

src/i18n/openfire_i18n_en.properties, src/i18n/openfire_i18n_nl.properties, src/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, src/web/muc-sysadmins.jsp
When a MUC room is configured to require a password upon entry, a sysadmin should be able
to join the room (without providing the password).
The above will now be the default configuration. It can be configured, through the admin
console, on a per conference service basis (which is the same context in which sysadmins
are defined).
=> OF-1670: Allow MUC sysadmins to join a password protected room (4.2 backport)

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, xmppserver/src/main/webapp/muc-room-edit-form.jsp
Group chat logging (message archiving) is currently disabled by default. Nowadays, the typical user will expect that it'll be possible to retrieve history from the server. We should enable logging, by default.
=> OF-1674: Enable MUC archive logging by default.

xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/util/Log.java
Two changes; 
1. Enabling debug logging no longer enables trace logging
2. A new property, log.trace.enabled, which if set to true will enable trace logging and above. Note; as this is really only for use in special circumstances, there is no trace.log file (output instead is in all.log) and no specific UI for changing. Instead, it's necessary to change the property via the System Properties screen.
=> OF-1681: Enabling debug logging no longer enables trace logging

plugins/pom.xml, xmppserver/pom.xml
The thread at https://discourse.igniterealtime.org/t/where-is-the-admin-jsp-source-java-files-in-openfire-4-3-0/83971 reminded me just how useful it can be to have the .java files that .jsp files generate. This PR makes these files available (in `target/classes/org/jivesoftware/openfire/admin` or `target/classes/org/jivesoftware/openfire/[plugin]` - but doesn't not inflate the resulting JAR file by specifically excluding them.
=> Keep jsp source

i18n/src/main/resources/openfire_i18n_en.properties, xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemPropertiesServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/admin/DefaultAdminProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/AuthFactory.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/HybridAuthProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/update/PluginDownloadManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java, xmppserver/src/main/java/org/jivesoftware/util/ListPager.java, xmppserver/src/main/java/org/jivesoftware/util/Log.java, xmppserver/src/main/java/org/jivesoftware/util/StringUtils.java, xmppserver/src/main/java/org/jivesoftware/util/SystemProperty.java, xmppserver/src/main/resources/admin-sidebar.xml, xmppserver/src/main/webapp/WEB-INF/web.xml, xmppserver/src/main/webapp/logviewer.jsp, xmppserver/src/main/webapp/system-properties.jsp, xmppserver/src/test/java/org/jivesoftware/util/SystemPropertyTest.java
~~This is still a work in progress, but though I'd see if there was general support for this idea before I progressed further.~~
The idea is that a `SystemProperty` can represent the system properties currently accessed via `JiveGlobals`, stored in `ofProperty`. By providing a single place where they are referenced (the static method `SystemProperty.getProperties()`) it should be possible to incorporate their current/default values and description on the existing System Properties page. 
I'm not proposing to replace every access of JiveGlobals with this class, instead gradually migrate over time, and as more properties are migrated the System Properties page becomes more complete. 
Creating a sysprop can be done so;
```
final SystemProperty<Long> property = …
```
=> OF-1687: Introduce a new SystemProperty class

xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/BroadcastMessageRequest.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/BroadcastPresenceRequest.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Openfire has routines to broadcast message and presence stanzas to occupants in a room.
Up until this method, any exception that occurred would:
- not be logged;
- stop the broadcast to any pending intended recipients.
This commit adds logging, and makes sure that failure to deliver a stanza to one entity
does not prevent other entities from receiving it.
=> OF-1689: Isolate broadcasts & log problems.

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCUser.java
When a client sends a presence 'unavailable' stanza to leave a multi-user chat room, Openfire broadcasts not that stanza, but one that was received earlier (and is modified to include 'unavailable').
This appears to be an oversight, combined with a better-safe-than-sorry override of the presence type.
Openfire should broadcast the original stanza (modified to add some metadata where needed). This will, for instance, keep intact the reflected stanza ID.
=> OF-1692: Broadcast original 'unavailable' stanza when leaving MUC.

pom.xml, xmppserver/src/main/java/org/apache/mina/management/MINAStatCollector.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NIOConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/MINAConnectionAcceptor.java
What could possible go wrong?
In addition to bumping the MINA version it also required the implementation of a new null-operation methods of an interface that's been updated.
=> OF-1697 Update to MINA 2.0.20

xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
Why? The single responsibility principle. It makes more sense (to me)
to ask the Cache to lock a key rather than the CacheFactory, which should
concentrate on creating cache's.
Note that only the API changes; the implementation still resides in
CacheFactory. Easiest to leave it there until the deprecated method is
removed.
=> OF-1712: Introduce a new API to provide locking of Cache entries.

xmppserver/pom.xml
Openfire xmppserver unit test fails if the system locale isn't English. We can configure surefire plugin to start the JVM with a specific locale via the <argLine> option, so it only impact the unit tests.
[Forum thread](https://discourse.igniterealtime.org/t/openfire-xmppserver-unitary-tests-failing-because-of-locale/84549/2)
[JIRA](https://issues.igniterealtime.org/browse/OF-1713)
=> OF-1713 Unit tests shouldn't break because of non English system locale

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
following up on 
https://discourse.igniterealtime.org/t/localmucroom-savedtodb-state-change-not-propagated-to-other-nodes/84564
=> propagate saveToDb state change to other nodes in the cluster

xmppserver/src/main/webapp/setup/setup-admin-settings.jsp
Symptom:
(1) Complete a setup;
(2) Change the setup property in the openfire.xml to false and run set up again;
Result:
In the page to set admin password, the old password always fails validation.
Root cause:
When validating the old password, the hardcoded default password is used.
AuthFactory.authenticate("admin", "admin");
Solution:
Use real password to authenticate
=> The old password always fails validation if the admin password is not the default one "admin"

xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java, xmppserver/src/main/java/org/jivesoftware/util/JiveProperties.java, xmppserver/src/main/java/org/jivesoftware/util/XMLProperties.java
Symptom:
(1) Run setup;
(2) Change the setup property in the openfire.xml to false and run set up again;
(3) Set a different key;
Result:
In the setup-datasource-standard.jsp page, the db username is displayed as gibberish.
You can also see some error messages in the log file, something like "[ERROR] LWCrypto encryp or descrypt failed".
Root cause:
The original logic for encryption key update is unfinished.
Solution:
Keep an old key in JiveGlobals, so that when updating the encryption key both the new key (for updating) and the old key (for retrieving) are available.
For example, the method JiveProperties.put() has both updating (updateProperty(key, value, isEncrypted);) and retrieval (JiveGlobals.clearXMLPropertyEncryptionEntry(key) -> openfireProperties.getProperty(name)) operation.
In …
=> The encrypted properties cannot be decrypted correctly if your run multiple setups

xmppserver/src/main/java/org/jivesoftware/openfire/admin/DefaultAdminProvider.java
Prior to the OF-1687 changes, the list returned by `org.jivesoftware.openfire.admin.DefaultAdminProvider#getAdmins` was mutable. This commit restores that characteristic, which is depended on in other parts of the code.
=> OF-1687: Retain mutability in returned list of admin JIDs.

xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java
Got the OK from my employer to feed back some changes we maintained. This is the first of a few sets of changes, so if you want some other way to discuss or review, don't hesitate.
I realise you maybe want this split up with some discussion / rejection of each - that's fine - I realise your time is precious!
Issues these are to fix were seen by using an http-bind load tester (I can't release) along with using network parameters under linux to simulate 3G connections with out-of-order, duplication etc.
Contents:
(1) Unsynchronized use of packetsToSend - we've seen nullpointer exceptions in the server logs where the use of "packetsToSend.add" without a guard means that where they are being removed it's possible to get stale references
(2) sendPendingPackets - the logic there seems to only …
=> OF-1731: http-bind bug fixes + config tweak

xmppserver/src/main/java/org/jivesoftware/database/DbConnectionManager.java, xmppserver/src/main/java/org/jivesoftware/database/DefaultConnectionProvider.java
General comment: The (new) connection pool updates for recent Openfire are a welcome addition! - thanks for those changes.
One thing we (my society) perhaps do a little differently to a stock install is that we don't use the "failure looping" of the DB connection pool - we found that this means unfair queueing occurs under burst load.
We use a configuration where maxRetries = 0 with a larger maxWaitTime (2.5 seconds).
To help us get there, we made a couple of tweaks - contents:
(1) getConnection logic change - ensure sleep on failure only occurs if we are about to go around the loop and ask for another connection (when maxRetries = 0, this change stops unnecessary sleeps)
(2) poolConfig - if the minimum connections asked for in the db config are set - tweak the poolConfig so that this is …
=> DB Connection Pool Tweaks

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/admin/LdapUserProfile.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapVCardProvider.java
Now shown on the System Properties screen:
=> OF-1709: Make it clearer that the ldap.override.avatar setting is dynamic

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterMonitor.java, xmppserver/src/main/webapp/decorators/main.jsp, xmppserver/src/test/java/org/jivesoftware/openfire/cluster/ClusterMonitorTest.java
a) Admin Console now highlights when it is the only member
b) Message now sent when a node leaves the cluster, e.g.
`<node> has left the cluster - there is now only 1 node in the cluster`
c) Message is sent when a multi-node cluster is reformed
`<node> has joined the cluster - resilience is restored`
d) Message is sent when this node leaves the cluster (e.g. if clustering is disabled)
`The local node ('<node>') has left the cluster - this node no longer has any resilience`
=> OF-1699: Add additional clustering information

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
NB. This is largely causes by excessive optimisation.
=> OF-1686: Clear the group cache when deleting/adding groups

xmppserver/src/main/java/org/jivesoftware/openfire/PresenceRouter.java, xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/component/InternalComponentManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/component/RequestComponentInfoNotification.java, xmppserver/src/main/java/org/jivesoftware/openfire/entitycaps/EntityCapabilitiesManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/ComponentStanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NIOConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/PresenceManagerImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheUtil.java, xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultLocalCacheStrategy.java
This PR contains a number of changes that aim to improve the shared state of Openfire instances that are part of a cluster.
This PR is not intended to be merged (just yet), as more reviewing is needed.
At the time of this PR, I'm particularly interested in finding out how performant the state-update is, when one node leaves a cluster (other nodes will try to do a clean-up, which involves acquiring cluster-wide locks on most entries of some high-volume caches).
=> OF-1700 OF-1701 OF-1705 OF-1706 OF-1707 OF-1729 OF-1732: Clustered state improvements

xmppserver/src/main/java/org/jivesoftware/util/XMLProperties.java, xmppserver/src/main/webapp/setup/setup-datasource-standard.jsp
It turns out the code has double escaped XML entities in `openfire.xml` for a long time. This PR fixes that, and also tidies up the code where the preset values are translated in to JavaScript (which is where I first thought the issue lay, incorrectly as it turns out).
Note; This also updates the preset MySQL JDBC driver name (the previous one was complaining about being deprecated in the console), and sets UTF-8 as the preset charset.
=> OF-1682: Don't double escape XML entities

xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java
How to reproduce on HEAD:
(1) Create a second administrator account "dan"
(2) Using web browser 1 log in as "dan" and open up the sessions list in the admin console
(3) User web browser 2 log in as other admin, and revoke the admin permission for "dan"
(4) Dan can still refresh and use the admin console
I've tested the regular paths with admin console users - but in all honesty I haven't tested the "auth token" path (although the code seems OK to my eyes).
How is the auth-token path exercised? (Clustering maybe?)
=> Expire any admin console sessions if user admin rights revoked

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java, xmppserver/src/main/java/org/jivesoftware/util/SystemProperty.java, xmppserver/src/test/java/org/jivesoftware/Fixtures.java, xmppserver/src/test/java/org/jivesoftware/openfire/user/UserManagerTest.java
Note; there can still be a considerable delay when viewing groups with users of another domain that do not exist; this delay is the value of `usermanager.remote-disco-info-timeout-seconds` (default: 1 minute).
Once viewed, their lack of existence is cached in the `Remote Users Existence` cache (default: 30 minutes) so subsequent calls are much quicker until that cache expires.
Note; this caching/timeout behaviour is unchanged from before. It's just that the code no longer uses inappropriate thread synchronisation methods.
=> OF-1665: Fix issue when adding "missing" remote users to a group

.travis.yml
This commit causes Travis to compile the project not only with Java 8, but also with Java 11.
=> OF-1383: Have CI use both Java 8 and 11.

xmppserver/pom.xml
Openfire uses javax.xml.bind.DatatypeConverterImpl#DatatypeConverterImpl, a class that has been removed from Java 11.
This commit adds a library that provides this class, JaxB API, as a dependency to XMPPServer. This makes the class available in Java 11.
=> OF-1383: Add library removed from Java 11 for backwards compatibility.

xmppserver/src/main/java/org/jivesoftware/util/JavaSpecVersion.java, xmppserver/src/test/java/org/jivesoftware/util/JavaSpecVersionTest.java
Java 11 should be considered newer than Java 1.8. The change in this commit changes the comparison to only use the last numeric value.
=> OF-1737: Fix Java Spec version comparison.

xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/component/InternalComponentManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/ClientRoute.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheUtil.java
The ClientRoute class contains a reference to the server NodeID. This value must be updated when joining/leaving a cluster.
=> OF-1705: Update NodeID in ClientRoute

documentation/database.html
(as the drivers can't readily be distributed with Openfire)
=> OF-1757: Update Oracle JDBC driver instructions

xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java
Didn't include this in the original httpbind pull request - it's a lot of noise for what are only logging changes (and I wanted to clean up our version so it was less verbose). Hope that's not too annoying.
Contents:
(1) Removes some unnecessary string concatenation on the hot path in HttpBindServlet.onDataAvailable/Read/WritePossible, HttpSession.checkOveractivity
(2) Improve lifecycle logging - use streamID where applicable to streamline issue diagnosis
Possible modification: One change to this approach might be to place the lifecycle logging ("session ## created etc") behind a different logging switch in JiveGlobals to the raw RECV and SEND. I leave this for the feedback cycle.
Thanks for your time, patience and help @guusdk and @GregDThomas - this is the last of my pull requests (for …
=> httpbind: Improved Logging / Diagnostics

distribution/pom.xml, documentation/translator-guide.html, i18n/pom.xml, plugins/pom.xml, pom.xml, xmppserver/pom.xml
I've not raised a JIRA for this; not sure if it's entirely necessary as it's essentially just a housekeeping exercise to avoid getting too far behind in plugin versions.
NB. the native2ascii-maven-plugin could be updated from 1.0-beta-1 to 2.0.1 - but that requires a change in configuration I'm not entirely comfortable in verifying correctly (https://github.com/mojohaus/native2ascii-maven-plugin/wiki/Usage:-resources)
=> Update maven plugins

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/webapp/muc-room-occupants.jsp
Enable JiveGlobals kick reasons when kicking via admin console or via automated timeout.
We find these useful (audit reasons) - our application always fills in a kick reason, this change allows us to do the same for the Openfire server itself.
Not sure if the keys fit OK with existing JiveGlobals hierarchy
* admin.mucRoom.timeoutKickReason
* admin.mucRoom.consoleKickReason
=> OF-1772 Enable configurable kick reasons for admin console + timeouts

xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterMonitor.java, xmppserver/src/test/java/org/jivesoftware/openfire/cluster/ClusterMonitorTest.java
During testing of split brain recovery (https://github.com/igniterealtime/openfire-hazelcast-plugin/issues/23) it became clear that the cluster monitoring introduced in https://github.com/igniterealtime/Openfire/pull/1332 had two (minor) flaws;
* When the junior node loses network connectivity, it attempts to send a message as it is now senior; this message can be stored in the DB, which may also be inaccessible. This all takes some time (a few seconds) to fail. To avoid slowing down the (synchronous) raising of ClusterEventListener events the sending of messages is now done in a background thread.
* Ensure existing remote node names are cached when the local node joins the cluster, as well as when new remote nodes join.
=> OF-1699 revisited

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/net/SASLAuthentication.java, xmppserver/src/main/java/org/jivesoftware/openfire/sasl/ExternalClientSaslServer.java
The validity of the peer-provided PKIX certificate has already been verified when the TLS session was established. There should not be a need to re-validate. This commit adds a new option that allows Openfire to be configured to skip re-validation of the certificate.
=> OF-1746: Add option that allows certificate revalidation to be skipped (client)

xmppserver/src/main/java/org/jivesoftware/database/SequenceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/java/org/jivesoftware/util/JiveConstants.java
1. Use SequenceManager to assign the next messageID in ofMucConversationLog, instead of using select count(*) as part of the insert query, to solve 2 issues:
- In a clustered environment, with concurrent transactions taking place and default tx isolation level repeatable read, it was the cause of continuous deadlocks.
- If a process to remove old conversation logs is set up, having count(*) as messageID would lead to duplicates.
2. Instead of inserting conversation logs message by message, they're stored in batches as part of a single db transaction, to improve performance.
=> Improve concurrency and performance of conversation log history.

xmppserver/src/main/webapp/available-plugins.jsp
Additionally, it no longer takes 5 seconds before the download starts. I've left a 1 second interval, for the spinner to show (which I guess is expected UX).
=> OF-1781: Fix download of plugins via admin console

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java
The class that is used as the default SSL/TLS TrustManager (which checks certificates from peers) should be made configurable.
=> OF-1776: Make SSL TrustManager pluggable

xmppserver/src/main/java/org/jivesoftware/openfire/session/Session.java
This is intended to make the OF-1771 API change compatible with older/existing versions of the clustering plugin.
=> OF-1771: Make software version have a default value

distribution/src/database/openfire_db2.sql, distribution/src/database/openfire_hsqldb.sql, distribution/src/database/openfire_mysql.sql, distribution/src/database/openfire_oracle.sql, distribution/src/database/openfire_postgresql.sql, distribution/src/database/openfire_sqlserver.sql, distribution/src/database/openfire_sybase.sql, distribution/src/database/upgrade/30/openfire_db2.sql, distribution/src/database/upgrade/30/openfire_hsqldb.sql, distribution/src/database/upgrade/30/openfire_mysql.sql, distribution/src/database/upgrade/30/openfire_oracle.sql, distribution/src/database/upgrade/30/openfire_postgresql.sql, distribution/src/database/upgrade/30/openfire_sqlserver.sql, distribution/src/database/upgrade/30/openfire_sybase.sql, xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
An earlier change introduced a new ofID-based sequence used for messageID, when writing MUC messages to the database. This commit initializes the counter that's used to the highest value that has already been logged.
=> OF-1790: Initialize ofID sequences.

distribution/src/database/upgrade/30/openfire_db2.sql, distribution/src/database/upgrade/30/openfire_hsqldb.sql, distribution/src/database/upgrade/30/openfire_mysql.sql, distribution/src/database/upgrade/30/openfire_oracle.sql, distribution/src/database/upgrade/30/openfire_postgresql.sql, distribution/src/database/upgrade/30/openfire_sqlserver.sql, distribution/src/database/upgrade/30/openfire_sybase.sql
This modifies the update script to handle a scenario of an upgrade (as opposed to a fresh installation), but without having any logged MUC messages.
=> OF-1790: Database update scripts should handle empty table.

xmppserver/src/main/java/org/jivesoftware/openfire/nio/ConnectionHandler.java
While processing an exception that relates to Openfire not being able to write data to peers,
do not try to write an error to that peer (as we've previously established that writing things
to the peer is problematic).
=> OF-1784: Don't write error when data cannot be written.

xmppserver/src/main/webapp/group-edit.jsp
Groups imported through LDAP initially have no properties. The admin console checks the Contact List Sharing configuration of a group, by evaluating the value of the sharedRoster.showInRoster property. Previously, this needed to have the value 'nobody' for the group to be marked as 'unshared'. This commit ensures that a group is also shown to be 'unshared' if the property is not set at all.
=> OF-1793: Contact List Sharing for LDAP groups shows wrong setting.

xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceSubscribeHandler.java
Old code assumed that users were local users, while they need not be.
=> OF-1796: Fix presence probe after subscription from remote user

xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQBindHandler.java
The missing 'catch' statement caused the exception to be handled by the caller class, which applies a generic error.
=> OF-1802: Fix IQ error when using invalid resource during bind.

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
Hi, I tested Openfire 4.2.3 with 200,000 MUC rooms. And I found out loading MUC rooms can be very slow in proportion to the number of rooms. In my case, it needed over 1 hour to start Openfire.
I identified the cause in MUCPersistenceManager. (This problem still exists in Openfire 4.3 or later)
- After fetching MUC rooms from `ofmucroom` table, each `LocalMUCRoom` loads its default properties from `ofmucserviceprop` table with MUCPersistenceManager. This process calls `SELECT` SQL about 200,000 * 12 times (the 12 is the number of LocalMUCRoom.xxx fields). In the end, the more MUC rooms the more time needed.
I tweaked MUCPersistenceManager.getProperty just a little bit. By this fix, Openfire startup time become about 90 seconds in 200,000 MUC room.
Please review.
=> OF-1797 Accelerate loading MUC rooms

xmppserver/src/main/webapp/system-cache.jsp
Openfire uses various caches. The admin console displays a warning when the cache isn't very effective (hinting that reconfiguration is needed.
The current formula to determine if a cache is ineffective, combines these three parts (which all must be true):
- amount of successful cache lookups is more than 500
- percentage of successful cache lookups is less than 85%
- the amount of unused capacity in the case is 20% or less
The first condition is likely introduced with the intention to avoid having caches marked as 'ineffective' when they're hardly used (or when the system just started). However, this causes the cache to _not_ be marked 'ineffective' in a scenario where it has many, many lookups, but none of them successful (which clearly is an ineffective cache).
The first part of the …
=> OF-1800: Cache low effectivity calculation improvement

xmppserver/src/main/webapp/system-cache.jsp
This improves the visibility of ineffective cache usage in the admin console.
This is a screenshot of ineffective caches, after the changes in this commit were applied:
I've opted to both use a red color, as well as a small asterisk, to help people that have trouble seeing colors.
=> OF-1801: Cache low effectivity should be shown more prominent

pom.xml, xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQBindHandler.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CaffeineCache.java
The JID class uses three caches, in which the result of stringprepping is stored. The capacity of these caches is hardcoded.
For high-volume instances of Openfire, the hardcoded values might not suffice. It should be possible to reconfigure the caches. Additionally, it would be nice if the caches are displayed in the cache summary admin console page.
This commit pulls in a new version of the Tinder dependency, that is as of yet unreleased (I'm using a SNAPSHOT version here). Before we release Openfire with this change, this dependency must be replaced with a proper, non-SNAPSHOT release.
This is a screenshot of the admin console, showing the caches from the JID implementation being exposed. I've tested that setting the corresponding properties allows you to reconfigure the caches' size …
=> OF-1799: Allow JID caches to be configurable

build/debian/build_debs.sh, build/rpm/build_rpms.sh
maven already provides `search.jar` thanks to some work @GregDThomas did.
=> remove un-needed search.jar copy in build scripts

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/ConversationLogEntry.java
toString() applies a pretty print formatter, which mangles the formatting of message text. This introduces https://github.com/igniterealtime/openfire-monitoring-plugin/issues/36
=> OF-1804: Retain original formatting when logging messages

.travis.yml
Developers that have Openfire forked and setup for Travis will always see failures due to `deploy` failing (rightfully so).  This change should skip the `deploy` script when travis is run on the forked repos.  This change [worked](https://travis-ci.org/akrherz/Openfire/builds/551854288) for me.
=> skip travis deployment step for non-ignite builds

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
This commit ensures that a previously cached negative result ('no such group') causes an exception to be thrown, rather than null to be returned.
=> OF-1811: Prevent NPE in GroupManager

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
When stopping a service, the archiver should be removed, not added (again).
=> OF-1814: Fix delete conference service

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
When stopping a service, the archiver should be removed, not added (again).
=> OF-1814: (4.4 branch) Fix delete conference service

.travis.yml
Recently, the default distribution used by Travis was changed from 'trusty' to 'xenial'. See https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
In Xenial, oraclejdk8 is not available (although openjdk8 is).
Openfire depends on oraclejdk8. This commit explicitly defines 'trusty' to be used, which should make oraclejdk8 available again.
=> Travis: explicitly define distribution

xmppserver/src/main/java/org/jivesoftware/openfire/muc/HistoryRequest.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
When using the Openfire with the hazelcast plugin we had some ClassCastExceptions in the LocalMucRoom at line 685 like: 
`java.lang.ClassCastException: org.jivesoftware.openfire.plugin.session.RemoteClientSession cannot be cast to org.jivesoftware.openfire.session.LocalClientSession`
For my bad, I don't have the full stack trace.
With this pull request this error does not occur anymore. It lets the three classes use the interface and not the implementing class.
This may only fix one symptom of another problem.
=> OF-1817: Fix a ClassCastException in LocalMUCRoom.java

distribution/src/database/openfire_sybase.sql, distribution/src/database/upgrade/26/openfire_sybase.sql, distribution/src/database/upgrade/27/openfire_sybase.sql, distribution/src/database/upgrade/28/openfire_sybase.sql, distribution/src/database/upgrade/29/openfire_sybase.sql, distribution/src/database/upgrade/30/openfire_sybase.sql
In Sybase every column should be defined NONNULL/NULL constraint, observed some columns without NONNULL/NULL, fixed by adding NULL to columns.
Semicolons are removed because it stopping script to execute in Sybase.
Corrected some datatypes which are not supporting for Sybase.
Column name "serviceID" is corrected in index "ofMucRoom_serviceid_idx".
Also, corrected last 5 upgrade scripts.
=> OF-1818: Some errors in Openfire sybase db script and last 5 upgrade scripts are corrected.

build/rpm/openfire.spec
Newer rpmbuild appears to error out without this setting.  The alternative is to see if we can remove `libshaj.so` from the noarch RPM.  The blast radius of this change is more limited :)
=> MNT: add rpmbuild opt to ignore binary files in noarch

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java, xmppserver/src/main/java/org/jivesoftware/util/SimpleSSLSocketFactory.java
This commit removes the hardcoded TLSv1 protocol that was used to initialize most SSLContexts. It is replaces by a Java-provided default, which can be overridden by a new property, xmpp.auth.ssl.context_protocol.
=> OF-1827: Make SSLContext protocol configurable

xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
The implementation introduced by OF-1809 causes collections of DataForm instances to be processed.
The new contract defines that a set must be present - null values are not allowed.
It's easy to overlook this new contract. For example, our own code returned a null value, instead of an empty collection.
This commit modifies the return of a null value (it now returns an empty value). Additionally, this PR adds a guard for problems like this, by explicitly checking of a value is null.
=> OF-1826: Prevent NPE in new DataForms implementation.

xmppserver/src/main/webapp/setup/setup-admin-settings.jsp, xmppserver/src/main/webapp/setup/setup-admin-settings_test.jsp
The testing page for checking a a particular user (that's configured to be an Openfire admin) can be retrieved from LDAP contained an XSS vulnerability. This commit fixes that.
Many thanks to Luke Arntson for finding and reporting this issue.
=> OF-1192: Fixes Reflected XSS in LDAP Setup test

distribution/src/database/openfire_oracle.sql
Hi,
please see https://discourse.igniterealtime.org/t/cannot-insert-null-into-openfire2-ofgroupprop-propvalue/52384
=> OF-1828 Fix that an empty string can not be inserted in ofgroupporp.propvalue

README.md
This pull requests adds the instruction to debug Openfire in IntelliJ IDEA with build-in run configurations.
=> add debug instruction for IntelliJ IDEA to the README.md

Dockerfile, build/docker/entrypoint.sh
**Fixes entrypoint.sh**
The absolute path of java didn't match of that of the JRE image.
Fixed to be agnostic, by using `which java`
**Improved maven caching during Docker builds**
Previously would only cache if the entire source was unchanged.
Now, by only copying over items explicitly required to resolve maven deps, will cache if all pom files remain unchanged.
=> Fix and improve docker build

xmppserver/src/test/java/org/jivesoftware/openfire/handler/IQEntityTimeHandlerTest.java
Disables a test that fails the mvn package step when running in a docker environment (and presumably any lower-resource build environment).
Disabling felt sensible - I'm uncertain of the value of the assertions (1 million runs of an inbuilt Java date formatting function must take <2s, 1 million runs of an Openfire date formatiing function must take <4s) - why would we want the performance of an inbuilt Java function to block building in a slower env, and where did those thresholds come from?
V happy to take input on this PR - maybe this needs deleting, or perhaps someone knows the legacy of this check?
=> Ignore flaky test that fails in slower environments

xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
The error handler of SM sets the namespace to null, causing an NPE when the client tries to resume that session. This in turn causes the socket to be closed abruptly, which triggers a reconnect loop in Conversations.
=> OF-1835: Prevent NPE when resuming faulty SM session

xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
Openfire already supports conversion between 'PEP' and 'Private Storage' type of bookmarks, but this support predates XEP-0411.
Openfire's support should match XEP-0411.
=> OF-1839 : add XEP-0411 support

xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketUtil.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialback.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
The session creation event must not be triggered before the created session has been fully registered. This prevents an issue where a new session is established by stanzas being sent by the trigger.
Additionally, duplicate events should be prevented.
=> OF-1848: Prevent duplicate S2S session establishment

xmppserver/src/main/java/org/jivesoftware/openfire/keystore/CertificateStoreManager.java, xmppserver/src/main/webapp/security-certificate-store-management.jsp
This primarily facilitates integrating with Windows certificate stores, by setting the type of 'Windows-ROOT' for truststores, and 'Windows-MY' for identity stores.
=> OF-1854: Allow trust- and identitystores to be of different type.

xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
The isAnonymous check should not depend on the fact that the provided JID is a full JID. This will give incorrect results ('not anonymous') if the provided JID is bare.
This commit checks for any anonymous session that matches the bare JID - if there's one then that's enough (a user cannot be both anonymous and not anonymous).
=> OF-1856: Fix isAnonymous detection

xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/ServiceAddedEvent.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/ServiceRemovedEvent.java
This is an odd one; 
* Updating MUC services seems to be OK - handled by the ServiceUpdatedEvent cluster task.
* Cluster tasks exist for ServiceAddedEvent, ServiceRemovedEvent, but were never used.
* There was also a bug in the above two which meant that updating a MUC on node 1 would update the MUC on node 2 which would update the MUC on node 1 which would ... well, you get the idea. Perhaps this is why they were never used?
**NOTE:** I have been unable to test this in a cluster (!). I think it's OK, but it would probably be a useful exercise to do so.
=> OF-1858: Ensure that adding/deleting MUC services is cluster aware

Dockerfile, build/docker/entrypoint.sh
Current docker builds don't have working logging infrastructure due to missing log4j config.
I've pointed to the config file in the entrypoint script (and done a little housekeeping on the Dockerfile)
=> Fix docker logs

xmppserver/src/main/webapp/setup/ldap-server.jspf, xmppserver/src/main/webapp/setup/setup-ldap-server_test.jsp
This commit intends to prevent disclosure of a previously configured password for LDAP. Now, the LDAP configuration page will only show a password value if that was provided in the same HTTP session. Likewise, a password value that might already have been stored is not updated, unless explicitly changed.
=> OF-1873: Don't disclose LDAP adminPassword

xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/ClientRoute.java, xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java, xmppserver/src/main/webapp/session-row.jspf, xmppserver/src/main/webapp/session-summary.jsp
OF-590 introduces a connection validity check to the client sessions that are to be listed on the admin console. This check fails for sessions that are detached, which caused them to go unlisted.
This commit removes the check that was introduced in OF-590. I feel confident that the problems that guarded for are fixed by OF-1700.
Additionally, some (debug) log statements were added / enriched with session data.
=> OF-1883 & OF-1884

xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemCacheDetailsServlet.java, xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemPropertiesServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java, xmppserver/src/main/webapp/WEB-INF/web.xml
This allows admin servlets to be tagged with the @WebServlet annotation instead of the arcane settings in the `web.xml` file. Lack of support has been bugging me a while, and it wasn't until I came across https://stackoverflow.com/a/26220672/359394 by accident did I come back to it.
PS. Happy to raise an issue to cover this off if people think it's worth while
PPS. It may be possible to replace further entries in `web.xml` with appropriate annotations, but baby steps ...
PPS. Would also like to introduce something similar for plugin servlets, but that may have to wait for another day
=> OF-1903 Support for @WebServlet annotation

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
This fixes two problems that occur while determining if a particular JID is allowed to unsubscribe a (potentially different) JID from a pubsub node.
=> OF-1901: Pubsub unsubscribe permissions

xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
It was just a typo. Also introduced constants for the property
parameters.
By testing this change I noticed that it is impossible to clear the cache properties because they are immediately rewritten with the default value. Is this intended?
(see https://discourse.igniterealtime.org/t/bug-in-cache-konfiguration/86452)
=> OF-1897 fix that the maxLifetime settings of a cache take effect on runtime

xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemCacheDetailsServlet.java, xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java
Note; this PR deliberately does not use system properties to determine if the contents of a cache should be displayed on there admin UI. If the developer does not wish a cache to be displayed on the admin UI, then it should not be possible for an administrator to override their wishes by changing a system property.
An implication of this is that the code must explicitly set the key and/or value to be secret.
=> OF-1894: Allow the contents of Cache's to be kept private

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
This commit limits what files can be accessed through the plugin servlet to those that are under the Openfire home directory.
A property has been provided to disable this new restriction.
=> OF-1886: Plugin Servlet shouldn't provide access to any file on the host

xmppserver/src/test/java/org/jivesoftware/util/CertificateManagerTest.java
The implementation is used only for one constant definition. We can copy the constant value in our code, instead of depending on proprietary code.
=> OF-1912: Stop using proprietary sun.security.x509.GeneralNameInterface

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
In order to avoid a stack overflow, this code first 'flattens' the set of dependent shared groups, before processing them.
=> OF-1917: Work with cyclic dependencies in shared groups.

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQBindHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
The changes in this PR intend to resolve an issue where a connection that reconnects and binds using the same resource (full JID) gets disconnected.
The original problem is caused by the cleanup task for stream management cleaning up sessions by full JID, even if the original session has been replaced by a new session (that uses the same full JID).
=> OF-1923 (and OF-1925, OF-1926, and trivial OF-1924) Fix for Stream Management 

.travis.yml, runIntegrationTests
Recently, the integration tests have been failing a lot. Flow suggested improving the version of Gradle that's used to run them. While at it, I'm also bumping the version of Smack that we use to the latest release (4.3.4).
=> Smack Integration Tests: use later version of Smack and Gradle.

xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java, xmppserver/src/test/java/org/jivesoftware/openfire/ldap/FlattenNestedGroupsTest.java, xmppserver/src/test/resources/org/jivesoftware/openfire/ldap/flattenNestedGroups.ldif
Nested / complex / hierarchic groups are flattened. This means: if
group A is member of group B, the members of group A will also be
members of group B.
Cyclic paths are detected and followed only once.
The features is disable by default.
Set property "ldap.flattenNestedGroups" to "true" to enable it.
=> OF-1890 Added support for flatting nested groups in LDAP.

xmppserver/src/main/java/org/jivesoftware/admin/servlet/SecurityAuditViewerServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/security/DefaultSecurityAuditProvider.java, xmppserver/src/main/webapp/security-audit-viewer-jsp.jsp
Also
a) Tidy up screen layout, and
b) swap the dates around if "from" is after "to"
=> OF-1936 - hopefully fix OOM error with Oracle

.gitignore, .travis.yml, distribution/src/conf/openfire-demoboot.xml, runIntegrationTests, test.gradle
This started as "I'll fix that sed statement, then these will run on my Mac", but snowballed.
Improved the running script for readability
Added options for running tests against an already running host, even if it isn't local
Added ability to run tests in a local Docker container (because the Smack tests won't run on case-insensitive file systems)
Added option to set hosts file whilst the script is running
I believe this to be complete, but concede that in coping with lots more scenarios there are some combinations I haven't spotted or tested.
Feedback so very welcome!
=> Better cross-platform integration tests

build/rpm/openfire.spec
removes a newly included demoboot.xml #1539 from being included in the RPM distribution
=> remove demoboot.xml from RPM distribution

documentation/ldap-guide.html, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java
We've found that with a connection timeout of larger than 4 seconds, Spark fails to authenticate against LDAP, when LDAP integration is making use of more than one LDAP server with the first of the two unavailable.
This commit reduces the connection timeout to a value that allows Spark to authenticate. It does not, however, prevent that Openfire operates with degraded performance.
=> OF-1937: Reduce connection timeout for LDAP.

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
This PR unloads any SystemProperty whose "plugin" property matches that of the plugin name (as defined in plugin.xml) when the plugin is removed. 
I did look at scanning a plugin to ensure all properties are correctly loaded with the plugin (as opposed to the first time that a class containing the property is referenced - cf. `scanForSystemPropertyClasses()` in XMPPServer.java) - however, there seems to be an incompatibility hat I couldn't resolve between the Openfire specific PluginClassLoader and the Guava utility to find classes.
=> OF-1895: Unload properties that belong to a plugin

documentation/plugin-dev-guide.html, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
The original code only worked /some/ of the time - the rest of time a CSRF false-positive was detected. It all depended on the caching in the browser, and the order in which non-servlet files (images, CSS etc.) were retrieved.
=> Fix plugin CSRF protection 

xmppserver/src/main/webapp/style/global.css
made some arb CSS changes to attempt to get better navigation alignment after #1460 
before:
after:
what do you think @mnsuccess ?
=> OF-1823 css margin tweak to get better alignment

pom.xml, xmppserver/pom.xml
After build (like mvn verify) code coverage report is generated in xmppserver/target/site/jacoco/index.html (there are also xml and csv versions). It should be useful during planing which tests to write first and you will be able to see which lines are not covered yet.
=> Add coverage reports

xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultCache.java, xmppserver/src/main/webapp/system-cache.jsp
Replace a Math.max with a Math.min
=> OF-1946: Correct cache size causing incorrect values display on admin UI

xmppserver/src/main/java/org/jivesoftware/openfire/MessageRouter.java
To be compliant with https://tools.ietf.org/html/rfc6121#section-8.5.3.2.1,
for private messages(type="chat"), in case of no resource match,
server MUST deliver this message to any of available resource with non-negative priority
=> OF-532: Fixed by including sessions with non-negative priority=0

xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
Currently Openfire send Jetty server name and version in response header :
This is a bad practice security-wise. Note that in the other connexions (like the admin panel) this option is already set to false.
This commit is for the 4.6 branch.
=> OF-1974 :lock: Don't send Jetty server name & version in websockets response

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CollectionNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java
- pubsub fixes to notification sent to subscribers upon node configuration change and upon node deletion
1. "Node configuration change" message was not sent to subscribers("nodes") of any parent nodes even when the depth was proper. Only if subscription was made directly to node which configuration was changed
2. "Node configuration change" message was not sent to subscribers ("nodes") of any parent nodes even when the depth was proper, because the node was deleted 1st from collection and therefore not found as descendant node later when the notification messages were sent.
=> OF-1977: Various pubsub fixes

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
With this feature, "join presence" of participating users cannot be sent. It is very useful if you don't want to send join presence in all groups. This will be preparation for [MUC lite](https://xmpp.org/extensions/inbox/muc-light.html)
=> OF-1978 (feature) Added xmpp.muc.join.presence

xmppserver/src/main/webapp/server-locale.jsp, xmppserver/src/main/webapp/setup/index.jsp
Openfire has Japanese translation, but lacked the option to select that translation. This commit rectifies that.
=> OF-1966: Allow Japanese i18n to be selected.

xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultExternalizableUtil.java, xmppserver/src/main/java/org/jivesoftware/util/cache/DummyExternalizableUtil.java, xmppserver/src/main/java/org/jivesoftware/util/cache/ExternalizableUtil.java, xmppserver/src/test/java/org/jivesoftware/util/cache/DefaultExternalizableUtilTest.java
This introduces a new ExternalizableUtilStrategy that, unlike the existing DummyExternalizableUtil, is fully functional.
The new implementation is named DefaultExternalizableUtil. It's implementation is a near copy of ClusterExternalizableUtil from the Hazelcast plugin.
=> OF-1984: Replace DummyExternalizableUtil

distribution/src/bin/openfire.sh
Adding arguments to openfire.sh that allows Openfire to be started, without a need to go through the web-based setup.
- demoboot: starts with fqdn and xmpp domain set to 'example.org', admin account: admin/admin
- devboot: same, but replaces 'example.org' with the hostname of the computer running Openfire.
hattip @Fishbowler
=> OF-1983: Add flags to skip setup

.travis.yml, distribution/src/conf/openfire-demoboot.xml, runAioxmppIntegrationTests
This commit adds a script, similar to the one for the Smack-based integration tests, that downloads and excutes the tests that are part of aioxmpp (https://github.com/horazont/aioxmpp)
aioxmpp requires anonymous authentication to be enabled. This commit achieves that by adding a corresponding autosetup configuration option to the demoboot config file.
=> Add aioxmpp-based tests to Travis

xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/BroadcastPresenceRequest.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCvCardHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
This largely follows the specification as defined by ProcessOne: https://docs.ejabberd.im/tutorials/muc-vcard, with an addition to make things work with Converse.
The change herein stores a room vCard into the same database table that's used for regular users (but using the JID for the room, as opposed to the username that's used for users).
A downside of this approach is that setting avatars for MUC rooms likely does not work in AD/LDAP setups (or other setups where the vCardProvider is read-only).
This commit lacks an admin console change (it would be nice to also be able to specify a vCard or avatar for a room through the admin console).
=> OF-1968: Add vCard (avatar) support for MUC rooms.

pom.xml
Bouncy Castle 1.65 instead of 1.64: https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
=> OF-1997: Bouncy Castle 1.65 instead of 1.64

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
RFC 6120 § 10.3. dictates that IQ and Message stanzas that have no 'to' attribute value should be processed as if the 'to' attribute value equals that of the bare JID of the sender.
This commit parses all inbound IQ and Message stanzas, setting the 'to' attribute value for stanzas that have none to the bare JID that matches the 'from' attribute value. A new system property `xmpp.server.rewrite.replace-missing-to` has been introduced that can be used to disable this functionality.
=> OF-872: Properly process IQ and Message without 'to' attribute.

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/lockout/LockOutManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java, xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/vcard/DefaultVCardProvider.java
This replaces the (often namespaced) interned strings used to synchronize on (which introduces a risk of deadlock) with a dedicated map of locks that mimics String interning for any other object type (that should be immutable).
Drawbacks of this solution:
- provided by Google Guava that is marked as 'Beta'
- probably more resource intensive than the native, String-based mutex.
=> OF-2000: Stop using intern'ed strings as locks

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_cs_CZ.properties, i18n/src/main/resources/openfire_i18n_de.properties, i18n/src/main/resources/openfire_i18n_es.properties, i18n/src/main/resources/openfire_i18n_fr.properties, i18n/src/main/resources/openfire_i18n_ja_JP.properties, i18n/src/main/resources/openfire_i18n_nl.properties, i18n/src/main/resources/openfire_i18n_pl_PL.properties, i18n/src/main/resources/openfire_i18n_pt_BR.properties, i18n/src/main/resources/openfire_i18n_pt_PT.properties, i18n/src/main/resources/openfire_i18n_ru_RU.properties, i18n/src/main/resources/openfire_i18n_sk.properties, i18n/src/main/resources/openfire_i18n_zh_CN.properties, xmppserver/src/main/webapp/muc-default-settings.jsp, xmppserver/src/main/webapp/muc-room-edit-form.jsp
MUC services have configurable default settings to be applied to new rooms. These defaults are already used when an end-user creates a room (through XMPP).
This commit takes applies the same settings to the room creation form that is in the Admin console, with one exemption: rooms created in the admin console are always persistent.
Note that it's possible to configure Openfire with more than one MUC service. If that's the case, selecting the MUC service in which the room is to be created is part of the room creation form. As at that point, the to-be-used service is still unknown, the (other) default values that are used on the same form are based on the first available service. That seems to be an acceptable trade-off, given the limited amount of installs that have more than one MUC …
=> OF-158: Make room default settings use configurable service defaults.

runIntegrationTests, test.gradle
and disable tests that fail with openfire.
=> sinttest: update smack to 4.4.0-alpha3-20200416.010506-6

xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
This fix is to remove the test for resuming a stream session in websockets before closing the xmpp session. XEP-0198 stream resumption is not yet implemented.
=> OF-963 - WebSocket keep-alive is not working as expected

xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
Note that it continues to be possible to register SesionListener instances that trigger on events for all (as opposed to a single) HttpSession instances through org.jivesoftware.openfire.http.SessionEventDispatcher
=> OF-1998: Remove broken support for event listener on single HTTP session

xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionType.java
According to OF-1191(https://github.com/igniterealtime/Openfire/commit/83c47b30237bca298da62c04faee39cc940c156c), WEBADMIN should be of client-oriented connection types.
=> WEBADMIN should be of C2S connection type

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
This removes an unused artifact of FMUC development. The code doesn't do what the name of the signature suggests.
=> OF-2030: Remove unused & incorrect code

xmppserver/src/main/java/org/jivesoftware/admin/AdminConsole.java
Under certain conditions (that I have been unable to reproduce) adding comments in the admin-sidebar.xml appears to influence the rendering of the admin console.
It has been reported that reconfiguring the SAX reader to ignore comments prevents the issue from occurring.
Although I've not been able to reproduce the issue, ignoring comments is sufficiently benign that it doesn't hurt to add that to the implementation.
=> OF-2046: Ignore comments in sidebar-admin.xml

xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java
Occasionally, Openfire enriches HTTP responses with additional headers.
HTTP responses can have duplicate headers. This often is not desired. To prevent this problem, Openfire should 'set' rather than 'add' headers. The former overwrites any preexisting headers of the same name.
=> OF-2047: Set, instead of add headers to HTTP responses

.github/workflows/continuous-integration-workflow.yml, i18n/src/main/resources/openfire_i18n.properties, runIntegrationTests, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
This commit aims to make subsequent actions wait on the completion of others. This should prevent the room from being deleted before the unavailable presence stanzas have been sent (which otherwise causes issues, as the room is used to compose those stanzas).
=> OF-2049: Do not remove room before presences are sent

xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
If form fields do no mention type, they are by default assumed to be of type text-single. This causes problem for clients in cases where multiple form field values are included without mentioning type. Check [here](https://xmpp.org/extensions/xep-0157.html#example-2).
However, field standardisation for the same xep-0157 [here](https://xmpp.org/extensions/xep-0157.html#registrar-formtype) suggests that the form field type is list-multi. And so, it is better if the server adds type to form fields as this saves the client from first checking `FORM_TYPE` and determine form field type as per standardisation .
Solves OF-2054
=> OF-2054: Add form field type to XEP-0157 form field

xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java, xmppserver/src/test/resources/org/jivesoftware/openfire/ldap/flattenNestedGroups.ldif
When 'flattenNestedGroups' was true and a group contained a not existing user, the whole group was not loaded.
(The previous version was also contributed by me https://github.com/igniterealtime/Openfire/pull/1501)
=> OF-2058: LDAP group with not existing user not loaded

xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQOfflineMessagesHandler.java
According to XEP-0013, If the requester is authorized but the node does not exist, the server MUST return an <item-not-found/> error.
https://xmpp.org/extensions/xep-0013.html#retrieve-specific
=> OF-2053 XEP-0013: return an <item-not-found/> error while retrieving specific offline message.

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultPubSubPersistenceProvider.java
Fix: Openfire if configured with Oracle, clearing ofPubsubItem table. On comparing with MySQL or PostgreSQL queries, oracle sub query is not returning expected rows. Its causes table getting cleared 
@guusdk @akrherz @deleolajide
=> Fix: Purging ofPubsubItem table when configured with Oracle because of incorrect Oracle query

xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
I encountered the following exception:
```
2020.08.27 09:37:19 ERROR [socket_c2s-thread-5]: org.jivesoftware.openfire.nio.ConnectionHandler - Closing connection due to error while processing message: <resume xmlns="urn:xmpp:sm:3" previd="bWFpbgAyYmJhMHl5OWFk" h="13"/> 
java.lang.NullPointerException: Domain cannot be null 
at org.xmpp.packet.JID.<init>(JID.java:506) ~[tinder-2.0.0.jar:?] 
at org.jivesoftware.openfire.streammanagement.StreamManager.startResume(StreamManager.java:289) ~[xmppserver-4.6.0-SNAPSHOT.jar:4.6.0-SNAPSHOT] 
at org.jivesoftware.openfire.streammanagement.StreamManager.process(StreamManager.java:158) ~[xmppserver-4.6.0-SNAPSHOT.jar:4.6.0-SNAPSHOT] 
at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:200) …
```
=> Null pointer for domain in StreamManagement when resuming

xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
There's no way in code that content can be retrieved after it has been expired (other than the component reconnecting). The javadoc also states that entries shouldn't expire. This commit adds explicit configuration that ensures this behavior (the default configuration _does_ configure the cache to eventually expire).
=> OF-2065: Entries of the 'Components' cache should not expire

xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterEventListener.java, xmppserver/src/main/java/org/jivesoftware/openfire/component/InternalComponentManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoItemsHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceUpdateHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/ClientSessionInfo.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
(the description of the PR is copied from the commit message of the second commit, which holds most relevant changes)
When a server joins or leaves a cluster, the implementation that's behind the Cache interface is swapped. When switching _to_ a clustered implementation (_from_ a local/non-clustered implementation), the replacement cache can be used to interact with the cache content that's shared in the cluster. When switching _from_ a clustered implementation (_to_ a local/non-clustered implementation) the cache is replaced with a new (empty) default cache.
OF-974 (now reverted) introduced a change that caused the content from the old implementation to be copied to the new one during the switch-over. This prevented data to be 'lost'. This approach has a considerable drawbacks: When data …
=> OF-2060: revert OF-974

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/cluster/GetClusteredVersions.java, xmppserver/src/main/webapp/system-clustering.jsp
This is to fix https://github.com/igniterealtime/openfire-hazelcast-plugin/issues/47 but it turned out to be easier to implement this in core Openfire rather than the clustering plugin itself. @guusdk is it worth raising an Openfire JIRA ticket to cover this off?
It was also fairly easy to display the various plugin versions too - probably useful as I've certainly tripped myself up when running subtly different versions on different nodes.
If any version is different, then a warning symbol is displayed.
What you see if you're running an old version of Openfire in the cluster;
What you see when that version has been upgraded;
(note the different version of the Hazelcast plugin and the missing XML Debugger plugin)
And what the other node sees:
=> OF-2068 Display the versions of various nodes in the cluster

xmppserver/src/main/java/org/jivesoftware/openfire/net/SASLAuthentication.java
By setting sasl.client.suppressEmpty and/or sasl.server.suppressEmpty one can now prevent a <mechanisms> tag to be included when it would not contain any SASL mechanisms (eg: when they're all disabled in configuration).
=> OF-2072: Allow empty mechanisms tag to be suppressed

Dockerfile
Release notes (https://maven.apache.org/docs/3.6.3/release-notes.html) indicate some useful fixes, especially
> [MNG-6759] - [REGRESSION] Maven fails to use <repositories> section from dependency when resolving transitive dependencies in some cases
=> Bump maven version in Docker build
