- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProvider.java
When an item is being requested that does not exist, the existing code for the CachingPubsubPersistenceProvider attempts to cache null, which is not allowed.
This modification simply skips caching the value. We could consider adding an Optional (to reflect the negative lookup), but that needs additional checking. I'm not sure if it'd work with the async persistence of content that's implemented in this class.
> OF-2080: Prevent caching null item

- xmppserver/pom.xml
Fixes minor security issue
Changelog: https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-21.html (although if you're reading this then you may wanna read 20, 19 and 18 too)
> OF-2088: Bump mysql-connector-java 

- .gitignore
- .travis.yml
Some PRs are failing due to 1 flaky test in the aioxmpp suite. For now, retry 3 times to get PRs with accurate info.
This isn't the real solution. This is an interim solution to help the CI surface accurate feedback.
(Next steps: Fix or exclude the test in aioxmpp)
> Defend against flaky tests

- .gitignore
I'm a monster who chooses to do Java work in VS Code on occasion, and these files are generated by the maven plugin.
> Ignore .factorypath files

- .github/workflows/continuous-integration-workflow.yml
Fixes the broken git pull in the publish job introduced in #1716
> Fix Github SHA for maven

- .github/workflows/continuous-integration-workflow.yml
Adds double braces on environment variable
> Fix Maven Publish job in GH Actions

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java
The author is assigned through new at the beginning of the method, it always is not null (or the method will throw an exception) so "else" never happens.
I am playing a bit with SonarQube so you might expect few more such small patches :)
> OF-2030 The author is always not null.

- runIntegrationTests
This PR disables a test that is known to be flapping due to a race condition in Smack, while it re-enables tests that failed to run due to bugs in an old (alpha) version of Smack.
> Smack Integration Test config changes

- pom.xml
When Openfire is compiled with Java 11, but executed in Java 8 a NoSuchMethodError can be thrown when a client tries to connect. This appears to be caused by Java 11 overriding the `Buffer.flip()` method in ByteBuffer and CharBuffer. To avoid issues, this commit casts explicitly to Buffer when the flip method is used, which is the suggested fix found in https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip
I'm not sure if this is the most optimal way to fix this problem, nor if a similar fix needs to be applied in other places. In any case, the client connection issue disappears with this fix.
> OF-2093: Prevent JDK11 NoSuchMethodError by something else than an explicit cast because Greg pointed me to a much better solution.

- starter/src/main/java/org/jivesoftware/openfire/launcher/Launcher.java
- xmppserver/src/main/java/org/jivesoftware/admin/AdminConsole.java
- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginCacheConfigurator.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMetadataHelper.java
- xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdVCardProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java
- xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java
- xmppserver/src/main/java/org/jivesoftware/util/WebXmlUtils.java
- xmppserver/src/main/java/org/jivesoftware/util/XMLProperties.java
Not properly configured XML parsers are potentially vulnerable to XXE attacks. Adding these settings should prevent most of this attacks.
https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing
Solution:
https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#saxreader
Found with SonarQube
> OF-2094 Mitigate XXE attacks

- xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java
There is a usage in the form of `webManager.userManager.getUser(member)` in the [group-edit.jsp](https://github.com/igniterealtime/Openfire/blob/c4cbe6564c9aa5fc6593bb1ebbcde1dbdf1e6764/xmppserver/src/main/webapp/group-edit.jsp#L672) file. The `member` is of type JID, but it is converted to string when called. And it comes to getUser method as "username@example.com". This is "java.lang.IllegalArgumentException: The input 'username@example.com' is not a valid JID node part: Contains prohibited code points." causing error.
This PR fixed that issue.
> UserManager getUser method overloaded for JID

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
In non-anonymous rooms, participants can/should see the others' real JID. That's usually done via presences. However, according to XEP-0045, section 7.2.13 a server MAY send the real JID also as an "addresses" stanza with type "ofrom" within the message.
This PR implements that. I opted to add the field if `canAnyoneDiscoverJID` is set to true for the room. Ofc, a more sophisticated implementation might include other cases based on the participant's role.
I wanted to write some tests for this, but `LocalMUCRoom` had some difficult to mock dependencies to singleton classes (namely the `MUCPersistenceManager` that is used in the constructor).
> OF-2089 XEP-0045 7.2.13 - ofrom adresses in message stanza

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/OfflineMessageStore.java
- xmppserver/src/main/java/org/jivesoftware/openfire/OfflineMessageStrategy.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/disco/DiscoInfoProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQBlockingHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQOfflineMessagesHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQPrivacyHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQPrivateHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQRosterHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceSubscribeHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceUpdateHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPServiceManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubServiceInfo.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/PresenceManagerImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java
- xmppserver/src/main/webapp/group-edit.jsp
- xmppserver/src/test/java/org/jivesoftware/openfire/user/UserManagerTest.java
The existing method signature is very easy to 'get wrong', as indicated by the various places where I've fixed it (see follow-up commits in this PR). I've changed the signature to better express its desired operation, leaving the old method in place, marking it deprecated.
As a byproduct, I found OF-2107, which I think is a bug that is unlikely to have manifested itself.
> OF-2106: UserManager.isRegisteredUser(JID address) API change

- .github/workflows/codeql-analysis.yml
Uses the GitHub template with some tweaks.
Integrates some of the high-level security stuff you get from LGTM into the GitHub security dashboard for the project.
Whilst there's no new functionality in GitHub's version (yet) and LGTM offers more (like Warnings) the ease of use makes this useful to org members.
> Add GitHub CodeQL to Openfire

- .github/workflows/continuous-integration-workflow.yml
It fails on forks, since it has no secrets, but would be nice not to fail.
e.g. https://github.com/akrherz/Openfire/actions/runs/310663956
Oops.
> Github Actions: Only run maven publish on IgniteRealtime, not on forks

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
Without this, restarting Jetty (sometimes) causes an error, indiating that we're trying to start something that's already started. This seems to happen only when the handler was being used when it was supposed to be stopped (eg: have an active BOSH connection).
> OF-1789: Explicitly close all handlers when stopping Jetty

- .dockerignore
Stop passing locally built artifacts into to the docker build and causing unpredictable outputs. This has repeatedly stung me in the past.
Future Me needs this, and will thank you.
> OF-2113: Add a proper dockerignore file

- pom.xml
In order to fix https://github.com/igniterealtime/openfire-pade-plugin/issues/76, we have to upgrade BC to 1.66
> OF-2114 Upgrade Bouncy castle to 1.66

- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
It was giving misleading information about how the method should be used.
> Fixed the @return for LocalClientSession->canProcess being incorrect

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
Stanzas without a from attribute are generally fine. So it's not ok to raise an exception when trying to route one in `IQRouter`.
In the PR, no exception will be thrown but also the stanza will NOT be routed if it's S2S and also doesn't have a "from".
> [OF-2112] Fixed NPE when routing an IQ without a "from" attribute

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRole.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQAdminHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
This effectively undoes a workaround that was introduced when implementing FMUC. That workaround introces the issue described in OF-2146.
After many hours of testing, we've not been able to reproduce the original issue that the workaround intends to fix.
> OF-2146: Fix affiliation and role change broadcasts in MUC

- xmppserver/src/main/java/org/jivesoftware/openfire/auth/JDBCAuthProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/stats/Statistic.java
With the removal of QDox, adding an otherwise unneeded semicolon is no longer needed. Those have been removed. The corresponding suppression of the warning that signals that unneeded semicolons are used can be removed too.
> OF-981: Stop suppressing warning that are no longer issued

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/webapp/setup/setup-ldap-server_test.jsp
This adds a stacktrace to the error dialog when for some reason, the LDAP connection fails.
> OF-2130: Show more information when LDAP connection fails

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Once caught this issue in clustering testing:
org.jivesoftware.openfire.muc.cluster.BroadcastPresenceRequest - An unexpected exception occurred while trying to broadcast a presence update from user1@xmpp.localhost.example/DaCa000346.local in the room muc1@conference.xmpp.localhost.example
java.lang.IllegalArgumentException: null
at org.jivesoftware.openfire.muc.spi.LocalMUCRoom.createAnonCopy(LocalMUCRoom.java:1580) ~[xmppserver-4.6.1-SNAPSHOT.jar:4.6.1-SNAPSHOT]
at org.jivesoftware.openfire.muc.spi.LocalMUCRoom.broadcast(LocalMUCRoom.java:1528) ~[xmppserver-4.6.1-SNAPSHOT.jar:4.6.1-SNAPSHOT]
at org.jivesoftware.openfire.muc.cluster.BroadcastPresenceRequest$1.run(BroadcastPresenceRequest.java:87) ~[xmppserver-4.6.1-SNAPSHOT.jar:4.6.1-SNAPSHOT]
at …
> Add more logging to muc failure

- xmppserver/src/main/java/org/jivesoftware/database/ProfiledConnectionEntry.java
Prevent a possible issue where a wider type gets added to narrower type.
Ideally, this is replaced by proper types (eg: Duration, Instant), but the cost/benefit of applying that larger change does not pay off.
> OF-2148: Change to wider type to prevent information loss

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/BroadcastMessageRequest.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/BroadcastPresenceRequest.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/MUCRoomTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
This commit takes the explicit 'from' address verification that was put in place for Presence broadcast handling, and applies the same to Message broadcast handling.
The check has been moved up a bit, and has been applied at the constructor of the tasks that are executed asynchronously. These can be expected to generate more useful stack traces.
> OF-2152: Apply more explicit address verification

- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
Openfire currently does not allow XEP-0198 resumption on a cluster node different than the one that originally had the session.
This commit adds exception handling for this scenario.
> OF-2153: Gracefully reject SM resumption on wrong cluster node

- xmppserver/src/main/java/org/jivesoftware/openfire/stanzaid/StanzaIDUtil.java
- xmppserver/src/test/java/org/jivesoftware/openfire/stanzaid/StanzaIDUtilTest.java
This fixes a misunderstanding of the text in the XEP. Although origin-id must be retained, its value shouldn't be re-used, as the local entity can't trust the owner to have used a unique value.
> OF-2159: Do not re-use origin-id when generating a stanza

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/AffiliationTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/CancelSubscriptionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/FlushTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/ModifySubscriptionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/NewSubscriptionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/NodeChangeTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/NodeTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/RefreshNodeTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/RemoveNodeTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/SubscriptionTask.java
This PR contains various commits that:
- improve the documentation to express the intent of the implementation
- mark code that should not be used as deprecated
- Fix implementations that unconditionally attempted to execute changes on pubsub entities that potentially are not loaded (OF-2077)
- rename some methods, also to better express intent (to avoid future variants of OF-2077).
Please refer to the comments on individual commits for more details.
> OF-2077: Improvements around cluster tasks that relate to pubsub.

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCUser.java
When a private message that's exchanged in a MUC room is processed, it receives a stable and unique stanza ID. As per specification, Openfire adds a 'by' attribute. However, for private messages, this value is a full JID (representing the nickname of the user that sent the message), instead of a bare JID (representing the room in which the message was exchanged). This is fixed by ensuring that the JID used is a bare JID.
> OF-2161: Ensure that SSID for MUC PMs is the MUC JID

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/HistoryRequest.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRole.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCvCardHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Delivering a stanza to a MUC room occupant changes the addressing of the stanza (the room JID is replaced by the real JID). It is often undesirable that this change is applied to the original stanza (that can be processed further), as such changes can leak the privacy-sensitive real address of the recipient.
This commit creates defensive copies of the stanza that is being sent, to prevent leaking the real address of the recipient.
> OF-2163: Prevent unexpected stanza modifications to leak information

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQOwnerHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
- xmppserver/src/main/webapp/muc-room-edit-form.jsp
Openfire offers functionality to suppress the broadcast of occupants that have a certain role. The old implementation is based on the definition of that role that should be present in the presence stanza to be broadcast.
When the presence stanza that is being processed does, for some reason, not include this role, the implementation fails. NullPointerExceptions have been observed in relation to this.
It should be a lot safer to base the broadcast/do not broadcast decision based on the role that is assigned to the user, as this prevents the need to parse a stanza. This commit applies this new strategy.
Additionally, this commit replaces the string-based represention of a role with a type-safe variant.
> OF-2168: MUC presence broadcast supression based on role

- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapVCardProvider.java
- xmppserver/src/test/java/org/jivesoftware/openfire/ldap/VCardTest.java
When a VCard template refers to an attribute that a user does not have, the resulting value should be empty. This commit prevents a NullPointerException to be thrown.
> OF-2169: Prevent exception for missing LDAP attribute

- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java
By caching lookup failures, subsequent lookups are prevented, which will increase performance.
@GregDThomas I would've used `Optional` if it was `Serializable`! ;)
> OF-2170: LDAP userDN cache should contain negative lookups

- xmppserver/src/main/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java
When an anonymous or non-existing user tries to log in, a very alerting warning can be logged, when the authentication mechanism in use tries to make use of the user's salt (which does not exist). This needlessly alarms administrators. The verbosity should be turned down a notch or two.
> OF-2174: Reduce verbosity of authentication failures

- xmppserver/src/main/java/org/jivesoftware/openfire/net/DNSUtil.java
A previous commit added a cache for WeightedHostAddress instances. To be cacheable, a class must be serializable. That's done in this commit.
> OF-2174: Cached value must be Serializable

- xmppserver/src/main/java/org/jivesoftware/util/CacheableOptional.java
When CacheableOptional has a toString, the cache summary pages on the admin console would show more useful data than object references.
> OF-2177: CacheableOptional should have a toString implemenation

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRole.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/RemoteMUCRole.java
Occupants of a MUC room have, in a clustered setup' one cluster node where they are considered 'local' to. It has been observed that for some occupants, notably those that are joined through server-to-server / federation, can change over time.
This commit:
- generates a warning when it detects that a occupant has unexpectedly switched from node (detection is based on the cluster member that performs a presence stanza update on behalf of the occupant).
- re-homes an occupant that appears to 'rejoin' (without having left the room), but does so from a different cluster node.
> OF-2179: Accommodate MUC occupants re-joining on another cluster node

- Dockerfile
Since we already build and test on both java versions, there would seem to be no harm in moving to the newer Java version.
The java11 images also have arm variants, making Openfire easier to develop and run on a Raspberry Pi (or the Apple M1, when Docker becomes stable there)
> Use java11 images for Docker

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_de.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/java/org/jivesoftware/admin/SessionListener.java
Add a http session listener to the Admin Console plugin that implements a configurable session timeout.
The session timeout is taken from the property `adminConsole.sessionTimeout`, the default is 30min.
> OF-2176 OF-763: Make Admin Console session timeout configurable

- xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java
Fixes OF-2155. Changes the header value from "same" to "sameorigin", fixing a Chrome console error - "same" isn't [a valid value](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#directives) for this header.
> OF-2155: Set X-Frame-Options to "SAMEORIGIN"

- xmppserver/pom.xml
- xmppserver/src/main/java/org/jivesoftware/admin/AdminConsole.java
- xmppserver/src/main/webapp/decorators/main.jsp
- xmppserver/src/main/webapp/decorators/setup.jsp
Add a subtle git sha to the footer so that we can observe the exact provenance of a given Admin interface
> OF-2195: Add Git SHA to Admin header

- xmppserver/pom.xml
Fixes https://igniterealtime.atlassian.net/browse/OF-2196
Adds an extra dependency to let XML REST APIs that depended on Java 8 APIs work on Java 11. Most importantly, it fixes support for the Rest API Plugin.
> OF-2196: Add dependency for JAXB-API in Java 11

- .dockerignore
- Dockerfile
- build/docker/buildWithDocker.sh
- build/docker/entrypoint.sh
Ditches the multi-stage docker build.
The high number of dependencies means that any POM change means an invalidation of cache, so a redownloading of the whole internet, and makes for a very slow build time.
Fixed this by moving the build to a separate script that does a docker *run* of the official maven image, with a volume mapping the m2 cache of the host.
The container build is closer to "standard" - grabbing built files from the distribution into a container. Lays the groundwork for publishing an official Docker image later.
It also:
* moves the CMD to an ENTRYPOINT, allowing for additional parameters (e.g. for java debugging)
* adds a step to the entrypoint script to copy plugins from /opt/plugins, allowing these to be provided for install at runtime e.g. `docker run …
> Remove multi-stage Docker build, add separate dockerised maven build

- distribution/src/database/upgrade/31/openfire_sqlserver.sql
Forum reveals SQL Server isn't processing multi-line upgrade scripts properly.
This only solves the one instance
https://discourse.igniterealtime.org/t/openfire-upgrade-to-4-6-causes-loss-of-group-chat-rooms/89626
> OF-2197: Replace multi-line block comment

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCUser.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/webapp/muc-room-occupants.jsp
- xmppserver/src/main/webapp/muc-tasks.jsp
This commit adds a new feature that complements the pre-existing feature that would kick idle users from a MUC room.
The new feature is defined in the section related to 'ghost users' in the MUC specification (XEP-0045). It is two-fold:
- When a room is sent a stanza that contains an error that indicates that an occupant is unreachable, drop that occupant from the room.
- When an occupant has not interacted for a configurable amount of time, send a ping to that occupant. If the occupant is unreachable, this will trigger an error to be sent back, that will be processed by the implementation of the first item in this list.
This new feature is configurable through the admin console (Group Chat > Group Chat Settings > (select service) > Other Settings), but is enabled by default.
> OF-2209: Detect and remove 'ghost users' from MUC.

- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
This reverts the change for OF-2012, which erroneously assumed it was fixing a typo.
Marking a session as unavailable is different from removing a session. By removing the session in this method, it later can't be found, and event listeners are not triggered as a result.
This is where @GregDThomas owes me an "I told you so" - he challenged OF-2012 at the time. :)
> OF-2210: Restore SessionDestroyed event handling

- .github/dockerhub.env
- .github/workflows/continuous-integration-workflow.yml
- documentation/docker.html
Adds to the existing CI build, and uses the existing build artifacts to create and publish a docker image to Docker Hub.
- Any tag pushed to the repo will be pushed as an equivalent tag to Docker Hub
- Anything pushed to master will be pushed to :latest on Docker Hub 
I've added some consideration for forks being able to push to Docker Hub. Anyone running the CI in their fork AND with the appropriate secrets set will attempt to use them to push an image.
To make it work:
- Create an account on Docker Hub
- Create a token for the user account (https://hub.docker.com/settings/security)
- Add a repository secret (https://github.com/igniterealtime/Openfire/settings/secrets/actions) for DOCKERHUB_USERNAME and DOCKERHUB_TOKEN - (do these want to live on the repo, in case we want to publish from …
> Publish an official container image to Docker Hub

- pom.xml
- xmppserver/pom.xml
I've been testing out Snyk on my fork, and it's spotted a number of out-of-date deps
- Jetty
- Apache Commons Pool2
- jSMPP
- Rome
- Postgresql JDBC driver
- MSSQL Server JDBC driver
This PR updates these deps to current versions, mosty via cherrypicks from the autogen'd PRs it creates.
I've tested Rome & Jetty locally. Pool2 and Jetty both get exercised by the CI tests. I've tested the JDBC drivers by exercising them in a branch that merges this with the database upgrade tests (see #1805) and those passed (https://github.com/Fishbowler/Openfire/actions/runs/726286422).
Only Jetty is a security upgrade, fixing https://nvd.nist.gov/vuln/detail/CVE-2021-28165
> OF-2213: Update dependencies

- xmppserver/src/main/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java
- xmppserver/src/main/webapp/import-keystore-certificate.jsp
- xmppserver/src/main/webapp/security-keystore-signing-request.jsp
- xmppserver/src/main/webapp/security-keystore.jsp
Openfire detects changes to its keystores, and reloads the various services that use them. This, for example, allows the CertificateManager plugin to update Openfire's security certificates dynamically.
One element that does not automatically get updated after keystore changes is the webserver that is serving the admin console (which also can serve other web content). This is a conscious choice, as the admin console can be used to update the keystores. It would be very undesirable to have the admin user be logged out as a result of applying a change to the keystores. To work around this issue, the admin console remains unchanged when a keystore change is detected (although a warning will be displayed, telling an admin to restart things).
This commit ensures that the admin console is …
> OF-2212: Allow admin console's cert to be auto-updated

- xmppserver/src/main/webapp/setup/setup-ldap-group_test.jsp
- xmppserver/src/main/webapp/setup/setup-ldap-server_test.jsp
- xmppserver/src/main/webapp/setup/setup-ldap-user_test.jsp
This commit ensures that a helpful error message is shown to the end-user when setup fails due to a broken HTTP session.
> OF-2201: Improve error message during LDAP setup

- .github/workflows/continuous-integration-workflow.yml
- runAioxmppIntegrationTests
Perhaps the flakiness we see in the aioxmpp tests are due to async bugs in python 3.6.  perhaps python 3.9 has less bugs like that :)
> use python 3.9 for testing

- runIntegrationTests
Smack integration tests aren't building with latest gradle. This change:
* Forces the known-good Gradle version
* Re-enables a previously broken test
* Bumps the Smack version used for tests
> Fix smack integration tests

- .github/workflows/continuous-integration-workflow.yml
Whilst pulling my hair out, I realized that Github Actions updated the `ubuntu-latest` about the time failures started to happen.  I then noticed python using the `epoll` reactor, which sometimes can be sensitive to the Linux distro being used.  Rolling back to `ubuntu-18.04` has worked twice for me, watch it fail here.
> use older ubuntu for aioxmpp tests (Epoll issue?)

- runConnectivityIntegrationTests
The BOSH-based connectivity tests regularly, but not consistently, fail on Github (but never locally, at least not for me).
It appears that it's always the first (of many) iteration that fails. Subsequent iterations of the same test seem to work.
Perhaps the test is starting 'to soon'? It's waiting for Openfire to start listening on port 7070 (which seem appropriate), but perhaps there's a brief period where that socket seems open, but data sent to it isn't properly being processed yet.
This commit adds an arbitrary 2 second wait between 'socket detected to be open' and the start of the test.
> Fix flappy behavior of connectivity tests

- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/OpenfireWebSocketServlet.java
In OpenMeetings (a part of Pàdé), one may switch form old-style BOSH to WebSockets for the XMPP controll connection.  but unlike the BOSH Service, the Websocket Service don't yet support CORS response headers.
Add this by using the code from https://github.com/igniterealtime/Openfire/blob/master/xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java
> OF-2256: Add CORS support to WebSocket Service

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/JMXManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/archive/ArchiveManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/filetransfer/proxy/ProxyConnectionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/mbean/ThreadPoolExecutorDelegate.java
- xmppserver/src/main/java/org/jivesoftware/openfire/mbean/ThreadPoolExecutorDelegateMBean.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/RosterManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/MINAConnectionAcceptor.java
- xmppserver/src/main/java/org/jivesoftware/util/TaskEngine.java
- xmppserver/src/test/java/org/jivesoftware/admin/LoginLimitManagerTest.java
This exposes statistics of most of Openfire's thread pools via JMX (OF-2257). In the process of implementing this, I found a couple of thread pools that had hard-coded configuration. I made that configurable (OF-2258).
> JMX support for thread pools

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_cs_CZ.properties
- i18n/src/main/resources/openfire_i18n_de.properties
- i18n/src/main/resources/openfire_i18n_es.properties
- i18n/src/main/resources/openfire_i18n_fr.properties
- i18n/src/main/resources/openfire_i18n_ja_JP.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- i18n/src/main/resources/openfire_i18n_pl_PL.properties
- i18n/src/main/resources/openfire_i18n_pt_BR.properties
- i18n/src/main/resources/openfire_i18n_pt_PT.properties
- i18n/src/main/resources/openfire_i18n_ru_RU.properties
- i18n/src/main/resources/openfire_i18n_sk.properties
- i18n/src/main/resources/openfire_i18n_zh_CN.properties
- xmppserver/src/main/webapp/group-edit.jsp
When looking at the members of a group, it's handy to have listed the (full) name of each member, instead of only its username.
I know I should've added a search filter, but that takes more time than what I have available now.
> OF-2260: Add user's name to listing of group members

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Openfire has specific logic for detecting when self-presence needs to occur on a broadcast. Kick works by sending a specific presence to the kicked user, removing them from the MUC, then sending the broadcast - the logic is never invoked.
This change adds the self-presence to that kick.
I've used some yet-to-be-contributed additional tests for Smack to test that it both failed before the change and succeeded afterwards. See https://github.com/Fishbowler/Smack/commit/0e6963330804580a43f82b61f667fc40163189da
> OF-2240: Add self-presence status to kick presence to "kickee"

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/GetNewMemberRoomsRequest.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/ServiceInfo.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCSearchHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMuclumbusSearchHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCRoomSearchInfo.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/webapp/muc-room-summary.jsp
- xmppserver/src/main/webapp/muc-service-delete.jsp
- xmppserver/src/main/webapp/muc-service-edit-form.jsp
The commits in this PR should:
- increase performance when loading many MUC rooms from the database
- allow administrators to disable pre-loading all MUC rooms from the database at startup
- stop Openfire from ignoring rooms that are unloaded from memory
- improve the admin console
Please refer to the commit messages for more details.
> Various improvements for instances that have many MUC rooms

- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
Although normally, an XmppSession will be available, that won't be the case when, for example, sending an error about the XmppSession not being available.
Not doing packet accounting (and resetting an idle time) is preferable to not delivering the message due to a NullPointerException.
> OF-2265: Websocket delivery should not depend on XmppSession being present

- xmppserver/src/test/java/org/jivesoftware/admin/LoginLimitManagerTest.java
By using different values for username and address, there's less of a chance of individual tests affecting the others (like what we've seen happen in Github Actions).
> Using unique values to prevent inter-test interference

- .github/workflows/codeql-analysis.yml
The Github UI gave this warning:
> 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
This commit removes that step.
> Simplyfiy CI CodeQL workflow

- runConnectivityIntegrationTests
For reasons beyond me, one connection (out of many) for the BOSH connectivity test seems to fail - but only on the infrastructure for Github Actions.
From the output, it appears to be the _first_ connection that fails. I suspect that this is triggered by a weird scheduling/timing/eventing thingy that is specific to that environment.
This commit adds an additional connection attempt, for which the outcome will be ignored. Hopefully by 'warming up' the system under test, we get more stable results.
> Add warm-up connection to connectivity tests

- runIntegrationTests
Smack uses an API for two tests (SoftwareInfoIntegrationTest and EntityCapsTest) that itself defines to be 'unstable'). In Openfire CI, we see these tests occasionally fail. It stands to reason that that's because of the Smack-based unstable solution.
This commit disables both tests (one already was disabled), so that they don't break our build.
> Disable unstable Smack Integration Test

- xmppserver/src/main/java/org/jivesoftware/openfire/JMXManager.java
This commit ensures that the JMX manager is not started more than once, preventing concurrency issues.
> OF-2268: Prevent concurrency issue when starting JMX

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQOwnerHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
This adds support for sections "[7.2.12 Room Logging](https://xmpp.org/extensions/xep-0045.html#enter-logging)" and "[10.2.1 Notification of Configuration Changes](10.2.1 Notification of Configuration Changes)" of XEP-0045 (as introduced by version 1.21 of that XEP).
> OF-2275 / OF-2276: Send privacy-related status codes in MUC rooms

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
When joining a room is configured to restrict presence broadcasts, the reflected 'self-presence' should still have all added annotations as it'd otherwise get.
This fixes a bug where people can't join such a room (as the client doesn't receive the proper self-presence stanza as a result of the join)
> OF-2273: Ensure that self-presence mods are made when joining anon room

- xmppserver/src/main/webapp/muc-room-summary.jsp
now starting with 1 on first line
Issue: the muc line number in table starts with 2, not with 1 on first line
> fix numeration on muc-room-summary table

- runAioxmppIntegrationTests
In https://github.com/horazont/aioxmpp/commit/ccd00b7e377e65d884e12ce1f2167151612af9b8 'nose' was replaced by 'pytest' and 'pytest-cov'. As we're using the HEAD of their repository, we must have those packages available when running.
> Reflect aioxmpp project change: replace nose with pytest

- xmppserver/src/main/java/org/jivesoftware/util/WebManager.java
Functionally, this shouldn't change anything, other than preventing a stacktrace to be logged on debug level.
> OF-2317: Prevent NPE when opening admin console page without session

- xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/lockout/LockOutManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
- xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/vcard/DefaultVCardProvider.java
- xmppserver/src/test/java/org/jivesoftware/Fixtures.java
- xmppserver/src/test/java/org/jivesoftware/openfire/user/UserManagerTest.java
com.google.common.collect.Interner is not safe when used with Strings: as with String.intern(), an equal string value could end up being used as a mutex for unrelated code blocks (introducing the risk of deadlocks between code blocks that have no functional relation).
When an Interner instance is used with anohter immutable type, the generated mutexes are local to the Interner instance. This allows, for example, for the same JID value to be used with two different Interner instances, without the resulting mutexes influencing each-other.
This commit replaces all occurrances of Interner<String>.
> OF-2289: Do not use Interner<String>

- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
The existing code is based around a route of last resort, the
OutgoingSessionPromise, which builds a helper - the PacketsProcessor - and
creates the new session. The PacketsProcessors operate from within a thread
pool, and thus have contended execution time.
As new packets arrives from onward transmission during the session setup, the
PacketsProcessor queues them for retransmission. However, the act of session
creation also creates the outgoing route, meaning that later packets will
bypass the queue, and be transmitted out of order.
This should give the impression of a randomly reordered set of stanzas, but
would in fact be two consecutive sequences of ordered stanzas which are
interleaved, hence if the two sequences are A-E, F-J, one might see:
A, B, F, G, C, H, I, D, J, E
The fix here …
> OF-2322: Ensure outgoing queue is emptied before routing newer stanzas

- xmppserver/src/main/webapp/server-session-details.jsp
Without this, various different hostnames would be used for the same IP address. Although technically not wrong, that's confusing, as it suggests that different servers are in play.
With this change, the same hostname is used for each occurrence of an IP address.
> OF-2283: Ensure that all IPs use the same hostname

- xmppserver/src/main/java/org/jivesoftware/openfire/vcard/DefaultVCardProvider.java
With the changes of OF-2289, the mutex value was expected to be a username. For MUC rooms, a bare JID is used. Using that as the node-part for a new JID causes problems.
> OF-2320: Restore ability to obtain MUC vcard

- xmppserver/src/main/java/org/jivesoftware/openfire/net/TLSStreamHandler.java
When a peer closes the connection while performing an initial TLS handshake, a problem occurs if the state of the handshake remains 'not complete': the code in TLSStreamHandler#start() will loop until the handshake is complete. Subsequent iterations will read nothing, which repeats indefinitely. This can drain the available CPU resources.
Instead, throwing an exception will force the invoker to give up.
> OF-2325: Prevent endless loop when peer closes during TLS handshake

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
- xmppserver/src/test/java/org/jivesoftware/openfire/nio/XMLLightweightParserTest.java
The name of the start tag is possibly terminated by any newline character (eg: a newline character), not only the space character.
> OF-2329: Fix XML parser behavior when detecting the name of the start tag

- xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultLocalCacheStrategy.java
The clustered locks (based on Hazelcast) have some methods implemented that are not available in the non-clustered code.
The changes that have been applied to MUC's clustering implementation (OF-2220 for example) has introduced usage of these optional methods. This results in failing functionality when running Openfire in a non-clustered setup.
This commit adds an implementation for these optional methods.
> OF-2328: Implement optional Lock functionality for local locks

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_cs_CZ.properties
- i18n/src/main/resources/openfire_i18n_de.properties
- i18n/src/main/resources/openfire_i18n_es.properties
- i18n/src/main/resources/openfire_i18n_fr.properties
- i18n/src/main/resources/openfire_i18n_ja_JP.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- i18n/src/main/resources/openfire_i18n_pl_PL.properties
- i18n/src/main/resources/openfire_i18n_pt_BR.properties
- i18n/src/main/resources/openfire_i18n_pt_PT.properties
- i18n/src/main/resources/openfire_i18n_ru_RU.properties
- i18n/src/main/resources/openfire_i18n_sk.properties
- i18n/src/main/resources/openfire_i18n_zh_CN.properties
- xmppserver/src/main/webapp/user-create.jsp
Updates the create user page to include an option for assigning a group directly from that first page.
This implementation uses a text field expecting the exact name of a group, could potentially be improved with a dropdown list of available groups.
> OF-264 Add group selection field in Create New User page

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java
Issue described here: 
https://discourse.igniterealtime.org/t/bug-in-pep-service-updates-to-nodes-are-not-pushed-to-roster-contacts/90928
> OF-2337: Fix issue in pep, where events were not sent to roster contacts

- xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultCache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/SerializingCache.java
When plugins use the standard caches (in a cluster), ClassCastExceptions will occur after a plugin that has seen usage is reloaded/updated.
To prevent these exceptions, a new cache is introduced by this commit that stores data without a reference to the classes that define the data.
> OF-2239: Introduce new cache to be used by plugins

- xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultCache.java
The javadoc contract defines that the removed value is to be returned.
> OF-2336: Return removed value when adding oversided new value

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
When a stanza addressed to a remote domain cannot be processed, it is 'bounced'. Processing of these bounces has been a factor in at least two recent deadlocks on the Ignite domain.
This commit attempts to alleviate the problem by making the processing of the 'bounce' be asynchronous to the process that leads up to sending to original stanza (that was bounced). This decoupling allows locks/mutexes kept by the 'supplying' code flow to be released, before the 'bounce' is being processed (which arguably is a completely new stanza which needs not be processed under the original locks/mutexes anyway).
> OF-2341 / OF-2342: Process S2S 'bounces' async to prevent deadlocks

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/OfflineMessageStrategy.java
- xmppserver/src/main/java/org/jivesoftware/openfire/filetransfer/proxy/FileTransferProxy.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
In various places in the code, Openfire generates a response to a stanza, to be delivered back to the sender of the original stanza. Typically, this involves errors, such as delivery errors.
Some of the existing code uses the RoutingTable to deliver these stanzas. This works, but bypasses a lot of checks and flags (as well as the interceptors). For "new" stanzas, it's more appropriate to use PacketRouter, as this will more closely resemble the normal stanza processing.
> OF-2340: send stanzas that are 'responses' through PacketRouter, not RoutingTable

- distribution/src/resources/log4j2.xml
Having a verbose log level is convenient for development, but should not be the default level.
> Bump down default log level

- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
A Plugin is should be 'hot' re-deployable, but this fails when jar files cannot be removed. An extra line is added to close the Plugin classloader to free the resources and jars used by the plugin.
This replaces https://github.com/igniterealtime/Openfire/pull/1858
> OF-2348: Fix removing jars of a plugin after destroy.

- xmppserver/src/main/webapp/system-properties.jsp
The system property page shows default values for each property, but the space for that is limited. Longer values are abbreviated, which makes it hard to determine exactly what their content is.
This commit adds the full default value in the 'edit' form.
> OF-2349: Show default value for property on admin console

- pom.xml
This addresses the CVE-2021-44228 "LogJam" vulnerability.
> OF-2351: Update log4j to 2.15.0

- pom.xml
To fix https://nvd.nist.gov/vuln/detail/CVE-2021-45105. Fixes OF-2355
> OF-2355: Update log4j to 2.17.0

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
In MUC code that deals with room destruction, the 'room' instance is considered 'nullable' (in other words: it might not be there anymore).
The same code has a fall-back routine that intends to deal with cluster-related events. Prior to this commit, this unconditionally assumes that a local copy of the room will be present.
The former seems to contradictd the latter. This commit adds a null-check to the latter.
> OF-2358: When room is destroyed, consider that room might be gone

- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java
for this line to be ignored from the dependency scan as a false positive
> adds lgtm alert [java/zipslip] to ignore false positive

- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
- xmppserver/src/main/java/org/jivesoftware/util/WebXmlUtils.java
Instead of using a generic servlet context, use a plugin-specific one when loading servlets from a plugin. This allows the init-param values from their web.xml to be processed.
(Also, lots of debug logging - which reflects a bit of the pain I went through figuring out what was causing the issue that lead to this).
> OF-2352: Use plugin-specific servlet context

- xmppserver/src/main/java/org/jivesoftware/openfire/admin/JDBCAdminProvider.java
Simple change to switch from locking on the string SQL statement to using a dedicated lock object in the class.
> JDBCAdminProvider replaces sync with synchronizing on an object lock

- xmppserver/changelog.html
- xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterManager.java
- xmppserver/src/main/webapp/system-clustering.jsp
Logic for clusterwide fetching of plugin versions was previously located in a jsp. This PR moves that logic to the cluster manager, so it becomes available for reuse.
Furthermore a new method is introduced that detects version discrepancies of plugins between the local and other nodes. This will be useful for (at least) improving the monitoring plugin.
> OF-2360 Move plugin / OF version retrieval to ClusterManager

- xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterManager.java
- xmppserver/src/main/webapp/system-clustering.jsp
Prior to this change, plugins that were not installed locally (only on other nodes) were not included in the report that includes plugin version differences.
> OF-2360: Also show plugins not installed locally

- pom.xml
Another one in few days, to fix https://nvd.nist.gov/vuln/detail/CVE-2021-44832.
- https://logging.apache.org/log4j/2.x/security.html
CVE-2021-4104
CVE-2021-44228
CVE-2021-44832
CVE-2021-45046
CVE-2021-45105
> OF-2355 Update log4j to 2.17.1

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java
When sending notifications to subscribers of a parent collection node, only include those that match the applicable AccessModel.
> OF-2365: Pubsub - limit notifications to eligible (parent) subscribers.

- xmppserver/src/main/java/org/jivesoftware/util/SystemProperty.java
- xmppserver/src/test/java/org/jivesoftware/util/SystemPropertyTest.java
When reading a comma-separated string to be parsed as a list of strings, whitespace surrounding the comma's should be ignored.
eg: "user@example.org, user@example.com" should be parsed as two values that contain no whitespace.
> OF-2354: Allow whitespace around comma-separated string values for list

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
This commit combines approaches introduced by OF-910 and OF-2209 to detect a 'ghost user' in MUC.
Per OF-910, any Presence or Message stanza that contains an error is considered indicative of a ghost.
Per OF-2209, an IQ 'Ping' is used to determine ghosts.
Unlike the original solution for OF-2209, not all IQ error responses should be considered as indicative of a ghost. Firstly, the IQ error must be in response to an IQ Ping that was sent by the service itself. Furthermore, 'service-unavailable' and 'feature-not-implemented' can be considered as responses sent by a client (that does not support the IQ Ping protocol).
Finally, this commit adds a kick of users that have been pinged, but for which no response has been received at all.
> OF-2368: Improve MUC ghost user detection

- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketUtil.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/RemoteServerManager.java
When Openfire is configured to not allow inbound S2S of a particular flavor (direct or non-direct TLS) do not try to establish outbound S2S of the same type.
This effectively makes an outbound S2S attempt impossible when Openfire is configured to not accept any inbound S2S.
> OF-2369: Do not do outbound S2S when inbound disabled.

- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
The queue should be large enough to easily hold the stanzas sent back to a federated user that is joining a MUC room.
> OF-2371: Increase queue capacity for OutgoingSessionPromise

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/OccupantManager.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
A 'ghost' occupant (one that is no longer reachable) should be detected by an IQ ping (or routing issues), which is now tied to the 'Check if users are still connected after they have been idle for X minutes' in the admin console (defaults to 'enabled', 8 minutes)
Removing an 'inactive' user (in context of the 'Kick users after they have been idle for Y minutes' admin console setting) should _not_ take into account Ghost detection, as the original intent of this feature appears to relate to connected, but otherwise inactive users.
Kicking a 'ghost' that fails to respond to an IQ Ping should be tied to the IQ Ping request/response (and not, as previously implemented, by detecting continued inactivity for some period after a Ping request should have been sent).
Kicking an occupant doesn't …
> OF-2381: Fixes for MUC 'ghost user' and 'idle user' detection

- xmppserver/src/main/java/org/jivesoftware/util/XMLProperties.java
- xmppserver/src/test/java/org/jivesoftware/util/XMLPropertiesTest.java
The changes in this PR are motivated by observed thread contention in a high-volume environment. That's where the fixes in the first two commits stem from. I've added some minor fixes in subsequent commits.
I started off by using a ConcurrentMap to fix OF-2377, but that didn't quite cover all cases (in particular with protecting access to the 'document' field of this class). Instead, I've opted to go with a ReadWriteLock. This probably adds a bit of overhead, but should be more thread-safe.
One concession that I had to make for being able to use a ReadWriteLock, is to move all modifications that happened while a 'read' lock is acquired, outside of the lock (as ReentrantReadWriteLock guarantees that trying to obtain a 'write' lock while a 'read' lock is being held will fail). I've marked …
> Improvements to XMLProperties

- xmppserver/src/main/webapp/group-create.jsp
- xmppserver/src/main/webapp/group-edit.jsp
The database allows for up to 50 characters for a group name, and up to 255 for a description. The admin panel should not allow the end-user to provide longer values.
> OF-113: Limit lenght of group name/description to database restrictions

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/webapp/muc-tasks.jsp
With this new default settings, there's a lot less risk of Openfire incorrectly identifying occupants that are XEP-0198-detached as MUC ghosts.
> OF-2390: Redefine MUC ghost detection timing defaults

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/webapp/muc-room-edit-form.jsp
- xmppserver/src/main/webapp/muc-room-summary.jsp
MUC rooms can be 'locked', which typically occurs when they are initially being created and configured. When a MUC room is 'locked', it cannot be entered by users.
The Openfire admin console should make it possible for an administrator to see if a room is locked.
This commit replaces the value in the 'users' column on the room summary page with a 'lock' icon, and displays a warning on the room settings page, when the room is locked.
> OF-2398: Admin console: add visual indication of MUC room being locked

- xmppserver/src/test/java/org/jivesoftware/openfire/admin/GroupBasedAdminProviderTest.java
The test that's modified in this plugin fails if its execution was not preceeded by another test that initializes the cache factory.
> OF-2385: Fix unreliable test

- xmppserver/pom.xml
Openfire's internals have many statics that are hard to 'unset'. As a result, unit tests are very likely to affect one another.
To prevent this kind of interaction, this commit configures the unit test execution to happen in isolation, using a new for for every test.
This trades execution speed for reliability.
> Run the unit tests in isolation

- .github/workflows/continuous-integration-workflow.yml
Java 17 is the latest LTS release of Java. Openfire should build successfully with it.
This commit adds Java 17 to the matrix of builds that Github's CI workflow performs.
> CI: add Java 17

- xmppserver/src/main/webapp/decorators/main.jsp
- xmppserver/src/main/webapp/decorators/setup.jsp
In OF-2409, the DOCTYPE of the admin pages has changed to HTML 5. This apparently has the side-effect that CSS identifiers have become case sensitive.
The change in this commit fixes the issue of the build/login/clustering status information block to move back to the top-right corner of each page.
> OF-2409: Fix casing of CSS identifier

- xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java
OF-2377 introduced an updated implementation of the thread-safety module of XmlProperties (the old one wasn't fully thread-safe).
This new implementation causes a very specific problem at startup: When the initial attempt to migrate an XmlProperty is undertaken, TaskEngine is instantiated, which in turn tries to read/write properties (while under lock). This causes a deadlock.
To work around this issue, this commit replaces the usage of TaskEngine with a throw-away thread (that does not use any properties).
> OF-2411: Prevent deadlock in XmlProperties

- xmppserver/src/main/java/org/jivesoftware/util/CookieUtils.java
As long as we're exposing the admin console on a non-HTTPS endpoint (our port 9090), we will have a need to set cookies on an unsecure endpoint. This raises (rightfully) the LGTM 'insecure-cookie' alert, as Insecure cookies may be sent in cleartext, which makes them vulnerable to interception.
However, LGTM also raises this alert when we remove the cookie (which we do by setting an immediately-expired cookie with no data). The alert can be suppressed for that one.
> LGTM: ignore insecure-cookie when unsetting the cookie.

- xmppserver/src/main/java/org/jivesoftware/openfire/commands/event/GroupAdminAdded.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/event/GroupAdminRemoved.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/event/GroupCreated.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/event/GroupDeleting.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/event/GroupMemberAdded.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/event/GroupMemberRemoved.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/event/GroupModified.java
- xmppserver/src/main/java/org/jivesoftware/openfire/group/AbstractGroupProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/group/DefaultGroupPropertyMap.java
- xmppserver/src/main/java/org/jivesoftware/openfire/group/Group.java
- xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/group/SharedGroupVisibility.java
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/Roster.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/RosterItem.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/RosterManager.java
- xmppserver/src/test/java/org/jivesoftware/openfire/group/AbstractGroupProviderTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/group/DefaultGroupProviderTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/group/GroupManagerNoMockTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/group/GroupManagerTest.java
Reduce complexity by centralizing the responsiblity of dispatching events to event listeners and cache updates.
Avoid using the event listener mechanism that's also being provided to users of this API in the implementation itself.
As a byproduct of the latter, this fixes OF-2426: an event dispatched by the implementation no longer re-populates the cache unexpectedly.
> OF-2426: Refactor Group implementation

- xmppserver/src/main/java/org/jivesoftware/util/FaviconServlet.java
LGTM static analysis spot that we obtain a favicon from user-provided input (a hostname). In OF-1885, we've addressed this by asserting that the entity that is retrieved is valid. This LGTM warning can be ignored here.
> LGTM: ignore ssrf result when obtaining favicon

- xmppserver/src/main/java/org/jivesoftware/openfire/Connection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/multiplex/ClientSessionConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/ServerSocketReader.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketReader.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketReadingMode.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/ConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NIOConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
When a stream is being closed, it's often helpful to signal why this happens, especially when the stream is closed due to an error.
This commit adds stream errors in various places where such context is desirable.
The API to close a connection has been modified to be able to include an optional stream error. This replaces an older structure where a stream error is first sent manually, followed by a call to the 'close' API. With this change, only one attempt to send data is made instead of two (one for the stream error, and another one for the end-stream tag).
As there's an API change, we'd better not include this change in a patch release.
> OF-2414: Where appropriate, send a stream error before closing a stream.

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
This implements a hack that redirects IQ requests from one MUC occupant to another to the bare JID of the occupant, rather than the full JID. This allows the home server of the occupant (rather than its client) to process the request. This is in-line with how XEP-0054 defines how VCards should be requested.
> OF-2428: Allow MUC occupants to request each-other's VCards

- .github/workflows/codeql-analysis.yml
This prevents a failure that logs this error: "Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events."
> Prevent CodeQL from running on Dependabot pushes

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java
The changes in this PR should lead to a fix for a BOSH related deadlock in Openfire 4.7.0 and 4.7.1, as described in [OF-2444](https://igniterealtime.atlassian.net/browse/OF-2444). When the PR was created, this wasn't yet achieved. I have created the PR as a draft for that reason.
My goal is to incrementally reduce complexity and, in particular, the usage of locks in the `HttpSession` class. In particular, I believe that the deadlock described in OF-2444 is prevented when the processing of inbound data (provided by a BOSH request) no longer occurs under guard of the lock represented by the `connectionQueue` field.
This PR builds up to a refactoring that would allow for that change to become possible.
The refactoring is sufficiently complex that I would welcome feedback on my approach …
> OF-2444: Deadlock in BOSH implementation

- xmppserver/src/main/java/org/jivesoftware/openfire/LocalSessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/ComponentStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SASLAuthentication.java
- xmppserver/src/main/java/org/jivesoftware/openfire/sasl/AnonymousSaslServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/sasl/ExternalClientSaslServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/LocalRoutingTable.java
- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
Under certain circumstances (notably, when a session is detached), a session's connection can be null.
This commit adds assertions to identify the null-ability of a sessin's connection, and ensures that a null connection is not attempted to be used in a context where it is assumed to be non-null.
> OF-2424: Assert when LocalSession is null

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
Calling 'close' will trigger event listeners, that in turn can try to consume queuedConnections. Deadlocks have been observed following this pattern.
This commit calls the 'close' method outside of the mutex, which prevents that problem.
> OF-2444: Call 'close' outside of lock

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
Probably due to a simple bug, the answer was given on the latest connection, rather than the connection that is being processed.
> OF-2450: BOSH pause response should be given on the connection that requests the pause

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
The code is using this List as a queue. Using an ArrayList for this isn't very efficient. A LinkedList (or any Queue) is expected to perform better.
> OF-2446: Use a more efficient List implementation for HttpSession's sentElements

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/net/ServerStanzaHandler.java
Openfire should not assume that JIDs in stanzas supplied by remote domains are stringprepped. It should apply stringprepping itself.
The property `xmpp.server.incoming.skip-jid-validation` can be used to control this behavior.
> OF-2462: Do not skip stringprep in S2S

- xmppserver/src/main/webapp/pubsub-node-configuration.jsp
This fixes a NullPointerException that was shown when someone looked at the configuration of a Pubsub node in Openfire's Admin Console.
> OF-2469: fix NPE on admin console (pubsub config)

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Claude and Dele isolatedf a case where a Jitsi client sends an IQ Result stanza with no child elements, causing an NPE in a new feature introduced in Openfire 4.7.2.
This defends against it. I can't see any other instances of this risk in this class.
Cherrypick for 4.7
> OF-2470: Protect against NPE from IQ stanza with no child elements

- pom.xml
- xmppserver/src/main/java/org/jivesoftware/openfire/net/StartTlsFilter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NIOConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionManagerImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java
By updating to Apache MINA to its 2.2 branch, a new TLS implementation is pulled in. In testing, this version has shown to resolve the issues with TLSv1.3 in direct TLS and StartTLS that are described in OF-2435.
> OF-2435: Update Apache MINA to version 2.2.1

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
This basically is a hack to get Tsung to connect to Openfire over websockets.
The functionality introduced here is switched off by default. If enabled, it replaces `stream` element names with `open` and `close` where appropriate, to conform to 'XMPP framing' as described in https://datatracker.ietf.org/doc/html/rfc7395#section-3.3
> OF-2479: Allow clients that do websockets without the required XMPP framing

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
Jetty's websocket implementation invokes `@OnWebSocketError` and `@OnWebSocketClose` annotated methods when certain erroneous conditions occur. These invocations happen synchronously.
As a result, a 'close' operation is called synchronously to the processing of the original request, which can happen under guard of a mutex. This leads to the 'close' implementation being called while a mutex is held that is intended to be held only while inbound data is being processed. This has lead to deadlocks.
An example scenario is when a websocket request arrives that asks to close the connection. Sometimes (presumably if the per immediately disconnects the connection, rather than waiting for an answer), returning a response fails ('EOF'). This then triggers error handling.
This commit makes the …
> OF-2473: Prevent websocket deadlock

- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/keystore/CertificateStoreManager.java
During setup, the CertificateStore manager is started briefly, to ensure that it contains at least a minimum viable certificate. After this has been established, it is shut down again.
This brief occurrence starts an entity that watches the file system for changes (OF-1373: Allow certificate changes to be applied without a restart). Having this watcher running prevents the admin console webserver from being restarted quickly, causing the admin console to be unavailable for about half a minute.
With the changes in this commit, the initial start of CertificateStoreManager will now happen without the 'watching' being started. This prevents issues with reloading the web server.
> OF-2480: Ensure that admin console starts after setup

- xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java
The fix (which as of yet is unreleased) for OF-2413 introduces a bug, where a call to close() doesn't do anything anymore.
This bug is introduced in commit 257806e4ce061462de782d69fe5afeabdcdc9264, which was merged in the main branch of the Openfire repository with pull request https://github.com/igniterealtime/Openfire/pull/2026. No releases have been made from that branch, since this issue was introduced. By merging this change prior to the next release of the main branch (expected to be v4.8.0), the bug can be fixed before it was ever released.
> OF-2413: Ensure that connections are closed, when no error occurs.

- xmppserver/src/main/webapp/muc-room-affiliations.jsp
The admin console page that allows you to change MUC room permissions / affiliations has a drop-down box that lists all possible affiliations. Whenever that drop-down is changed, the page used to reload, causing all modifications to be lost. This was done to show or hide the 'nickname' input field.
This commit shows/hides that field with javascript magic, removing the need for a page reload.
> OF-2467: Do not reload admin page when changing MUC affiliation dropdown

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java
this is a rebase of an old PR:
https://github.com/igniterealtime/Openfire/pull/1571
-using range retrieval on group lookups if needed
-using ldap.pagedResultsSize for range pagesize 
... cause there is a limit of 1500
see: https://docs.microsoft.com/de-de/previous-versions/windows/desktop/ldap/searching-using-range-retrieval?redirectedfrom=MSDN
> OF-2116 Using range retrieval for LDAP groups on Active Directory

- xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java
Openfire property `update.lastCheck` stores as a truncated to millis value, so we should truncate the last check instant before doing a comparison against the stored property.
> OF-2484 truncate last update instant to millis

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
XEP-0045 mandates a 'from' attribute on the 'invite' element, used for mediated invitations. This aught to be the address of the inviter. In some scenarios, there is not an identifiable XMPP entity that is the inviter (eg: when an invitation is generated through the admin console or REST api). In such cases, this commit will use the bare JID of the room itself as the invitation. Reasoning that it can be thought of as the inviter, and having at least some value is less likely to break clients that expect the attribute to be present.
> OF-2486: Ensure mediated MUC invite has a 'from'.

- xmppserver/src/main/webapp/import-truststore-certificate.jsp
- xmppserver/src/main/webapp/security-truststore.jsp
This mimics similar behavior introduced by OF-2212 for the identity store. When the trust store is modified by an administrator, restarting the admin console immediately is undesirable, as it kicks out the admin that is busy applying changes.
> OF-2483: Delay restart of admin console when truststore content is changed

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
Prior to this, the failure to identify a client session as a (regular) user session resulted in the session being assumed an anonymous user session. When a session is removed twice (which should not occur, but does occur with websockets for some reason), this causes a second client route to be removed from the cache.
This commit ensures that a session is indeed an anonymous session before assuming that it is.
For websockets, a warning will still be logged, as there are still two attempts to remove the session. Optimizing this is the subject of another issue: OF-2485
> OF-2423: Improve removal of client sessions from cache

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
Openfire's database support only 100 characters for a MUC room subject.
To prevent database errors, this commit truncates subjects that are longer than this.
> OF-400: Truncate MUC subjects longer than 100 characters

- xmppserver/src/main/java/org/jivesoftware/util/XMLProperties.java
When updating XMLProperties files (`openfire.xml`, `security.xml`), do not:
- create a new temp file
- remove the old file
- copy temp file to the location of the old file
- remove the temp file file
Instead, do this more atomicly, as such:
- create a new temp file
- move temp file to replace to old file
There will leave Openfire in a more consistent state if somewhere along the line, things go wrong. Also, it reduces code a bit.
> OF-2487: More atomicly replace XMLProperties files

- xmppserver/src/main/java/org/jivesoftware/openfire/net/DNSUtil.java
When a particular DNS SRV record doesn't exist, there is no need to log this on level ERROR with a stack trace. The administrator of Openfire is unlikely to be able to fix this, while it occurs all the time.
> OF-2488: Reduce log level sevierty of DNS lookup failure

- xmppserver/src/main/java/org/jivesoftware/openfire/filetransfer/proxy/ProxyConnectionManager.java
Whenever a peer sends unexpected data to the file transfer proxy, an exception occurs. As this is not something that can be 'fixed' by an Openfire administrator, the error shouldn't be logged as verbosely as on level ERROR.
This commit reduces the log level on which this is logged, and improves the wording of the logged message a little.
> OF-2489: Reduce log level severity of SOCKS5 error

- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
Only local, registered users of Openfire have a PEP service. Other users do not. When a client tries to interact with such a non-existing PEP service, the current behavior of Openfire is to very verbosely log this as an (unexpected) error.
This code tries to properly handle this scenario, by returning a nice error back to the requestee, and logging it less verbosely.
> OF-2490: Better handle PEP requests to non-local/non-registered users

- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
This commit ensures that the handling of the onError event is done in the same thread pool as that is using data. This should help ensure that those events are handled in roughly the same order. This in turn prevents data that has been supplied previously from going unprocessed, because the onError handler is executed 'early'.
> OF-2495: Websocket onError handler prevents earlier data to be processed

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/HistoryStrategy.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
- xmppserver/src/test/java/org/jivesoftware/openfire/muc/HistoryStrategyTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/muc/MUCRoomTest.java
As suggested in a 'TODO' comment in code, this replaces the MUC history that is stored inline with each MUC room, with a cache lookup.
This change intends to result in a performance boost, as retrieving/storing MUC rooms from a cache (and serializing them between cluster nodes) no longer includes the history. The data associated with history is typically very large (~50kb for 25 messages), but changes a lot less often than the room itself.
> OF-2499: No longer serialize MUC history with room

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
When collecting statistics, two MUC methods iterate over caches. That is inefficient in itself, but the cache can also be clustered. If that's the case, then a lot of data serialization, which is a waste of resources.
This commit introduces a new cache in which statistics can be stored. This way, the statistics need not be recalculated every time, saving resources at the expense of potential inaccuracy.
> OF-2502: Do not iterate over clustered cache when calculating stats

- .github/workflows/macos-release-artifact.yml
Motivation: I want to remove the ancient mac on my desktop that just runs an Ignite Realtime bamboo agent :)
This PR creates a Github Action on MacOS that:
- builds openfire
- creates the DMG artifact
- conditionally uploads it to github when releases are made
I made a [fake release](https://github.com/akrherz/Openfire/releases/tag/v9.9.6) within my fork to hopefully test that this upload works.
> create macos github action job for releases

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java
- xmppserver/src/main/resources/admin-sidebar.xml
- xmppserver/src/main/webapp/system-admin-console-access.jsp
- xmppserver/src/test/java/org/jivesoftware/admin/AuthCheckFilterTest.java
This adds an 'allow' and 'block' list of IP(v4) addresses, that controls access to the admin console.
A third property is added that can be used to configure if these lists should also be applied when accessing pages that are otherwise 'excluded' from access control by the AuthCheckFilter.
An admin console page has been added to easily configure the new properties.
> OF-2474: IP-based access control for the admin console

- distribution/src/bin/openfirectl
This fixes a bug in the openfirectl script that failed to store the PID of the Openfire process that it just started.
> OF-2509: openfirectl should store PID value

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/HistoryStrategy.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
Typically, rooms are configured to retain only 25 message of history, to be sent to clients that join a room (note that this does _not_ relate at all to MAM).
When loading a room from the database, Openfire should not load _all_ messages from the database, but only the ones that are potentially going to be sent to clients. For rooms which a large history, this saves a considerable amount of resources.
This commit uses somewhat of a hack that is based on database driver functionality (skipping ahead in the resultset), as opposed to modifying the SQL query that is used to obtain the records. Such modification would likely depend on non-standardized SQL staments (TOP / LIMIT / ROWNUM), which would introduce the need for database-vendor specific code.
> OF-2511: Prevent loading unused historic messages for MUC rooms.

- xmppserver/src/main/webapp/user-lockout.jsp
When using a longer value as a custom amount of lock-out minutes, the multiplication of two integers overflows the maximum integer value. Using longs instead of ints prevents this.
> OF-2512: Fix for long custom user lockout values

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
Openfire keeps track of the amount of stanzas sent through a connection. For BOSH connections, the outgoing count was never updated. This is fixed in this commit.
This change also ensures that a 'last activity' field is updated more frequently. This could improve the stability of BOSH connections.
> OF-2517: Fix 'packet sent' count for BOSH connections

- .github/workflows/codeql-analysis.yml
v1 is being deprecated: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
> Update CodeQL action from v1 to v2

- xmppserver/src/main/java/org/jivesoftware/util/FaviconServlet.java
This adds an additional attempt to load the favicon. With this, both HTTPS and HTTP are attempted.
Additionally, the URL that's used is now being constructed through a builder, which should further reduce the attack vector of using 'user-provided input'.
> OF-2518: Attempt to load favicon over HTTPS

- distribution/src/database/openfire_db2.sql
- distribution/src/database/openfire_hsqldb.sql
- distribution/src/database/openfire_mysql.sql
- distribution/src/database/openfire_oracle.sql
- distribution/src/database/openfire_postgresql.sql
- distribution/src/database/openfire_sqlserver.sql
- distribution/src/database/openfire_sybase.sql
- distribution/src/database/upgrade/34/openfire_db2.sql
- distribution/src/database/upgrade/34/openfire_hsqldb.sql
- distribution/src/database/upgrade/34/openfire_mysql.sql
- distribution/src/database/upgrade/34/openfire_oracle.sql
- distribution/src/database/upgrade/34/openfire_postgresql.sql
- distribution/src/database/upgrade/34/openfire_sqlserver.sql
- distribution/src/database/upgrade/34/openfire_sybase.sql
- xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/HistoryStrategy.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
Two changes (see individual commit messages for details):
- add all messages to the history in one batch, to prevent repeated acquiring and releasing of a (cluster-wide) lock
- add database index to speed up query to retrieve messages from the database.
> OF-2524: Improving speed of loading MUC history from database

- .github/workflows/continuous-integration-workflow.yml
- .github/workflows/macos-release-artifact.yml
Fixes #2528
Remove use of deprecated 'set-output' function in Github Actions.
> OF-2528: Migrate set-output to use $GITHUB_OUTPUT

- xmppserver/pom.xml
Fixes OF-2529
Updates Apache commons-text in Openfire to prevent it incorrectly appearing as vulnerable to CVE-2022-42889, even though it isn't, since we don't use the affected portions of the library.
> Update apache commons-text from 1.6 to 1.10.0

- build/docker/entrypoint.sh
Without this fix, mapping an empty folder prevents Openfire from booting
> OF-2415: Allow empty plugins directory at boot time in Docker entrypoint

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/pom.xml
- xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java
- xmppserver/src/main/webapp/system-admin-console-access.jsp
- xmppserver/src/test/java/org/jivesoftware/admin/AuthCheckFilterTest.java
This adds to the new IP-based access control for the admin console that was introduced in 4.8 via OF-2474 / https://github.com/igniterealtime/Openfire/pull/2074
Now, IP _ranges_ can also be used (eg, 192.168.2.0/24).
Also improved IPv6 support
> OF-2533: AdminConsole's IP access should allow ranges

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubModule.java
XEP-0060 defines, amongst many others, the 'multi-items' service discovery feature.
This feature can be advertised by a pubsub service, when clients are allowed to configure a node in such a way that it can accept more-than-one item, by:
- setting `persist_items` to `true`
- setting `max_items` to a value higher than 1.
Openfire supports allows for both. It can/should advertise the feature `http://jabber.org/protocol/pubsub#multi-items` on its pubsub services.
> OF-2537: Advertise support for pubsub's 'multi-item' feature

- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java
ZipSlip is possible only when explicitly enabled by an administrator. No need to have a static analyzer alert for this particular case.
> Suppress LGTM alert for ZipSlip in PluginMonitor

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
The pubsub node configuration option `pubsub#deliver_payloads` is defined in XEP-0060 to control if payloads are included in pubsub notification events. Openfire should not use it to determine if payloads are to be included when answering item retrievals (those should _always_ have payloads, if they exist on the item).
> OF-2543: When retrieving pubsub items, always include payload

- xmppserver/src/main/java/org/jivesoftware/openfire/Channel.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java
- xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdGroupProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdUserProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/keystore/CertificateStoreWatcher.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
- xmppserver/src/main/java/org/jivesoftware/util/SAXReaderUtil.java
This overrides the default name (pool-x-thread-y) used for threads generated by an executor service to something that is more identifiable. Should not introduce functional changes.
> OF-2539: Improve naming of threads

- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
Let's decouple the stream ID and resource identifier that's used by default. This should help make both less predictable.
> OF-2523: Do not re-use stream ID as the default resource ID

- xmppserver/src/main/java/org/dom4j/io/XMPPPacketReader.java
- xmppserver/src/main/java/org/jivesoftware/openfire/Connection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
- xmppserver/src/test/java/dom/io/XMPPPacketReaderTest.java
XMPP connections take the form of an XML document, starting with a 'stream' root element.
Openfire processes the direct child elements as if they were individual documents (for reasons beyond the scope of this issue). In that approach, any namespaces defined in the original root element are lost.
Generally, this isn't much of an issue, as a default namespace is assumed/used that is specific to the connection type. However, if the root element defined _other_ issues, that information is lost.
Defining additional namespaces is allowed in XML/XMPP, but isn't typically used. If it were, we would have hit problems long ago. There is one known application of this, which is Dialback (refactoring Openfire's S2S server to use MINA as part of OF-1112 is how this issue was found).
Openfire should be …
> OF-2556: Record namespace prefixes sent on root XML element

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionListener.java
This fixes a bug that occurs when the verifyCertificateValidity call of a ConnectionListener is delegated to a fall-back ConnectionListener.
> OF-2561: Fix fallback for ConnectionListener 'verify'

- xmppserver/src/main/java/org/jivesoftware/openfire/net/DNSUtil.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
The value of `xmpp.server.tls.policy` is an enum. It should not be evaluated as a boolean.
> OF-2551: Fix readout of TLS Policy config value for S2S

- xmppserver/src/main/java/org/dom4j/io/XMPPPacketReader.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
- xmppserver/src/test/java/dom/io/XMPPPacketReaderTest.java
Additionally ignore any explicity declaration of the http://etherx.jabber.org/streams namespace.
> OF-2556: Ignore stream namespace

- distribution/pom.xml
The 1.1.2 version is 5 years newer than 1.1.1, so it has to be better, right?
> bump install4j maven plugin to latest release

- distribution/src/resources/log4j2.xml
Fixes OF-2527.
Changes the log4j2.xml configuration to default to using milliseconds in the Openfire log file.
> OF-2527: Default to millisecond-precision in log4j

- xmppserver/src/main/java/org/jivesoftware/util/JiveProperties.java
When deleting a property, its child properties are expected to be deleted.
The original code would also delete properties that shared a common prefix. That is fixed by this commit.
> OF-2538: Only delete true child properties

- xmppserver/src/main/java/org/jivesoftware/openfire/commands/admin/muc/CreateMUCRoom.java
Openfire provides an ad-hoc command that can be used to create a room. Openfire must ensure that room name values provided through that command are properly normalized (nodeprepped).
> OF-2508: Nodeprep room name when creating through Ad-hoc command

- xmppserver/src/main/webapp/session-row.jspf
- xmppserver/src/main/webapp/session-summary.jsp
Tidies up the implementation from OF-2192, adding the name of the software being used, as well as the version.
Openfire appears to allow for other properties in the map created from the pairs received in the IQ, but Name and Version are the only props required by XEP-0092.
> OF-2573 Add Name to Version in Session Summary

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/webapp/server-locale.jsp
- xmppserver/src/main/webapp/setup/index.jsp
- xmppserver/src/main/webapp/style/setup.css
Admin console pages in which translations are selected now have a text that invites people to supply translations via Transifex.
> OF-2581: Add invite to Transifex to admin console

- .github/workflows/continuous-integration-workflow.yml
We had hard coded to run on `ubuntu-18.04` due to perceived issues with python+epoll on later ubuntu releases.  Well, this runner is going away at GHA by the end of the month, so lets see what `ubuntu-latest` yields us now.
> CI: run on ubuntu-latest

- .github/workflows/codeql-analysis.yml
- .github/workflows/continuous-integration-workflow.yml
- .github/workflows/database-upgrades.yml
- .github/workflows/macos-release-artifact.yml
This updates all Github actions for which the following deprecation warning is logged:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v1, bruceadams/get-release@v1.2.3, actions/upload-release-asset@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
There is one exception: the 'upload-release-asset' used by macos-release-artifact does not have an update.
> Github actions update (node12 -> node16)

- .github/workflows/continuous-integration-workflow.yml
This reverts commit 63e2e12d32c34ba11d855e73411fc74fce0f54f3.
https://github.com/horazont/aioxmpp/issues/391 suggests that with the new Python 3.11.4, the problem that occured in 3.11.3 has been resolved. If that's the case, we no longer have to pin to 3.11.2.
> Revert "Limit aioxmpp's python to 3.11.2 "

- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingServerSocketReader.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialback.java
While waiting for a response to a Dialback request, Openfire should terminate when the underlying connection is closed.
> OF-2608: Do not wait for Dialback response if connection is closed

- xmppserver/pom.xml
This intends to replace https://github.com/igniterealtime/Openfire/pull/2203
> OF-2616: Upgrade Gauva from 30.1-jre to 32.0.1-jre

- plugins/openfire-plugin-assembly-descriptor/src/main/resources/assemblies/openfire-plugin-assembly.xml
* When creating a plugin project using src/java for the source root, plugin.xml must be in the root.
* When creating a plugin project using the default src/main/java structure, the plugin.xml must be in the src folder.
This is because the openfire-plugin-assembly specifically looks for this file two directories above.
This makes the building more flexible, searching in the project root for the plugin.xml and html files, but keeps the old rule too to avoid breaking existing plugins.
Most of our plugins (e.g. Rest API, Monitoring, Hazelcast) use `src/java` and so have plugin.xml in the root. There are some exceptions (Push Notification, Thread Dump, MUC RTBL) which use the default structure and store the XML in the `src` directory. Real outliers include the Password Reset plugin (which uses …
> OF-2614 - Always allow plugin.xml in be the root of a plugin source tree

- xmppserver/src/main/webapp/muc-service-summary.jsp
The room count href link on muc-service-summary.jsp jump to muc-room-summary.jsp add parameter use '==', this will jump to the default page on muc-room-summary.jsp.
> OF-2621: Fix the href link error on muc-service-summary.jsp

- documentation/implementing-authprovider-guide.html
- documentation/implementing-groupprovider-guide.html
- documentation/implementing-userprovider-guide.html
- documentation/index.html
- documentation/ldap-guide.html
- documentation/pluggable-roster-support-guide.html
This PR intends to add three developer guides, for each of the `Provider` interface:
- AuthProvider
- GroupProvider
- UserProvider
Some slight refactoring of exising documentation cannot be ruled out. :)
> Documentation: add Custom Provider Guides

- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
When autosetup is running, existing code forced the database connection provider to be the default, when the authprovider was the default.
I'm not seeing why this is needed.
The result of this is that after running auto-setup (with a default auth provider config), all starts of Openfire except for the first one are likely to fail, when the original setup used something else than the default database provider (eg: the embedded provider).
> OF-2592: autosetup: Do not force default DB when authprovider is default

- xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemPropertiesServlet.java
This param "encrypt" is in request form body, not in request attribute.
> OF-2630 - Get parameter uses incorrect method

- xmppserver/src/main/webapp/group-create.jsp
- xmppserver/src/main/webapp/group-delete.jsp
- xmppserver/src/main/webapp/group-edit.jsp
- xmppserver/src/main/webapp/group-summary.jsp
This prevents issues with working with group names that have URL-escaped characters in their name (like the `+` character).
> OF-2627: Correctly URL-escape group names in admin console

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
- xmppserver/src/test/java/org/jivesoftware/openfire/nio/XMLLightweightParserTest.java
Prevent possibility of regular expression execution depending on user-provided values taking exceptionally long / many resources to complete
This commit replaces the regular expression with a solution that doesn't use regular expressions. Arguably, the complexity of this code does not change much.
> OF-2628: Avoid polynomial regular expression used on uncontrolled data

- documentation/index.html
- documentation/load-balancing.html
Rendered preview: https://htmlpreview.github.io/?https://github.com/igniterealtime/Openfire/blob/6431308e58fda3f3f6f643faa3bafc3cf3efb83f/documentation/load-balancing.html (this link points to a very specifc commit and is likely to outdate pretty fast).
> Documentation: add Load Balancing Guide

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/PrivateStorage.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/admin/GetServerStats.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCRegisterHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQOwnerHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CollectionNode.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultNodeConfiguration.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PendingSubscriptionsCommand.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubModule.java
- xmppserver/src/main/java/org/jivesoftware/util/LocaleUtils.java
- xmppserver/src/main/webapp/pubsub-node-edit.jsp
When a user is requesting a data form, try to localize the text in the form according to the user's preferred language.
In this commit, the preferred language is being obtained from the session of a locally connected user. This will not work for federated users.
As a fallback, the default langague as configured in Openfire is used (as is already the case prior to this commit).
> OF-2624: Try to answer data forms in users' preferred language

- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
This might have been a problem that existed in the code for a long time, but only popped up with the migration from MINA to Netty: that's when ServerStanzaHandler started to being used in anger.
ServerStanzaHandler is invoked to create a session. The code more or less assumes that this always happens.
When a session is not created, the code should inform the peer that something went wrong. Without that, the peer is left hanging.
In this commit, any attempt to create a session that does not lead to a session being created results in a stream error to be returned to the peer, after which the connection is forcefully closed.
> OF-2559: When Inbound S2S session fails, return stream error

- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
When Openfire is configured to require TLS for S2S, the StartTLS feature that’s advertised should be marked as being “required”. It currently is only when Dialback is not available (making TLS needed for authentication purposes).
> OF-2633: When S2S TLS is required, announce that

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyIdleStateKeepAliveHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java
- xmppserver/src/main/webapp/server-session-details.jsp
Fixes session cleanup on idle
Adds idle state handling for outbound connections so that they are automatically closed when idle, as is already the case for inbound connections. Closes the connection on idle, not just the channel, to ensure that connections and sessions are cleaned up properly.
Also fixes:
- NPE on server session details page in admin console
- Errors when compression is enabled with TLS
> Fix for Netty connection cleanup bug

- documentation/install-guide.html
The firewall section of the install guide should make it clear that even though the admin console _can_ be exposed to the general internet, it should not be.
By highlighting port numbers and using paragraphs per subject, the text becomes easier to consume.
The old text discarded the DirectTLS ports. At some point in time, it was believed that these would be phased out. As that's not the case, they should be mentioned in the guide.
> OF-2638: Firewall documentation improvements

- xmppserver/src/main/java/org/jivesoftware/openfire/net/ServerStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnectionHandler.java
This fix restores the pre-existing behaviour of Openfire before the migration to the Netty framework for NIO (OF-2559).
> OF-2641 - Cannot establish S2S with conference subdomain

- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionListener.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalIncomingServerSessionTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalOutgoingServerSessionTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteReceivingServerDummy.java
Prior to this commit, the unit test for LocalIncomingServerSession used the old, pre-Netty code. With this commit, the Netty code is being used instead.
Insteead of the old blocking code, the test now uses a (Netty-backed) ConnectionListener directly. To identify the LocalIncomingServderSession instance that is to be created, a streamID value is used, which is collected by the dummy server peer implementation for that purpose.
> OF-2559: Use Netty for LocalIncomingServerSessionTest

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
This intends to guard against null pointer exceptions.
With the new Netty code, I'm seeing null pointer exceptions on the admin console (see screenshot).
Although this PR might prevent the NPE, there migth be a deeper issue that is not addressed by this PR. At the time that this screenshot was taken, Openfire did not have any active server-to-server sessions (as verified by the `netstat` command).
> OF-2559: Do not assume that all connections have established TLS

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/sasl/ExternalServerSaslServer.java
In the old days, the 'from' attribute on a stream element was not present. This made providing an authorization identity during the SASL handshake a requirement (otherwise, you'd not know who you'd be talking to).
Now that the 'from' attribute can be relied on to provide the identity of the peer, it does not need to be included in the SASL EXTERNAL handshake any longer.
This commit drops this requirement, but adds a new property (`xmpp.auth.sasl.external.server.require-authzid`) that can re-introduce it.
> OF-2639: No longer require authzid for S2S SASL EXTERNAL

- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
This code aims to prevent PEP from being used to store avatars. The existing code will not prevent this, and should be removed.
Potentially, it is to be replaced with something that integrates the avatar upload with the VCardManager, to facilitate conversions between the various avatar-based XEPs. See OF-2034
> OF-2642: Remove incorrect code to prevent XEP-0084

- xmppserver/src/test/java/org/jivesoftware/openfire/session/AbstractRemoteServerDummy.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java
TLS handshaking is resource intensive. Relax the SO_TIMEOUT value a bit, to prevent test failures in constraint environments.
> Improve SO_TIMEOUT for more stable S2S unit test execution

- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalIncomingServerSessionTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalOutgoingServerSessionTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteReceivingServerDummy.java
As the automated S2S tests now use Netty we can confidently run these tests using TLSv1.3
This PR also removes the modification of expected outcome logic for LocalOutgoingServerSessionTest as it appears to no longer be needed.
> Implement use of TLSv1.3 for S2S automated tests

- xmppserver/src/main/java/org/jivesoftware/openfire/csi/CsiManager.java
There is an unintended fall-through in a switch/case that leads to a warning being logged.
> OF-2649: Prevent incorrect CSI warning message from being logged

- xmppserver/src/main/java/org/jivesoftware/util/FaviconServlet.java
Do not try to resolve the input value when trying to validate it. This is resource intensive, and will fail for valid values that are not currently being used (for which the lookup will return no hits).
> OF-2653: Optimize hostname validation

- xmppserver/src/main/java/org/jivesoftware/database/EmbeddedConnectionProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/component/InternalComponentManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java
- xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java
- xmppserver/src/main/java/org/jivesoftware/util/FaviconServlet.java
- xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java
- xmppserver/src/main/java/org/jivesoftware/util/XMLProperties.java
- xmppserver/src/main/webapp/setup/setup-datasource-settings.jsp
- xmppserver/src/test/java/org/jivesoftware/Fixtures.java
This removes all code that was marked as being deprecated, and to be removed in or after release 4.8.0
Most of the removal revolves around making references to files more type-safe, by moving from String to Path.
> OF-2647: Remove deprecated code

- xmppserver/src/main/java/org/jivesoftware/openfire/RoutingTable.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
- Explicitly add close listener for new sessions that are created.
- Fix the new session on stream ID code for outbound S2S by verifying the streamID is new.
- Clear routing table cache of any lingering session objects via a replaceServerRoute function in the RoutingTable for atomic session replacement
> OF-2655: Fix S2S outbound hanging

- xmppserver/src/main/java/org/jivesoftware/database/EmbeddedConnectionProvider.java
- xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/audit/spi/AuditManagerImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/component/InternalComponentManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdProperties.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/ResourceServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/keystore/CertificateStoreManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java
- xmppserver/src/main/java/org/jivesoftware/util/FaviconServlet.java
- xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java
- xmppserver/src/main/java/org/jivesoftware/util/Log.java
- xmppserver/src/main/webapp/index.jsp
- xmppserver/src/main/webapp/logviewer.jsp
- xmppserver/src/main/webapp/setup/setup-datasource-settings.jsp
- xmppserver/src/test/java/org/jivesoftware/Fixtures.java
A previous commit for OF-2647 replaced the argument to the getter and setter of `JiveGlobals.setHomeDirectory()` from a String to a Path.
This leads to compatibility issues in various plugins:
- https://github.com/igniterealtime/openfire-bookmarks-plugin/issues/20
- https://github.com/igniterealtime/openfire-certificateManager-plugin/issues/19
- https://github.com/igniterealtime/openfire-monitoring-plugin/issues/362
In hindsight, the signature change was to much of a change. This commit 'undoes' that change, by:
- introducing `get/setHomePath(Path)` (instead of replacing `getHomeDirectory`)
- restoring `get/setHomeDirectory(String)` and marking it as being deprecated
This should restore backwards compatilibity, and give plugin implementors time to migrate from the old to the new API.
> OF-2647: Restore JiveGlobals.getHomeDirectory(String)

- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
In OF-2556, a workaround was provided to 'restore' namespace declarations on a stream element that had been parsed during the setup of the session.
This workaround injected a prefix-less 'stream' element. Unless the original stream defined a default namespace, this will not properly be parsed by an XML parser.
In this commit, the prefix 'stream' is used for the injected element (which is a de-facto standard in XMPP), and, for good measure, the namespace for that prefix is added, if it wasn't already recorded before.
> OF-2648: Restore restoration of stream namespaces

- xmppserver/src/main/java/org/jivesoftware/openfire/net/ServerStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
Openfire keeps track of namespace declarations on `stream` elements that it receives. These are intended to be used when parsing child elements, which are provided later / separately of their original stream root element. See OF-2556 for details.
These recorded namespaces should only be used for parsing data that's received in the same stream. Erroneously, Openfire also used them in an outbound stream definition. This introduced duplication of certain elements, causing remote servers to fail XML parsing.
> OF-2659: Do not use received namespaces on outbound stream

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyXMPPDecoder.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
The current code does not set the 'maxBufferSizeExceeded' flag to true until the parser.read function is called. This PR changes the boolean logic such that the NettyXMPPDecoder will release the byte buffer and return if the max buffer size is exceeded, preventing the error from being thrown
> OF-2652 - Fix max buffer size error

- pom.xml
- starter/pom.xml
- xmppserver/pom.xml
This updates the slf4j logging dependency from 1.7.36 to 2.0.9.
As no compatible log4j2 binding is available for the version of log4j2 that was used (2.17.1), this dependency has also been updated to 2.20.0.
> OF-2540: Update slf4j and log4j2

- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
This, combined with fixes in https://github.com/igniterealtime/Openfire/pull/2263, seems to help getting S2S outbound connections established.
I'm not sure why though, and if by doing this, something important is neglected.
I got the idea of doing this, as I observed that when an outgoing session was being created to another Openfire server, a thread seemed to linger for a _long_ time waiting on obtaining a lock. I suspect a deadlock-like scenario.
I feel that more investigation is needed here, but I wanted to share this finding.
> Prevent deadlock in Netty Outbound S2S

- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
Original commit to explicitly check the streamId is a new ID before creating a new session (fc79a39f) had the is-new-stream logic inverted.
> fix: OF-2655 - correct is new stream ID logic

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/NettyServerInitializer.java
XMPP mandates that UTF-8 must be supported. Netty's default StringDecoder uses the character set that's the default of the server. Force UTF-8 instead.
> OF-2677: Use UTF-8 character sets when Netty decodes strings

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java
SNI checks hostnames. Admin is usually addressed via tunnels and via localhost, which fails the SNI check.
This makes SNI configurable (for TLS and for hostname verification via the same setting) and defaults it to false.
This puts the same configuration to Admin and to HTTPBind - we might want to extend this later to separate it.
> OF-2675: Make SNI configurable (defaults to off)

- distribution/src/bin/openfire.sh
When debugging on an Amazon Linux EC2 instance we've found that the remote debug command failed as the asterisk character needed to be escaped.
@Fishbowler I see from your original commit message that you were working in Docker, I assume it already worked there so I'm not sure if this change breaks it for your Docker scenario.
> fix: escape asterisk in remote debug command args

- xmppserver/src/test/java/org/jivesoftware/Fixtures.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalOutgoingServerSessionTest.java
A race condition can cause LocalOutgoingServerSessionTest to occasionally fail. This seems to affect the Github based runners more than my local machine.
The issue is caused by a NullPointerException that is thrown immediately after a S2S connection has been set up. This causes the connection to close at the same time that the connection state is evaluated.
This commit prevents the NPE by adding a mock for the routing table to the test fixture.
> Stabilize LocalOutgoingServerSessionTest outcome

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java
- DirectTLS now waits for TLS to be negotiated before attempting to start a stream
> OF-2660: Fix DirectTLS for S2S 

- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java
Exception no longer thrown, logs now appropriate level for message and stack trace, and mention remote domain.
> fix: OF-2650 - improve strictCertificateValidation failure logging

- xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialbackErrorException.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialbackKeyInvalidException.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteReceivingServerDummy.java
Two commits, one that fixes the namespace that's used when doing Server Dialback, and another that prevents the namespace declaration to be sent on both the parent 'stream' element, as well as its child elements.
> OF-2690: Server Dialback namespace usage

- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
This modification prevents the org.jivesoftware.openfire.Connection#additionalNamespaces collection being modified upon (first) use. The change intends to reduce the chance of concurrent modification exceptions to occur.
> OF-2682: Prevent modification of shared collection

- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/webapp/server-session-details.jsp
- last activity will no longer show 1970  if no activity is detected - will instead show creation time.
- session details tables now flex - no more overflow off the page
> Session details page fixes

- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
Various caches used by SessionManager are expected to be configured as unlimited, never expire. However, they had no explicit configuration, therefor had the default size limitation and expiry. This leads to cache inconsistency issues as documented in OF-2665
For two out of three caches, it appears that the names of the caches have at some point been modified, without that same change having been applied to the cache configuration. The third cache is new, and never had cache configuration added.
This commit fixes that, be updating/adding cache configurion.
Special care needs to be taken with regards to a second set of cache configuration, that lives in the Hazelcast plugin. The names used in Openfire and there should be equal!
> OF-2665: Ensure correct cache config for SessionManager caches

- xmppserver/src/main/java/org/jivesoftware/openfire/LocalSessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
@AlexGidman added trace logging to diagnose OF-2665. With OF-2665 fixed, we no longer need this. As it can be quite verbose, I'd rather take it out, even if it's just logging on trace.
This reverts commit b5ed121675a9b0223954e84fc8b9485c60ac6fc3.
> Revert "OF-2665: Add trace logs for when caches are modified for incoming server sessions (#2293)"

- xmppserver/src/main/java/org/jivesoftware/openfire/net/ServerStanzaHandler.java
The connection to the authoritative server can be authenticated (I'm assuming that it uses laxer SASL EXTERNAL rules). Over that connection, dialback-namespaced data is sent. So, we'll need the namespace prefix to be defined on its stream.
> OF-2681: Add Server Dialback namespace even on authenticated connections

- xmppserver/src/main/webapp/js/behaviour.js
It should iterate over the `list` of rules instead of the non-iterable Behaviour object.
In several places `for..in` was used to iterate over the values of an array instead of `for..of`.
> Fixed behaviour.js

- xmppserver/src/main/java/org/jivesoftware/openfire/session/ConnectionSettings.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
This changes the default value for the server-to-server initialization timeout from 5 to 10 seconds, and the idle timeout from 6 to 30 minutes. This is more in line with behavior experienced on Ignite's own XMPP domain.
> Modify server-to-server connection timeouts

- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientStanzaHandler.java
- xmppserver/src/test/java/org/jivesoftware/openfire/websocket/WebSocketClientStanzaHandlerTest.java
This primarily works around an apparent bug in Smack: SMACK-935
Note that this _also_ fixes a bug where Openfire would send an incomplete XML snippet.
> OF-2703: Ensure websocket 'open' element is not expanded

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/MessageRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/PresenceRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/RoutingTable.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/cluster/RemotePacketExecution.java
- xmppserver/src/main/java/org/jivesoftware/openfire/component/InternalComponentManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQOfflineMessagesHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceSubscribeHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/interceptor/PacketCopier.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketPacketWriteHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/Roster.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/RosterManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/PresenceManagerImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
RFC 6121 section 8.5.3 defines how a server should process a stanza that is addressed to a full JID. When a matching resource is found, the specification does not distinghuis between an “available” resource and a “connected” resource. Instead, it refers to an “available resource or connected resource” (this is different for processing of stanzas to bare JIDs, in section 8.5.2).
Openfire’s implementation of routing stanzas addressed to a full JID of a resource for which a route exist should not evaluate the ‘availability’ of the route, as this contradicts the RFC, which doesn’t differentiate between ‘available’ and ‘connected’.
> OF-2705: Improve routing stanzas to matching full JID

- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketConnection.java
When closing a websocket connection, a `<close xmlns='urn:ietf:params:xml:ns:xmpp-framing'/>` should be sent prior to closing the connection.
> OF-2715: Websockets should send closing frame when disconnecting

- runIntegrationTests
Although the modular connections are experimental, lets experiment with enabling them.
It is particularly desirable to have Websocket support.
> CI: use _all_ Smack connection types

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
Fixes a behaviour we saw in `testDisconnectAfterConnect` in Smack's `ModularXmppClientToServerConnectionLowLevelIntegrationTest` where Openfire closed a connection before it could send a stream closure to the departing client.
> OF-2661: Ensure we send everything (flush) before actual channel closure

- plugins/pom.xml
- xmppserver/pom.xml
- xmppserver/src/assembly/taglib.xml
In this commit, a second artifact is produced from the xmppserver module. Apart from the prexisting 'jar' artifact, there now is a 'taglib' artifact.
This taglib artifact is a jar file (that needs to go into our maven repository), that holds the Admin Console taglibs, in a spec-compliant directory structure.
The plugin's parent pom-file is modified to be able to make use of this new artifact.
With this, compilation of a plugin that defins the plugin parent pom as its parent succeeds (although an unhealty amount of errors is logged). The resulting admin console pages appear functional, at least in Openfire 4.8.
> OF-2668 / OF-2723: Allow plugins to be compiled against Openfire 4.8

- .dependency-check-suppressions.xml
- build/ci/updater/pom.xml
- pom.xml
- xmppserver/pom.xml
OF-2725 updates `dependency-check-maven` to 8.4.2, then adds suppressions for known false positives
OF-2726 updates `dom4j` to 2.1.4
OF-2727 updates `mysql-connector-j` to 8.2.0
Notes:
* Remaining CVEs are all against `org.mortbay.jasper/apache-jsp@9.0.52` which is a dependency of Jetty 10. I've suppressed the obvious/easy ones, but suspect we're vulnerable to zero.
* There might be other out of date dependencies that weren't flagged. I've not looked.
> OF-2725: Update dependency-check, and deal with the results

- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
RFC6120 dictates that during S2S, the Receiving Entity _must_ set a stream ID to the stream header. This commit fails explicitly when that's the case. Prior to this, a NullPointerException was thrown.
It is likely that this commit fixes a symptom rather than the cause of an issue. It appears that the stream-without-ID is sent by Prosody, that's attempting to send a stream error. Openfire might fail to close a socket, after giving up setting up a connection (or something of that nature).
> OF-2692: Explictly check if S2S Receiving Entity sets StreamID

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java
As per Alex' suggestion: When closing the channel we switched to using `ctx.channel().close();` rather than calling `close` directly on the context: `ctx.close()` starts to flow through the `ChannelPipeline` from the point of the `ChannelHandlerContext` while `ctx.channel().close()` will start from the tail of the `ChannelPipeline` all the time.
> OF-2730: Change the way channels are closed

- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
This prevents very loud errors being logged.
> OF-2663: Ignore disco/info errors sent over S2S

- xmppserver/src/main/java/org/jivesoftware/openfire/roster/Roster.java
Fixes OF-1183 and OF-1224
This reverts commit a9c43db148902f3511f73a1235a252e5a49f4a56.
OF-317 seems to incorrectly state that the observed behavior is a bug. When a subscription request was processed (and rejected), it seems acceptable to have a roster item in both rosters (as long as they're of state 'None').
> Revert "OF-317 Subscribe with Response Unsubscribed Causes Roster Push to Responding Client"

- distribution/pom.xml
The Openfire distribution contains one plugin: the search plugin.
It currently ships with version 1.7.3, while the latest release is 1.7.4.
Openfire should ship with the latest release.
> OF-2732: Updated bundled 'search' plugin to 1.7.4

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_fr.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- i18n/src/main/resources/openfire_i18n_uk_UA.properties
- xmppserver/src/main/webapp/pubsub-node-summary.jsp
To be consistent with other admin console summary pages, the identifier of nodes on the PEP and Pubsub Node summary pages should be clickable.
This commit replaces the 'config' column with a link on the pre-existing node ID.
> OF-1389: Admin Console - PubSub Node ID should be clickable

- xmppserver/src/main/webapp/group-edit.jsp
- xmppserver/src/main/webapp/muc-room-edit-form.jsp
- xmppserver/src/main/webapp/user-create.jsp
- xmppserver/src/main/webapp/user-password.jsp
- xmppserver/src/main/webapp/user-search.jsp
Auto-complete is helpful when logging into the admin console, but it is not helpful when creating new users or other forms where usernames and/or passwords are to be provided to create something new (like a MUC room).
> OF-1382: Admin console should not autocomplete username/password in all forms

- xmppserver/src/main/webapp/pubsub-node-edit.jsp
'Max number of items' is now only configurable when 'persist items' is enabled.
> OF-1399: PubSub Admin Console - Max number of items to persist config

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/MessageRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/PresenceRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/interceptor/PacketRejectedException.java
This change allows a PacketError to be added to the exception that is used to reject (incoming) stanzas in PacketInterceptors. This new field is used in the error that's sent back to the sender, allowing for more detailed error reporting.
> OF-2699: Define optional PacketError on PacketRejectedException

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQSessionEstablishmentHandler.java
This builds on a previous attempt to add support for IQ handling with regards to RFC 6121 Section 8.5.1 (No Such User), which was added in 15e6c5619d6ade7c40de95a1a7a158b1a9358ff0 and got partially reverted in 637cc81733092275c2726b43ebe603c0cbd438fe
The original fix got reverted, because pre-existing code (in IQHandlers of plugins) depends on non-compliant behavior.
With this new commit, I'm re-introducing the fix, but am adding a mechanism for individual plugins to opt out.
> OF-880: IQHandlers must comply with RFC 6121 Section 8.5.1 by default

- distribution/src/bin/openfire.sh
Old default no longer exists.
Modern macOS has a utility for this.
> OF-2740: Fix fallback JAVA_HOME on macOS

- xmppserver/src/main/java/org/jivesoftware/openfire/csi/CsiManager.java
- xmppserver/src/test/java/org/jivesoftware/openfire/csi/CsiManagerTest.java
If CSI is active, a call inviation should not be queued, as the user needs to respond to it directly.
> OF-2750: Jingle call initiations should not be queued by CSI

- xmppserver/src/main/java/org/jivesoftware/openfire/Connection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/multiplex/ClientSessionConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyXMPPDecoder.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketConnection.java
Prior to this commit, a session was (stream management) resumable whenever it got closed.
When a session is closed 'cleanly' (eg, with an exchange of `</stream>`), then a session should never be resumed.
This commit attempts to reverse the strategy. It is implied that a session is never resumable, unless it is closed unexpectedly (for example, as caused by a network disconnect).
> OF-2752: Sessions should be resumable only if closed due to 'unclean' disconnect

- xmppserver/src/main/java/org/jivesoftware/openfire/Connection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/multiplex/ClientSessionConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyIdleStateKeepAliveHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyXMPPDecoder.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketConnection.java
In the previous commit for this issue, it was assumed that the state of a connection was always known 'good' or 'terminated'. In reality, there are lenghty periods in which Openfire cannot be sure of a connection is terminated, or simply unresponsive.
To avoid clients being disconnected by Openfire without their knowledge, Openfire should always try to send an end-of-stream indication. Without this, clients might assume for indefinite amounts of time that they're connected, while they are not.
> OF-2752: Refactor solution

- runIntegrationTests
Use the latest release of Smack when running integration tests.
> CI: bump Smack from 4.4.6 to 4.4.7

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java
This fixes a bug in pub/sub notification handling that assumed that all subscribers were local users.
> OF-2757: Allow pub/sub notifications to be sent to federated full JIDs

- xmppserver/src/main/webapp/setup/index.jsp
Previously, the method assumed that the format of the JRE version is: `major.minor.build`. 
However, for `openjdk 21`, the value of `System.getProperty("java.version")` is `21`. 
This caused the previous method of determination to fail, resulting in the following error message:
> Error: Can not proceed with Openfire Setup.
Your current installation fails to meet minimum server requirements - please see the checklist below: ✗ At least JRE 11
✓ Servlet 2.3 Support
✓ JSP 1.2 Support
✓ Openfire Classes
✓ Openfire Home found (/usr/local/openfire)
Therefore, the method was modified to extract the significant digits using the regular expression `^\d+(\.\d+)?` for version comparison. 
The modified method for determination was tested in the following environments:
| **JRE Version** | 21 | 17.0.1 | …
> OF-2756 Modify the method for determining JRE version

- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
Refer OF-2647, since code changed from:
```
File file = new File(pluginDirectory, parts[1] + File.separator + "web" + contextPath);
```
to:
```
Path file = pluginDirectory.resolve(parts[1]).resolve("web").resolve(contextPath);
``` 
If `contextPath` start with `/`, the variable `file` will change to `contextPath` after `.resolve(contextPath)`, that is not correct. If system property "plugins.servlet.allowLocalFileReading" not setting, will get http status code 403, restAPI document page cannot open `/plugins/restapi/docs/index.html`, and monitoring resource `/plugins/monitoring/images/*.gif` cannot download.
> fix: View plugin pages or resource reports http status code 403

- xmppserver/src/main/webapp/session-details.jsp
The first bit of the data shown in the table is only available on the local cluster node. That is being excluded from the output, but by mistake, the table header was excluded too.
> OF-2736: Admin console: missing header in session details

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
When an IQ Service gets send an IQ result, it generates a null response, which it tries to route. That causes NullPointerExceptions to be logged.
With this commit, such null responses are silently dropped.
> OF-2761: Prevent NPE when MUC service gets unexpected IQ result

- Makefile
- build/docker/buildWithDocker.sh
- documentation/ide-vscode-setup.html
- documentation/plugin-dev-guide.html
- documentation/source-build.html
- documentation/working-with-openfire.html
- runAioxmppIntegrationTests
- runIntegrationTests
* Fixes docs
* Fixes makefile
* Fixes integration test scripts
* Fixes dockerised build script (this one's a tiny bit more extensive - it swaps the maven image for a temurin one)
> OF-2765: Use mvnw everywhere

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/NettyServerInitializer.java
Whenever data is received, the 'idle' state of a Netty connection is to be reset. Prior to this commit, this occured conditionally on a particular handler being set (which was set only for s2s connections). With this change, the idle flag is always reset upon inbound data.
> OF-2774: Fix reset of 'idle' state of Netty connections

- xmppserver/src/main/java/org/jivesoftware/admin/servlet/BlogPostServlet.java
- xmppserver/src/test/java/org/jivesoftware/admin/servlet/BlogPostServletTest.java
Prior to this change, the dates from Ignite's RSS feed were parsed in the system locale. When that is not English, the RSS feed would fail to be visible as a result of a parsing error.
> OF-2775: Ensure that RSS dates are parsed in English locale

- .github/workflows/continuous-integration-workflow.yml
setup-java now includes caches, so the separate cache steps are redundant
> Remove unnecessary caching in Github Actions

- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/SerializingCache.java
- xmppserver/src/test/java/org/jivesoftware/util/cache/CacheFactoryTest.java
The newly created cache gets wrapped (so that its implementation can be changed on the fly, when clustering starts or stops). The previous implementation caused a ClassCastException that is herein prevented.
> OF-2781 & OF-2782: Bugfixes for SerializingCache

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubModule.java
Openfire already implements the functionality described in https://xmpp.org/extensions/xep-0060.html#publisher-delete but failed to announce this properly.
> OF-2791: Announce support for deletion of pubsub items

- xmppserver/src/main/java/org/jivesoftware/openfire/forward/Forwarded.java
- xmppserver/src/test/java/org/jivesoftware/openfire/forward/ForwardedTest.java
Code should first evaluate disqualifiers, before qualifiers. Added a unit test based on a real-world example that exposes the problem with the original code.
> OF-2778: Fix for Carbons in context of MUC

- xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheWrapper.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CaffeineCache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultCache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/SerializingCache.java
- xmppserver/src/main/webapp/system-cache.jsp
When clustering the 'Cache Summary' page in the admin console should provide a correct overview of the state of the caches. With the commits in this PR, this is improved (but not _fixed_ - for that, a change in the Hazelcast plugin is needed).
Please refer to https://igniterealtime.atlassian.net/browse/OF-2792 for details on the problem.
The commit message of the second commit describes the most relevant changes.
This is a screenshot of the admin console, with the changes in this PR, but without an updated Hazelcast plugin:
> OF-2792: Admin Console Cache Summary page improvements

- xmppserver/src/main/java/org/jivesoftware/openfire/admin/AdminManager.java
When a user is being deleted, that user should no longer be marked as an admin.
> OF-2758: Remove admin flag when deleting user

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionManagerImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/NettyConnectionAcceptor.java
Fixes for two related issues. As with MINA, Netty _should_ use a distinct thread pool for processing data of a particular connection type (OF-2788). The threads that are used should be aptly named (OF-2651)
> OF-2788 & OF-2651: Netty threadpool usage

- xmppserver/src/main/java/org/jivesoftware/database/DbConnectionManager.java
All other methods that close database resources perform a null-check. This commit applies the same check when closing a transactional connection.
This prevents (additional) NullPointerExceptions from being logged when a transactional connection that could not be obtained (and thus is null) is 'closed'.
> OF-2800: Guard against surplus Exceptions when closing transactional connection

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/SyncLocalOccupantsAndSendJoinPresenceTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/OccupantManager.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/ConsistencyChecks.java
- xmppserver/src/main/webapp/muc-room-cache.jsp
- xmppserver/src/test/java/org/jivesoftware/openfire/muc/spi/OccupantManagerTest.java
When clustering, every Openfire cluster node tries to maintain a minimal set of data describing rooms and occupants. The primary reason to do this is to be able to reconstruct data in case of a cluster node unexpectedly dropping out of the cluster. This data is (mostly) managed by the OccupantManager class.
Prior to this commit, the OccupantManager associated every occupant with one or more cluster nodes (by cluster node ID). This commit changes that, in the following way:
- Users of the local/non-federated XMPP domain are associated with exactly one cluster node: the one that they're 'physically' connected to (eg: where their TCP connection terminates).
- Users of non-local/federated XMPP domains are no longer associated with any cluster node in particular.
The prior association of …
> OF-2799: MUC occupant management for federated users in a cluster

- build/ci/updater/pom.xml
- xmppserver/pom.xml
This addresses CVE-2024-1597. Openfire does not seem to be affected by this, but as the reported severity is 10/10, static analyzers will undoubtedly cause a sense of urgency.
@akrherz This is updating to the latest/greatest. Is there a good reason for us to stick to the 4.6 branch of this driver?
> OF-2802: Upgrade Postgresql JDBC driver from 42.6.0 to 42.7.2

- xmppserver/src/main/java/org/jivesoftware/openfire/group/DefaultGroupPropertyMap.java
When a GroupProperty is added, modified or deleted, an event listening mechanism is activated. This, among other things, is used to clean up cache content and push changes to rosters.
This commit fixes a problem with the 'modified' handler. It caused the wrong event to be emitted ('deleted', rather than 'modified').
> OF-2807: Fix event handling for Group Property changes

- xmppserver/src/main/java/org/jivesoftware/openfire/group/Group.java
- xmppserver/src/main/webapp/group-edit.jsp
When a group is to be shared with other groups, this is stored in the database as a group property of name `sharedRoster.showInRoster` having a value of `onlyGroup`. The group property value for `sharedRoster.groupList` controls to what groups this group is shared. It either is a comma-separated list (denoting group names), or it's empty. An empty value signals that the group is shared only with members of the same group.
This commit corrects how these values are managed in the database.
This change largely fixes OF-2777, although one issue remains (or is possibly introduced by this change): When _disabling_ roster sharing for a group that was previously shared with other groups, then contacts (roster items) are NOT removed from the rosters of people that no longer have the shared group.
> OF-2777: Allow groups to be shared with other groups

- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
Unlike the old MINA connections, Netty connections issue a 'formal close' when closed. This prevents them from being resumable.
When a connection is 'resumed', the resumed connection should itself be resumable again. This allows for subsequent network interruptions to be recoverable.
> OF-2810: Ensure that resumed streams are themselves resumable

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java
This prevents a new user by the same name to claim the affiliation.
I've not yet found the time to test these changes. I'd appreciate someone stepping up to help out with that.
I am somewhat worried about the performance of this solution in a big cluster full of chat rooms. Suggestions to improve on this are welcome.
> OF-2795 / OF-2166: Remove MUC affiliation of a user that is being deleted.

- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientConnectionHandler.java
When the max idle time is configured to be negative, then do not schedule the check to see if the connection is still active.
> OF-2809: Guard against negative max idle time for websockets

- .github/workflows/continuous-integration-workflow.yml
* Use mvn install to get Openfire into the mvn repo
* Stash the repo at the end of the Java 11 build
* Restore the repo before building the Database Updater
> OF-2813: Stash the mvn repo after build, and re-use in later jobs

- .github/workflows/continuous-integration-workflow.yml
* Have the database test jobs depend on the check_branch job that determines if this run will result in a publish
* Have the database tests run if either the relevant files have changed or the run will result in a publish (previously it was just the first check)
* Have the publish job await the database tests as well as the other tests
The publish now depends on jobs that might not run, but that seems fine, since the database tests will always run if the publish job would run (and at other times too)
> Always run database tests if we're gonna publish

- pom.xml
Changes:
- https://netty.io/news/2023/11/09/4-1-101-Final.html
- https://netty.io/news/2023/12/13/4-1-103-Final.html
- https://netty.io/news/2023/12/15/4-1-104-Final.html
- https://netty.io/news/2024/01/16/4-1-105-Final.html
- https://netty.io/news/2024/01/19/4-1-106-Final.html
- https://netty.io/news/2024/02/13/4-1-107-Final.html
- https://netty.io/news/2024/03/21/4-1-108-Final.html
(Yes, that's correct - there is no 4.1.102)
Nothing stood out as scary. All appear to be bugfixes and performance tweaks.
> OF-2819: Update Netty from 4.1.100 to 4.1.108

- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/OpenfireWebSocketServlet.java
This corrects a mistake where a configuration of having a _maximum_ buffer size was turned into having a _fixed_ buffer size.
Having 5MB buffers is bad, as with a limited amount of messages, a _lot_ of memory is being consumed.
This commit removes the hard-coded buffer size configuration, while retaining the maximum message length directive.
I've tested that, using a websocket client connection:
- a message of 128k characters can be sent using the default configuration;
- a message of 128k characters can not be sent when Openfire is reconfigured to use 4k for the `xmpp.parser.buffer.size` property
> OF-2818: Netty should not use 5MB buffers

- xmppserver/src/main/java/org/jivesoftware/openfire/RoutingTable.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteIncomingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/Session.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
The distinct commits in this PR each intend to address a separate issue, where the first three commits are preparing the code for easier application of the fourth commit.
The over-arching goal of all commits is to make the implementation of RoutingTable less error prone (in context of client sessions/routes). it does so by:
- adding strictness with regards to allowed `null` and bare vs. full JID usage
- simplifying the code (doing away with an optimization that I suspect plays a role in the cause of observed data inconsistency)
- replacing per-cache lock usage to usage of one lock, to guard the manipulation of three related caches. This intends to remove a potential synchronization issue.
> OF-2824: Addressing data consistency in caches of routing table 

- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoItemsHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQHandler.java
Service Discovery's section 8 describes some security considerations that Openfire must implement.
These security considerations partially contradict what's defined in RFC-6121 8.5.1. To allow for that implementation to be applied differently, this commit refactors the code to allow for an override of the original implementation of the 'no-such-user' handling.
> OF-2825: Implement XEP-0030's security considerations

- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapVCardProvider.java
Allows avatars to be stored in the local database for MUC rooms, when AD/LDAP integration is enabled.
> OF-2832: LDAP MUC avatar

- xmppserver/src/main/java/org/jivesoftware/openfire/user/User.java
Since OF-2768, various 'date'-based properties of the User class are more likely to be null (especially in context of LDAP/AD).
In this commit, a serialization issue is fixed that is triggered by these null-values.
> OF-2833: Fix serialization of User when date properties are null

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyXMPPDecoder.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
- xmppserver/src/test/java/org/jivesoftware/openfire/nio/XMLLightweightParserTest.java
Prioer to this change, parsing errors occurred when multi-byte characters where provided to the parser byte-by-byte (or in byte arrays where a multi-byte character was split over more than one byte array).
This commit re-introduces the fix for this problem that was created under OF-458. It uses a CharsetDecoder that will only read 'enough' bytes from an array, leaving bytes that form an incomplete character in the byte array (to be processed in the next iteration, when hopefully more data was added).
The original fix is refactored a little to account for the different API that is provided by Netty (as compared to the old MINA based code), and to facilitate unit testing (of which a couple are added).
> OF-2814: Ensure that multi-byte characters in the XMPP data are parsed properly

- xmppserver/src/main/java/org/jivesoftware/util/XMPPDateTimeFormat.java
- xmppserver/src/test/java/org/jivesoftware/util/XMPPDateTimeFormatTest.java
Parsing should return null values (rather than throw an Exception) when null or empty values input values are used (to be more fault-tolerant). A parsing exception's message should include the offending value (to help diagnostics).
> OF-2840: Minor improvements to XMPPDateTimeFormat parsing

- pom.xml
The OWASP dep-scan tool (https://github.com/owasp-dep-scan/dep-scan) has identified various CVEs related to the version of the BouncyCastle dependency that we're currently using. This commit updates the library to resolve that issue.
> OF-2834: Bump BouncyCastle from 1.76 to 1.78.1

- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
The previous fix for OF-2825 erroneously prevented a user to query for its own disco#info.
> OF-2825: Allow self to query for disco#info

- xmppserver/src/main/java/org/jivesoftware/openfire/disco/DiscoInfoProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
Instead of applying the security considerations of section 8, XEP-0030 globally, they now are applied to the individual discovery data providers. This prevents them to be applied to providers where they do not apply (eg: MUC, that doesn't apply presence subscription based authorization at all).
> OF-2825: Moved implementation of Service Discovery security considerations to individual providers

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
Prior to this change, this element was present only when one of the optional attributes was provided.
> OF-2848: Ensure `<destroy/>` element in presence unavailable when MUC is destroyed

- .github/workflows/continuous-integration-workflow.yml
This PR:
1. Updates the aioxmpp git repo to its present home
2. Enables all tests that pass locally for me on Openfire 4.8.3
A before and after
```diff
- 46 passed, 4575 skipped, 4 deselected, 133 warnings in 7.01s
+ 4599 passed, 23 skipped, 3 deselected, 188 warnings in 31.61s
```
I have created Jira issues for the three tests currently being skipped and documented those within the CI config.  Watch how many of these tests now fail here :)
PS.  I have brought `aioxmpp` into [conda-forge](https://conda-forge.org/).  So our CI could be updated to make more speedy usage of it, but the difference is likely negligible
> Update aioxmpp testing

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
When sending a private message to a user that's not an occupant of the room, XEP-0045 section 7.5 defines that a different error condition is to be used than the one that Openfire has been using. This commit corrects the error condition.
> OF-2858: Fix error condition for MUC PM

- distribution/pom.xml
- distribution/src/assembly/basic-distribution.xml
See individual commit messages and/or JIRA issues for details.
These changes should all be benign, but remove some warnings that are generated when Maven is building the project.
> Fix Maven warnings for distribution module

- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
- xmppserver/src/test/java/org/jivesoftware/openfire/container/PluginServletTest.java
Two commits:
- the first adds unit tests, which necessitates a bit of refactoring of the code under test.
- the second commit intends to fix the issue.
> OF-2830 plugin servlet mapping

- xmppserver/src/main/java/org/jivesoftware/admin/LdapUserTester.java
- xmppserver/src/main/java/org/jivesoftware/openfire/entitycaps/EntityCapabilitiesManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapVCardProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCvCardHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SASLAuthentication.java
- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/vcard/PhotoResizer.java
- xmppserver/src/main/java/org/jivesoftware/util/AesEncryptor.java
- xmppserver/src/main/java/org/jivesoftware/util/Base64.java
- xmppserver/src/main/java/org/jivesoftware/util/StringUtils.java
- xmppserver/src/main/webapp/login.jsp
- xmppserver/src/main/webapp/system-clustering.jsp
- xmppserver/src/test/java/org/jivesoftware/openfire/keystore/KeystoreTestUtils.java
- xmppserver/src/test/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServerTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java
Marked `org.jivesoftware.util.Base64` as deprecated, replaced all usage with `java.util.Base64`.
This replaces customer code with code provided by Java itself, reducing the maintenance load.
> OF-2864: Deprecate org.jivesoftware.util.Base64

- xmppserver/src/main/java/org/jivesoftware/openfire/Connection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/RoutingTable.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionPacketRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/commands/SessionData.java
- xmppserver/src/main/java/org/jivesoftware/openfire/component/ExternalComponentManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketReader.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketReadingMode.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSessionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/Session.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketConnection.java
- xmppserver/src/main/java/org/jivesoftware/util/JiveConstants.java
- xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java
- xmppserver/src/main/java/org/jivesoftware/util/TaskEngine.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
Code that was marked for removal in version 4.9.0 should be removed.
Note that we shouldn’t remove code when the mark was applied in versions 4.8.1 or later. In those cases, lets bump up the removal to the next minor version (4.10.0). This allows developers to have one ‘full’ release cycle to be aware of deprecation, and adjust their code accordingly.
> Remove code marked for deprecation in 4.9.0 or later

- xmppserver/src/main/webapp/setup/index.jsp
By removing deprecated code, the Openfire setup failed. Specifically, a validation that checks for some runtime configuration failed, because it no longer could identify the 'home' directory. As this implementation used Java reflection, it went below the radar until now.
> OF-2867: Openfire setup should not use removed code

- xmppserver/src/main/webapp/server-session-details.jsp
This fixes a bug that occurs on the server session details page, as it was using Openfire API that is removed as part of OF-2867.
> OF-2867: Admin console should not use removed code

- xmppserver/src/main/webapp/server-session-details.jsp
Fixing reference to `usingServerDialback` and `usingSaslExternal` (that are no true 'properties', and thus cannot be referenced like ones).
This fixes an earlier fix for OF-2867
> OF-2867: Admin console server-session-details fix

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
- xmppserver/src/test/java/org/jivesoftware/openfire/nio/XMLLightweightParserTest.java
The previous code failed to properly update the read index of the ByteBuffer that is being read, in cases where the ByteBuffer that is parsed had an initial read index higher than 0.
Through manual testing, I've observed this to fix an issue where client connections that send Cyrillic characters get disconnected with a "Stopped parsing never ending stanza" exception.
> OF-2872: Fix XML parsing when previous buffer couldn't be fully parsed

- build/debian/copyright
- build/debian/openfire.conffiles
- build/debian/postinst
As a side note I recommend to install DEB and RMP plugins for IntelliJ and they can highlight some problems
> OF-2873 debian package

- plugins/pom.xml
This will allow to inherit the configuration to plugins.
E.g. target Java version
> plugins parent pom.xml: move maven compiler plugin configuration to <pluginManagement>

- xmppserver/src/main/java/org/jivesoftware/util/TaskEngine.java
- xmppserver/src/test/java/org/jivesoftware/util/TaskEngineTest.java
This adds a method to TaskEngine that allows a job's result to be collected through a Future instance.
> OF-2885: TaskEngine jobs with Future

- xmppserver/src/main/java/org/jivesoftware/openfire/group/Group.java
When a user of a group is made an 'admin' of the group, its removal from the 'members' group should not cause it to be removed from the group completely.
> OF-2884: Fix group user removal when making it admin

- distribution/src/bin/openfire.sh
openfire.sh can be invoked with a number of arguments (eg `-demoboot`, `-debug`). Prior to this commit, unrecognized arguments were ignored.
With this commit, unrecognized argumetns are passed through to the java command that starts Openfire. This allows anyone to add arguments, like system properties, by doing something like `./bin/openfire.sh -Dfoo=bar`
> Passthrough unrecognized openfire.sh arguments

- distribution/src/bin/openfire.sh
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/DNSUtil.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/HappyEyeballsResolver.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/IndexedResolvedServiceAddress.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/ResolvedServiceAddress.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketUtil.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SrvRecord.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
- xmppserver/src/main/java/org/jivesoftware/util/ScheduledExecutorCompletionService.java
- xmppserver/src/main/webapp/dns-check-resulttable.jspf
- xmppserver/src/main/webapp/dns-check.jsp
- xmppserver/src/main/webapp/index.jsp
- xmppserver/src/test/java/org/jivesoftware/openfire/net/DNSUtilTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/net/HappyEyeballsResolverTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/net/SrvRecordTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalIncomingServerSessionTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalOutgoingServerSessionTest.java
The commits in this PR implement (much of the) Happy Eyeballs algorithm, as defined in the protoXEP in https://xmpp.org/extensions/inbox/xep-happy-eyeballs.html
The commits in this PR isolate distinct changes, which preferably are not to be squashed together.
This commit also explicitly sets `-Djava.net.preferIPv6Addresses=system` which causes the Java virtual machine to follow the system's preference with regards to IPv6 vs IPv4 usage (as opposed to the default, which is 'IPv4', at least in Java 11. Is there a more appropriate way of going about this?
Some aspects that are excluded from this implementation:
- Separate resolution of A and AAAA records (the Java API does that in one go - it seems silly to bypass that only to adhere to the specifications)
- Much of the 'sorting' as defined …
> OF-2786: Happy Eyeballs (for outbound S2S connections)

- documentation/client-minimal-working-example-mellium.html
- documentation/client-minimal-working-example-moxxmpp.html
- documentation/client-minimal-working-example-smack.html
- documentation/client-minimal-working-example-stanzajs.html
- documentation/client-minimal-working-example-stropejs.html
- documentation/client-minimal-working-example-twistedwords.html
- documentation/client-minimal-working-example-xmppdotnet.html
- documentation/demoboot-guide.html
- documentation/index.html
The website needs an update after this gets released (to update the Openfire documentation page to point to the new guide introduced by this PR).
> Add demoboot documentation

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/LocalSessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQBindHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQRegisterHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/ConnectionSettings.java
A collection of pre-authenticated sessions was maintained incorrectly (using a type-unsafe key that was both used as a stream-ID and a JID), which caused every session that was ever created to remain a part of that collection, until the server got restarted. This introduces a memory leak (and possibly functional issues, although those have never been reported).
The second commit resolves the problem. It hides access to the collection to enforce proper maintenance. A more type-safe key is used, which should help prevent future issues like these.
The changes in the second commit affect the API. I've opted to not include backwards-compatibility (with deprecation), as I believe the per-existing API to be simply broken. Any usage of that API should be revisited, which is enforced by removing …
> OF-2896 & OF-2897: Fix memory leak when dealing with pre-authenticated Sessions

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java
- xmppserver/src/main/webapp/plugin-admin.jsp
Plugins like the REST API Plugin require wildcard routes (because they do HTTP calls that include username or JID in the path). Some of these require the new(-ish) adminConsole.access.allow-wildcards-in-excludes property to be set so that they can either be open, or so that they can apply their own authentication outside that of the normal Admin Console access.
Whilst there have been attempts to update documentation, not everyone reads it. This even trips up the folk most familiar with it (meaning: me, almost every time).
This adds a warning in the Plugin Admin page that displays when a loaded plugin has a wildcard exception declared, but the System Property is not set.
https://igniterealtime.atlassian.net/browse/OF-2893
> OF-2893: Warn administrator when a wildcard pattern is loaded

- xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
because .connect manager session(LocalConnectionMultiplexerSession) have't SASLMechanisms. we change org.jivesoftware.openfire.net.StanzaHandler.java tlsNegotiated method when getSASLMechanisms() method return null. not add to features:
> OF-2899: Connect manager connect fail when upgrade openfire 4.9.0.

- documentation/one-time-access-token-guide.html
Replace 'ipaddress' with 'localhost' to avoid confusion.
Adds a note on Admin Console binding by default only on the loopback interfaces of a server.
> Documentation: Admin Console Recovery to use localhost

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheUtil.java
An earlier change prevented the SessionDestroyed event from being sent to event listeners, which is fixed in this commit.
I've not tested this change.
> OF-2898: Restore SessionDestroyed event

- xmppserver/src/test/java/org/jivesoftware/openfire/keystore/KeystoreTestUtils.java
- xmppserver/src/test/java/org/jivesoftware/util/CertificateManagerTest.java
Some stricter OS won't provide the 'lower' crypto configurations that our unit tests use. This makes tests fail.
> OF-2900: Update Increase crypto config used by tests

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java
Introduces a new property that defines how long warnings are suppressed after they've been logged.
> OF-2901: Reduce verbosity of LDAP unencrypted connection warning

- xmppserver/src/main/java/org/jivesoftware/util/cert/SANCertificateIdentityMapping.java
- xmppserver/src/test/java/org/jivesoftware/util/CertificateManagerTest.java
OtherName values are tagged, which should be taken into account by the parser.
Unit tests that generate a certificate should include an EXPLIT tagged OtherName.
After two days of ... pain ... I've resorted to converting the BouncyCastle-generated certificate to PEM and back again, which for some reason that's beyond me appears to be required to make the parsing be successfull on both Java 17 and 21.
Adds additional unit test that uses a certificate generated by OpenSSL.
Many thanks to @dwd for invaluable help on this.
> OF-2904: Fix parsing issue of OtherName

- xmppserver/src/main/webapp/setup/index.jsp
Fixes a copy/paste error that prevented the security config file from being parsed properly.
Fixes an error where a non-existing variable is checked, thus never passing the check.
This is an untested fix for the problem that is apparent on https://discourse.igniterealtime.org/t/reinstalled-openfire-but-now-get-an-error-that-it-doesnt-meet-server-requirements/94891/1
> OF-2906: Fix setup page that checks config files

- build/rpm/openfire.spec
From testing, this allowed a RPM built on Rocky Linux 9 to install on the older Amazon Linux.
> OF-2907 Use older gz compression for RPM installer

- documentation/plugin-dev-guide.html
- documentation/plugins-affected-by-jetty12-upgrade.html
- plugins/pom.xml
- pom.xml
- xmppserver/pom.xml
- xmppserver/src/main/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/TempFileToucherTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/OpenfireWebSocketServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientConnectionHandler.java
Upgrading to Jetty 12.0.14 using the Java EE 8 platform.
Additional notes on previous commits:
- AdminConsolePlugin.java: Resource.newResource method is no longer available. Utilising ResourceFactory to construct new resource as suggested by Joakim.
> Jetty 12.0.14 ee8 upgrade

- build/ci/updater/pom.xml
- xmppserver/pom.xml
Atlassian's Maven repository serves us a dependency (`com.github.jgonian:commons-ip-math:1.32`) that appears to be different from the dependency served under the same Maven coordinates by Maven-Central. Atlassian's one makes Openfire fail at runtime.
Atlassian has announced that they'll stop serving third-party artifacts in early 2025.
This commit removes Atlassian's Maven repository from Openfire's Maven configuration. There was one artifact used by Openfire in Atlassian's repository that couldn't be obtained elsewhere (`com.cenqua.shaj:shaj:0.5`). This has now been added to Ignite's own Maven repository.
> OF-2910: No longer use Atlassian's Maven repository

- build/ci/updater/pom.xml
- plugins/pom.xml
- xmppserver/pom.xml
In this version of Openfire, Jetty is updated from 10 to 12 (using EE8). When a plugin compiles its JSPs against this version of Openfire, it should use the JSP-compiler of that Jetty version (the Maven artifacts of the compiler have changed).
> OF-2717: Plugins should use JSP compiler from new Jetty

- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketUtil.java
When cancelling a DNS resolution (because a valid resolution was completed elsewhere), log this as something else than a problem.
> OF-2729 / OF-2785: Reduce log level of to-be-expected exception

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/webapp/server-session-details.jsp
- xmppserver/src/main/webapp/server-session-row.jspf
- xmppserver/src/main/webapp/server-session-summary.jsp
Adding a 'family type' in the S2S session overview, that signals if a connection to a remote domain is using IPv4 or IPv6 (or both).
Layout of the table is done better by the browser than our guestimates based on width.
> OF-2729: Ipv6-related admin console tweaks

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
When the XML LightweightParser encounters invalid data, it sets itself in an invalid state. It doesn't expect to be called again.
If it is called again, a confusing null pointer exception is thrown. In this commit, that has been replaced by a more explicit exception.
> OF-2911: Catch NPE in Parser that is in an invalid state

- xmppserver/src/main/webapp/index.jsp
From my reading if
```java
dnsIssue = dnsSrvRecords.stream().anyMatch(r -> hostname.equalsIgnoreCase(r.getHostname()));
```
evaluates as true, the next section is skipped, but the flag should be inverted prior to returning
> OF-2912 Fix dnsIssue flag on admin console

- xmppserver/src/main/webapp/server-db.jsp
Prior to this change:
After this change:
> OF-2913: Admin Console database page: prevent horizontal scrollbar

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyXMPPDecoder.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
Moves most verbose (and likely confusing to most users) messages related to S2S / TLS failures from WARN to DEBUG level of logging (effectively hiding them). The messages are replaced by a more human-descriptive message informing the user what's going on.
> OF-2914: Reduce verbosity of logged messages when S2S fails.

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java
When TLS fails in a server-to-server connection, this frequently is followed up with another exception, mentioning that a `^W` character couldn't be parsed as valid XMPP.
This End-of-Transmission character is likely sent by the peer, as the end of the (failed) TLS handshake. Openfire should let the TLS handler process that character. This prevents the XMPP handler from having to process it.
> OF-2919: Prevent exception after S2S TLS fails

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
To prevent a stream management issue described in OF-2808, two fixes were applied.
One of them, invoking close listeners synchronously, is suspected to have undesirable side-effects. This commit removes that fix, which is expected to be redundant anyway.
> Remove redundant 'sync' when closing Netty connection

- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
Historically, disabling the Stream Management functionality has been a work-around for various issues.
To be able to work around a deadlock issue as described in OF-2921, this commit prevents a Stream Management-related mutex to be acquired when the Stream Management feature is disabled.
> OF-2921: Do not acquire mutex on unused StreamManager

- xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceSubscribeHandler.java
When a contact is a contact by virtue of being in a shared group, the presence subscription between the roster owner and this contact is deemed to be static.
Presence subscriptions sent by the client of either party should not affect this status.
I've not tested this change at all. I'm not at all sure if it is complete (does it cover all applicable cases? does it also process messages sent by both the 'roster owner' as well as the contact itself)? I also worry about potential side-effects.
I'm creating this PR mostly as a means of getting started. Hopefully someone can pitch in and help test, and possibly improve this change.
> OF-2397: Do not process subscription requests for shared contacts

- xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java
When items on a pubsub leaf node are processed, ensure that the access model of the node itself (and not just its collection) are taken into account.
> OF-2631: Enforce pubsub node access model

- .dockerignore
- .github/workflows/continuous-integration-workflow.yml
- Dockerfile
- build/docker/entrypoint.sh
- pom.xml
This changes the Dockerfile quite radically, so that Openfire is built within Docker rather than outside of it. This should simplify building the image, and also make the results more repeatable.
In order to maximize the use of the cache while keeping the image size under control, this uses three stages:
* The first stage locates and extracts all the POM files and any JAR files. This stage will be re-run on any change, but it short.
* The second stage takes the output of the first stage and gathers dependencies. These will be cached, unless the output of the first stage (ie, the dependency information) changes. Then it copies in the full source, and builds it.
* Finally, the runtime container is setup much as it was before, except that the runtime files are copied from the build stage …
> Improvements to Docker file

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_cs_CZ.properties
- i18n/src/main/resources/openfire_i18n_de.properties
- i18n/src/main/resources/openfire_i18n_es.properties
- i18n/src/main/resources/openfire_i18n_fr.properties
- i18n/src/main/resources/openfire_i18n_he.properties
- i18n/src/main/resources/openfire_i18n_ja_JP.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- i18n/src/main/resources/openfire_i18n_pl_PL.properties
- i18n/src/main/resources/openfire_i18n_pt_BR.properties
- i18n/src/main/resources/openfire_i18n_pt_PT.properties
- i18n/src/main/resources/openfire_i18n_ru_RU.properties
- i18n/src/main/resources/openfire_i18n_sk.properties
- i18n/src/main/resources/openfire_i18n_uk_UA.properties
- i18n/src/main/resources/openfire_i18n_zh_CN.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/update/AvailablePlugin.java
- xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java
- xmppserver/src/main/webapp/available-plugins.jsp
- xmppserver/src/main/webapp/plugin-admin.jsp
The Plugins and Available plugins pages have two icons for documentation (README) and changelog.
The icons are very small and placed together that makes it difficult to understand them.
The icons are only 16px and the only way to understand is to put a cursor over them to see a title. This wouldn't be possible to to from a mobile at all (minor issue).
As a solution we can switch to a table where each cell can have a few lines.
I moved the changelog icon into the Version column as a an additional row. The re
Similarly the Documentation link moved into the Description column, and the Description merged into the Plugin Name.
> OF-2892 Available Plugins page: redesign to make Documentation easier to see

- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientConnectionHandler.java
When a client drops offline, a presence update is broadcast on behalf of that client. We've observed deadlocks occurring when this happens (as the broadcast itself, especially when it occurs in context in of MUC rooms, will acquire mutexes).
There appears to be little reason for this broadcast to happen synchronous to the process of session termination process. To reduce the likelihood of deadlocks, this commit makes the broadcast happen in an asynchronous process.
> OF-2921: Prevent deadlock by not broadcasting synchronously

- xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/AbstractRemoteServerDummy.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalIncomingServerSessionTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalOutgoingServerSessionTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java
- xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteReceivingServerDummy.java
The unit tests that verify s2s behavior take a _long_ time to execute. The changes in this PR reduce that time (significantly).
This is mostly achieved by changes to the test code. Also, one improvement in Openfire itself is provided: it no longer waits for a timeout on certain irrecoverable outbound s2s failures (OF-2942).
> Reduce runtime of long-running S2S unit tests (and fix OF-2942 as a byproduct)

- xmppserver/src/main/java/org/jivesoftware/openfire/update/Update.java
- xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java
- xmppserver/src/main/java/org/jivesoftware/util/Version.java
- xmppserver/src/test/java/org/jivesoftware/util/VersionTest.java
For certain versions of plugins, Openfire incorrectly identifies that an update is available.
When Openfire has installed `10.1.7.3-SNAPSHOT` it incorrectly identifies that version `10.1.7.2` is an update.
This seems to be caused by Openfire’s abuse of the 4th numeric value in a version. It was originally intended to be a classifier for the status (eg: ‘the second beta release’). When that 4th value is used as part of a four-digit version, things do not quite compare as expected.
To illustrate, compare these two scenarios. The numbers 3 and 2 are all stored in the same field, which gets interpreted differently.
- `10.1.7 beta 3` is older than `10.1.7 release 2`
- `10.1.7.3-SNAPSHOT` is expected to be newer than `10.1.7.2` (release).
Prior to this commit, Openfire did not flag that …
> OF-2941: Improve Version comparison that involve SNAPSHOTs

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCEventDispatcher.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCEventListener.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/OccupantManager.java
A MUC room of the same name (JID) can be created, destroyed and recreated again. The two rooms should be seen as two different rooms.
When using the JID of the rooms, there's no way to distinghuish between them. For that, Openfire's numeric ID can be used.
In this commit, the numeric ID is added to selected MUC events.
> OF-2918: Expose numeric MUC room ID in events

- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
- xmppserver/src/main/webapp/index.jsp
When plugins fail to load, add a warning on the landing page. This should make the problem more visible.
> OF-2939: Admin console landing page should show plugin warnings

- xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
When a plugin fails to load, a warning should be displayed on the admin console plugin page.
This commit fixes a bug where this warning would be removed when an automatic reload of the plugin was attempted.
> OF-2938: Fix missing warnings for incompatible plugins

- i18n/pom.xml
- plugins/pom.xml
- pom.xml
- starter/pom.xml
- xmppserver/pom.xml
Pin the build timestamp and disable Built-By, Created-By and Build-Jdk-Spec fields from generated manifest. The Maven JAR plugin is updated to latest version that has the new option addDefaultEntries
https://igniterealtime.atlassian.net/browse/OF-2877
> OF-2877 Reproducible builds

- xmppserver/src/main/java/org/jivesoftware/openfire/ConnectionCloseListener.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/AbstractConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/ComponentStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSessionLocator.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSessionLocatorImpl.java
This revisits the fix for OF-2921, which introduces a problem in which a broadcast of presence occurs while the session is removed from the session manager. This causes issues, as the broadcast needs data associated to the session (such as its roster, privacy lists, etc). 
This PR holds two changes that improve on the previous solution. Please refer to individual commit messages for details.
> Make close event handling asynchronous and remote session locator improvement

- plugins/pom.xml
- xmppserver/pom.xml
After upgrading to Jetty 12, we also updated the Jetty plugin that performs precompilation of the JPS pages that make up the admin console. We are now using jetty-ee8-jspc-maven
Since this update, the build process is spewing out rather long stack traces, related to missing JAR files. The stack traces can be seen in https://igniterealtime.atlassian.net/browse/OF-2945
We have not noticed any failing functional behavior because of this. Nonetheless, the stack traces are annoying, as they suggest that something is wrong.
The missing JAR files seem to relate to the Xalan project, which is not a dependency of Openfire. It is, however, a dependency of Jetty's JSPC plugin.
On a hunch, I've excluded that dependency from the plugin during our build. That makes the stack trace go away. JSP …
> OF-2945: Prevent stack traces when pre-compiling JSP pages

- .github/workflows/continuous-integration-workflow.yml
When a PR gets merged to the Main branch, or when a tag is created, a Docker image should be published to the GitHub-provided registry.
> Publish Docker image to GitHub registry

- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/ClientSessionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
Reverts some of the changes introduced to prevent a deadlock (OF-2921).
Routing the unavailable presence that's sent out when a session closes cannot be made asynchronous. If the 'next step' is done prior to the routing of unavailable presence having completed, the session seems to be (partially) re-added. This causes an invalid state: the routing table no longer has the session, but caches such as the Routing Users Cache does.
This incorrect behavior was introduced by a fix for OF-2921: https://github.com/igniterealtime/Openfire/commit/b98a83d3470e06b66fbe718a304cfcf39bfba8c5
It was already partially reverted by https://github.com/igniterealtime/Openfire/commit/7aca93f16826c00215e0e7909ec8519a375a4701
The first commit in this PR reverts the remainder.
> OF-2921: Async closure partial revert

- xmppserver/src/main/java/org/jivesoftware/openfire/PacketDeliverer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/multiplex/MultiplexerPacketDeliverer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/OfflinePacketDeliverer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/PacketDelivererImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/PresenceManagerImpl.java
Adds a facility to allow for non-blocking stanza delivery.
The new facility is used when probing presence of entities on remote domains (as that can slow down a client that's connecting to Openfire).
Potentially this could/should be used in other places too (as the act of delivery doesn't return a result, and thus isn't expected to be needing a blocking operation), but I thought it best to take baby steps here.
> OF-2951: Async stanza delivery

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Openfire will kick 'ghost' users from a MUC room. It does so by tracking non-response to IQ Pings.
There's a suspicion of false positives in this check. To be a bit more forgiving, the default time-outs have been increased four-fold in this commit.
> OF-2958: Increase MUC idle kick time for ghost users

- xmppserver/src/test/java/org/jivesoftware/openfire/muc/MUCOccupantTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/muc/MUCRoomTest.java
This modifies existing unit tests to explicitly use data that appears to have triggered OF-2831. The resulting tests do not fail.
> OF-2831: Modify tests to cover offending data

- distribution/src/database/openfire_db2.sql
- distribution/src/database/openfire_hsqldb.sql
- distribution/src/database/openfire_mysql.sql
- distribution/src/database/openfire_oracle.sql
- distribution/src/database/openfire_postgresql.sql
- distribution/src/database/openfire_sqlserver.sql
- distribution/src/database/openfire_sybase.sql
- distribution/src/database/upgrade/10/openfire_db2.sql
- distribution/src/database/upgrade/10/openfire_hsqldb.sql
- distribution/src/database/upgrade/10/openfire_oracle.sql
- distribution/src/database/upgrade/10/openfire_postgresql.sql
- distribution/src/database/upgrade/10/openfire_sqlserver.sql
- distribution/src/database/upgrade/10/openfire_sybase.sql
- distribution/src/database/upgrade/19/openfire_db2.sql
- distribution/src/database/upgrade/19/openfire_hsqldb.sql
- distribution/src/database/upgrade/19/openfire_oracle.sql
- distribution/src/database/upgrade/19/openfire_postgresql.sql
- distribution/src/database/upgrade/19/openfire_sqlserver.sql
- distribution/src/database/upgrade/19/openfire_sybase.sql
- distribution/src/database/upgrade/37/openfire_db2.sql
- distribution/src/database/upgrade/37/openfire_hsqldb.sql
- distribution/src/database/upgrade/37/openfire_mysql.sql
- distribution/src/database/upgrade/37/openfire_oracle.sql
- distribution/src/database/upgrade/37/openfire_postgresql.sql
- distribution/src/database/upgrade/37/openfire_sqlserver.sql
- distribution/src/database/upgrade/37/openfire_sybase.sql
- xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
The database table ofSASLAuthorized is unused, while its definition causes database installation/upgrade errors for some users.
This commit removes the database table completely, both for fresh installs of Openfire, as for updates.
> OF-2956: Drop database table ofSASLAuthorized

- xmppserver/src/main/java/org/jivesoftware/openfire/audit/spi/AuditorImpl.java
- xmppserver/src/main/java/org/jivesoftware/util/FastDateFormat.java
- xmppserver/src/main/java/org/jivesoftware/util/XMPPDateTimeFormat.java
- xmppserver/src/test/java/org/jivesoftware/util/XMPPDateTimeFormatTest.java
This marks the third-party FastDateFormat class as deprecated, and replaces its usage with Java-native APIs.
> OF-2754: Deprecate FastDateFormat

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProvider.java
- xmppserver/src/test/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProviderAffiliationOperationsTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProviderItemOperationsTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProviderNodeOperationsTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProviderSubscriptionOperationsTest.java
This new unit test verifies behavior of CachingPubsubPersistenceProvider (which fails, as indicated by some of these test failing).
The tests introduced here only cover one (of three) types of operations that are being scheduled by the implementation:
- Node creation/changing/removal
These two other types of operation still need to be added:
- Affiliation creation/update/removal
- Subscription creation/update/removal
> OF-2437: Improve CachingPubsubPersistenceProvider

- build/ci/updater/pom.xml
- documentation/database.html
- xmppserver/pom.xml
Given changes in the Oracle license, we can now bundle their database drivers with Openfire. The changes in this commit do just that.
I've opted to use ojdbc11-production rather than ojdbc17-production as the latter is documented to be compatible with Jakarta. We do not use Jakarta. ojdbc11 has been documented to be compatible with Java 17 and 21, which should be good enough for us for now.
Jetty's JSP compiler plugin is not happy with the standard Oracle dependencies. It fails on expecting but not finding oracle.i18n.util.LocaleMapper. The internet suggests that this is caused by Oracle's xmlparserv2 dependency. Excluding that 'fixes' the problem. I'm not sure what functionality this affects.
As a side-effect, the `lib` folder of a distribution now contains an unneeded POM file. I can't …
> OF-2793: Bundle an Oracle database driver

- build/ci/updater/pom.xml
- pom.xml
- xmppserver/pom.xml
This works around an issue that creeps up when using the BOM project: it causes a POM file to be included in Openfire's distirbution. That file in turn causes the RPM build to fail.
As the distribution cannot be easily changed, this commit prevents usage of the project that introduces the POM file.
More context is provided in https://igniterealtime.atlassian.net/browse/OF-2960
> OF-2960: Replace Oracle database driver's BOM project with individual dependencies

- pom.xml
This release from Netty's 4.1 branch fixes a couple of CVEs: https://netty.io/news/2025/02/10/4-1-118-Final.html
> OF-2961: Upgrade Netty from 4.1.115 to 4.1.118

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/admin/servlet/CertificateExpirtyCheckerServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
- xmppserver/src/main/java/org/jivesoftware/util/cert/CertificateExpiryChecker.java
- xmppserver/src/main/resources/admin-sidebar.xml
- xmppserver/src/main/webapp/security-certificate-expiry-check-page.jsp
This commit adds a new feature that periodically checks if TLS certificates are expired, or are about to expire.
When such an expired is detected, an XMPP message is sent out to all admins (similar to the notifications sent out on available plugin updates).
A new admin console page has been added that can be used to configure this functionality.
> OF-2952: Warn admins of certificate expiry

- xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
With this change, any database upgrade scripts that update the database content beyond what is in the database install script will be executed directly after the install scripts are executed.
One side-effect of this approach is that under certain conditions, the 'success' message can be logged twice. I'm not bothered by that to much:
```
2025.02.11 20:56:20.914 INFO  [PluginMonitorExec-2]: org.jivesoftware.database.SchemaManager - Database update successful.
2025.02.11 20:56:20.914 INFO  [PluginMonitorExec-2]: org.jivesoftware.database.SchemaManager - Database update successful.
```
> OF-2940: After database install, run database upgrade check

- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/admin/servlet/SessionSummaryConfigServlet.java
- xmppserver/src/main/webapp/session-row.jspf
- xmppserver/src/main/webapp/session-summary-config-page.jsp
- xmppserver/src/main/webapp/session-summary.jsp
In OF-2706, the 'resource' column disappeared from the admin console page that showed the overview of client sessions. This proved to be problematic for some users.
In this commit, the columns that are shown on that page can be configured by each admin user. To do so, a new configuration page is added (accessible through a small link in the top-right corner of the session summary page). Settings are saved per-user, to allow for personal preferences.
> OF-2821: Admin Console Client Sessions page with configurable columns

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/LocalRoutingTable.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/ConsistencyChecks.java
Instead of having one 'local' routing table to track routes from all types of connections (component, server, client) a distinct table for each of these types should be used.
This allows for more granular control of data access. It will become easier to move invocations under a guard of a lock form a corresponding cache.
In this commit, only minor functional changes are applied. This affects some exception handling (a more generic `Throwable` is caught when processing of a stanza fails) and the registration of a task that cleans up server sessions (this task is now cancelled when the RoutingTable is stopped).
Changes are applied to classes and methods that all have limited visibility outside of the RoutingTableImpl class (or its package). It's therefor unlikely that this change introduces …
> OF-3026: Splitting up LocalRoutingTable

- xmppserver/src/main/java/org/dom4j/io/XMPPPacketReader.java
- xmppserver/src/main/java/org/jivesoftware/database/JNDIDataSourceProvider.java
- xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/audit/spi/AuditManagerImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdAuthProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceUpdateHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindBody.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapVCardProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/mediaproxy/MediaProxyService.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCSearchHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/net/ComponentStanzaHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/user/DefaultUserProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/user/JDBCUserProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/user/User.java
- xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java
- xmppserver/src/main/java/org/jivesoftware/util/ParamUtils.java
- xmppserver/src/main/java/org/jivesoftware/util/XMLWriter.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/SerializingCache.java
- xmppserver/src/main/webapp/import-truststore-certificate.jsp
- xmppserver/src/main/webapp/log.jsp
- xmppserver/src/main/webapp/login.jsp
- xmppserver/src/main/webapp/loginToken.jsp
- xmppserver/src/main/webapp/setup/setup-admin-settings_test.jsp
- xmppserver/src/main/webapp/user-create.jsp
- xmppserver/src/main/webapp/user-edit-form.jsp
- xmppserver/src/main/webapp/user-groups.jsp
Various bits of automation keep insisting that using `isEmpty()` is generally more readable and efficient than comparing against an empty string (`""`). I don't particularly feel that this is a worthwhile change in itself, were it not for it being a good way to reduce the number of 'hints' that are generated from our code base. That in itself may help to reduce noise: it can make other (more important) hints stand out better.
This should not introduce any functional change.
Code changes have been applied using IDE-provided automation (rather than manual changes).
> chore: replace empty string comparision with `isEmpty()`

- xmppserver/src/main/java/org/jivesoftware/openfire/cluster/RemotePacketExecution.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
Where a stanza is used in a toString(), use to `toXML` rather than `toString` of the stanza, as the latter uses 'pretty print' (which introduces newlines).
> OF-2967: Remove newlines in toString implementations

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
This builds on the change in https://github.com/igniterealtime/Openfire/pull/2687 and introduces guards, when modifying state of LocalRoutingTable instances. The first commit in this PR is equal to that in #2687. The second commit in this PR is the relevant bit.
When modifications to a LocalRoutingTable is made, this should always happen under guard of a lock that also guards related changes to the corresponding cache.
This commit should reduce the possibility of state inconsistencies. It does so by re-using the Cache-sourced locks that were originally introduced by the changes for issue ENT-425.
In the past, we introduced deadlock potential by putting more operations under guard of a lock. From history, I don't think we ever attempted this change. Additionally, as the code that's now …
> OF-3026: State changes of LocalRoutingTable should happen under guard of a lock

- xmppserver/src/main/java/org/jivesoftware/openfire/http/BoshBindingError.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/ResourceServlet.java
- xmppserver/src/main/java/org/jivesoftware/openfire/http/SessionListener.java
The first three commits in this PR build towards a fix for a race condition, in which terminated BOSH clients can leave Openfire in an inconsistent state (and, in certain circumstances, lead to memory starvation). See https://igniterealtime.atlassian.net/browse/OF-2966 for details.
> OF-2966: Fix race condition in BOSH (noticable during logout)

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/NettyConnectionAcceptor.java
To facilitate debugging, the various threads used by Netty EventLoops should have names that at least contain the type of connection that they're operating for.
This commit changes the name of threads of the
- 'parent' eventloop from `nioEventLoopGroup-7-1` (a Netty default) to `socket_s2s_ssl-acceptor-7`
- 'child' eventloop from `socket_s2s_ssl-thread-3` (a Netty default) to `socket_s2s_ssl-worker-3`
To do this, a new theadpool factory is introduces for the 'parent' eventloop. The new factory is configured to use the same priorty and daemon settings as the default Netty threadpool factory.
> OF-3027: Give Netty threads a recognizable name

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/NettyConnectionAcceptor.java
As we're overriding the thread factories used for Netty EventLoops to change the names of threads, we've also changed the default configuration of threads used by Netty.
Netty's default configuration can be expected to be optimized for performance. Openfire should use a similar configuration.
In this commit, the configuration is reverted back to the default configuration that's used by Netty (based on `io.netty.util.concurrent.DefaultThreadFactory`).
> OF-3028: Netty threads from 'child' EventLoop should use Netty-default settings

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
OF-2808 describes an issue in which a session that is resumed gets closed. This is caused by the asynchronous 'close' operation to execute 'connection close' listeners on a session that, in another thread, has already been resumed.
The fix for OF-2808 introduces a Latch, that causes a thread to block. If that thread is one of a Netty EventLoop, all processing stops (possibly leading to the latch never be released, as the connection close listeners cannot operate).
This commit reverts the change for OF-2808, and applies a new fix for that issue: disallow a session that's already in the process of being closed from resumed.
> OF-2811: Must not block on eventloop

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
It appears that this warning is also logged (incorrectly) in a scenario where user has a session that relates to a different route (in other words: when the user is using more than one device / the addressing uses different resource-parts in their JIDs). Openfire should not be logging that warning in such cases.
> OF-3029: Prevent false warnings about data inconsistency

- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/Session.java
In the early days, a Session was always backed by a (socket) connection. When the connection was closed, so was the session, and vice versa.
With Stream Management, this no longer is the case. A session can remain unclosed (detached) while its connection is closed.
This commit changes the behavior of `LocalSession#isClosed()` to be based on the session's `status` field, and no longer on the connection's connectivity state.
> OF-3031: Session's 'close' state no longer based on its backing connection

- xmppserver/src/main/java/org/jivesoftware/openfire/session/ClientSessionTask.java
The 'removeDetached' cluster task is preemptively fired, and is likely to not find a session to be detached.
As not finding an applicable session is to be expected, this shouldn't be logged as an error.
> OF-3034: Reduce log level for cluster task that can be expected to fail.

- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSessionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/Session.java
- xmppserver/src/main/webapp/session-details.jsp
- xmppserver/src/main/webapp/session-row.jspf
- xmppserver/src/main/webapp/session-summary.jsp
This commit ensures that all cluster nodes can see the 'detached' state of a session. Prior to this change, this was only visible at the local cluster node. Because of this, cluster tasks that cannot operate on detached sessions no longer are invoked.
Additionally, certain cluster tasks that cannot succeed on a detached session are now logged in a less verbose manner than on level 'error'.
> OF-3035: Propagate session 'detached' state through cluster

- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/nio/NetworkEntityUnreachableException.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
This drops the stack trace, and changes the log message in such a way that it's more descriptive to an admin.
> OF-3036: Improve log message when remote domain is unreachable

- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQBindHandler.java
When a session is closed, there is no need to apply resource-part conflict resolution anymore (as that session isn't going to be used anyway).
This can also prevent a cluster task exception: the cluster task to increase a conflict count will throw an exception when the session being operated on is non-existing, or existing-but-closed.
> OF-3039: Avoid resource conflict resolution on closed session

- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/TerminationDelegate.java
In certain conditions (specified in[ OF-3033](https://igniterealtime.atlassian.net/issues/OF-3033)), the default implementation that determines if a detached session (in Stream Management context) is to be terminated, is overly strict. This commit introduces a delegate mechanism that can be used to delegate the decision if a detached session is to be terminated.
> OF-3033: Allow customization to determine if detached sessions can be terminated

- distribution/src/database/openfire_sqlserver.sql
- distribution/src/database/upgrade/36/openfire_sqlserver.sql
The Transact-SQL timestamp data type is different from the timestamp data type defined in the ISO standard. In MSSQL, `timestamp` is a synonym for the `rowversion` data type.
> OF-2760: Fix MSSQL date/time column

- xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java
Earlier commits for this issue have removed the same initializer elsewhere.
See mailinglist thread starting at https://www.eclipse.org/lists/jetty-users/msg10880.html
This hopefully helps reduce scanner warnings when Openfire is booting up.
> OF-2717: Remove JasperInitializer from BOSH context

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/MessageRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java
Introduces an alternative to `LocalSession#canProcess`: `#canDeliver`, to fix:
- no longer generate two error stanzas if `LocalOutgoingServerSession#canProcess` returns `false`
- have implemenations be responsible for generating any error stanzas, making it possible for each implemenation to choose the best type of error. No longer assume that every error must be related to XEP-0016.
- prevent synchronous error processing in `LocalOutgoingServerSession` that can introduce a deadlock (similar to OF-2341 and OF-2342).
This commit replaces `#canProcess` but marks it as being deprecated. The replacement method, `#canDeliver` has temporarily received a default implementation that is backwards compatible with the preexisting code. This should allow any third-party implementations to be able to …
> OF-3041: Prevent Deadlock by reworking `LocalSession#canDeliver()`

- .github/workflows/continuous-integration-workflow.yml
- build/ci/updater/src/main/java/com/igniterealtime/openfire/updaterunner/Main.java
- distribution/src/database/openfire_db2.sql
- distribution/src/database/openfire_hsqldb.sql
- distribution/src/database/openfire_mysql.sql
- distribution/src/database/openfire_oracle.sql
- distribution/src/database/openfire_postgresql.sql
- distribution/src/database/openfire_sqlserver.sql
- distribution/src/database/openfire_sybase.sql
Prior to this commit, Openfire's continuous integration already had some scripts that verify the scripts used to update the database managed by Openfire from some base version to a newer version. These checks do not verify the installation script - only the update scripts, which provide a 'delta'.
In this commit, the mechanism used to test the update scripts is repurposed to also test the install scripts:
- instead of provisioning the database with a known-good (but old) database installation script, the latest version of the script is used (which is the system under test)
- the 'update runner' is not executed at all - instead, it is assumed that a bug in the install script will cause the docker build to fail.
> CI: Introduce checks for the database install scripts

- build/debian/openfire.init.d
Split from https://github.com/igniterealtime/Openfire/pull/2563 to simplify of review.
This change is the openfire.init.d is same as was made in 30b4a176 for openfire.sh
> When establishing an outbound connection, Openfire now prefers the IP family as defined by the order in which the operating system returns addresses.
The Debian init script makes almost the same as the `openfire.sh` so they should be synced until the SystemD migration.
CC @guusdk
> OF-2786: Openfire to use system-defined preferences for IPv6 over IPv4

- xmppserver/src/main/java/org/jivesoftware/openfire/commands/AdHocCommandHandler.java
We missed a couple back in #2381 
There are 2 commands that were implemented, but weren't registered, so were never in disco, and never responding.
https://igniterealtime.atlassian.net/browse/OF-3043
> OF-3043: Fix Adhoc command registration

- distribution/src/bin/openfire.sh
Split from #2563 to simplify of review.
The `openfire.sh` is used to start the service with a detected JRE.
It's included into the tarball distribution so it must be used by those who installed the Openfire manually.
However, the Debian and RPM packages doesn't use the script but instead their init scripts are doing almost the same themselves.
When migrating to SystemD service I decided to reuse the `openfire.sh` to avoid code duplication and use the same wrapper with expected behavior.
But before I made the refactoring and improvements.
The script itself is has a problem with detection of OPENFIRE_HOME when the value of the var is overwritten few times. I didn't fixed that.
>  openfire.sh

- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/ReverseLookupUpdatingCacheEntryListener.java
- xmppserver/src/test/java/org/jivesoftware/util/cache/ReverseLookupUpdatingCacheEntryListenerTest.java
Some instances of `ReverseLookupUpdatingCacheEntryListener` are used in contexts where it's expected that exactly one cluster node 'owns' the data for which an event was fired.
For such scenarios, this commit adds an optimization that removes data registered for _other_ nodes, when data is being registered for a node. This intends to add some resilience against data inconsistency.
> OF-3044: ReverseLookupUpdatingCacheEntryListener optimization for unique ownership

- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
This doesn't fix a bug, but prevents future issues by avoiding confusion.
> Add missing braces to if-statement

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCSearchHandler.java
Replaces comparisons with String.indexOf() calls that can be replaced with a call to the String.contains() method.
> Replace String.indexOf with contains

- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
StringBuilder is a non-thread-safe replacement for StringBuffer.
> Replace StringBuffer with StringBuilder

- .github/workflows/continuous-integration-workflow.yml
- xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java
After SchemaManager runs database upgrade scripts, it should not assume success, but explicitly check for it.
> OF-3045: SchemaManager explict check for success

- .github/workflows/continuous-integration-workflow.yml
- build/ci/updater/pom.xml
- build/ci/updater/src/main/java/com/igniterealtime/openfire/updaterunner/Main.java
Instead of hard-coding the location of Openfire's source code, this location should be provided to the application.
Additionally:
- Use the location to generate a mock 'OPENFIRE_HOME' directory, that can be used to both: 
-- Read and write property files used by the update runner
-- Retrieve the database scripts that are being tested by the update runner.
- Close the database connection after use
> CI: Database tests shouldn't use hardcoded file paths

- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java
Openfire’s implementation splits values based on the $ character. The method used, however, interpret that character as a regular expression. Instead, it should be used literally (per RFC 3112).
> OF-3047: Fix parsing of LDAP 'authPassword' attribute.

- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQBindHandler.java
After resource binding succeeds, clean-up of older, detached sessions will be problematic (as that needs to update state, but typically also sends out presence unavailable on behalf of the user).
In this commit, any detached sessions matching the full JID that will be the result of a successful resource binding is terminated, prior to resource binding being allowed to complete.
> OF-3044: When resource binding, ensure that old detached sessions are removed

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCOccupant.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
To prevent spoofing, not one, but _all_ provided `occupant-id` values should be removed. Thanks Travis!
> OF-2607: Remove _all_ client-provided `occupant-id` values

- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoItemsHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapVCardProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/mediaproxy/MediaProxyService.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCOccupant.java
- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCRegisterHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
There are various bits in the code where an XML snippet (typically an XMPP stanza) is being manipulated by removing a particular child element. This can have various reasons, including:
- removing client-provided data that should be server-provided (to avoid spoofing)
- re-use of an element for other purposes
When an element is removed, a common assumption is that there will be at most one such element in the XML snippet. This is driven mostly by an expectation, not by inspection.
To be safe, remove all occurrences, not just the first one.
> OF-3055: When removing childelement, don't assume there's only one

- xmppserver/src/main/java/org/jivesoftware/openfire/user/UserMultiProvider.java
HybridUserProvider throws IndexOutOfBoundsException when trying to rerieve users with a paged search.
When using the function UserProvider.findUSers( crit, query, index, maxPage ) and a configured HybridUserProvider, an exception is thrown: 
java.lang.IndexOutOfBoundsException: toIndex = 50
at java.util.AbstractList.subListRangeCheck(AbstractList.java:509) ~[?:?]
at java.util.ArrayList.subList(ArrayList.java:1190) ~[?:?]
at org.jivesoftware.openfire.user.UserMultiProvider.findUsers(UserMultiProvider.java:306) ~[xmppserver-5.0.0-alpha-org.jar:5.0.0-alpha]
at org.jivesoftware.openfire.user.UserManager.findUsers(UserManager.java:418) ~[xmppserver-5.0.0-alpha-org.jar:5.0.0-alpha]
Solved by conditionally setting the toIndex value.
> OF-3054: HybridUserProvider throws IndexOutOfBoundsException

- .github/actions/startserver-action/action.yml
- .github/actions/startserver-action/startCIServer.sh
- .github/workflows/continuous-integration-workflow.yml
This modifies the GitHub action that's used to start Openfire to take an optional log level. When set, the log4j configuration used by Openfire is modified accordingly.
The continuous integration jobs that use this action are now logging on level 'debug'. That should provide more analytics, in case a step fails.
> CI: Allow Openfire to log at different levels

- xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceUpdateHandler.java
When _removing_ a directed presence from memory (which happens when an 'unavailable' is sent), the previous code seems to try to 'optimize' things, by differentiating between a presence removal that's registered for a client session, or any other session.
Such an optimization is undesirable, for a number of reasons:
- it requires the client to currently be online;
- it sets a cluster-side lock (through the lookup on RoutingTable)
- it adds quite a bit of code complexity (making maintenance harder)
When _adding_ the directed presence, the distinction is _not_ made, which adds to the believe that there is code smell.
In this commit, the 'optimization' is replaced by a simpler code path.
> OF-3056: Refactor processing of directed presence

- xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java
- xmppserver/src/main/java/org/jivesoftware/openfire/RoutingTable.java
- xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/ClientSessionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteClientSession.java
- xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSessionTask.java
- xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
- xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/ConsistencyChecks.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/ConsistencyMonitor.java
- xmppserver/src/main/webapp/session-row.jspf
- xmppserver/src/test/java/org/jivesoftware/util/cache/CacheFactoryConfigTest.java
The commits in this PR remove:
- the concept of having a _route_ that is anonymous. Instead, a _session_ can be anonymous
- the clustered cache that stores anonymous sessions (apart from 'regular' session). Instead, all sessions are stored in one cache
Please refer to the individual commit messages for more details.
> OF-3059 Remove anonymous route

- plugins/pom.xml
- pom.xml
For good measure, use the latest available release. Also prevents CVE-2025-1948 from popping up in static code analyzers (I'm not sure if Openfire was affected by this issue).
> OF-2717: Bump Jetty from 12.0.14 to 12.0.21

- xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionListener.java
Connection Managers are rarely used, and their implementation hasn't seen an update in a decade. Having this disabled by default seems to be a good idea. If anything, it may prevent an attack surface.
> OF-2453: Disable Connection Managers by default

- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQRosterHandler.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/Roster.java
- xmppserver/src/main/java/org/jivesoftware/openfire/roster/RosterItem.java
When calculating the 'version' of a roster:
- apply changes before the calculation;
- base the calculation on state of the roster, not on a memory address (`Object#hashCode()`)
Instead of using Roster's `hashCode()` implementation, this commit introduces a very similar method. This calculates a hash based on only those bits of state that are relevent for roster versioning (notably, it excludes RosterItem's 'subscribeStanza' field).
> OF-3064: Fix Roster Versioning

- xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQRosterHandler.java
- xmppserver/src/test/java/org/jivesoftware/openfire/handler/IQRosterHandlerTest.java
RFC 6121 section 2.1.5 defines:
> The following rules apply to roster sets: [...] The server MUST ignore any value of the 'subscription' attribute other than "remove"
Openfire currently ignores subscription values that are otherwise valid subscription item values (such as none and both) but it throws an error when a different value (e.g.foobar) is used.
The specification clearly states that any value MUST be ignored, so returning an error is not quite right. Instead, that value should be ignored and the Roster Set should be processed as if it wasn’t there.
> OF-3062: Improve Roster Set processing (ignore subscription value)

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultPubSubPersistenceProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/InMemoryPubSubPersistenceProvider.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceProvider.java
The old codebase defined two queries to get the last item for a pubsub node, and to get all items for a pubsub node. The actual SQL of both definitions is the same. It does not contain any ‘limit’ or ‘top’ clause (although database driver hints are given).
This is likely the result of Openfire supporting multiple database systems, that each have their own clauses to limit a resultset. SQLServer uses `SELECT TOP(?) ...`, Oracle has `... FETCH FIRST ? ROWS ONLY` while other databases generally use `... LIMIT ?`. It is inconvenient to fold all these alternatives in one implementation.
In this commit, the code is modified to:
- limit the size of the requested resultset from the database appropriately.
- remove SQL duplication (getting the latest item can use the same query as getting the …
> OF-3061: Improve DB query to get last pubsub items

- xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
This prevents an artificial resource constraint to kick in whenever a user with contacts on many different domains logs in.
> OF-3067: Allow for more concurrent s2s connections.

- xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketUtil.java
When no s2s connections to a target domain can be set up, do not wait for the timeout (of five minutes) to give up.
This introduces a simple periodic check (every 2 seconds) to see if the attempt can be aborted.
> OF-3068: Give up faster when s2s connection attempts have exhausted

- xmppserver/pom.xml
The issue was described here:
https://discourse.igniterealtime.org/t/java-11-module-issue-xpp3-dependency-in-xmppserver-provides-duplicate-qname-class/95185
In short, xpp3/xpp3/1.1.4c contains javax.xml.namespace.QName class, which it should't
This started to cause issues since java11
> update xpp3 from xpp3/xpp3/1.1.4c to org.codelibs/xpp3/1.1.4c.0

- distribution/pom.xml
- plugins/pom.xml
- pom.xml
This should fix a stacktrace that's shown when opening admin console pages of plugins that are compiled against older versions of Openfire (this issue appears only in unreleased versions of Openfire).
> OF-3079: Bump Jetty from 12.0.21 to 12.0.22 (restore plugin compat)

- build/rpm/openfire.spec
After new SystemD config files were added (for Debian), the RPM build failed with this error:
```
+ /usr/lib/rpm/check-buildroot
error: Installed (but unpackaged) file(s) found:
/opt/openfire/dist/etc/ufw/applications.d/openfire
/opt/openfire/dist/usr/lib/systemd/system/openfire.service
/opt/openfire/dist/usr/lib/systemd/system/openfire.slice
Installed (but unpackaged) file(s) found:
/opt/openfire/dist/etc/ufw/applications.d/openfire
/opt/openfire/dist/usr/lib/systemd/system/openfire.service
/opt/openfire/dist/usr/lib/systemd/system/openfire.slice
mv: cannot stat '/home/bamboo-agent3/bamboo-agent-home/xml-data/build-dir/OPENFIRE-NMRB-JOB1/rpmbuild/RPMS/noarch/openfire*rpm': No such file or directory
```
The new files for Debian seem to break the RPM build.
The changes in this commit …
> OF-2526: Don't include SystemD artifacts in RPM

- xmppserver/src/main/java/org/jivesoftware/openfire/auth/JDBCAuthProvider.java
- xmppserver/src/test/java/org/jivesoftware/openfire/auth/JDBCAuthProviderTest.java
Password hashes are easier to brute force than they would be if following the latest guidance. Reasonably strong passwords will still resit brute forcing in a reasonable time frame on current hardware.
The default (previously defined to be 10) is used only when the property `jdbcAuthProvider.bcrypt.cost` is not set. Thus, the change that is applied in this commit can be worked around (for backwards compatibility) by setting that property to the original value, 10.
> OF-3078: Increase default JDBCAuthProvider bcrypt cost

- Dockerfile
Openfire wouldn't build using `podman`, but spotted that it was due to a double colon in the `user:group` part of the chown.
Whilst I was there, I switched to using the configured variable for the username, as was done in the previous stage.
> Dockerfile: Remove errant colon, and use env vars for ownership

- xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactoryStrategy.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CacheWrapper.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/CaffeineCache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultCache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultLocalCacheStrategy.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/SerializingCache.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/lock/CacheKey.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/lock/LocalLock.java
- xmppserver/src/main/java/org/jivesoftware/util/cache/lock/LockAndCount.java
Based on the single responsibility principle, the CacheFactory should not be managing Locks. Instead, Caches should do that themselves.
Back in 2019, the method in CacheFactory that generates locks was marked as deprecated because of that, with a removal note in the distant future: 5.0.0.
As 5.0.0 is upon us, the deprecated code has now been removed. The cache locking implementation has been moved to a dedicated class (`LocalCache`) that is used by caches directly.
This commit attempts to achieve the desired removal of deprecated methods with a minimum of refactoring.
Further improvements may be desired (e.g. not storing locks for all caches in one shared data structure, but rather in a per-cache data structure).
> OF-3084 OF-3088: Refactor Cache Locking implementation

- xmppserver/src/main/java/org/jivesoftware/database/DefaultConnectionProvider.java
- xmppserver/src/main/java/org/jivesoftware/database/EmbeddedConnectionProvider.java
While making a Debian package I made an error when the /var/lib/openfire/embedded-db wasn't created during setup. And the Embedded DB folder  /usr/share/openfire/embedded-db is a link to the non esisting /var/lib/openfire/embedded-db.
I fixed it but before that I had a problem on the http://localhost:9090/setup/setup-datasource-settings.jsp page. It saw that the folder is not exists and tried to create it. But there was the link, it just was broken. So the PR just improved error handling for this situation to simplify debugging.
Additionally it contains some changes:
Remove deprecated finialize() method since it won't be called anyway anymore.
Commits on Jul 7, 2025
[EmbeddedConnectionProvider.destroy(): add dataSource.close()](https://github.com/igniterealtime/Openfire/commit/0f6b0cf3c7bd …
> OF-3102 Improve error handling in the embedded db

- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEventDispatcher.java
- xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubListener.java
Introduces a simple event listening mechanism, similar to others already available.
This mechanism has support for events that are triggered when PubSub items are published, and deleted.
> OF-3099: Add basic PubSub event listener mechanism

- xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQOwnerHandler.java
As defined by XEP-0045 section 10.2.1 "Notification of Configuration Changes.
Openfire already sent a notification when privacy or security settings were changed. It now sends a 104 for any other change.
> OF-3104: When a MUC room's config gets changed, send appropriate status codes

- documentation/openfire.doap
- documentation/protocol-support.html
- i18n/src/main/resources/openfire_i18n.properties
- xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/vcard/VCardManager.java
- xmppserver/src/main/java/org/jivesoftware/openfire/vcard/xep0398/PresenceEnhancer.java
- xmppserver/src/main/java/org/jivesoftware/openfire/vcard/xep0398/UserAvatarToVCardConvertor.java
This adds basic support for XEP-0398, that:
- converts vCard avatars into PEP avatars
- converts PEP avatars into vCard avatars
- adds an avatar hash to presence available stanzas sent by users (per section 4)
Additionally, the code checks if vCard avatars are to be migrated when a vCard is loaded from a vCard provider. This aims to pick up changes that are applied to external data stores (such as LDAP / AD).
The existing code does not _remove_ avatars, when a removal is initiated in one of both systems.
> OF-2034: Add support for XEP-0398: User Avatar to vCard-Based Avatars Conversion

- build/debian/openfire.init.d
The Dash which is the default shell in the Debian/Ubuntu the command returns nothing:
grep -oe \/.*\/bin\/java
To solve this we need to quote the regexp argument.
https://igniterealtime.atlassian.net/jira/software/c/projects/OF/issues/OF-3106
> OF-3106 Fix: when JAVA_HOME is empty it fails to detect the best java version

- build/debian/openfire.init.d
- distribution/src/bin/openfire.sh
Since v5.0 the Debian installer installs both /etc/init.d/openfire and SystemD unit in the /usr/lib/systemd/system/openfire.service. The SystemD itself will work with the unit file but some users may have still use the old init.d script directly. They should migrate to using of the `systemctl start openfire` command instead.
The SystemD unit doesn't construct JVM options but instead it calls the `openfire.sh` script as an entry point.
The init.d script constructs the options itself and it turned out that it had a bug when JAVA_HOME wasn't detected that is fixed now.
To make the transition more smoother and to minimize code duplication we should make the `/etc/init.d/openfire` to work similarly to the SystemD unit and call the `openfire.sh` instead. …
> OF-3107 Debian: Use openfire.sh in the /etc/init.d/openfire similarly to SystemD serivice

- .github/workflows/continuous-integration-workflow.yml
This isn't strictly needed, but it's slightly more correct and serves as a nice way for me to kick off a build that should pick up the latest changes of that framework.
> CI: rename 'smack' tests into 'XMPP testing framework'

- .github/workflows/continuous-integration-workflow.yml
Can't recall who or why SHA pins were introduced, but it was probably me in some wild abundance of caution. It's unnecessary, and it's certainly inconsistent.
> CI: Stop using SHA-pinned docker actions, use tags instead

- .github/workflows/continuous-integration-workflow.yml
- Dockerfile
The goal here is to ensure that docker rebuilds are fast, and especially so when inside CI.
This PR achieves this by two methods:
Using build-time cache mounts to handle the Maven repository. These are held independent of the "hash", so can persist (or not) between builds even if the calling hash changes. In our case, this means that if the pom.xml files change, we may reuse an "old" Maven repo and just fetch the changes.
Having the docker engine upload the docker cache (which includes the above, and also layers) to Github's cache API, and restore it prior to a build.
Tested by:
Enabling the docker build for this branch, and disabling push. Forced a rebuild which executed very quickly. This is as far as I think we can go at this stage. Realistically, I would expect this to be a step on …
> Improve docker caching

- documentation/translator-guide.html
- i18n/src/main/resources/openfire_i18n.properties
- i18n/src/main/resources/openfire_i18n_cs_CZ.properties
- i18n/src/main/resources/openfire_i18n_de.properties
- i18n/src/main/resources/openfire_i18n_es.properties
- i18n/src/main/resources/openfire_i18n_fa_IR.properties
- i18n/src/main/resources/openfire_i18n_fr.properties
- i18n/src/main/resources/openfire_i18n_he.properties
- i18n/src/main/resources/openfire_i18n_it_IT.properties
- i18n/src/main/resources/openfire_i18n_ja_JP.properties
- i18n/src/main/resources/openfire_i18n_nl.properties
- i18n/src/main/resources/openfire_i18n_pl_PL.properties
- i18n/src/main/resources/openfire_i18n_pt_BR.properties
- i18n/src/main/resources/openfire_i18n_pt_PT.properties
- i18n/src/main/resources/openfire_i18n_ru_RU.properties
- i18n/src/main/resources/openfire_i18n_sk.properties
- i18n/src/main/resources/openfire_i18n_sv.properties
- i18n/src/main/resources/openfire_i18n_tr_TR.properties
- i18n/src/main/resources/openfire_i18n_uk_UA.properties
- i18n/src/main/resources/openfire_i18n_zh_CN.properties
Keep only important note about { and ''.
Move important notes to the Translations documentation.
The dead link to language codes replaced with Wikipedia article.
This saves 20kb of space and makes it faster to parse the props.
> i18n: remove preamble in properties files

- xmppserver/src/test/java/org/jivesoftware/openfire/group/AbstractGroupProviderTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/group/DefaultGroupProviderTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/group/GroupManagerNoMockTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/group/GroupManagerTest.java
- xmppserver/src/test/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServerTest.java
- xmppserver/src/test/java/org/jivesoftware/util/AdminConsoleTest.java
- xmppserver/src/test/java/org/jivesoftware/util/CertificateManagerTest.java
- xmppserver/src/test/java/org/jivesoftware/util/SAXReaderUtilTest.java
- xmppserver/src/test/java/org/jivesoftware/util/StringUtilsTest.java
- xmppserver/src/test/java/org/jivesoftware/util/XMPPDateTimeFormatTest.java
The test suite contains several patterns where `fail` was used in a way that does follow JUnit Jupiter's best practices.
This PR attempts to improve those calls, and use (or not use) `fail` in a more idiomatic way,
Note that all the tests modified in this PR were functionally correct. The PR does not attempt to improve their correctness, just the style in which they use JUnit.
The PR addresses three main patterns:
**Boolean assertion with a constant value:**
```java
assertFalse(false, "If we reached here, the test should fail");
```
Since the condition is a literal, there's no point in using a conditional assertion, and the unconditional `fail` should be used instead:
```java
fail("If we reached here, the test should fail");
```
**Using `if` statements to assess conditions for failure …
> Improve tests usage of fail
