src/java/org/jivesoftware/openfire/http/HttpBindManager.java
Update the BOSH connector (HttpBindManager) to properly initialize and restart the HTTP binding service after applying a configuration change.
=> OF-877: Cleanup BOSH start/stop/restart

src/java/org/jivesoftware/openfire/handler/IQRosterHandler.java
There were some issue with this code:
1. Before this change the else branch (removeRosterItem(roster)) did return null and therefore violated IQ semantics.
2. IQs targeted at the user's own bare JID were routed to the else branch, which was wrong.
3. IQs targeted directly to the server were responded to. Prosody returns an error in this case and I think it's correct.
It now checks if the sender equals the recipient or the recipient is null. Otherwise return service-unavailable.
I don't understand the comment (// The packet must be a roster removal from a foreign domain user.)
AFAIK IQHandlers only deal with IQs which were routed to the own server. Foreigen domains are already handled by IQRouter (I think).
I also don't understand why it must be a roster removal then. Anybody?
There's also …
=> OF-875 Roster requests to bare JID of the user are not responded

src/java/org/jivesoftware/openfire/SessionManager.java
Returns an empty iterator if the inbound packet is incomplete.
=> OF-874: Fix NPE if from/to is missing

src/java/org/jivesoftware/openfire/http/HttpBindManager.java
This fix reverts behavour to reset the web contexts handler collection as it removes the webservices added by plugins at class construction time.
=> OF-877 breaks plugins webservices fix

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/JustMarriedController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/exceptions/ExceptionType.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/UserRosterService.java
* Added possibility to rename a user (Thanks to JustMarried plugin)
* Adjusted HTTP Codes by conflict to HTTP CODE: 409
* Added subject to Chat room
* Disabled jersey logging on startup
* By create a new chat room the chat room service will be created if it was not there
=> Update to REST API plugin version 1.0.1

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/GroupController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/GroupEntities.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/GroupEntity.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/GroupService.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java
* User will be kicked by a lockout (ban)
* Added: new endpoints for groups (Get overview over all or specific group and to create, update or delete a group)
=> Update to REST API plugin version 1.0.2

src/java/org/jivesoftware/openfire/pep/IQPEPHandler.java, src/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
This pull request is for https://igniterealtime.org/issues/browse/OF-858
=> OF-858: Auto create new nodes in PEP

src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
OF-888 is presumed to be a recursion due to an attempt to bounce a bounce, in
other words it's failing to handle a double-bounce.
It appears to be caused when routing a stanza from a MUC fails, and for some
reason I don't yet understand, the routing of the bounce to the originating
MUC source also fails.
The test for the double bounce is only present for the IQ case, but this fails
in any case because it tests only for the IQ case, and uses a test which checks
the IQ's symbolic type; this is not actually set by Packet.setError(), so does
not trigger.
Tom's fix inserted a sentinel into the original failing stanza, however a new
stanza is created for the bounce, which will not contain the sentinel; therefore
the fix will not protect from a recursion.
Therefore this patch:
1) Removes Tom's …
=> Change OF-888 fix to be based on error

src/plugins/userservice/src/java/org/jivesoftware/openfire/plugin/service/UserGroupService.java, src/plugins/userservice/src/java/org/jivesoftware/openfire/plugin/service/UserRosterService.java, src/plugins/userservice/src/java/org/jivesoftware/openfire/plugin/service/UserService.java, src/plugins/userservice/src/java/org/jivesoftware/openfire/plugin/service/UserServiceProperties.java
Return responses from **userservice** REST plugin in json format too for easy consumption from javascript.
In order to get responses in JSON add header
**Accept: application/json**
=> Plugin: userservice. Get REST responses in JSON too

src/java/org/jivesoftware/openfire/nio/ConnectionHandler.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java
The commits in this pull request address:
- an issue where only the MINA session, not the entire Openfire connection, is closed upon an error
- re-closing a connection that's already being closed (potentially looping)
More details can be found in the commit messages.
=> Two additional fixes that relate to OF-883

src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Currently, only stanzas containing errors of type cancel will cause the
occupant to be removed, however this doesn't appear to catch and remove many
occupants in practise.
This patch therefore removes occupants from the service on any message or
presence error stanza, irrespective of the error type. IQ stanzas do not
trigger the same response, as these may be due to lack of client support
rather than a vanished occupant.
=> OF-910 - Error stanzas to MUC room should remove occupants

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/SessionController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/SessionEntities.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/SessionEntity.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/SessionService.java
Added: new endpoints for sessions (Get overview over all or specific user sessions)
=> Update the REST API plugin to version 1.1.0

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
I am unsure of patch, just making a PR with what is in the Jira ticket.
=> OF-477 Correct SASLserver to use consistent digest-uri

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/SessionController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/SessionService.java
Added: new endpoint to close user sessions
=> Update the REST API plugin to version 1.1.1

src/web/server-locale.jsp
git diff makes this change look ugly, but should be correct.
=> OF-682 Add Portuguese as option for server-locale

src/java/org/jivesoftware/openfire/handler/IQEntityTimeHandler.java
=> XEP-0202 Entity Time should respect Daylight Saving Time

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0059/XmppResultSet.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/IQRetrieveHandler.java
https://community.igniterealtime.org/thread/56171
https://community.igniterealtime.org/thread/56173
=> Fix collection requests XEP-0059

src/plugins/ofmeet/src/java/org/jitsi/jigasi/xmpp/IQUtils.java
FIXED:  typo
1. 'from' was 'fro' (Line 18)
=> FIXED:  typo

documentation/docs/install-guide.html
https://igniterealtime.org/issues/browse/OF-931
=> Improve installation guide

src/java/org/jivesoftware/openfire/auth/DefaultAuthorizationPolicy.java
If the property sasl.proxyAuth is set to true, then administrative users can
authorize as any user on the system. This is convenient for testing, and to
manipulate other users' accounts.
An admin can, of course, change passwords anyway, so this doesn't reduce
security much, but is off by default in any case.
Testing is problematic since I can't actually find a client which allows this.
=> Add Proxy Authorization to DefaultAuthorizationPolicy

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
FIX: Monitoring plugin list request with max tag does not work correctly
https://community.igniterealtime.org/thread/56168
=> FIX: Monitoring plugin list request with max tag does not work correctly

src/database/upgrade/22/openfire_sqlserver.sql
Syntax glitch; refer to https://msdn.microsoft.com/en-us/library/ms190273.aspx#add for more info.
=> OF-631: Fix upgrade script for SQLServer

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/CORSFilter.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java
- Added: CORS to all endpoints
=> Update the REST API plugin to version 1.1.2

src/plugins/hazelcast/changelog.html, src/plugins/hazelcast/classes/hazelcast-cache-config.xml, src/plugins/hazelcast/plugin.xml
Per community feedback here: https://community.igniterealtime.org/thread/56508
=> Update default HZ config file to match new schema

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
1) Re-Implemented Pull Request #230 (Pull Request #249 reverted #230)
2) Implemented change as per Kalchenko Alexandr (https://community.igniterealtime.org/thread/55544)
=> Fixed Kerberos SSO Challenge Response

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MsgArchiveController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/StatisticsController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/SessionsCount.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/StatisticsService.java
- Added: get concurrent sessions (local or cluster wide)
=> Update the REST API plugin to 1.1.4

src/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java
Added a couple of specific null-checks, as well as a generic SASLException wrapper for any unchecked exceptions.
=> OF-939: Should have safeguards against runtime exceptions.

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/JustMarriedController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MessageController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/MessageEntity.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/JerseyWrapper.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MessageService.java
- Added: Send broadcast message to all online users
=> Update the REST API plugin to 1.1.5

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/exceptions/RESTExceptionMapper.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/GroupService.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/UserGroupService.java
Fixed: the problem with wrong media type by error
=> Updated the REST API plugin to 1.1.6

build/build.xml, documentation/docs/overlay.html
Through overlay / customization, it should be possible to add/adjust
the files under /src/resources/
=> OF-948: Overlay should allow modification of /src/resources

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java
Fixed feature-not-implemented error
See https://github.com/igniterealtime/Openfire/pull/213
https://igniterealtime.org/issues/browse/OF-862
=> monitoring plugin version 1.4.7

src/plugins/restAPI/plugin.xml, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomAdminsService.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomMembersService.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOutcastsService.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomOwnersService.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/utils/UserUtils.java
Since 3.10.0 OF-179 (https://igniterealtime.org/issues/browse/OF-179) has
been implemented. This patch makes it possible to use the restAPI for
that.
=> Handle group addition/removal per MUCRoom

src/java/org/jivesoftware/openfire/muc/cluster/OccupantAddedEvent.java
Applying patch proposed by Luki de Silva.
=> OF-954: Fix MUC room sync in cluster

src/java/org/jivesoftware/database/DbConnectionManager.java
Some cloud environments will enforce throttling parameters on database access (Microsoft Azure is a great example of that). As such, it is important that administrators are able to configure OpenFire's retry policy on the database login in order to prevent DoS'ing themselves from the database.
This small change does the following:
- introduces `database.defaultProvider.maxRetries` as the server property that will indicate how many retries can be used before giving up (default: 10 retries)
- introduces `database.defaultProvider.retryDelay` as the server property that will indicate how much OpenFire will wait until retrying the connection (default: 250 ms). (Note: should it be called "retryDelayMs" for better clarity? Seems weird. "retryDelayMsec"?)
- refactored some `if (condition) { …
=> Made connection retry parameters configurable

src/plugins/ofmeet/src/ofmuc.js
Todo: user should be able to upload PDF presentation
=> Adding some inline user documentation

src/java/org/jivesoftware/openfire/group/ConcurrentGroupList.java, src/java/org/jivesoftware/openfire/group/ConcurrentGroupMap.java, src/java/org/jivesoftware/openfire/group/GroupAwareMap.java
Fixes caching issue which prevented users from joining MUC rooms in
certain cases.
=> OF-921: Reset MUC group cache for group changes

src/java/org/jivesoftware/admin/AuthCheckFilter.java, src/java/org/jivesoftware/database/SchemaManager.java, src/java/org/jivesoftware/openfire/audit/spi/AuditManagerImpl.java, src/java/org/jivesoftware/openfire/clearspace/ClearspaceVCardTranslator.java, src/java/org/jivesoftware/openfire/container/PluginServlet.java, src/java/org/jivesoftware/openfire/http/FlashCrossDomainServlet.java, src/java/org/jivesoftware/openfire/ldap/LdapAuthorizationMapping.java, src/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java, src/java/org/jivesoftware/openfire/ldap/LdapManager.java, src/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, src/java/org/jivesoftware/openfire/net/DNSUtil.java, src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/openfire/net/SocketReadingMode.java, src/java/org/jivesoftware/openfire/net/StanzaHandler.java, src/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java, src/java/org/jivesoftware/openfire/pubsub/PubSubModule.java, src/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceManager.java, src/java/org/jivesoftware/openfire/pubsub/PublishedItem.java, src/java/org/jivesoftware/openfire/session/LocalClientSession.java, src/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java, src/java/org/jivesoftware/openfire/user/DefaultUserProvider.java, src/java/org/jivesoftware/openfire/user/JDBCUserProvider.java, src/java/org/jivesoftware/util/LocaleUtils.java, src/java/org/jivesoftware/util/StringUtils.java
This is the more correct API and also has very minor performance benefits.
=> Prefer StringBuilder.append(char) over append(String).

src/java/org/jivesoftware/openfire/FlashCrossDomainHandler.java, src/java/org/jivesoftware/openfire/clearspace/URLUTF8Encoder.java, src/java/org/jivesoftware/util/FastDateFormat.java, src/java/org/jivesoftware/util/LocaleUtils.java, src/java/org/jivesoftware/util/StringUtils.java
And don't use String concatenation within the append() method.
=> Replace StringBuffer with StringBuilder (for performance).

src/java/org/jivesoftware/database/DbConnectionManager.java, src/java/org/jivesoftware/database/SchemaManager.java, src/java/org/jivesoftware/openfire/XMPPServer.java, src/java/org/jivesoftware/openfire/container/PluginIconServlet.java, src/java/org/jivesoftware/openfire/container/PluginManager.java, src/java/org/jivesoftware/openfire/container/PluginServlet.java, src/java/org/jivesoftware/openfire/filetransfer/proxy/DefaultProxyTransfer.java, src/java/org/jivesoftware/openfire/http/FlashCrossDomainServlet.java, src/java/org/jivesoftware/openfire/http/ResourceServlet.java, src/java/org/jivesoftware/openfire/launcher/Launcher.java, src/java/org/jivesoftware/openfire/update/UpdateManager.java, src/java/org/jivesoftware/util/FaviconServlet.java, src/java/org/jivesoftware/util/WebManager.java, src/java/org/jivesoftware/util/XMLProperties.java, src/java/org/jivesoftware/util/cert/SANCertificateIdentityMapping.java, src/test/java/org/jivesoftware/util/TestUtils.java
- Not all resources were closed in finally block (see Launcher, PluginManager, UpdateManager, FaviconServlet, ...)
- Get rid of verbose finally blocks and empty catch blocks, which makes the code more readable.
- Generally, this is the more modern approach to deal with resources.
=> Use try-with-resources statement to properly close resources.

src/java/org/jivesoftware/openfire/container/PluginClassLoader.java
Fix PluginClassLoader load resource path issue   commit:8a4fc5071be2ab3872785c9fd95239b94990e294
When load plugin resource files old commit will load all resource with / path
Like /images/WEB-INF/web.xml
old commit is /web.xml
should be /images/WEB-INF/web.xml
=> Fix PluginClassLoader load resource path issue  

src/java/org/jivesoftware/openfire/MulticastRouter.java, src/java/org/jivesoftware/openfire/commands/AdHocCommandHandler.java, src/java/org/jivesoftware/openfire/disco/IQDiscoItemsHandler.java, src/java/org/jivesoftware/openfire/filetransfer/proxy/FileTransferProxy.java, src/java/org/jivesoftware/openfire/handler/IQLastActivityHandler.java, src/java/org/jivesoftware/openfire/handler/IQOfflineMessagesHandler.java, src/java/org/jivesoftware/openfire/handler/IQPrivacyHandler.java, src/java/org/jivesoftware/openfire/handler/IQPrivateHandler.java, src/java/org/jivesoftware/openfire/handler/IQRegisterHandler.java, src/java/org/jivesoftware/openfire/handler/IQRosterHandler.java, src/java/org/jivesoftware/openfire/handler/IQVersionHandler.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, src/java/org/jivesoftware/openfire/net/DNSUtil.java, src/java/org/jivesoftware/openfire/pep/IQPEPHandler.java, src/java/org/jivesoftware/openfire/vcard/VCardManager.java
This has performance benefits. On my machine it's nearly twice as fast.
=> Use Collections.singleton() where ArrayList has only one element.

src/java/org/jivesoftware/openfire/audit/spi/AuditorImpl.java, src/java/org/jivesoftware/openfire/http/HttpBindServlet.java, src/java/org/jivesoftware/openfire/net/SocketConnection.java, src/java/org/jivesoftware/openfire/nio/ConnectionHandler.java, src/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java, src/java/org/jivesoftware/openfire/update/UpdateManager.java, src/java/org/jivesoftware/util/XMLProperties.java, src/java/org/jivesoftware/util/XMLWriter.java
This is a followup for fcf665a.
=> Use StandardCharsets.UTF_8 with Reader/Writer classes.

src/java/org/jivesoftware/openfire/ldap/LdapManager.java, src/java/org/jivesoftware/util/SimpleSSLSocketFactory.java
This should cover
of-887
of-332
of-926
=> Ldapconnectionfixes

src/java/org/jivesoftware/openfire/container/PluginClassLoader.java
Now Hazelcast plugin work fine.
=> 	Fix PluginClassloader not implement getResources Method

src/java/org/jivesoftware/openfire/container/PluginClassLoader.java
Reverts igniterealtime/Openfire#355
=> Revert "	Fix PluginClassloader not implement getResources Method"

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/AuthFilter.java
Added: Provide the possibility to use a Custom Auth Filter
Fixed: Preflight request will be not blocked by Authentication
Added: Group names in ChatRoom Entity
=> Update REST API Plugin to 1.1.7

src/java/org/jivesoftware/openfire/Connection.java, src/java/org/jivesoftware/openfire/net/SocketConnection.java, src/java/org/jivesoftware/openfire/net/VirtualConnection.java, src/java/org/jivesoftware/openfire/nio/NIOConnection.java
Avoid recursion and synchronization issues
=> OF-881: Simplify connection close semantics

src/java/org/jivesoftware/openfire/roster/RosterManager.java
patch from Ignite Community user andrelab
=> OF-868 update roster cache on userModified

src/plugins/fastpath/src/java/org/jivesoftware/openfire/fastpath/history/ChatTranscriptManager.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/util/XmppDateUtil.java
=> Replace deprecated JiveConstants.XMPP_DELAY_DATETIME_FORMAT usage

src/java/org/jivesoftware/openfire/audit/spi/AuditManagerImpl.java
Supporting property changes in AuditManagerImpl.  See: https://community.igniterealtime.org/thread/57548
=> Adding PropertyListener support to AuditManagerImpl

src/java/com/jivesoftware/tools/selector/BaseSelector.java, src/java/com/jivesoftware/tools/selector/EditionSelector.java, src/java/com/jivesoftware/tools/selector/IncludeSourceSelector.java, src/java/com/jivesoftware/tools/selector/JavaDocSelector.java
The intention here is to eventually remove this code with updated code that does not depend on qdox.
=> Add Legacy Jive build code for eventual removal

src/java/org/jivesoftware/openfire/container/PluginManager.java
NIO.2 is the more modern and faster API and smooths the way for further improvements, e.g. using java.nio.file.WatchService to watch the plugin directory for changes.
This is no critical PR, but nonetheless I think it's a good idea to modernize some code.
Please review carefully, and preferably do some tests before merging, because PluginManager is pretty important!
=> Modernize PluginManager internals with Java NIO.2 File API.

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Fixed an cluster issue by create a chat room
Sry for the whole diff, something went wrong with my IDE
=> Update REST API plugin to 1.2.1

src/java/org/jivesoftware/openfire/net/ServerSocketReader.java
This patch removes the thread pool from the ServerSocketReader, causing
stanzas from a particular S2S session to be processed serially on the same
thread used by the ServerSocketReader.
Each ServerSocketReader currently has a thread to itself, so this is unlikely
to have a serious impact on performance, but does have a very positive impact
on correctness.
=> OF-115 Process S2S stanzas from a session serially

build/build.xml, src/java/org/jivesoftware/openfire/XMPPServer.java
https://community.igniterealtime.org/message/253510
=> Denote master version as 4.0.0 alpha

src/java/org/jivesoftware/openfire/pubsub/Node.java
This NPE caused two issues:
- subscribers are not correctly notified
- change is not persisted to the DB
https://community.igniterealtime.org/thread/57584
=> Fix NPE in Node.java when changing node configuration.

src/java/org/jivesoftware/openfire/http/HttpBindServlet.java
This exception caused serious trouble, e.g.:
- Clients got an invalid/incomplete packet, which breaks them.
- Openfire logged related exceptions like org.jivesoftware.openfire.http.HttpConnectionClosedException: The http connection is no longer available to deliver content
It was caused by calling complete() although the previous write() has not completed (due to its async nature).
I also restructured that the Content-Length header is only set once.
Fixes OF-989.
See also https://community.igniterealtime.org/thread/57622
=> Prevent WritePendingException during delivery of BOSH packets.

src/java/org/jivesoftware/openfire/http/HttpSessionManager.java
When the BOSH manager is restarted, the thread pool (and other components that are used) should be recreated or re-initialized. Currently, restarting the manager won't actually work (as the executor pool isn't accepting any new tasks).
=> OF-992: Re-init on restart

src/web/connection-settings-external-components.jsp, src/web/muc-room-edit-form.jsp
Both found by @tjdurden using BurpSuite
=> Reflected XSS Issues in Admin Console

src/java/org/jivesoftware/openfire/net/TLSWrapper.java
When a peer sends a non-encrypted data where we expected encrypted,
a confusing exception is logged. This commit wraps that exception,
giving a clear explanation.
This typically occurs during a failed TLS handshake, where the peers
should be closing the connection without sending data, but does not
so (typically, the exceptions that are logged indicate that
</failure or </stream is received in plain text).
=> OF-793: Improve exception message

src/java/org/jivesoftware/openfire/IQRouter.java, src/java/org/jivesoftware/openfire/MessageRouter.java, src/java/org/jivesoftware/openfire/PresenceRouter.java
I believe that this fixes the flooding issue that we experienced on igniterealtime.org yesterday.
=> OF-1008: Prevent loops of message failure

src/java/org/jivesoftware/openfire/net/TLSStreamHandler.java
Although not 'properly ended', the handshake failed in an expected manner.
This should be processed as a 'normal' handshake failure (not an exceptional
one).
=> OF-1009: Ignore the exception indicating an error

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/IQRetrieveHandler.java
This PR contains two cherry-picked commits from the original PR here: https://github.com/igniterealtime/Openfire/pull/161
=> OF-856: Cherry Picking of linuschien solution

src/plugins/websocket/changelog.html, src/plugins/websocket/plugin.xml, src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
Optimized configuration for XMPPPacketReader pool; improved exception
handling and reporting.
=> OF-1006: Improve handling for pooled resources

src/i18n/openfire_i18n_en.properties
Add explanation to setup about default admin password
https://igniterealtime.org/issues/browse/OF-1016
=> Add explanation to setup about default admin password

src/java/org/jivesoftware/openfire/server/ServerDialback.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
The S2S (federation) code was not big on logging. This commit introduces new logging, and structures the logged messages. This commit does not introduce functional changes.
=> Improving logging for S2S / dialback

src/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java
When LDAP search returns a multiple result set for a user CN,
we now iterate through the entire set to find a matching user DN.
=> Fixed group population for colliding full names.

build/build.xml, build/lib/ant/web-app_2_3.dtd
Ant (or rather, the XMLTask in our build) attempts to lookup DTDs
online. The build (of plugins) will fail if no internet connectivity
is available. This commit references DTDs locally, allowing Ant to
skip the online lookup.
=> OF-998: Ant should resolve DTDs locally

src/java/org/jivesoftware/openfire/http/HttpBindManager.java
The thread pool that performs processing of data received through the HTTP-based
connections of BOSH (as provided by Jetty) should not have a hardcoded upper bound.
Instead, the pool size should be configurable.
For other connection types, this is managed by properties named as such:
- xmpp.client.processing.threads (client sockets)
- xmpp.multiplex.processing.threads (connection managers)
- xmpp.component.processing.threads (components)
BOSH does have a similar property: httpbind.client.processing.threads
It's value however is not used to configure the amount of worker threads. It is
used to configure the amount of (NIO) acceptors instead. In NIO, acceptor
threads handle network IO, and hand off processing to the worker threads.
There's little benefit in being able to configure the …
=> OF-999: Allow configuration of BOSH worker thread pool

src/java/org/jivesoftware/openfire/net/SocketUtil.java, src/java/org/jivesoftware/openfire/server/ServerDialback.java, src/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java
This builds on https://github.com/igniterealtime/Openfire/pull/476 and further improves logging. Also, code complexity is reduced by removing unused code, and refactoring duplicated code into a utility class.
=> S2S logging

src/java/org/jivesoftware/openfire/server/ServerDialback.java
When a TLS failure occurs during dialback, allow for a non-TLS
based fallback.
=> OF-1009: Allow non-TLS dialback

src/java/org/jivesoftware/openfire/admin/DefaultAdminProvider.java
This class logged to debug on any property change (including properties
that do not relate to the class itself).
=> Remove verbose logging

src/java/org/jivesoftware/openfire/net/StanzaHandler.java, src/java/org/jivesoftware/openfire/session/LocalSession.java, src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java, src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/StreamManagementPacketRouter.java
This started as a fix for OF-1028, but along the way, I refactored quite a bit of the code. I left the individual commits in place, as each of them are pretty isolated (makes for easier reviewing).
=> OF-1028 Stream Management refactoring

src/java/org/jivesoftware/openfire/session/LocalClientSession.java, src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java, src/plugins/websocket/changelog.html, src/plugins/websocket/plugin.xml, src/plugins/websocket/readme.html, src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/StreamManagementPacketRouter.java, src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/WebSocketConnection.java, src/plugins/websocket/src/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
Update dependencies and documentation to prep for pending Openfire 4.0
release.
=> Cleanup websocket plugin

src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
301 - User is banned.
332 - Service is shutting down.
=> OF-1033: Should use the correct status code.

src/java/org/jivesoftware/openfire/PrivateStorage.java
The comment in Line 105: "If the name and namespace of the element matches another" is correct, but the implementation is wrong, it checks "username and namespace" rather than "name and namespace".
=> Fix implementation bug for XEP0049.

src/java/org/jivesoftware/openfire/disco/DiscoItem.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Corrects issue with multiple JIDs sharing a nickname (masquerading)
=> OF-821: Prevent duplicates for MUC item query

src/i18n/openfire_i18n_en.properties, src/web/connection-settings-advanced.jsp, src/web/connection-settings-external-components.jsp, src/web/connection-settings-socket-c2s.jsp, src/web/connection-settings-socket-s2s.jsp, src/web/import-keystore-certificate.jsp, src/web/import-truststore-certificate.jsp, src/web/security-certificate-store-management.jsp
This PR contains non-functional changes only. Text that was hard-coded in the JSP pages got replaced by i18n bundle usage.
=> OF-1004: Apply i18n to admin console

src/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java
Made a search by distinguishedName Active Directory specific
as it is difficult to come up with a generic solution.
=> A fix for OF-1041

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/SessionController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/SessionEntity.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/utils/UserUtils.java
Added: Presence status to the Session Entity. E.g. Online, Away etc.
Fixed: Node parameter in the Session Entity. E.g. Local or Remote
=> REST API Plugin update to version 1.2.2

src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusteredCacheFactory.java, src/plugins/hazelcast/src/web/system-clustering-node.jsp
Ensure cluster listener is properly initialized (and destroyed).
=> OF-1045: Fix NPE in cluster info page

src/java/org/jivesoftware/openfire/OfflineMessageStrategy.java
=> XEP-0016 error messages should set correct from attribute (the sender).

src/java/org/jivesoftware/openfire/muc/MultiUserChatManager.java
Patch submitted by community member lukzie.
=> OF-954: Cleanup MUC rooms for defunct node

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
When a room occupant sends an availability update to a host in an
Openfire cluster, other users cannot join the room from other hosts in
the cluster. The availability update causes the other hosts to lose an
occupant's role and affiliation. New occupants encounter an NPE when
joining and are prevented from joining the room. Specifically, the NPE
occurs when Openfire attempts to send initial presences for current
occupants.
Remote hosts in the cluster lose the occupant's association because the
local room simply broadcasts the presence packet for the occupant's
availability update. Because it is from the client, this packet does not
have the occupant's role or affiliation. The remote hosts treat the
presence packet as the occupant's presence without modification.
This fix changes the order …
=> Cannot join room in a cluster after an availability update.

src/i18n/openfire_i18n_zh_CN.properties
Yes, it is just a file replaced with new one. Can't make contributors to provide proper diff files.
=> Update Chinese Simplified translation (OF-1088)

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/openfire/sasl/SaslProvider.java, src/java/org/jivesoftware/openfire/sasl/SaslServerFactoryImpl.java
This PR fixes various issues that were introduced with my latest PR on the subject: https://github.com/igniterealtime/Openfire/pull/548
=> OF-1092 Various fixes

src/java/org/jivesoftware/openfire/container/PluginServlet.java
Although I'd rather have this case sensitive, that would break backwards compatiblity.
This way, paths with capital letters can be used at least.
=> OF-1105: Plugin servlet mapping should be case insensitive.

build/debian/control, build/debian/rules
untested by me, just a simple s/7/8/ with the debian build files
=> OF-1115 Use Java 8 for Debian packaging

src/java/org/jivesoftware/openfire/keystore/CertificateUtils.java
When validating a certificate chain, the provided chain aught to be ordered. If our
own ordering fails, we should use the first certifcate of the (unordered) chain,
instead of failing completely.
=> OF-1119: Do not depend on ordering of chains

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
This PR combines fixes for OF-1122, OF-1123 and OF-1124, all of which are related, and all of which relate to SASL generically, or the SASL GSSAPI mechanism.
@speedy01 found the original issue (OF-1122). He has tested a local build that included these changes successfully.
=> Various SASL-related changes

.gitignore, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/OccupantEntities.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/OccupantEntity.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java
I added an occupants endpoint for the restAPI plugin. The current participants endpoint only returns participants (no admins, owners,...)
=> Occupants endpoint for restAPI

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/GroupController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/GroupEntity.java
* Added: Add a group with role to a chat room
* Added: Occupants endpoint for chat room
* Fixed: Admin and Member list to group endpoint
=> REST API plugin update to 1.2.3

src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/Conversation.java
Changed so that correct JID is returned
=> Fix for Monitoring Plugin Wrong JID Returned

build/debian/control, build/debian/rules
Will build on bamboo + debian with java7 as well
=> Going back to Java7 for Debian  OF-1115

src/java/org/jivesoftware/util/cache/Cache.java, src/java/org/jivesoftware/util/cache/DefaultCache.java
Hazelcast clustered cache implemented by MapProxyImpl by preventing null
keys and values being added. Also document this behaviour in the Cache
interface.
=> OF-1156: Be consistent with the contents of DefaultCache with the HZ cache

src/plugins/xmldebugger/changelog.html, src/plugins/xmldebugger/plugin.xml, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/DebuggerPlugin.java, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/RawPrintFilter.java
o delay adding socket interceptors until the pluginManager is ready
o Correctly interpret the sent/received messages
=> OF-1152: Ensure that raw XML is logged;

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
- Fixed: Send a presence by affiliation change
=> REST API Plugin update to version 1.2.4

src/java/org/jivesoftware/openfire/commands/admin/GetListActiveUsers.java, src/java/org/jivesoftware/openfire/commands/admin/GetUsersPresence.java, src/java/org/jivesoftware/openfire/commands/admin/group/GetListGroups.java
This PR fixes reading of max_items parameter: currently it silently ignored due to typo in conditional statement.
=> max_items reading is fixed

src/java/org/jivesoftware/openfire/spi/ConnectionManagerImpl.java
Uses the config variable "adminConsole.interface". If empty uses the standard interface configuration.
Useful for situations where the console must be bound to a different network interface than the regular openfire server ports (for example inside a DMZ).
=> OF-1153 Optionally allow binding admin console to separate network interface

src/java/org/jivesoftware/util/cache/Cache.java, src/java/org/jivesoftware/util/cache/DefaultCache.java
This reverts commit d93e8d83ffa2e33403eca044a40a4e3cc80320ae, which was merged in https://github.com/igniterealtime/Openfire/pull/609/
=> Revert "OF-1156: Be consistent with the contents of DefaultCache ..."

src/java/org/jivesoftware/openfire/filetransfer/proxy/FileTransferProxy.java
Instead of one address, the file transfer proxy should lists all
interfaces on which it is reachable (unless configured otherwise).
=> OF-1170 Advertise all proxy addresses

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCUser.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
IQ requests must always be responded to, if only with an error reply. For good
measure, IQ-Ping support was added too.
=> OF-1174: MUC should always respond to IQ requests.

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
Judging from most current implementations (Smack, Conversations,
Gajim), most clients will use the domain name rather than the
fully qualified host name when constructing the DIGEST-MD5
digest-uri. Although this isn't conforming to RFC2831, interop
is of more value than 'doing the right thing'.
This commit makes SASL use the domain name when the mechanism
in play is DIGEST-MD5, and will use the host name for other
mechanisms.
=> OF-477: For DIGEST-MD5, use domain rather than host name.

build/debian/control
completely untested by me, will attempt to find folks to comment on this.
=> OF-1169 Allow java 7 or 8 as requirements for debian

build/build.xml, documentation/dist/changelog.html, src/java/org/jivesoftware/openfire/XMPPServer.java
Lets end the pain that is the daily open_chat/forums complaints about debian 4.0.2 artifacts.  OF-477 remains open and we can turn around a 4.0.4 once somebody wants to own that change...
=> Denote Openfire 4.0.3 Release

src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/util/cache/ClusterExternalizableUtil.java
Optimization ClusterExternalizableUtil writeByteArray performance
=> 	Optimization ClusterExternalizableUtil writeByteArray performance

src/i18n/openfire_i18n_de.properties
Fixed typo in german documentation
=> fixed i18n typo for de

build/eclipse/classpath
Adds the built "libs/merge/jsmpp.jar" to the eclipse project dependencies.
=> Add missing jsmpp jar to satisfy eclipse project dependencies for build.

src/web/connection-settings-socket-s2s.jsp
previously setting "Allowed to Connect" option was a NOOP
=> OF-1209 enable whitelist/blacklist functionality on admin console

src/web/setup/setup-admin-settings.jsp
on setup password configuration page.
=> OF-927 make continue button default enter action

src/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceManager.java
OF-955 updated the HSQL library and it introduced a JDBC requirement that
executeBatch() calls actually have batched items to do.  It appears there
is no API available to check for if batched statements have been added, so
we hack in a simple sentinal to safegaurd calls to `executeBatch`.  Thankfully,
only PubSubPersistenceManager.java uses this API.  Otherwise, an option is to
set `allow_empty_batch` on the connection parameters.
=> OF-1229 Safeguard JDBC.executeBatch() calls on empty batch

src/plugins/monitoring/src/i18n/monitoring_i18n.properties, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/ConversationEvent.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/ConversationManager.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/GroupConversationInterceptor.java, src/plugins/monitoring/src/web/archiving-settings.jsp
in the settings there is now a switch allowing to add complete stanza to
the archive for muc conversations
=> add possibility to store complete stanza in archive

src/plugins/monitoring/src/i18n/monitoring_i18n.properties, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/ConversationEvent.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/ConversationManager.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/GroupConversationInterceptor.java, src/plugins/monitoring/src/web/archiving-settings.jsp
Reverts igniterealtime/Openfire#668
=> Revert "add possibility to store complete stanza in archive"

src/java/org/jivesoftware/openfire/auth/ScramUtils.java, src/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java
hope resolve https://issues.igniterealtime.org/projects/SPARK/issues/SPARK-1803
=> SPARK-1803 Can't use usernames with non-latin symbols

src/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, src/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
This PR adds extension points to MUC, allowing both Services and Rooms to be extended by plugins (and other code).
=> OF-1213 Add extension points to MUC

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
as oracle database cannot use distinct modifier on clob columns, some
statments must be adjusted so they don not fail on oracle database
=> adjust sql statements to work properly with oracle database

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
as oracle 12.0 and below do not know the keywords limits and offset the
expression has to be adjusted to work with those versions of the oracle
database
=> adjust limit expression for oracle 12.0 and below

build/installer/openfire.install4j
OF-1217, this change was created by the install4j GUI to update the config
to the current-release (6.1.3) schema.
=> Update schema for install4j configuration

src/plugins/monitoring/src/database/monitoring_oracle.sql, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
Collected pathes from "hammington", which were supplied as PRs against 4.0.
=> OF-1212 Oracle database issues

src/java/org/jivesoftware/openfire/ldap/LdapAuthorizationPolicy.java
Patch by Antonio Petrelli, *untested by me*
=> OF-355 ldap.authorizeField is ignored in LdapAuthorizationPolicy

src/database/openfire_db2.sql, src/database/openfire_hsqldb.sql, src/database/openfire_mysql.sql, src/database/openfire_oracle.sql, src/database/openfire_postgresql.sql, src/database/openfire_sqlserver.sql, src/database/openfire_sybase.sql, src/database/upgrade/24/openfire_db2.sql, src/database/upgrade/24/openfire_hsqldb.sql, src/database/upgrade/24/openfire_mysql.sql, src/database/upgrade/24/openfire_oracle.sql, src/database/upgrade/24/openfire_postgresql.sql, src/database/upgrade/24/openfire_sqlserver.sql, src/database/upgrade/24/openfire_sybase.sql, src/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java, src/java/org/jivesoftware/openfire/muc/spi/ConversationLogEntry.java, src/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
PR request made for easy comparison to #668, without prejudice.
=> OF-817 Persist entire MUC stanza

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
=> OF-1240 Disallow empty nicknames in rooms with reserved nicknames

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/admin/AuthCheckFilter.java, src/java/org/jivesoftware/openfire/container/PluginServlet.java, src/plugins/clientControl/src/web/client-features.jsp, src/plugins/clientControl/src/web/permitted-clients.jsp, src/plugins/monitoring/src/web/archiving-settings.jsp, src/web/audit-policy.jsp, src/web/group-summary.jsp, src/web/logviewer.jsp, src/web/security-certificate-details.jsp, src/web/server-db-stats.jsp, src/web/setup/setup-admin-settings.jsp
This closes off several issues found by Simon Waters (Surevine Ltd).
=> OF-942 et passim

src/plugins/monitoring/src/database/monitoring_hsqldb.sql
related to upgrade of HSQL done with OF-955 PR#679
=> OF-1247 HSQL VARBINARY now requires length

src/java/org/jivesoftware/openfire/group/GroupManager.java
untested by me, patch by @aberenguel
=> OF-867 Wrong key in groupMetaCache evict

src/database/openfire_db2.sql, src/database/openfire_hsqldb.sql, src/database/openfire_mysql.sql, src/database/openfire_oracle.sql, src/database/openfire_postgresql.sql, src/database/openfire_sqlserver.sql, src/database/openfire_sybase.sql, src/database/upgrade/25/openfire_db2.sql, src/database/upgrade/25/openfire_hsqldb.sql, src/database/upgrade/25/openfire_mysql.sql, src/database/upgrade/25/openfire_oracle.sql, src/database/upgrade/25/openfire_postgresql.sql, src/database/upgrade/25/openfire_sqlserver.sql, src/database/upgrade/25/openfire_sybase.sql, src/java/org/jivesoftware/database/SchemaManager.java, src/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java, src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/MucMamPersistenceManager.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep/AbstractIQHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep/AbstractXepSupport.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/IQListHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/IQRetrieveHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/Xep0136Support.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/Xep0313Support.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/Xep0313Support1.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/ConversationManager.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/plugin/MonitoringPlugin.java
Tidied:
* Lots of bugfixes to 1:1 MAM here as well.
* Some of this patch seems to have slipped into the existing master (basically the database upgrade scripts contain the new fields already).
* As per discussions, the MAM-MUC code is actually hitting the core's database, not the Monitoring Plugin's MUC tables, so we can move it when the 1:1 MAM code moves.
=> OF-1246 MAM for MUC

build/build.xml, documentation/dist/changelog.html, src/java/org/jivesoftware/openfire/spi/XMPPServerInfoImpl.java
Sorry that the changelog diff was a complete rewrite :(
=> Denote Openfire 4.1.0 Release

src/plugins/clientControl/changelog.html, src/plugins/clientControl/plugin.xml, src/plugins/clientControl/src/i18n/clientcontrol_i18n.properties, src/plugins/clientControl/src/web/client-features.jsp
This fix applies to the Client Control plugin.
=> OF-1260: Improve CSRF error message

documentation/dist/README.html
Version and build date are already in the changelog. Other than that Readme is static. Fixed a few links and removed cheerful thanking. When user looks at it online, he hasn't yet downloaded anything. When he has installed it already, thanking for downloading seems out of place.
=> OF-1270 fix Readme

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep/AbstractXepSupport.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/Result.java
This adds attributes mandated by MAM, by missing from the rendering in the
PacketExtension.
=> OF-1288 Add missing attributes

src/java/org/jivesoftware/openfire/auth/DefaultAuthProvider.java
The recursion logic here was all wrong.
This:
1) Fixes it.
2) Adds a guard
3) Tries to pretend it was someone else's fault.
=> OF-1278 Do not be such an idiot while recursing

src/java/org/jivesoftware/openfire/net/SASLAuthentication.java
Agreed with the suggestion in the bug report - this should be OR instead of AND. The logging message even says as much.
=> OF-1195 Correct SCRAM supported logic

src/plugins/xmldebugger/changelog.html, src/plugins/xmldebugger/plugin.xml, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/DebuggerPlugin.java, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/RawPrintFilter.java
Causes the plugin to print the remote address, as well as less 'garbage' (compressed and/or encrypted data).
=> OF-1299 / OF-1300: Fixes for XML Debugger plugin.

src/web/muc-room-edit-form.jsp
This bug may have existed for 9 years :)
=> OF-1292 fix NPE when canceling new room creation on admin console

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/net/SASLAuthentication.java, src/java/org/jivesoftware/util/JiveGlobals.java, src/web/reg-settings.jsp
The latter depends on (and is a showcase for) the former, which is why I combined them in one PR.
=> Fixes for OF-1311 and OF-1312

src/plugins/motd/changelog.html, src/plugins/motd/plugin.xml, src/plugins/motd/src/i18n/motd_i18n.properties, src/plugins/motd/src/java/org/jivesoftware/openfire/plugin/MotDPlugin.java, src/plugins/motd/src/web/motd-form.jsp
In an annoying quest to reproduce a bug related to JSTL and plugins I completely redid the MoTD plugin admin console page. I added CSRF protection to justify my changes.
Never did reproduce that bug...
=> OF-1313: Add CSRF protection to the MoTD plugin.

src/plugins/dbaccess/src/web/db-access.jsp
Straightforward failure to escape in this debugging plugin.
=> OF-1272 Close XSS in dbaccess plugin

src/java/org/jivesoftware/openfire/pubsub/LeafNode.java
patch contributed by Evgeny Kuklo
=> OF-1310 Fix removal of last item of pubsub node

build/installer/openfire.install4j
Fix filename for x64 installer
=> Install4j- Correct filename for x64

src/i18n/openfire_i18n_en.properties, src/web/group-edit.jsp
This commit adds some UX improvements to the 'edit group' page on the admin console.
=> OF-1347: Improve Admin Console Group Edit page

documentation/docs/install-guide.html, documentation/docs/upgrade-guide.html
Should be merged when 4.1.5 is released.
=> OF-1343 update docs about new windows service behavior

src/java/org/jivesoftware/openfire/nio/NIOConnection.java
=> Gracefully close the stream with </stream:stream>

src/plugins/candy/plugin.xml, src/plugins/candy/src/i18n/candy_i18n.properties, src/plugins/inverse/plugin.xml, src/plugins/inverse/src/i18n/inverse_i18n.properties
We should aim to put the webclients menu item at the top level to enable each individual web client have a menu level to use for other app features beyond settings
=> OF-1359: PR to elevate webclients to top level menu in openfire admin UI

src/i18n/openfire_i18n_en.properties
This i18n string is only used on the admin console (login.jsp)
=> OF-1262 correct error message on failed admin console login

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/handler/IQRegisterHandler.java, src/java/org/jivesoftware/openfire/http/HttpSession.java, src/web/reg-settings.jsp
There's no point in offering in-band registration when the user provider disallows any modifications.
=> OF-1369: Skip IBR when readonly user provider

src/web/http-bind.jsp
No functional changes intended.
=> Admin console: apply JSTL to http-bind page.

src/plugins/hazelcast/changelog.html, src/plugins/hazelcast/plugin.xml, src/plugins/hazelcast/pom.xml, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/OutgoingServerSessionTask.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteOutgoingServerSession.java, src/plugins/hazelcast/src/java/org/jivesoftware/openfire/plugin/session/RemoteSessionTask.java
This is a fix for API changes introduced with the fix for OF-1309.
=> OF-1309: Make Hazelcast plugin use new API

src/java/org/jivesoftware/util/S2STestService.java
Added some extra field details on s2s certificates.
=> OF-159: Add an s2s testing feature

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/interceptor/InterceptorManager.java, src/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java, src/java/org/jivesoftware/openfire/server/RemoteServerManager.java, src/java/org/jivesoftware/util/S2STestService.java, src/resources/jar/admin-sidebar.xml, src/web/connection-settings-socket-s2s.jsp, src/web/server-connectiontest.jsp
I'm sorry for the whitespace commit, but let's not add more new files with different line-endings or indentation. Individual commits will expose the exact changes.
@richmidwinter Could you consider installing http://editorconfig.org/ for your IDE / editor of choice? It'll automatically set-up the little bit of code convention that we have (tabs and line-endings)
=> OF-159: Various tweaks

src/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java
getIterations() threw an exception which
caused early termination of the SASL exchange.
Spotted by Phil Roberts of Surevine Ltd.
=> OF-1381 Close SCRAM enumeration attack

src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java
Suggested patch by David Liffmann
=> OF-1304 Correct query builder syntax

src/plugins/userImportExport/changelog.html, src/plugins/userImportExport/plugin.xml, src/plugins/userImportExport/pom.xml, src/plugins/userImportExport/src/java/org/jivesoftware/openfire/plugin/OpenfireExporter.java
With the default import, users where not created when it was possible.
=> UserImportExport plugin: users where not created

build/installer/openfire.install4j
* related to OF-1383 work on java9 support
* also updated setting to set min jre version to 1.7
=> allow Install4j 7.0.3 to update config schema

documentation/docs/upgrade-guide.html
Documentation update which should have been done along with proposing x64 installers. This only covers Windows x64 as i don't have much experience with RPM or other Linux versions.
=> OF-1356 add section for Windows on x86 to x64 move

.editorconfig, src/bin/openfire.bat
Also, edit the .editorconfig file so .bat files keep their CRLF endings.
=> OF-1410: Allow the openfire.bat file to be run from anywhere.

src/web/system-cache.jsp
Also remove unnecessary variable assignment
=> OF-1409: Ensure that clearing the cache is audited.

src/web/system-cache.jsp
Screen shot of extra information:
=> OF-1408: Display count of entries/hits/misses on Cache summary screen

src/web/muc-room-edit-form.jsp
When creating a new MUC room, using an invalid name (invalid JID) should not cause an ugly
stacktrace to be displayed.
=> OF-394: Show proper error on invalid MUC room name.

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, src/web/session-details.jsp
Cut/paste error in removeClientRoute() caused old sessions to be
kept around.
In order to help debug this, I also added some detailing to
session-details.jsp which turned out not to be needed. But it
might prove useful/interesting.
=> OF-1429 Fix client route removal

src/java/org/jivesoftware/openfire/keystore/CertificateStoreWatcher.java
This commit prevents file changes from being applied while the file is still being modified.
=> OF-1373: Wait until file modifications are complete.

src/plugins/bookmarks/src/i18n/bookmarks_i18N_ru_RU.properties
=> Translation into Russian

src/plugins/jingleNodes/src/i18n/jinglenodes_i18n_ru_RU.properties
=> Translations into Russian

src/java/org/jivesoftware/database/EmbeddedConnectionProvider.java
I just spotted that the OF-1419 change to commons-dbcp change completely broke the embedded database provider which relied on Proxool via a Class.forName("org.logicalcobwebs.proxool.ProxoolDriver") which meant it compiled just fine.
=> OF-1419 revisited: ensure that the embedded database works too.

src/plugins/fastpath/changelog.html, src/plugins/fastpath/plugin.xml, src/plugins/fastpath/src/java/org/jivesoftware/openfire/fastpath/FastpathPlugin.java, src/plugins/fastpath/src/java/org/jivesoftware/xmpp/workgroup/Workgroup.java
Fixed minor issues blocking ofmeet working with fastpath.
See https://issues.igniterealtime.org/browse/OF-1461
=> OF-1461 - Making fastpath plugin compatible with openfire meetings

src/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
Note; this only checks for *currently* connected servers/components to subscribe. The assumption is that a connection must have been made in order to send the subscription request. 
This removes the need to send a disco#info back to the requester to confirm their identity (cf. remote users).
Authentication/Authorisation is implicit by the fact that the remote server has successfully connected.
=> Allow remotely connected servers to subscribe to local pubsub nodes

src/java/org/jivesoftware/openfire/keystore/TrustStore.java
So the full stack trace can be displayed. I also fixed the typo (Unkown -> Unknown).
=> ", e" added like for the other "Log.warn"

src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
When a client tells us that it received an amount of stanzas that's greater than the number of stanzas
that we've sent it, the stream should be terminated. Similarly, we should not allow a client to resume
a stream when it tells us it received more data on the old stream than what we've sent it.
=> OF-1471: Terminate upon invalid Stream Management data.

documentation/docs/database.html, src/web/setup/setup-datasource-standard.jsp
=> OF-1492 remove brackets from default JDBC connection strings

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/pom.xml, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/JdbcPersistenceManager.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/impl/MucMamPersistenceManager.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0059/XmppResultSet.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/IQListHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/IQPrefHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0136/IQRetrieveHandler.java, src/plugins/monitoring/src/java/com/reucon/openfire/plugin/archive/xep0313/IQQueryHandler.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/ConversationManager.java, src/plugins/monitoring/src/java/org/jivesoftware/openfire/archive/cluster/HasWrittenAllDataTask.java
I'm making this PR as a call for feedback. 
The fix for OF-1200 is not complete, and will starve the client thread pools under even moderate amounts of clients that concurrently perform MAM requests - which is dangerous. The fix does hint at what direction I plan to take this though.
The other commits should be workable, I think, but can perhaps be improved. Feedback, please!
=> OF-1200 OF-1486 OF-1487 OF-1489: Monitoring plugin fixes

src/plugins/callbackOnOffline/plugin.xml
I think this should fix version showing in Admin Console. I haven't changed the version itself as this is a trivial fix. But it would be nice to have 1.2.0 version back on the site instead of 1.0 which for some reason is showing again on Plugins page.
=> OF-1502 fix version format

src/i18n/openfire_i18n_en.properties, src/java/org/jivesoftware/openfire/keystore/IdentityStore.java, src/java/org/jivesoftware/util/CertificateManager.java, src/web/security-keystore-signing-request.jsp, src/web/security-keystore.jsp
Note: this PR builds on the changes in #1029 (maybe merge that first?)
=> OF-1495: Add subject alternative names to certs and CSRs

src/java/org/jivesoftware/openfire/muc/spi/LocalMUCRole.java
=> OF-1504: Caching the session will prevent carbons.

src/java/org/jivesoftware/openfire/auth/HybridAuthProvider.java
Although not in line with that what has been stated in this issue, this
fixes the possibility to change passwords in the GUI for those users
which are stored in the DefaultUserProvider.
=> OF-1345 Can't create/reset passwords when using HybridAuthProvider

documentation/docs/install-guide.html
Add Firewall section into installation guide.
=> OF-1519 add info about firewall

src/java/org/jivesoftware/openfire/muc/spi/IQOwnerHandler.java, src/java/org/jivesoftware/openfire/pep/IQPEPHandler.java, src/java/org/jivesoftware/openfire/pubsub/CollectionNode.java, src/java/org/jivesoftware/openfire/pubsub/LeafNode.java, src/java/org/jivesoftware/openfire/pubsub/Node.java, src/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java, src/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java, src/java/org/jivesoftware/openfire/pubsub/PubSubModule.java
This PR includes a new feature, as well as a bugfixes.
=> OF-1511 OF-1513 OF-1514: Pubsub / PEP changes

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/pom.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java
Fixed: That created rooms were not propagated to other nodes OF-1535
Fixed: Missing documentation for "new" json mapping
=> REST API update to 1.3.1

src/i18n/openfire_i18n_en.properties, src/i18n/openfire_i18n_ja_JP.properties, src/i18n/openfire_i18n_pt_PT.properties, src/i18n/openfire_i18n_sk.properties, src/plugins/clientControl/src/i18n/clientcontrol_i18n.properties, src/plugins/clientControl/src/i18n/clientcontrol_i18n_zh_CN.properties, src/plugins/monitoring/src/i18n/monitoring_i18n.properties, src/plugins/monitoring/src/i18n/monitoring_i18n_pt_BR.properties, src/plugins/monitoring/src/i18n/monitoring_i18n_zh_CN.properties, src/plugins/search/src/i18n/search_i18n.properties, src/plugins/search/src/i18n/search_i18n_lt.properties
Changed 'propertis' to 'properties'.
=> Fix typos in comments

src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/DebuggerPlugin.java, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/InterpretedXMLPrinter.java, src/plugins/xmldebugger/src/web/debugger-conf.jsp
NB. Also included some IntelliJ-suggested code tidy-ups
=>  OF-1551: Allow the admin UI to enable/disable the interpreted debugger

src/java/org/jivesoftware/openfire/container/PluginMonitor.java
Two properties are added that can be used to configure the plugin monitor:
- 'plugins.loading.monitor.enabled' controls if monitoring is enabled (true by default)
- 'plugins.loading.monitor.interval' defines the scan interval, in seconds (20 by default)
=> OF-1544: Make plugin monitor configurable.

pom.xml, src/plugins/pom.xml
This PR adds no functionality to the server, but makes it easy to view current and out of date dependencies.
e.g. to view current dependencies ...
```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.igniterealtime.openfire:xmppserver >---------------
[INFO] Building Core XMPP Server 4.3.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ xmppserver ---
[INFO] org.igniterealtime.openfire:xmppserver:jar:4.3.0-SNAPSHOT
[INFO] +- org.igniterealtime.openfire:dbutil:jar:4.3.0-SNAPSHOT:compile
[INFO] +- org.igniterealtime.openfire:i18n:jar:4.3.0-SNAPSHOT:compile
[INFO] +- org.igniterealtime:tinder:jar:1.3.0:compile
[INFO] |  \- …
```
=> Add ability to view current and out of date dependencies

src/java/org/jivesoftware/openfire/session/LocalClientSession.java, src/java/org/jivesoftware/openfire/streammanagement/StreamManager.java, src/java/org/jivesoftware/openfire/websocket/XmppWebSocket.java
Note; I've also moved the detection of enabled/disabled to a single place, rather than in two places across the code (hopefully we'll be able to re-enable it RSN),
=> OF-1563: Disable stream management by default

src/java/org/jivesoftware/openfire/crowd/CrowdManager.java, src/java/org/jivesoftware/openfire/update/UpdateManager.java, src/java/org/jivesoftware/util/FaviconServlet.java, src/web/index.jsp, xmppserver/pom.xml
Notes;
1. I've updated the display of the RSS feed in index.html to use the same proxy that is used for the (server/plugin) UpdateManager (update.proxy.host / update.proxy.port)
2. I've tested both the RSS feed and UpdateManager with and without a proxy, that's working fine. 
3. I've tested the FavIconServlet (which does not need a proxy) and that's working fine. 
4. I've not tested the CrowdManager, which allows the use of Atlassian Crowd as a UserProvider, AdminProvider, etc. etc., at all.
=> OF-1556: Update code to use Apache HttpClient 4.5.5

src/plugins/xmldebugger/changelog.html, src/plugins/xmldebugger/plugin.xml, src/plugins/xmldebugger/pom.xml, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/DebuggerPlugin.java, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/InterpretedXMLPrinter.java, src/plugins/xmldebugger/src/java/org/jivesoftware/openfire/plugin/RawPrintFilter.java, src/plugins/xmldebugger/src/web/debugger-conf.jsp
NB. Also removed logged of empty messages, and made the Interpreted logger be consistent with the name of `RECV`d messages.
=> OF-1571: Ensure RECVd messages are logged

distribution/src/installer/openfire.install4j, distribution/src/installer/rpmscripts/post_install.sh, distribution/src/installer/rpmscripts/pre_uninstall.sh
WIP, will make some commentary here as I make progress.
=> OF-1532 continue work on Linux RPM and DEB install4j media files

src/java/org/jivesoftware/openfire/muc/spi/IQMUCSearchHandler.java
This should fix the referenced ticket: OF-1499. Instead of zero being displayed when there are is no max number of users, "unlimited" will display.
=> OF-1499 display text for no max users instead of zero.

xmppserver/pom.xml
When property xmpp.jmx.enabled is true, at startup we have an error: 
```
2018.04.24 08:55:49 ERROR [pool-4-thread-1]: org.jivesoftware.openfire.container.PluginMonitor - An unexpected exception occurred:
java.lang.NoClassDefFoundError: org/apache/mina/integration/ognl/IoServicePropertyAccessor
at org.apache.mina.integration.jmx.ObjectMBean.<clinit>(ObjectMBean.java:114)
at org.jivesoftware.openfire.spi.MINAConnectionAcceptor.configureJMX(MINAConnectionAcceptor.java:294)
at org.jivesoftware.openfire.spi.MINAConnectionAcceptor.start(MINAConnectionAcceptor.java:112)
at org.jivesoftware.openfire.spi.ConnectionListener.start(ConnectionListener.java:216)
at org.jivesoftware.openfire.spi.ConnectionManagerImpl.startListeners(ConnectionManagerImpl.java:298)
at …
```
=> Add mina ognl dependency.

src/plugins/restAPI/changelog.html, src/plugins/restAPI/plugin.xml, src/plugins/restAPI/pom.xml, src/plugins/restAPI/readme.html, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/RESTServicePlugin.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/MUCRoomController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/controller/UserServiceController.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCRoomMessageEntities.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/entity/MUCRoomMessageEntity.java, src/plugins/restAPI/src/java/org/jivesoftware/openfire/plugin/rest/service/MUCRoomService.java, src/plugins/restAPI/src/web/rest-api.jsp
Add MUC Room Get Chat History endpoint
Add logging for MUCRoomController and UserServiceController
=> OF-1585 Add MUCRoom Get Chat History endpoint

src/plugins/monitoring/changelog.html, src/plugins/monitoring/plugin.xml, src/plugins/monitoring/pom.xml, src/plugins/monitoring/src/java/org/jivesoftware/openfire/reporting/graph/GraphEngine.java
Commented setter to null which is according to latest javadoc not allowed.
=> OF-1578 Monitoring small Graphs Not Being Generated.

Dockerfile
While switching from ant to maven the target path have changed.
=> fixed path to distribution target

src/plugins/monitoring/readme.html
This change doesn't warrant new version. So current jar can just be replaced with new one and readme will be replaced on the site for new users to see this info.
=> OF-1593 mention MAM in readme

src/plugins/externalservicediscovery/changelog.html, src/plugins/externalservicediscovery/plugin.xml, src/plugins/externalservicediscovery/pom.xml, src/plugins/externalservicediscovery/src/web/external-service-discovery-config.jsp
Also updates version number to denote new release of this plugin.
=> OF-1595 ext service disco adminconsole udp bug

src/java/org/jivesoftware/openfire/net/VirtualConnection.java
The notification will trigger some shutdown procedures that, amongst other things,
check what type of session (eg: anonymous) is being closed. This check depends on the
session still being available.
For that reason, it's important to first notify the listeners, and then close the
session - not the other way around.
This fixes a very visible bug where MUC users would remain in the MUC room long after
their session was closed. Effectively, the bug prevents the MUC room from getting a
presence update to notify it that the user logged off.
=> OF-1596: Allow connections to properly close

src/plugins/fastpath/changelog.html, src/plugins/fastpath/src/java/org/jivesoftware/openfire/fastpath/commands/UpdateWorkgroup.java, src/plugins/fastpath/src/java/org/jivesoftware/xmpp/workgroup/WorkgroupManager.java, src/plugins/fastpath/src/web/workgroup-queues.jsp
I am accessing Fastpath admin remotely in the chat api plugin to manage workgroups. This PR adds the missing code to update an existing workgroup with new members.
=> Added new ad-hoc command - Update Workgroup

xmppserver/src/main/webapp/server-locale.jsp
Also fix up a few trivial items that IntelliJ picked up
=> OF-1632: Ensure form is UTF-8 encoded so the form can be properly parsed

src/plugins/httpFileUpload/pom.xml, src/plugins/httpFileUpload/readme.html
Also clear up some IntelliJ suggested inspections.
=> OF-1463: Include a comment about http-bind being enabled.

xmppserver/src/main/webapp/setup/ldap-server.jspf, xmppserver/src/main/webapp/setup/ldap-user.jspf, xmppserver/src/main/webapp/setup/setup-ldap-server.jsp
Also fix up some of the IntelliJ inspections
=> OF-1600: Correct XSS issues when setting up LDAP

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginServlet.java
Also clean up some tech debt, including replace the code to detect MIME type with URLConnection.guessContentTypeFromName()
=> OF-1584: Only fail a single servlet at a time

xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java, xmppserver/src/main/java/org/jivesoftware/util/XMLProperties.java, xmppserver/src/main/webapp/setup/setup-finished.jsp
Also fix some IntelliJ suggested inspections.
=> OF-1569: Let the admin know if openfire.xml can't be written to.

distribution/src/bin/extra/embedded-db-viewer.bat, distribution/src/bin/extra/embedded-db-viewer.sh
The names of the JAR files have changed, so use a wildcard instead. 
Also use CR/LF as it's a BAT file
=> Fix embedded-db-viewer

xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/OccupantLeftEvent.java
When an occupant left an XMPP node, the remote XMPP node may remove
a wrong entry by nickname when an occupant had multiple sessions
joining a room.
=> Remove an occupant by nickname with matching full JID.

distribution/src/database/openfire_mysql.sql, xmppserver/src/main/java/org/jivesoftware/database/DbConnectionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/roster/DefaultRosterItemProvider.java
Tested on MySql 8, PostgreSQL 9.6
=> OF-1630: Properly escape rank to allow support for MySQL 8.x

starter/src/main/java/org/jivesoftware/openfire/starter/ServerStarter.java
(as the WEB-INF/lib folder no longer exists in the Maven world)
=> Remove spurious warning logged by ServerStarter

plugins/search/pom.xml
(so that the right version is stored in the plugin.xml!)
=> Add the version number to the pom.xml

distribution/pom.xml, distribution/src/assembly/basic-distribution.xml
(once as starter-[version].jar, once as startup.jar)
=> Stop startup.jar from being deployed twice

xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PublishedItem.java
Also correct the min JDK version in pom.xml when using JDK8
=>  OF-1642: Ensure a published item is properly persisted

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
Two commits
https://github.com/igniterealtime/Openfire/commit/6b02e249711e0a5e5a42fc0ff4c6187c990e9069 - encapsulates the contents of the groupMetaCache better
https://github.com/igniterealtime/Openfire/commit/c6e320f5ba56daaa22586fe0a72625195bd0a24d - stores the group names as a HashSet not an ArrayList
=> OF 1589 revisited

xmppserver/src/main/java/org/jivesoftware/util/Version.java, xmppserver/src/test/java/org/jivesoftware/util/VersionTest.java
=> OF-1671: Ensure Openfire can copy with a non-snapshot four digit version

src/java/org/jivesoftware/openfire/pubsub/PublishedItem.java, xmppserver/pom.xml
Also correct the min JDK version in pom.xml when using JDK8
=> OF-1642: Ensure a published item is properly persisted (4.2 backport)

build/debian/openfire.init.d
Signed-off-by: akrherz <akrherz@iastate.edu>
=> OF-1676 define -Dlog4j.configurationFile for debian

documentation/protocol-support.html, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCUser.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/stanzaid/StanzaIDUtil.java, xmppserver/src/test/java/org/jivesoftware/openfire/stanzaid/StanzaIDUtilTest.java
This commit adds a generic framework that implements XEP-0359 Unique and Stable Stanza IDs,
and applies that framework to MUC rooms.
=> OF-1673: Add support for XEP-0359 (MUC)

xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java
Make sure that 'SENT' and 'RECV' are recorded in the same place.
=> OF-1672: Consistently log BOSH debug messages.

xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterManager.java
and ClusterManager#isSeniorClusterMemberOrNotClustered()
which are hopefully largely self-explanatory.
=> Add ClusterManager#waitForClusteringToStart()

xmppserver/src/main/java/org/jivesoftware/openfire/stanzaid/StanzaIDUtil.java
This fixes a XMPP-spec violation, introduced in Openfire 4.3.1.
=> OF-1683: Fix for XEP-0359

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java, xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheWrapper.java, xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultCache.java
Note; I've checked every place that a reference to Cache.keySet(), entrySet() or values() is referenced - and modified the only place I could find.
It's possible that the code takes a Cache and stores it in a Map - but there are too many references to Map.keySet(), entrySet() or values() to check, so hopefully that hasn't happened.
=> Default cache improvements

xmppserver/src/main/java/org/jivesoftware/openfire/nio/XMLLightweightParser.java
The suggestions at https://issues.igniterealtime.org/projects/OF/issues/OF-1323 make sense, but I'm not sure how much of a practical difference this actually makes. I've actually made the similar sort of changes twice - and run some tests locally and it all seems to be OK, but treat this one with caution!
=> OF-1323: Trivial performance optimisation

xmppserver/src/main/java/org/jivesoftware/openfire/commands/admin/user/DeleteUser.java
https://xmpp.org/extensions/xep-0133.html#delete-user describes an ad-hoc command that is used to delete users. Our old implementation allows for just one user to be deleted, while the XEP defines that multiple JIDs should be allowed.
=> OF-1691: XEP-0133's "Delete User" should use jid-multi

.travis.yml, runIntegrationTests
My premature, because untested, PR, based on the work by @guusdk. This is an alternative to #1292.
=> Add Smack integration tests

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceManager.java
Fix the SQL syntax error for sqlserver and oracle.
=> PubSubPersistenceManager - Incorrect syntax near the keyword 'LEFT'

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/admin/LdapUserProfile.java, xmppserver/src/main/java/org/jivesoftware/database/bugfix/OF1515.java, xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServerInfo.java, xmppserver/src/main/java/org/jivesoftware/openfire/admin/AdminManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/admin/JDBCAdminProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/AuthToken.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/DefaultAuthorizationMapping.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/DefaultAuthorizationPolicy.java, xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/keystore/IdentityStore.java, xmppserver/src/main/java/org/jivesoftware/openfire/lockout/LockOutManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/security/SecurityAuditManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/XMPPServerInfoImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/user/UserManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/vcard/VCardManager.java, xmppserver/src/main/webapp/setup/ldap-group.jspf, xmppserver/src/main/webapp/setup/setup-admin-settings.jsp, xmppserver/src/main/webapp/setup/setup-host-settings.jsp, xmppserver/src/main/webapp/setup/setup-profile-settings.jsp
This now means all system properties that are set on a fresh install are now migrated to a SystemProperty
=> More sys props

xmppserver/src/main/java/org/jivesoftware/openfire/update/AvailablePlugin.java, xmppserver/src/main/webapp/available-plugins.jsp
=> OF-1710: Display release date on the available plugins page

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java
Two plugins are considered the same if the share the same
JAR/WAR file name (ignoring case) or the same <name> tag in the plugin.xml
=> OF-1715: Only allow a "plugin" to be loaded once.

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
(which could be outside of the authors direct control)
=> OF-1719: Introduce new API that is less sensitive to file renames

xmppserver/src/main/java/org/jivesoftware/openfire/update/DownloadStatus.java, xmppserver/src/main/java/org/jivesoftware/openfire/update/PluginDownloadManager.java, xmppserver/src/main/webapp/plugin-admin.jsp
Now shows old and new version:
=> OF-1695: Show update to plugin version when it is updated

plugins/pom.xml, pom.xml, xmppserver/pom.xml
Also take the opportunity to tidy up the pom.xml for the MINA artifacts
(need to make one final check before merging)
=> OF-1718: Update to Mina 2.1.1 to resolve issues with MINA compression filter

xmppserver/src/main/java/org/jivesoftware/openfire/OfflineMessageStrategy.java, xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/component/ExternalComponentManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/component/InternalComponentManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/lockout/LockOutEventDispatcher.java, xmppserver/src/main/java/org/jivesoftware/openfire/mediaproxy/Echo.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCEventDispatcher.java, xmppserver/src/main/java/org/jivesoftware/openfire/privacy/PrivacyListManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/roster/RosterEventDispatcher.java, xmppserver/src/main/java/org/jivesoftware/openfire/user/PresenceEventDispatcher.java, xmppserver/src/main/java/org/jivesoftware/openfire/vcard/VCardEventDispatcher.java
I found and replaced all instances with Exception (try-catch) pattern
=> OF-1744 Failing listener should not prevent others from executing

xmppserver/pom.xml
Was hoping this would fix https://issues.igniterealtime.org/browse/OF-1652 but sadly not.
=> OF-1747: Update to Rome 1.12.0

xmppserver/src/main/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java
NB. If it can't be renamed (ten attempts are made) this will shut down Openfire
=> OF-1647: Rename the legacy WEB-INF/lib folder on startup

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
Openfire uses various caches. Typically, some value is looked up from the database (say, a Group) when it's not already in a cache, and is stored in the cache. The next time that that group is used, it is retrieved from the cache.
This works well, but only for data that exists. In the above example, a query for a non-existent Group will cause a database lookup each time (as the Group is not cached).
Openfire should cache the negative ("group does not exist"), to prevent unneeded look-ups.
Note that this PR currently applies negative caching to only one type of object: groups. If accepted, this should be done for other types of cached objects too.
=> OF-1539: Negative caching for groups.

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/webapp/muc-room-affiliations.jsp
Let configure the nickname of the new room member when adding a new member
=> OF-258: Allow nicknames of MUC members to be reserved in the admin console

i18n/src/main/resources/openfire_i18n.properties
Didn't feel like creating a ticket for such a trivial change
=> Small typo

xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java
The UserProvider defines a method that returns all usernames. This is used when a group is being shared with 'everyone'.
The LdapUserProvider will query everything in LDAP, every time this method is called. Adding some kind of cache should dramatically improve performance.
=> OF-1794: Cache 'all usernames' result from LDAP.

xmppserver/src/main/java/org/jivesoftware/openfire/roster/DefaultRosterItemProvider.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
This adds a rudementary cache for RosterItem instances.
=> OF-1795: Introduce a cache for RosterItems

xmppserver/src/main/java/org/jivesoftware/openfire/commands/admin/group/AddGroupUsers.java, xmppserver/src/main/java/org/jivesoftware/openfire/commands/admin/muc/CreateMUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCSearchHandler.java
Dataform boolean values can have various representations. This commit improves handling those values in various places.
=> OF-1798: Properly parse boolean values.

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java, xmppserver/src/main/java/org/jivesoftware/admin/SiteMinderServletRequestAuthenticator.java, xmppserver/src/test/java/org/jivesoftware/admin/AuthCheckFilterTest.java, xmppserver/src/test/java/org/jivesoftware/admin/SiteMinderServletRequestAuthenticatorTest.java
Also use a SystemProperty for the adminConsole.servlet-request-authenticator
=> OF-1805: Make the SiteMinder header configurable.

.travis.yml
quote the string and remove extraneous ";", maybe?
=> fix travis.yml loop for trigger plugins

xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
(cherry picked from commit db4c323f471d89272e28b7b9d18ecb7eed47e6c5)
=> OF-1808: Be more restrictive over those caches we try to migrate (Openfire 4.4 branch)

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java, xmppserver/src/test/java/org/jivesoftware/openfire/group/GroupManagerTest.java
@guusdk - for your consideration. This was bugging me. Even if you don't like the refactoring, it's probably worth keeping the tests, anyway.
=> Group manager improvements

xmppserver/src/main/webapp/log.jsp
We had the problem that the logfiles sometimes cannot be loaded correctly. This pull request solves this problem.
=> OF-1816: Close input streams in log.jsp correctly

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMuclumbusSearchHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/java/org/jivesoftware/util/StringUtils.java, xmppserver/src/test/java/org/jivesoftware/util/StringUtilsTest.java
This commit adds support for the search functionality as described on and used by https://search.jabbercat.org/
=> OF-1815: Add MUC search 'muclumbus' support.

xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java
This reverts commit e0b1056c7e5a380e68044dd49f806d31895bfd41.
=> Revert "OF-1826: Prevent NPE in new DataForms implementation."

i18n/src/main/resources/openfire_i18n_de.properties
This pull requests changes the german translation:
* every key from the english resource file is translated to german
* every non existitng key from the english file is deleted
* a little bit reordering (intellij adds all new keys to the end. They have been moved to the respective group, but not sorted in this group.)
=> OF-1819 update the german translation

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java, xmppserver/src/main/webapp/setup/ldap-user.jspf, xmppserver/src/test/java/org/jivesoftware/util/LDAPTest.java
NB. Turns out my local corporate AD has ~750,000 user entries. Turns out to be a tad more than I expected.
=> OF-1821: Ensure that the ldap.pagedResultsSize is automatically set for ActiveDirectory

xmppserver/src/main/java/org/jivesoftware/openfire/net/TLSStreamHandler.java
This extends the solution that was introduced by OF-1009 with another exception message that's similar to the one already being handled as a 'normal' handshake rejection.
=> OF-1830: Add ignorable message during TLS handshake abort.

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/webapp/session-details.jsp
=> OF-1832: Admin console should show more data for a client session

xmppserver/src/main/java/org/jivesoftware/util/S2STestService.java
https://issues.igniterealtime.org/browse/OF-1845
=> [Fix] The interceptor could not intercept a domain that is null

xmppserver/src/main/java/org/jivesoftware/openfire/net/TLSWrapper.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialback.java
This isn't the nicest of fixes, but my tests started to fail after attempting to improve on this. As a result, I'm providing this as-is, as I suspect it's a functional improvement.
=> OF-793: Fixes for 'unsupported record version' exception

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java
Openfire should verify that the structure of the plugin archive does not include files that are expanded outside of the target directory.
=> OF-1860: Check plugin archive structure.

xmppserver/src/main/resources/META-INF/admin.tld, xmppserver/src/main/webapp/META-INF/admin.tld, xmppserver/src/main/webapp/WEB-INF/admin.tld
This allows for the formatting function to be used with JSTL.
=> OF-1251: Expose time elapsed formatting as taglib function.

xmppserver/src/main/java/org/jivesoftware/openfire/OfflineMessageStore.java, xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQOfflineMessagesHandler.java
Instead of retrieving all rows from the database to count them, use a count() SQL query.
=> OF-1882: Optimize counting offline messages.

xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java
(every time I look in to the LDAP code I keep thinking it's in severe need of a re-write. I simply took the opportunity to improve some caching behaviour this time, in addition to the additional feature)
=> OF-1866: Identify LDAP Openfire users from Group membership

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java
Openfire should follow XEP-0060 Pubsub § 6.1.3.7.
=> OF-1899: Pubsub subscribing while subscription pending should cause error

xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemCacheDetailsServlet.java, xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemPropertiesServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java, xmppserver/src/main/webapp/WEB-INF/web.xml
We need this support for the changes in #1510  to work.
=> OF-1903 OF-1916 Support for @WebServlet annotation

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_de.properties, i18n/src/main/resources/openfire_i18n_es.properties, i18n/src/main/resources/openfire_i18n_pt_PT.properties, i18n/src/main/resources/openfire_i18n_ru_RU.properties, i18n/src/main/resources/openfire_i18n_zh_CN.properties, xmppserver/src/main/java/org/jivesoftware/admin/LdapUserTester.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapAuthProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapAuthorizationMapping.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapAuthorizationPolicy.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapVCardProvider.java, xmppserver/src/main/webapp/profile-settings.jsp, xmppserver/src/main/webapp/setup/ldap-server.jspf, xmppserver/src/main/webapp/setup/setup-admin-settings.jsp, xmppserver/src/main/webapp/setup/setup-admin-settings_test.jsp, xmppserver/src/test/java/org/jivesoftware/openfire/ldap/LdapManagerTest.java, xmppserver/src/test/java/org/jivesoftware/util/LDAPTest.java
Various LDAP improvements, summed up by:
- Replace usage of String with more appropriate types to represent LDAP data.
- Improve escaping of data.
- Stop wrapping DNs in double-quotes.
More details can be found in the individual commits.
Note: I'm not sure if each individual commit leaves the code in a state that can be compiled without error.
=> OF-353: LDAP

i18n/src/main/resources/openfire_i18n.properties
Also fix the property name for plugins.servlet.allowLocalFileReading which is nothing to do with 1865, but I'll invoke the boy-scout rule ;)
=> OF-1865 revisited: Correct the name of the property in the resource

xmppserver/src/main/java/org/jivesoftware/openfire/auth/POP3AuthProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdGroupProvider.java, xmppserver/src/main/java/org/jivesoftware/util/cache/Cache.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheWrapper.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CaffeineCache.java, xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultCache.java, xmppserver/src/main/webapp/system-cache.jsp
(see https://discourse.igniterealtime.org/t/bug-in-cache-konfiguration/86452/)
this may be a breaking change!
I'll also make a pull request in the Hazelcast plugin.
=> OF-1898 make the max cache size consistent to long

xmppserver/src/main/java/org/jivesoftware/util/FaviconServlet.java
(also fixes the issue that prevents the load of the default icon where no favicon exists)
=> OF-1902: Restrict retrieve of favicon to connected servers

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
The field `occupantsByNickname` is readed from and written to without a lock:
```java
List<MUCRole> occupants = occupantsByNickname.get(nickname.toLowerCase());
// Do not add new occupant with one with same nickname already exists
if (occupants == null) {
occupants = new ArrayList<>();
occupantsByNickname.put(nickname.toLowerCase(), occupants);
```
This pull request surround all code parts, in which this happens, with the existing write lock.
=> OF-1930: Make LocalMUCRoom more thread safe

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceManager.java
Fixes Statement for SQL SERVER purge function
=> OF-1779: Fix SQL Statement in Pubsub

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_de.properties, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/webapp/muc-service-edit-form.jsp
with option xmpp.muc.keep_from_cleanup you are now able to prevent mucs from deletion
Added options to service preferences tab on admin console
=> OF-1935: Feature keep muc from deletion

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/webapp/setup/setup-admin-settings.jsp, xmppserver/src/main/webapp/setup/setup-admin-settings_test.jsp
(see messages of individual commits)
=> OF-1943: LDAP group admin

xmppserver/src/main/webapp/muc-service-edit-form.jsp
This fixes a problem introduced by OF-1935, which causes NullPointerExceptions to show in the admin console when creating a new MUC service.
@mightymop - as the original author, would you care to review this?
=> OF-1954: Fixes NPE when creating new MUC service

xmppserver/src/main/java/org/jivesoftware/openfire/keystore/CertificateStoreManager.java
Save encrypted passwords to DB
=> [Security issue]Keystore passwords are not encrypted in the ofProperty table

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
So, the original change for OF-1951 didn't work if a plugin attempted to create a SystemProperty during instantiation. This is because the SystemProperty attempts to retrieve the plugin class loader from the PluginManager to find the i18n file - but as the PluginManager has yet to fully load the plugin it can't find a class loader.
To fix this;
a) Default to the "current" class loader if a plugin-specific one cannot be found (instead of throwing an NPE), and
b) Instantiate the plugin with the plugin class loader as the current class loader.
The first of these I'm 100% comfortable with.
The second is more interesting. I don't think it would have any side effects as the same class loader is used to create the plugin either way - but other views welcome. 
I've tested this with a couple of …
=> OF-1951 (plugin i18n for a SystemProperty) revisited

xmppserver/src/main/java/org/jivesoftware/openfire/sasl/ScramSha1SaslServer.java
Logging username in case of authfail
=> OF-1969: Update ScramSha1SaslServer.java

xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemCacheDetailsServlet.java, xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemPropertiesServlet.java, xmppserver/src/main/java/org/jivesoftware/util/ListPager.java, xmppserver/src/main/webapp/security-truststore.jsp
Note that `StringEscapeUtils.escapeHtml4()` will not escape single/double quotes. However `StringEscapeUtils.escapeXml11()` will. Every day is a school day!
Plus a couple of other outputs that were simply un-escaped.
=> OF-1963: Fix XSS issues identified by CSW Document No: C1055

.dockerignore
Improves caching of build stages
=> Exclude files not relevant to the docker image

xmppserver/src/main/java/org/jivesoftware/openfire/carbons/Received.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
Also;
a) general code tidy up, based on IntellilJ inspections
b) Replace use of a deprecated method with new method
c) Remove unnecessary lock when a node leaves a cluster.
=> OF-1888: Fix NPE

.github/workflows/continuous-integration-workflow.yml
Shall we experiment with this?
=> Add a Github Actions workflow that builds the project.

documentation/install-guide.html
This adds documentation for the feature introduced in https://github.com/igniterealtime/Openfire/commit/8bf8d5cbb1589361266c9783d95ea9f38fb2a909
=> Add 'autosetup' functionality to documentation.

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, src/java/org/jivesoftware/openfire/pubsub/InMemoryPubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPService.java, xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPServiceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CollectionNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultNodeConfiguration.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultPubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/InMemoryPubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeAffiliate.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubModule.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceProviderManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubService.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PublishedItem.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/FlushTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/ModifySubscriptionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/RefreshNodeTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/models/AccessModel.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/models/PublisherModel.java, xmppserver/src/main/webapp/pubsub-node-summary.jsp, xmppserver/src/test/java/org/jivesoftware/openfire/pubsub/CollectionNodeTest.java, xmppserver/src/test/java/org/jivesoftware/openfire/pubsub/LeafNodeTest.java
This is a refactoring of the PubSub code. Please review individual commit messages for a listing of features.
=> Various pubsub improvements

pom.xml
SLF4J 1.7.30 instead of 1.7.26: http://www.slf4j.org/news.html
=> SLF4J 1.7.30 instead of 1.7.26

xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NIOConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/LocalRoutingTable.java, xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java
Notably, these commits should fix the infinite "invalid connection" that's being reported in the admin console for sessions that are resumed more than once.
=> Various fixes for Stream Management

pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java
This PR fixes issue OF-2017 by upgrading Jetty
=> Update Jetty to 9.4.28.v20200408

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultPubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java
This fixes the issue of PEP Services not being loaded properly, as introduced by my earlier pubsub work on Master.
=> OF-2016: Fix PEP Service instantiation issue

xmppserver/changelog.html, xmppserver/src/main/java/org/jivesoftware/openfire/archive/ArchiveManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/archive/Archiver.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/webapp/muc-tasks.jsp
Please refer to individual commit messages for a breakdown of the changes introduced by this PR.
=> OF-2019 muc archiving delay start

xmppserver/changelog.html, xmppserver/src/main/java/org/jivesoftware/openfire/archive/ArchiveManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/archive/Archiver.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/webapp/muc-tasks.jsp
This is #1631 but applied to the 4.5 branch. Commits have been cherry-picked.
=> OF-2019 Delay start of MUC archiving

distribution/src/installer/openfire.install4j
Includes a large verbatim schema update done by the install4j GUI.
=> OF-1982 JVM updates for install4j

xmppserver/src/main/java/org/jivesoftware/openfire/net/BlockingReadingMode.java
Up until now, receiving stream errors were processed in the chatch-all "we don't know what to do with this" code. Instead, Openfire should support proper error parsing.
Functionally, this won't introduce much of a change, as the behavior for processing unprocessable data is to close the connection, which is similar to what happens after processing a stream error.
=> OF-1836: Properly handle S2S stream errors

documentation/protocol-support.html
* Scanned Openfire, Tinder and plugins for keywords RFC and XEP. Did not check maturity and completeness of implementation.
* Aligned tables with XEP-0423: XMPP Compliance Suites 2020
=> Bring protocol support in-line with Openfire 4.6.0

documentation/openfire.doap
This takes the list of supported XEPs (as updated in 959090578cac8b569548306926ccf85e2cbbe38c) and formats it as a DOAP file.
=> OF-1880: Provide DOAP for Openfire

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/session/SoftwareVersionManager.java
Openfire queries the peer on new connections for their version information. This PR improves that functionality.
=> Minor improvements to the automatic version check functionality

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java
@dominic-surevine, can you please have a look at these?
=> OF-1972 and OF-1973 plugin manager improvements

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java
more info here:
https://discourse.igniterealtime.org/t/pubsub-unsubscription-could-fail-with-xmpp-pubsub-multiple-subscriptions-true/88415
=> OF-2059: PubSub unsubscription could fail with “xmpp.pubsub.multiple-subscriptions=true”

xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPService.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CollectionNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeAffiliate.java
XEP-0136 mandates that notifications are sent to all connected resources of the owner of the PEP service (subject to notification filtering).
=> OF-2057: Send PEP notifications to PEP Service owners connected resources

distribution/src/database/openfire_db2.sql, distribution/src/database/openfire_hsqldb.sql, distribution/src/database/openfire_mysql.sql, distribution/src/database/openfire_oracle.sql, distribution/src/database/openfire_postgresql.sql, distribution/src/database/openfire_sqlserver.sql, distribution/src/database/openfire_sybase.sql, distribution/src/database/upgrade/31/openfire_db2.sql, distribution/src/database/upgrade/31/openfire_hsqldb.sql, distribution/src/database/upgrade/31/openfire_mysql.sql, distribution/src/database/upgrade/31/openfire_oracle.sql, distribution/src/database/upgrade/31/openfire_postgresql.sql, distribution/src/database/upgrade/31/openfire_sqlserver.sql, distribution/src/database/upgrade/31/openfire_sybase.sql, xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPService.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultPubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubModule.java
I've only tested the SQL for HSQLDB, but this PR also contains scripts for all other databases. A review of those would be desirable.
=> OF-2062 pubsub item payload size

xmppserver/src/test/java/org/jivesoftware/openfire/ldap/FlattenNestedGroupsTest.java
Disable this test until a fix can be found.
@MarcelHeckel would you mind trying to dig into this problem?
=> OF-2070: Tests in FlattenNestedGroupsTest regularly fail - disable

xmppserver/src/main/java/org/jivesoftware/openfire/IQRouter.java, xmppserver/src/main/java/org/jivesoftware/openfire/cluster/IQResultListenerTask.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java
If an IQ result can't be processed locally, try to identify another cluster node that can.
=> OF-2064: Invoke IQResultListener on other cluster nodes

xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoItemsHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceUpdateHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialback.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/PresenceManagerImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, xmppserver/src/main/java/org/jivesoftware/util/AutoCloseableReentrantLock.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheUtil.java, xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultLocalCacheStrategy.java
And for good measure, replace usage of the deprecated CacheFactory#getLock with Cache#getLock
=> OF-2071: 'Lock' should be locked in front of a 'try' block (instead of in to block).

plugins/pom.xml, pom.xml
=> OF-2087: Jetty version bump

documentation/plugin-dev-guide.html
* FAQ for artifact naming
* Better examples for date conventions
=> Improve Plugin Dev documentation

distribution/src/database/openfire_db2.sql, distribution/src/database/openfire_hsqldb.sql, distribution/src/database/openfire_mysql.sql, distribution/src/database/openfire_oracle.sql, distribution/src/database/openfire_postgresql.sql, distribution/src/database/openfire_sqlserver.sql, distribution/src/database/openfire_sybase.sql, distribution/src/database/upgrade/32/openfire_db2.sql, distribution/src/database/upgrade/32/openfire_hsqldb.sql, distribution/src/database/upgrade/32/openfire_mysql.sql, distribution/src/database/upgrade/32/openfire_oracle.sql, distribution/src/database/upgrade/32/openfire_postgresql.sql, distribution/src/database/upgrade/32/openfire_sqlserver.sql, distribution/src/database/upgrade/32/openfire_sybase.sql, i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/database/SchemaManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQOwnerHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/webapp/muc-room-federation.jsp
This adds configuration persistency, by storing config to the database. As a result of adding this, some rework was needed. Basic testing seems to indicate that functionality has been preserved, but this could use further testing.
=> OF-2030: FMUC persist config

xmppserver/src/main/java/org/jivesoftware/admin/AdminConsole.java
Not functional changes, just refactor to use less code to do the same things. Perhaps I could work to reduce it a bit more.
=> Remove duplicated code

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/openfire/privacy/PrivacyItem.java, xmppserver/src/main/java/org/jivesoftware/openfire/privacy/PrivacyList.java, xmppserver/src/main/resources/admin-sidebar.xml, xmppserver/src/main/webapp/user-privacylists.jsp
This adds a simple page that displays all privacy lists for users to the admin console.
=> OF-2108: Admin console should show privacy lists

xmppserver/src/main/java/org/jivesoftware/openfire/pep/IQPEPHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPService.java, xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPServiceInfo.java, xmppserver/src/main/java/org/jivesoftware/openfire/pep/PEPServiceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/DefaultPubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/InMemoryPubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubModule.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubPersistenceProviderManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubService.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/FlushTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/ModifySubscriptionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/RefreshNodeTask.java
This primarily addresses the reported memory leak (OF-2092) but has also fixes for issues identified in the progress of performing the rewrite.
=> PEP notification rewrite

xmppserver/src/test/java/org/jivesoftware/openfire/spi/ConnectionTypeTest.java
Test from #1652 had a typo, so a good opportunity.
=> Refactor ConnectionTypeTest to be parameterised

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Fixes a typo in a setting name
https://issues.igniterealtime.org/browse/OF-2111
https://discourse.igniterealtime.org/t/group-chat-settings-not-taken-into-the-account/88977
=> OF-2111: Read and write MUC maxbatchsize to the same setting

README.md, documentation/openfire.doap, plugins/pom.xml, pom.xml, xmppserver/changelog.html, xmppserver/src/main/java/org/jivesoftware/openfire/container/AdminConsolePlugin.java, xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQRosterHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/TempFileToucherTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java, xmppserver/src/main/java/org/jivesoftware/util/cache/ComponentCacheWrapper.java, xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultExternalizableUtil.java, xmppserver/src/test/java/dom/io/XMPPPacketReaderTest.java, xmppserver/src/test/java/org/jivesoftware/openfire/ldap/VCardTemplateTest.java, xmppserver/src/test/java/org/jivesoftware/openfire/ldap/VCardTest.java, xmppserver/src/test/java/org/jivesoftware/util/CacheUtilTest.java
see https://discourse.igniterealtime.org/t/89041
=> update Jira links to new atlassian cloud instance

xmppserver/src/main/java/org/jivesoftware/openfire/net/DNSUtil.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java, xmppserver/src/test/java/org/jivesoftware/openfire/net/DNSUtilTest.java
This improves logging around DNS SRV queries, and adds some other minor enhancements.
=> OF-2172: Minor enhancements to DNSUtil

xmppserver/src/main/java/org/jivesoftware/openfire/muc/HistoryStrategy.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoom.java
Fixes a bug introduced by OF-2163.
=> OF-2173: Prevent NPE when joining rooms without subject

xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/OccupantAddedEvent.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/cluster/RoomInfo.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
This is a generic clean-up of the MUC code, that should not introduce (relevant) functional changes. This commit intends to lead up to more structural changes.
=> MUC refactoring

.dependency-check-suppressions.xml, pom.xml
use `mvn verify -P deps` to see an HTML report outputted to to the target directory
=> Add dependency checking maven profile

.github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration-workflow.yml
At Ignite Realtime, we care about all branches.
=> run CI on all branches

xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java
When a BOSH session gets terminated, the client should be told that not only the request is 'done' (eg: gets responded to) but also the session that the connection is part of is terminated. Without this, there is no way for the client to determine that this is the case, other than receiving an error on the next request where the client attempts to re-use the session (sends a request with the old SID value).
=> OF-2206: When closing BOSH session, send 'terminate'

xmppserver/src/main/java/org/jivesoftware/openfire/entitycaps/EntityCapabilitiesManager.java
The problem fixed here is most apparent when a user is being deleted, while at the same time presence unavailable for the same user is being processed.
=> OF-2205: Prevents a race condition in EntityCapabilitiesManager

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/webapp/session-details.jsp, xmppserver/src/main/webapp/session-row.jspf, xmppserver/src/main/webapp/session-summary.jsp
Fixes https://igniterealtime.atlassian.net/browse/OF-2192
Incorporates community feedback: https://discourse.igniterealtime.org/t/client-sessions-column-chooser/89434
=> OF-2192 - Admin: Add version info to Session Summary

.github/workflows/database-upgrades.yml, build/ci/compose/mssql.yml, build/ci/compose/mysql.yml, build/ci/compose/postgresql.yml, build/ci/compose/scripts/mssql.sh, build/ci/compose/scripts/wait-for-it.sh, build/ci/updater/README.md, build/ci/updater/pom.xml, build/ci/updater/src/main/java/com/igniterealtime/openfire/updaterunner/Main.java, build/ci/updater/src/main/java/com/igniterealtime/openfire/updaterunner/PropertiesReader.java
Tests upgrade process for MySQL, MS SQL Server, PostgreSQL.
Prompted by OF-2197, where a broken MS SQL Server upgrade snuck into a release.
Reviewer notes:
* Welcome some input on the java structure - it works, but I don't know if it's unnecessarily time consuming to build, especially since I've intentionally kept it away from the parent POM (perhaps wrongly?)
* The rules on the Github Actions file try to prevent running the CI unnecessarily, but haven't been validated yet (beyond the commit that added the restrictions didn't trigger the workflow since it was a commit to a non-master branch)
=> Database Upgrade tests for Openfire

xmppserver/src/main/java/org/jivesoftware/openfire/session/SoftwareVersionManager.java
Instead of scheduling an immediate task that does nothing for X seconds, schedule a task that will start in X seconds, that immediately does something.
This prevents using up a thread from the TaskEngine that's not doing anything for a significant amount of time.
=> OF-2243: Version check task should not be busy doing nothing

xmppserver/src/main/java/org/jivesoftware/util/ListPager.java, xmppserver/src/main/webapp/muc-room-summary.jsp
Issue described in: https://discourse.igniterealtime.org/t/of-4-6-4-bug-in-adminconsole-when-paging-through-mucs/90362
=> fix listpager on muc-room-summary.jsp when using multiple chatservices

xmppserver/src/main/java/org/jivesoftware/openfire/RemotePacketRouter.java, xmppserver/src/main/java/org/jivesoftware/openfire/RoutingTable.java
connectoin -> connection
outoing -> outgoing
connecte -> connect
deliverying -> delivering
=> fix wrong typo for connectoin,outoing,connecte and deliverying

xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
This PR replaces https://github.com/igniterealtime/Openfire/pull/1901, which got into a bit of merge mess.
=> OF-2314 Prevent local s2s duplication

xmppserver/src/main/java/org/jivesoftware/openfire/server/OutgoingSessionPromise.java
When an outgoing s2s session is being established, stanzas addressed to the remote domain are cached. Only the first (and not all) queued packets should attempt to establish the connection.
The original code would attempt to establish a session for each queued stanza, which is handled somewhat gracefully in the sense that the existing session is used. However, an event is fired for each attempt. That event is picked up by an event listener that sends a new stanza to that domain, which causes recursion and a never-empty queue.
With this fix, only the first stanza (or the first stanza after a failure) attempts to establish the connection.
=> OF-2322: Do not re-auth s2s for every queued stanza

xmppserver/src/main/java/org/jivesoftware/openfire/update/UpdateManager.java
Updates the updates notifications to include the hostname of the node which have plugins to be updated.
Tidies up an iterator in the same method
=> OF-2158 Update notifications should include cluster node reference

xmppserver/src/main/java/org/jivesoftware/database/AbstractConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/admin/JDBCAdminProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/audit/spi/AuditManagerImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/models/AccessModel.java
Not related to a specific task.
Various Code Quality Improvements (suggested by static analysis):
AbstractConnection - changes public constructor of abstract class to protected (Constructors of abstract classes can only be called in constructors of their subclasses. So there is no point in making them public.)
AccessModel - switched static and final positions to fit java convention
AuditManagerImpl - Explicitly specifies types on returned interface, removes null check when item cannot be null
JDBCAdminProvider- Removes use of deprecated function and utilises the new method of doing this
=> Trivial changes as my first contribution. 

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCSearchHandler.java
fix a NPE when name = null in IQMUCSearchHandler
=> OF-2338: fix npe on muc search if name is empty

build/rpm/build_rpms.sh, build/rpm/openfire.spec, distribution/src/installer/openfire.install4j
Note: we need to address [INFRA-44](https://igniterealtime.atlassian.net/browse/INFRA-44), to get install4j updated on ignite's bamboo instance.
=> OF-2199 Remove JRE Bundling with artifacts

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Ensure all rooms are properly known to the service after encountering a cluster split.
This PR introduces a check at two moments: right after a cluster breakup happened, and just before responding to a room discovery request.
=> OF-2339 Ensure all rooms are properly known to the service

distribution/pom.xml, i18n/pom.xml, plugins/openfire-plugin-assembly-descriptor/pom.xml, plugins/pom.xml, pom.xml, starter/pom.xml, xmppserver/changelog.html, xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/spi/XMPPServerInfoImpl.java
=> denote Openfire 4.7.0 Beta release

build/debian/openfire.init.d, distribution/src/bin/extra/openfire-launchd-wrapper.sh, distribution/src/bin/extra/redhat/openfire, distribution/src/bin/openfire.bat, distribution/src/bin/openfire.sh, distribution/src/bin/openfirectl, distribution/src/installer/openfire.install4j, distribution/src/resources/log4j2.xml, pom.xml, xmppserver/src/test/resources/log4j2-test-mvn.xml, xmppserver/src/test/resources/log4j2-test.xml
Most of these will likely be redundant, but better safe than sorry?
=> OF-2353: Upgrade to log4j2 2.16.0 and adding various mitigation actions

pom.xml
https://www.bouncycastle.org/releasenotes.html
=> OF-2356: Update Bouncy Castle to 1.70

pom.xml
http://www.slf4j.org/news.html
=> OF-2357: Update slf4j to 1.7.32

xmppserver/src/main/java/org/jivesoftware/openfire/group/GroupManager.java
Replaces the usages of synchronized(string) with synchronized(lock object) in the GroupManager class.
No tidy method of replacing the strings that were previously used (e.g. GROUP_COUNT_KEY) as these are referred to from some static contexts and the values are needed so synchronizing on an instance of a "string lock" object isn't a great strategy.
=> Replaces the usages of synchronized(string) with synchronized(lock object) in the GroupManager class

xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultExternalizableUtil.java
When a ClassLoader instance is provided (when reading data), this instance should actually be used.
=> OF-2350: ExternalizableUtil should not ignore provided ClassLoader

xmppserver/src/main/webapp/js/behaviour.js, xmppserver/src/main/webapp/js/controls.js, xmppserver/src/main/webapp/js/cookies.js, xmppserver/src/main/webapp/js/effects.js, xmppserver/src/main/webapp/js/lightbox.js, xmppserver/src/main/webapp/js/setup.js
Updates assorted javascript files under webapp with sonarqube and LGTM alerts, some emphasis replacing unnecessary global variables with the correct assignment (e.g. let/const) to correctly scope.
=> OF-2363 Assorted improvements to javascript files

pom.xml
Send to 4.6 branch just in case we make another release there.
=> OF-2355 Bump log4j to 2.17.1

xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java, xmppserver/src/test/java/org/jivesoftware/util/CacheableOptionalTest.java
Replace the one single usage that we have with a equivalent bit of code.
=> OF-2366: Drop commons-io

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
Previously, Openfire was sending an IQ Ping to inactive users, but didn't register the response as activity.
=> OF-2368: Register MUC ping responses as user activity

distribution/pom.xml, i18n/pom.xml, plugins/openfire-plugin-assembly-descriptor/pom.xml, plugins/pom.xml, pom.xml, starter/pom.xml, xmppserver/changelog.html, xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/spi/XMPPServerInfoImpl.java
=> denote Openfire 4.7.0 Release

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/OccupantManager.java
See individual commit messages for details.
=> Various improvements to OF-2381's MUC idle and ghost user detection.

pom.xml
https://www.slf4j.org/news.html
=> OF-2393: Update slf4j to 1.7.36

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java
Add version info to the "Successfully loaded plugin"-message
=> OF-2405: Enhance log info of loaded plugin by version

xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdAdminProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdGroupProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdProperties.java, xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdUserProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/crowd/CrowdVCardProvider.java
This resolves warnings generated by LGTM and Intellij in the org.jivesoftware.openfire.crowd package. No functional changes are intended.
=> OF-2408: Fix static analysis warnings in Crowd package

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/InMemoryPubSubPersistenceProvider.java
This pulls in the fix for OF-2379, which is a requirement for OF-2380.
The fix for OF-2380 introduces a non-compatible change to a cache definition used in clustering. We'd best not include this in a patch release, and instead do this only for a major release.
=> OF-2380 pubsub inmemory collection types

xmppserver/src/main/webapp/http-bind.jsp
The original implementation of OF-2395 introduced a couple of bugs. This commit fixes those.
=> OF-2395: Remove deprecated code follow-up

.github/workflows/continuous-integration-workflow.yml, .github/workflows/database-upgrades.yml, README.md, documentation/docker.html, documentation/plugin-dev-guide.html, documentation/working-with-openfire.html, pom.xml
Preparing for the default branch migration to main tomorrow (21 Apr) as per [announcement on forums](https://discourse.igniterealtime.org/t/moving-openfire-github-repositories-from-master-to-main-branch/91567)
=> update master git branch to main

xmppserver/src/main/java/org/jivesoftware/openfire/handler/PresenceSubscribeHandler.java
[RFC 6121 section 3.1.3](https://datatracker.ietf.org/doc/html/rfc6121#section-3.1.3) mandates that when processing an inbound presence subscription request, if the contact exists and the user already has a subscription to the contact's presence, then the contact's server MUST auto-reply on behalf of the contact by sending a presence stanza of type "subscribed"
Openfire currently does not do this. This behavior was removed as part of [OF-38](https://igniterealtime.atlassian.net/browse/OF-38), to prevent a loop of presence stanzas that occur when an RFC3921-style client acknowledges receipt of a ‘subscribed’ presence stanza by sending a ‘subscribe’ stanza (see the last paragraph of [section 8.2 of RFC3921](https://datatracker.ietf.org/doc/html/rfc3921#section-8.2)).
This commit changes the …
=> OF-2404 / OF-38: Inbound presence 'subscribe' for preexisting contact MUST be auto-responded

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/OccupantManager.java
A CME has been observed while one thread is modifying the local occupants, while the other is reading from it.
This commit adds a read/write lock that should prevent this.
=> OF-2421: Prevent ConcurrentModificationException in OccupantManager

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/auth/AuthorizationManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/AuthorizationMapping.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/AuthorizationPolicy.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/DefaultAuthorizationMapping.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/DefaultAuthorizationPolicy.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapAuthorizationMapping.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapAuthorizationPolicy.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/SASLAuthentication.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/XMPPCallbackHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/sasl/ExternalClientSaslServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/sasl/SaslServerPlainImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/sasl/VerifyPasswordCallback.java
The main purpose of this PR is to fix OF-2443, but leading up to that, a couple more changes (that should be harmless) were made. Please refer to individual commits in this PR for details.
=> Minor changes to SASL implementation

xmppserver/src/main/webapp/muc-room-affiliations.jsp
Sorted alphabetically (ignoring case), as shown below:
=> OF-2466: Groups presented in MUC room affiliation page should be ordered

xmppserver/src/main/resources/admin-sidebar.xml, xmppserver/src/main/webapp/style/global.css
=> OF-2482 & OF-2181 fixes

xmppserver/src/main/webapp/server-session-details.jsp
=> OF-2481: Fix server details on s2s page

xmppserver/src/main/webapp/muc-room-affiliations.jsp
When modifying MUC permissions for a Group, display the Group name, not its base-32 identifier.
=> OF-2471: Display GroupJID human readable name in Audit viewer

xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java
This reverts commit 3acccea61e18ee36f2c0b91f0310200e3cba8ab7.
=> Revert "OF-400: Truncate MUC subjects longer than 100 characters"

xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRole.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/OccupantManager.java, xmppserver/src/test/java/org/jivesoftware/openfire/muc/spi/OccupantManagerTest.java
During stress testing of MUC, various areas of poor performance were detected. This PR fixes three of them.
=> OF-2498 muc performance

xmppserver/src/main/java/org/jivesoftware/openfire/spi/MINAConnectionAcceptor.java
The MINA-provided JMX beans are not functional (they throw runtime exceptions). This commit replaces them with generic executor thread pool MBeans. These give less data, but work.
=> OF-2504: Replace broken MINA JMX monitoring

distribution/src/installer/openfire.install4j
I just launched install4j and let it migrate the schema.
=> take install4j schema update verbatim

xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionListener.java
For SASL EXTERNAL to be used to authenticate server-to-server connections, Java's "client authentication" must be enabled, allowing peer certificates to be processed.
This improves on the changes in OF-1855, which would enable this by default _if_ the local server had a non-selfsigned certificate installed. That condition does not make a lot of sense, as the local certificate does/should not affect the validation of the certificates provided by the peer.
=> OF-2521: Allow SASL EXTERNAL for S2S by default

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
To fix https://igniterealtime.atlassian.net/browse/OF-1649 a user/JID-based lock was introduced. This lock made the creation of a user-and-joining-a-room atomic with respect to the cleanup action remove-all-users-that-are-not-in-any-room.
With the rewrite of MUC in https://igniterealtime.atlassian.net/browse/OF-2224 (and friends), the cleanup of users is no longer based on room membership, but on duration since last activity. This will prevent https://igniterealtime.atlassian.net/browse/OF-1649. The lock that was put in place now no longer serves a purpose, and should be removed.
=> OF-2531: Remove unneeded JID-based lock in MUC

xmppserver/pom.xml
This adds functionality that allows to mock statics.
=> OF-2547: Upgrade Mockito to 4.9.0

i18n/src/main/resources/openfire_i18n.properties, xmppserver/src/main/java/org/jivesoftware/openfire/net/SASLAuthentication.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialback.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/IncomingServerSessionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/OutgoingServerSessionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteIncomingServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteOutgoingServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteSessionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/ServerSession.java, xmppserver/src/main/webapp/server-session-details.jsp
The first commit is a functional change (arguably a bugfix). The second commit refactors the implementation.
=> OF-2564: Refactor server session authentication state

xmppserver/src/main/webapp/session-summary.jsp
...by resolving a TODO that I left myself when I implemented it
=> OF-2242: Fix filtering by client version

.github/workflows/continuous-integration-workflow.yml, runAioxmppIntegrationTests
Upgrade from Python 3.9 to Python 3.11
Also, whilst we're there, upgrade the setup-python GH action from v1 to v4
=> OF-2578 Bump python version to fix aioxmpp tests

xmppserver/src/main/webapp/reg-settings.jsp
One space character added :tada:
=> OF-2575 Fix text formatting for Inband Registration

xmppserver/src/main/webapp/server-locale.jsp, xmppserver/src/main/webapp/setup/index.jsp
This PR adds a new translation for the Ukrainian language (uk_UA), created and provided by Yurii Savchuk (@svais) and his son Vladislav Savchuk (Bruhmozavr)!
Also, a selection issue for Portuguese (pt_PT) is fixed.
=> Fixes for OF-2579 (add Ukrainian) and OF-2580 (fix Portuguese)

.github/workflows/continuous-integration-workflow.yml
4.7 branch equivalent of #2184
=> CI: run on ubuntu-latest

xmppserver/src/main/java/org/jivesoftware/database/ProfiledConnection.java
Logs a warning (and stack traces) when one thread obtains more than one database connection from the database connection pool. This intends to flag inefficient code.
This feature is enabled only when ProfiledConnections are used, which is not the case by default.
=> OF-2572: Detect thread obtaining more than one database connection

.github/dependabot.yml
=> enable dependabot to update github actions

xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java
When an invalid database connection string is provided during setup, the PluginMonitor tries to use it to read properties until it is corrected.
This leads to database connection errors being logged every time that the monitor runs (once every 30 seconds). It's mostly benign, but annoying.
With this commit, the PluginMonitor does not try to read from the database until setup has been completed (apart from the admin plugin, no other plugins are loaded during setup anyway).
=> OF-2606: Prevent surplus DB connection errors during setup

xmppserver/src/main/java/org/jivesoftware/openfire/spi/EncryptionArtifactFactory.java
Please review the individual commit messages. The first one fixes a bug in the new Netty implementation, the second one is more of a cleanup.
=> OF-2559: EncryptionFactory improvements for Netty

xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyClientConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyComponentConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyMultiplexerConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyServerConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java
This intends to make debugging running systems easier.
=> OF-2654: Add/improve toString implementations

xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java, xmppserver/src/main/java/org/jivesoftware/util/S2STestService.java
This is a collection of smaller issues with the new Netty outgoing server-to-server implementation. Please refer to individual commit messages (and their JIRA issues) for details.
=> Various Netty improvements

xmppserver/src/main/java/org/jivesoftware/openfire/LocalSessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/util/cache/ConsistencyChecks.java
This should remove one of the reported cache inconsistencies, and generate more debug information to help diagnose the remaining issue.
=> OF-2665: Inconsistent cache state

xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/ClientStanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/ComponentStanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/MultiplexerStanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/RespondingServerStanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/SASLAuthentication.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/ServerStanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketReader.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketReadingMode.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/StanzaHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java, xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialback.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalComponentSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalConnectionMultiplexerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalIncomingServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalOutgoingServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalServerSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/websocket/WebSocketClientStanzaHandler.java, xmppserver/src/test/java/org/jivesoftware/openfire/session/AbstractRemoteServerDummy.java, xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalIncomingServerSessionTest.java, xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalOutgoingServerSessionTest.java, xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java, xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteReceivingServerDummy.java
This builds on https://github.com/igniterealtime/Openfire/pull/2275
=> OF-2678 prefer xml datatypes

.github/workflows/continuous-integration-workflow.yml
Doesn't generate test coverage if it's not main
Doesn't upload test coverage if it's not main
=> OF-2686: Test coverage on main only

documentation/client-minimal-working-example-mellium.html, documentation/client-minimal-working-example-moxxmpp.html, documentation/client-minimal-working-example-smack.html, documentation/client-minimal-working-example-stanzajs.html, documentation/client-minimal-working-example-stropejs.html, documentation/client-minimal-working-example-twistedwords.html, documentation/client-minimal-working-example-xmppdotnet.html, documentation/index.html
This PR adds documentation for various client libraries that show a minimum working example of how to use that client with Openfire.
=> Documentation: add minimal working examples

xmppserver/src/main/java/org/jivesoftware/openfire/entitycaps/EntityCapabilitiesManager.java
Openfire should not try to send any IQ query to a MUC room: it is not an occupant of that room, so the requests are likely to fail.
=> OF-2696: Do not resolve CAPS hashes when peer is MUC occupant

xmppserver/src/main/webapp/WEB-INF/classes/META-INF/tags/admin/infoBox.tagx, xmppserver/src/main/webapp/decorators/main.jsp
… rather than force them to duplicate
There's only one of these that I can find. And it's a 1 character change.
=> OF-2620: Use Openfire assets on Plugin pages

xmppserver/src/test/java/org/jivesoftware/openfire/group/GroupTest.java
This new unit test verifies behavior of caching and event listeners in relation to operations on a Group.
=> New unit tests for Group

xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettySessionInitializer.java
Ideally we'd get rid of the extra socket altogether.
This at least tidies it up.
=> OF-2721: (Partial fix) Close the extra socket that we don't need

xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyOutboundConnectionHandler.java
This is a bit of a rewrite of NettyOutboundConnectionHandler. It is aimed at having clear, concise outcomes for the various scenarios: either a session is ready to be used, or it is properly abandoned in all of them now.
=> OF-2730: Avoid Dialback being attempted when S2S Strict is enabled

xmppserver/src/main/java/org/jivesoftware/util/cache/ExternalizableUtil.java
Mostly non-functional changes, to reflect changes already applied under a duplicate ticket.
=> OF-1654: Minor change to reflect change in OF-1984

xmppserver/src/main/webapp/server-connectiontest.jsp
The S2S test is a potentially long-running process. The admin console should show some kind of indicator that something is happening.
This is my poor attempt at adding a spinner. There will be much better approaches, but this is what my limited experience gets you within the amount of time I'd like to spend on something like this. Feel free to improve on this! :)
=> OF-1407: Admin console should have a visual indicator when S2S test is running

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/webapp/security-certificate-details.jsp
... and added a bit of Dutch translation.
=> OF-2753: Admin Console: fix title on TLS store details page

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/util/S2STestService.java, xmppserver/src/main/webapp/server-connectiontest.jsp
When the end-user provides an invalid value, try to correct for common mistakes, or show a nicer error message.
=> OF-1405: Validate XMPP domain field of S2S Tester in admin console

xmppserver/src/main/webapp/server-connectiontest.jsp
Still allows the content to be copied.
=> OF-1406: Admin Console S2S Connection Test output should be read-only

distribution/pom.xml, i18n/pom.xml, plugins/openfire-plugin-assembly-descriptor/pom.xml, plugins/pom.xml, pom.xml, starter/pom.xml, xmppserver/changelog.html, xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/openfire/spi/XMPPServerInfoImpl.java
:rocket: :moon: :partying_face:
=> Openfire 4.8.0 Beta

xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CollectionNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/LeafNode.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/Node.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeAffiliate.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/NodeSubscription.java
The Pub/Sub implementation had hardly any logging. This makes analyzing issues hard.
In this commit, copious amounts of trace logging has been added.
A couple of mostly trivial code changes were applied (mostly IDE suggested improvements).
=> OF-2770: Add debug logging to Pub/Sub

xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java
When a cluster node leaves the cluster, cleanup code is executed. Part of this code is a check that verifies if a certain cache contains entries for each incoming server session. This compares incoming server sessions from another data structure with the content of that cache.
This code previously assumed that there could only be one session per remote domain, which is a false assumption. Moreover, it didn't properly verify the StreamID value.
The assumption in the old code causes an exception to be thrown, which prevents the 'left cluster' event from being finished completely, leading to state inconsistencies.
Although it is likely unexpected that Openfire maintains multiple sessions per remote domain, having more than one is entirely feasible. The code should allow for this.
=> OF-2755: Fix bug in cluster cleanup code

plugins/pom.xml, pom.xml, test.gradle
s/www.igniterealtime.org/igniterealtime.org/
=> mnt: standarize igniterealtime archiva address

xmppserver/src/test/java/org/jivesoftware/openfire/group/GroupTest.java
Adds trivial unit tests for #2431
=> OF-2777: Add tests

i18n/src/main/resources/openfire_i18n_he.properties, xmppserver/src/main/java/org/jivesoftware/util/LocaleUtils.java, xmppserver/src/main/webapp/decorators/main.jsp, xmppserver/src/main/webapp/decorators/setup.jsp, xmppserver/src/main/webapp/server-locale.jsp, xmppserver/src/main/webapp/setup/index.jsp
This adds support for the Hebrew language.
The translations are made by Schimon Jehudah Zackary. Thanks!
=> OF-2816: Add support for Hebrew language

i18n/src/main/resources/openfire_i18n.properties, i18n/src/main/resources/openfire_i18n_nl.properties, xmppserver/src/main/java/org/jivesoftware/openfire/handler/IQvCardHandler.java
Two distinct issues fixed. Please look at the commit messages for details.
=> OF-2838 & OF-2829: Improvement around error scenarios when retrieving VCards

xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnection.java
This should prevent connections from having to wait for a 10-minute timeout when an exception occurs while trying to invoke the close listeners.
=> OF-2845: Countdown latch on connection close exception

xmppserver/src/main/webapp/system-clustering.jsp
Fixed: fix memory usage status bar issue.
=> OF-2853 Fix memory usage status bar issue.

xmppserver/src/main/java/org/jivesoftware/openfire/muc/HistoryRequest.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCEventDelegate.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRole.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoom.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MUCRoomHistory.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/MultiUserChatService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQAdminHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCRegisterHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQOwnerHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java, xmppserver/src/main/java/org/jivesoftware/util/cache/ConsistencyChecks.java, xmppserver/src/main/webapp/muc-room-affiliations.jsp, xmppserver/src/main/webapp/muc-room-edit-form.jsp, xmppserver/src/main/webapp/muc-room-occupants.jsp, xmppserver/src/test/java/org/jivesoftware/openfire/muc/MUCRoleTest.java, xmppserver/src/test/java/org/jivesoftware/openfire/muc/MUCRoomTest.java
See individual commit messages for more details.
The commits in this PR are intended to be suitable to be backported and included in a patch release.
=> OF-2860: The non-breaking changes leading up to renaming the class MUCRole

build/debian/control, build/debian/rules
=> OF-2875 remove obsolete cdbs

xmppserver/src/main/webapp/setup/setup-admin-settings.jsp
A small HTML-fix for the page on which admin passwords are tested.
=> OF-2891: Alignment on admin setup (directory services)

documentation/plugin-dev-guide.html
Merged the two Plugin Structure.
Used more `<code>` tags.
=> plugin-dev-guide.html refresh and improve structure

distribution/pom.xml, i18n/pom.xml, plugins/openfire-plugin-assembly-descriptor/pom.xml, plugins/pom.xml, pom.xml, starter/pom.xml, xmppserver/pom.xml, xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java, xmppserver/src/main/java/org/jivesoftware/openfire/commands/SessionData.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/DNSUtil.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/LocalClientSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/XMPPServerInfoImpl.java, xmppserver/src/main/java/org/jivesoftware/util/Base64.java, xmppserver/src/main/java/org/jivesoftware/util/StringUtils.java, xmppserver/src/test/java/org/jivesoftware/openfire/session/LocalClientSessionTest.java
This updates all the deprecations as well.
=> Set Openfire next release to 5.0.0

.github/actions/connectivitytests-action/action.yml, .github/actions/connectivitytests-action/conntest/pom.xml, .github/actions/startserver-action/action.yml, .github/workflows/codeql-analysis.yml, .github/workflows/continuous-integration-workflow.yml, .github/workflows/macos-release-artifact.yml, Dockerfile, build/ci/updater/pom.xml, build/docker/buildWithDocker.sh, documentation/ide-vscode-setup.html, documentation/install-guide.html, documentation/source-build.html, plugins/pom.xml, pom.xml, xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java, xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteReceivingServerDummy.java
Openfire now requires Java 17 or later to run.
=> OF-2876: Raise minimum Java version from 11 to 17

plugins/pom.xml, xmppserver/pom.xml
These were missed in the earlier commit.
=> OF-2876: Additional changes to migrate from Java 11 to 17

distribution/pom.xml, i18n/pom.xml, plugins/openfire-plugin-assembly-descriptor/pom.xml, plugins/pom.xml, pom.xml, starter/pom.xml, xmppserver/pom.xml
The intention here is to create build and maven artifacts that can be targeted as we rapidly approach 5.0.0 Beta.
=> Denote Openfire 5.0.0 Alpha

build/rpm/build_rpms.sh
Very hacky approach, but should work(tm)
=> OF-2948 Support Alpha and RC releases in RPM build

documentation/plugin-dev-guide.html, xmppserver/pom.xml
This updates Sitemesh to a more recent release, 2.5.0. No major functional changes were identified.
=> OF-2903: Update Sitemesh to 2.5.0

xmppserver/src/main/java/org/jivesoftware/admin/servlet/SecurityAuditViewerServlet.java, xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemCacheDetailsServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/AffiliationTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/CancelSubscriptionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/ModifySubscriptionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/NewSubscriptionTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/RefreshNodeTask.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/cluster/RemoveNodeTask.java, xmppserver/src/main/java/org/jivesoftware/util/FaviconServlet.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CaffeineCache.java
For readability, change "Not Optional is Present" with "Optional is Empty".
This should not introduce any functional change.
Code changes have been applied using IDE-provided automation (rather than manual changes).
=> chore: replace `!Optional#isPresent()` with `Optional.isEmpty()`

xmppserver/src/main/java/org/jivesoftware/openfire/http/BoshBindingError.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpSessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/ResourceServlet.java, xmppserver/src/main/java/org/jivesoftware/openfire/http/SessionListener.java
Backport of #2681 to 4.9.
I've created this backport manually, as there was a minor merge conflict that prevented automation to perform this.
=> [Backport 4.9] OF-2966: Fix race condition in BOSH (noticable during logout)

xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java
It's not something that needs to be warned about, it's informational.
=> OF-3030: Adjust log level of "setting locale to"

xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyXMPPDecoder.java
Clients, and IOS-based clients in particular, can be expected to drop their TCP connection a lot. This event currently logs a stack trace (shown below). For an event that is very expected, this is to verbose. Lets reduce the verbosity of this event.
I’d prefer to keep the verbosity for other connection types than client-to-server connections. Remote servers, for example, are not expected to close the TCP connection ‘uncleanly'.
=> OF-3038: Reduce verbosity of Socket Connection reset log messages (c2s only)

.github/workflows/continuous-integration-workflow.yml, build/ci/compose/mysql.yml, build/ci/compose/oracle.yml, build/ci/compose/postgresql.yml, build/ci/compose/scripts/1.oracle-init.sql, build/ci/updater/pom.xml, build/ci/updater/src/main/java/com/igniterealtime/openfire/updaterunner/Main.java
Based on a free-lite image that is made available by Oracle at https://container-registry.oracle.com/ords/ocr/ba/database/free
=> CI: add Oracle support to database update test

xmppserver/src/main/java/org/jivesoftware/admin/AdminConsole.java, xmppserver/src/main/java/org/jivesoftware/openfire/SessionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/IQMUCSearchHandler.java, xmppserver/src/main/webapp/user-roster.jsp
Collections.sort is just a wrapper, so it is better to use an instance method directly.
=> Replace Collections.sort(list, comparator) with list.sort(comparator)

xmppserver/src/main/java/org/jivesoftware/openfire/server/ServerDialback.java, xmppserver/src/main/java/org/jivesoftware/util/Base64.java, xmppserver/src/main/java/org/jivesoftware/util/cache/DefaultExternalizableUtil.java, xmppserver/src/main/webapp/decorators/setup.jsp
Where possible, switch to Java 7 Automatic Resource Management, which is less error-prone.
=> Replace try/finally with try-with-resources

xmppserver/src/main/java/org/jivesoftware/admin/AdminConsole.java, xmppserver/src/main/java/org/jivesoftware/database/DefaultConnectionProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/auth/POP3AuthProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapUserProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/mediaproxy/MediaProxyService.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCPersistenceManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MUCServiceProperties.java, xmppserver/src/main/java/org/jivesoftware/openfire/streammanagement/StreamManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/user/User.java, xmppserver/src/main/java/org/jivesoftware/util/FastDateFormat.java, xmppserver/src/main/java/org/jivesoftware/util/JiveGlobals.java, xmppserver/src/main/java/org/jivesoftware/util/JiveProperties.java
Explicit boxing and unboxing was only needed prior to Java 5.
These changes were all automatically applied by IntelliJ.
=> No longer do explicit boxing and unboxing

starter/src/main/java/org/jivesoftware/openfire/launcher/Launcher.java, xmppserver/src/main/java/org/jivesoftware/admin/AuthCheckFilter.java, xmppserver/src/main/java/org/jivesoftware/openfire/Channel.java, xmppserver/src/main/java/org/jivesoftware/openfire/MulticastRouter.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginClassLoader.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java, xmppserver/src/main/java/org/jivesoftware/openfire/filetransfer/proxy/FileTransferProxy.java, xmppserver/src/main/java/org/jivesoftware/openfire/ldap/LdapGroupProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/LocalMUCRoomManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/SocketConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/net/VirtualConnection.java, xmppserver/src/main/java/org/jivesoftware/openfire/nio/NettyConnectionHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/privacy/PrivacyList.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubServiceInfo.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, xmppserver/src/main/java/org/jivesoftware/openfire/user/User.java, xmppserver/src/main/java/org/jivesoftware/openfire/websocket/XMPPPPacketReaderFactory.java, xmppserver/src/main/java/org/jivesoftware/util/WebManager.java, xmppserver/src/main/java/org/jivesoftware/util/cache/SerializingCache.java, xmppserver/src/main/webapp/setup/ldap-group.jspf, xmppserver/src/main/webapp/setup/setup-admin-settings.jsp, xmppserver/src/main/webapp/setup/setup-datasource-standard.jsp, xmppserver/src/main/webapp/setup/setup-host-settings.jsp, xmppserver/src/main/webapp/setup/setup-ldap-group.jsp, xmppserver/src/main/webapp/setup/setup-ldap-server.jsp, xmppserver/src/main/webapp/setup/setup-ldap-user_test.jsp, xmppserver/src/main/webapp/user-roster.jsp
This change was applied automatically by IntelliJ.
=> Replace explicity type definition with diamond

starter/src/main/java/org/jivesoftware/openfire/launcher/Launcher.java, starter/src/main/java/org/jivesoftware/openfire/starter/JiveClassLoader.java, xmppserver/src/main/java/org/jivesoftware/openfire/Channel.java, xmppserver/src/main/java/org/jivesoftware/openfire/JMXManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/XMPPServer.java, xmppserver/src/main/java/org/jivesoftware/openfire/cluster/ClusterManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginClassLoader.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java, xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoInfoHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/disco/IQDiscoItemsHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/filetransfer/proxy/ProxyConnectionManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/keystore/CertificateStoreWatcher.java, xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/FMUCHandler.java, xmppserver/src/main/java/org/jivesoftware/openfire/privacy/PrivacyList.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/CachingPubsubPersistenceProvider.java, xmppserver/src/main/java/org/jivesoftware/openfire/pubsub/PubSubEngine.java, xmppserver/src/main/java/org/jivesoftware/openfire/roster/RosterManager.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java, xmppserver/src/main/java/org/jivesoftware/util/WebManager.java, xmppserver/src/main/webapp/muc-room-cache.jsp, xmppserver/src/main/webapp/muc-room-clear-chat.jsp, xmppserver/src/test/java/org/jivesoftware/openfire/session/RemoteInitiatingServerDummy.java
This PR contains four distinct sets of changes, each in their own commit. All of the changes replace code with more alternatives that are more concise/clear, mostly using lambdas.
=> Java 8 lambdas

xmppserver/src/main/webapp/reg-settings.jsp
The previous commit for this issue introduced nested HTML forms, which won't work. Additionally, the form shouldn't differ between null values, and empty string values for provided settings.
=> OF-2784: Fix admin console pages

distribution/src/conf/openfire-demoboot.xml, documentation/client-minimal-working-example-mellium.html, documentation/client-minimal-working-example-moxxmpp.html, documentation/client-minimal-working-example-smack.html, documentation/client-minimal-working-example-stanzajs.html, documentation/client-minimal-working-example-stropejs.html, documentation/client-minimal-working-example-twistedwords.html, documentation/client-minimal-working-example-whixp.html, documentation/client-minimal-working-example-xmppdotnet.html, documentation/demoboot-guide.html
The demoboot setup provisions the server with two users: jane and john. This commit adds a third, juan.
=> Add third user to demoboot

xmppserver/src/main/java/org/jivesoftware/openfire/SessionResultFilter.java, xmppserver/src/main/java/org/jivesoftware/openfire/session/RemoteClientSession.java, xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
Various changes to improve the performance of the Client Sessions Summary admin console page.
Please refer to the individual commit messages for more details.
=> Admin panel session summary fixes

xmppserver/src/main/java/org/jivesoftware/openfire/handler/DirectedPresence.java
Please review individual commit messages.
=> OF-3057 &OF-3058: Minor changes to DirectedPresence class

xmppserver/src/main/java/org/jivesoftware/openfire/spi/RoutingTableImpl.java
When removing an outgoing server to server session, this must be invoked from the cluster node that holds the physical connection (this is a pre-existing contract).
With this change, Openfire explicitly checks if the closing server indeed is the owner of the physical server (disregarding the request otherwise).
This intends to reduce the amount of cluster cache inconsistencies that relate to server-to-server sessions (such as: "Not all elements in of LocalServerRoutingTable's response exist in Routing Servers Cache.").
=> OF-2280: Prevent closure of Server sessions of other cluster nodes

xmppserver/src/main/java/org/jivesoftware/admin/servlet/SystemCacheDetailsServlet.java, xmppserver/src/main/java/org/jivesoftware/util/cache/CacheFactory.java, xmppserver/src/main/java/org/jivesoftware/util/cache/SerializingCache.java
Please refer to the individual commit messages.
=> OF-3082 / OF-3083: Fixes for SerializingCache

xmppserver/src/main/java/org/jivesoftware/openfire/muc/spi/MultiUserChatServiceImpl.java
A user can join the same MUC using multiple resources. The 'ghost' detection, would completely remove the user from the MUC if only _one_ of these resources would become unresponsive.
This leads to scenarios where someone that is joined on a mobile device and a laptop to be removed when only the laptop goes into hibernation.
When a resource becomes unresponsive, only that resource is to be removed from the room. The users is kicked only after _the last_ resource leaves.
=> OF-3098: Do not kick MUC user when other resources are active
